### ISSUE TITLE
Lifecycle issue

### ISSUE THREAD

**Issue by Shivam-magenative** [PierfrancescoSoffritti/android-youtube-player#1000]
.gradle/caches/modules-2/files-2.1/androidx.lifecycle/lifecycle-common/2.6.0/10f354fdb64868baecd67128560c5a0d6312c495/lifecycle-common-2.6.0.jar!/META-INF/lifecycle-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.0, expected version is 1.6.0.
Hey there I am getting this issue while using youtube player library can you please help me

**Comment by PierfrancescoSoffritti** [comment]
Maybe you need to upgrade your dependencies?

**Comment by Akash-github-project** [comment]
@Shivam-magenative i was facing the same issue upgrade your androidx-lifecycle related dependency and you would be ready to go. as the 2.6.0 is using kotlin version 1.6.0 and this library is using 1.8.0
