### ISSUE TITLE
Youtube Player View not working properly after pause

### ISSUE THREAD

**Issue by rachit1797** [PierfrancescoSoffritti/android-youtube-player#1004]
# Bug Report

### Description of the Bug

- This issue happens when I am pausing the youtube using custom layout. The Video again and again maximixes and minimizes automatically after a while it becomes normal.
- I have uploaded video for refrence.
- https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/53536171/00ceb0ce-c7f8-4cb1-85e6-846e6bff0f06

### Environment details

Android Version:  13
API Version: 

Tested devices:

- OnePlus Nord Ce3 Lite
- Android 13

Youtube Player Library Version: 
12.0.0

**Comment by PierfrancescoSoffritti** [comment]
I have never seen this happening. Maybe there's an issue with your custom layout?

**Comment by rachit1797** [comment]
I am using the same app in other devices it is working fine. Also I think it is some sort of problem with iframe because the layout is not changing only the webview in which iframe is working is changing.

**Comment by PierfrancescoSoffritti** [comment]
I see, it could be a problem with the Webview implementation on that particular device.

**Comment by rachit1797** [comment]
But I am use the Same code for iframe implementation I can send the snippet
`    val options: IFramePlayerOptions =
            IFramePlayerOptions.Builder().controls(0).rel(0).build()
        youTubePlayerView!!.initialize(listener, options)`

**Comment by PierfrancescoSoffritti** [comment]
Webview implementation can change based on the OEM and version of Android.

**Comment by rachit1797** [comment]
So what can I do to solve the problem

**Comment by PierfrancescoSoffritti** [comment]
I would suggest trying to replicate it using the sample app from this project.

**Comment by rachit1797** [comment]
Ok will try it and get back.
