### ISSUE TITLE
an error occurred while initializing the youtube player

### ISSUE THREAD

**Issue by suryamurugesan55** [PierfrancescoSoffritti/android-youtube-player#1009]
![Screenshot_20230620-125743](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/115150113/5793c734-4425-49ba-85c5-1aa785d230a4)

**Comment by PierfrancescoSoffritti** [comment]
It looks like you're doing something wrong on your end. Please refer to the sample app.
