### ISSUE TITLE
Remove Share/ Setting/ Menu/ Title Option

### ISSUE THREAD

**Issue by suryamurugesan55** [PierfrancescoSoffritti/android-youtube-player#1010]
How we hide Share/ Settings / Menu Options

**Comment by PierfrancescoSoffritti** [comment]
Hi, I don't think the IFrame player allows it unfortunately.

**Comment by dendrocyte** [comment]
But how to support the share feature? There is nothing happen when click the share button

**Comment by PierfrancescoSoffritti** [comment]
Can you provide a video showing the issue?

**Comment by dendrocyte** [comment]
Sorry to reply late. 
The native share button and native more video list are unavailable to touch when using DefaultPlayerUiController.
The view named panel interrupts the touch event.
If I hide panel, it will work fine.
