### ISSUE TITLE
How to make a mini portrait and fullscreen landscape( if i have code like this)?

### ISSUE THREAD

**Issue by elpafras** [PierfrancescoSoffritti/android-youtube-player#1019]
package org.sabda.konseling;

import android.content.Intent;
import android.content.pm.ActivityInfo;
import android.os.Bundle;
import android.util.DisplayMetrics;
import android.view.Gravity;
import android.view.View;
import android.view.WindowManager;

import androidx.appcompat.app.AppCompatActivity;

import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.FullscreenListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.YouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.options.IFramePlayerOptions;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;

import org.jetbrains.annotations.NotNull;
import org.sabda.konseling.ClassDatabase.VideoDetailModel;

import kotlin.Unit;
import kotlin.jvm.functions.Function0;

public class Video extends AppCompatActivity {

    public static final String ITEM_EXTRA = "item_extra";

    FullScreenHelper fSH;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video);

        setTheme(R.style.NoTitleBarTheme);

        fSH = new FullScreenHelper(this);

        portraitLayoutParams();

        Intent intent = getIntent();
        VideoDetailModel url = intent.getParcelableExtra(ITEM_EXTRA);

        String id = url.getTitle();

        YouTubePlayerView youTubePlayerView = findViewById(R.id.yt_video);
        getLifecycle().addObserver(youTubePlayerView);

        YouTubePlayerListener listener = new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NotNull YouTubePlayer youTubePlayer) {
                super.onReady(youTubePlayer);
                youTubePlayer.loadVideo(id, 0);

            }
        };
        IFramePlayerOptions options = new IFramePlayerOptions.Builder().controls(1).fullscreen(1).build();
        youTubePlayerView.addFullscreenListener(new FullscreenListener() {
            @Override
            public void onEnterFullscreen(@NotNull View view, @NotNull Function0<Unit> function0) {
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                fSH.enterFullScreen();
            }

            @Override
            public void onExitFullscreen() {
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);
                fSH.exitFullscreen();
                portraitLayoutParams();
            }
        });

        youTubePlayerView.initialize(listener, options);

    }

        getWindow().addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);

        WindowManager.LayoutParams attrs = getWindow().getAttributes();
        attrs.flags |= WindowManager.LayoutParams.FLAG_FULLSCREEN;
        attrs.flags |= WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON;
        getWindow().setAttributes(attrs);

        int uiOptions = View.SYSTEM_UI_FLAG_FULLSCREEN;
        getWindow().getDecorView().setSystemUiVisibility(uiOptions);

        getWindow().setLayout(WindowManager.LayoutParams.MATCH_PARENT, WindowManager.LayoutParams.MATCH_PARENT);
    }

    private void portraitLayoutParams(){
        DisplayMetrics dm = new DisplayMetrics();
        getWindowManager().getDefaultDisplay().getMetrics(dm);

        int width = (int) (dm.widthPixels * 0.8);
        int height = (dm.heightPixels * 8/25);
        getWindow().setLayout(width,height);

        WindowManager.LayoutParams params = getWindow().getAttributes();
        params.gravity = Gravity.CENTER;
        params.x = 0;
        params.y = -20;

        getWindow().setAttributes(params);
    }

}

**Comment by PierfrancescoSoffritti** [comment]
Hi, I am not sure what you're asking. Feel free to reopen if you want to explain clearly what do you need, what have you tried and what is not working.
