### ISSUE TITLE
Error in YoutubeDataEndpoint

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#102]
SingleOnSubscribe<String> **onSubscribeß**;
        onSubscribe = emitter -> {<
In YoutubeDataEndpoint.java you wrote badly onSubscribe
Hope to help

**Comment by PierfrancescoSoffritti** [comment]
Hi, what do you mean? it looks good to me

**Comment by Trusted97** [comment]
I've download it 23 March and it give me error because can't resolve 'onSubscribe' because is declared as 'onSubscribeß'

**Comment by PierfrancescoSoffritti** [comment]
mmm have you used the library's project or have you copy-pasted the code in an other project? if you're copy-pasting remember to enable java 8 compatibility in your gradle file:

```
compileOptions {
  sourceCompatibility JavaVersion.VERSION_1_8
  targetCompatibility JavaVersion.VERSION_1_8
 }
```

In case you have any trouble making the code work follow what I'm doing in the sample app.

Also `Build -> Clean Project` and `Build -> Rebuild Project` in Android Studio may help.
