### ISSUE TITLE
Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag

### ISSUE THREAD

**Issue by marvingonzales27** [PierfrancescoSoffritti/android-youtube-player#1026]
# Question / Problem

Hello, I would like to ask on how to override "youtube_button" click listener under DefaultPlayerUiController. I have a YouTubePlayerView inside the adapter. whenever I try to click youTubeButton, it always throws a runtime exception "Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?".

I need to override/remove youtubeButton listener, so that I can set a new onClick listener. and do the intent outside the adapter. 

or does the library has an existing method/approach for this?

thaanks!

**Comment by PierfrancescoSoffritti** [comment]
Why don't you provide the Activity context to the method doing startActivity?

**Comment by marvingonzales27** [comment]
I would love to, but how?. I've tried to override/instance **youtubeButton** and set a new onClickListener so that I can provide Activity context for the startActivity, but, the one first set inside **DefaultPlayerUiController** was always being called.

![Screen Shot 2023-07-17 at 2 10 00 PM](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/81164716/c54356cf-b2b1-4222-96e7-dc0fc32fcf59)

thaanks!

**Comment by marvingonzales27** [comment]
It works now. been thinking what you just said, I just pass activity context into adapter.

I completely forgot about this, been using dagger for a while, I don't normally pass activity context into adapter.

thaanks!

**Comment by PierfrancescoSoffritti** [comment]
I'm glad you figured it out :)
