### ISSUE TITLE
Fork and modify some content, try to use jitpack but fail...

### ISSUE THREAD

**Issue by hijacker4163** [PierfrancescoSoffritti/android-youtube-player#1027]
# Question / Problem
Fork and modify some content, try to use jitpack but fail...

### Summary

I use branches, fix some ad issues, try to use jitpack for gradle usage, but keep running into issues...

### What I've tried

I have found that this project has the same situation in jitpack after 11.0.0.

Tried to make some official corrections for gradle7.0, but still failed.

For example: using dependencyResolutionManagement
Try to remove repositories...

Is there any other workaround?

**Comment by PierfrancescoSoffritti** [comment]
I think in order to use Jitpack you need to add a config file somewhere. I suggest check their website documentation.
