### ISSUE TITLE
Question about player

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#103]
It's possible hide in the player the youtube menu's ?

**Comment by PierfrancescoSoffritti** [comment]
Yes,` youTubePlayerView.getPlayerUIController().showMenuButton(false)`

**Comment by Trusted97** [comment]
but if i want hide the everything and let only the play/pause button?

**Comment by PierfrancescoSoffritti** [comment]
You can hide each individual view from the UIController. All the methods are listed [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/ui/PlayerUIController.java).

**Comment by Trusted97** [comment]
I've read them but i can't hide everything and let only the play/pause button. 
showUI hide everything o show everything

**Comment by Trusted97** [comment]
Ok nothing know my mistake

**Comment by PierfrancescoSoffritti** [comment]
As I said, you can hide **each individual view** from the UIController.

Just call the right methods.

```
void showCurrentTime(boolean show);
void showDuration(boolean show);
void showSeekBar(boolean show);
void showYouTubeButton(boolean show);
void showFullscreenButton(boolean show);
void showVideoTitle(boolean show);
```

**Comment by Trusted97** [comment]
Sorry my mistake i apologize
