### ISSUE TITLE
Inquiry about YouTube Video Full-Screen Mode in Android WebView Externes

### ISSUE THREAD

**Issue by mohamedkammoun123** [PierfrancescoSoffritti/android-youtube-player#1031]
I have successfully integrated the YouTube iframe API into my Android app, allowing users to watch embedded YouTube videos in the WebView. However, I am curious to know if there is any way to enable full-screen mode automatically without requiring the user to manually press the full-screen button within the YouTube player controls.

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes it's possible. [Have a look at the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/fullscreenExample/FullscreenExampleActivity.kt#L79)

**Comment by mohamedkammoun123** [comment]
It doesn't work, and the console log shows an error related to an undefined function :""Uncaught TypeError: event.target.toggleFullscreen is not a function", source: file///..." here is the code : 

<!DOCTYPE html>
<html>
<body>
<style type="text/css">
        body {
        overflow: hidden;
        }

        #over {
        position: absolute;
        top: 50%;
        left: 50%;
        z-index: 1000;
        border: 2px solid black;
        pointer-events: none;
        }

        iframe {
        max-width: 100%;
        position: absolute;
        border: none;
        box-sizing: border-box;
        width: 100%;
        height: 100%;
        }

        ul {
        list-style-type: none;
        float: left;
        margin: 2px;
        width: 100%;
        }

        ul li {
        float: left;
        width: 30%;
        }
        /* The Overlay (background) */

        .overlay {
        display: none;
        /* Height & width depends on how you want to reveal the overlay (see JS below) */
        height: 60%;
        width: 35%;
        position: fixed;
        /* Stay in place */
        z-index: 1;
        /* Sit on top */
        right: 0;
        top: 0;
        background-color: rgb(0, 0, 0);
        /* Black fallback color */
        background-color: rgba(0, 0, 0, 0.9);
        /* Black w/opacity */
        overflow-x: hidden;
        /* Disable horizontal scroll */
        transition: 0.5s;
        /* 0.5 second transition effect to slide in or slide down the overlay (height or width,
        depending on reveal) */
        }
        /* Position the content inside the overlay */

        .overlay-content {
        position: relative;
        width: 100%;
        }

        canvas {
        display: block;
        }
    </style>

<div id="player">

</div>
<script>
      // 1; function to get parmas of url as dict
      var QueryString = function() {
            // This function is anonymous, is executed immediately and
            // the return value is assigned to QueryString!
            var query_string = {};
            var query = window.location.search.substring(1);
            var vars = query.split("&");
            for (var i = 0; i < vars.length; i++) {
                var pair = vars[i].split("=");
                // If first entry with this name
                if (typeof query_string[pair[0]] === "undefined") {
                    query_string[pair[0]] = decodeURIComponent(pair[1]);
                    // If second entry with this name
                } else if (typeof query_string[pair[0]] === "string") {
                    var arr = [query_string[pair[0]], decodeURIComponent(pair[1])];
                    query_string[pair[0]] = arr;
                    // If third or later entry with this name
                } else {
                    query_string[pair[0]].push(decodeURIComponent(pair[1]));
                }
            }
            return query_string;
      }();
      var $ = document.querySelector.bind(document);

      // 2. This code loads the IFrame Player API code asynchronously.
      var tag = document.createElement('script');

      tag.src = "https://www.youtube.com/iframe_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

      // 3. This function creates an <iframe> (and YouTube player)
      //    after the API code downloads.
      var player;
      function onYouTubeIframeAPIReady() {
        player = new YT.Player('player', {
          height: '100%',
    	  width: '100%',
          videoId: QueryString.videoId,
          playerVars: {
            autoplay: 1,
            playsinline: 0
          },
          events: {
            'onReady': onPlayerReady,
            'onStateChange': onPlayerStateChange
          }
        });

      }

      // 4. The API will call this function when the video player is ready.
      function onPlayerReady(event) {
        event.target.mute();
        event.target.playVideo();
        event.target.toggleFullscreen();
      }

      // 5. The API calls this function when the player's state changes.
      //    The function indicates that when playing a video (state=1),
      //    the player should play for six seconds and then stop.
      var done = false;
      function onPlayerStateChange(event) {
        if (event.data == YT.PlayerState.PLAYING && !done) {
          setTimeout(stopVideo, 60000);
          done = true;
        }
      }

      function stopVideo() {
        player.stopVideo();
      }
    </script>
</body>
</html>

**Comment by PierfrancescoSoffritti** [comment]
uhm, this code looks unfamiliar, it doesn't look like you're using this library?

**Comment by mohamedkammoun123** [comment]
yes you are right

**Comment by mohamedkammoun123** [comment]
I didn't find this function in  youtube iframe api documentation is there another solution pls ?

**Comment by PierfrancescoSoffritti** [comment]
I'm afraid I can't help you if you're not using the library. I am unfamiliar with your code.
