### ISSUE TITLE
chromecast

### ISSUE THREAD

**Issue by waseem-terafort** [PierfrancescoSoffritti/android-youtube-player#1036]
is there anyway that local videos cast on google smart tv???
how to do that??

**Comment by PierfrancescoSoffritti** [comment]
Yes, please have a look of the chromecast section of the doc.

**Comment by waseem-terafort** [comment]
Brother, my question was local videos like which is gallery u updating and casting the video from link YouTube like, i wanna cast the local videos which are in my gallery, http server but it doesn't work tell me what will be the problem

**Comment by PierfrancescoSoffritti** [comment]
I see, this library is to play YouTube videos (from YouTube), not local videos. So it won't work.
