### ISSUE TITLE
In the landscape mode, duration and other options are not coming which is coming if I change activity to Portrait

### ISSUE THREAD

**Issue by jimmytrivediuser** [PierfrancescoSoffritti/android-youtube-player#1037]
The YouTube player view wrapped in compose UI scaffold instead LinearLayout

In the manifest, I've defined screenOrientation as landscape.

```
<activity
            android:name=".app.YouTubePlayerActivity"
            android:screenOrientation="landscape" />
```

**Requirement / Scenario:** On the clicking of button, I want to display a public YouTube video. So I've created a YouTubeActivity and inside I've written a compose + Kotlin code. Now in compose, I took Scaffold and inside that I called one Kotlin file called YoutubePlayer.kt which contains implementation of your library.

YouTubePlayerActivity:
```
@AndroidEntryPoint
class YouTubePlayerActivity : BaseComposeActivity() {

    @Composable
    override fun GetContent() {
        Scaffold(
            modifier = Modifier.fillMaxSize(),
           ) { rootPaddingValues ->

            YoutubePlayer(
                modifier = Modifier.padding(rootPaddingValues).fillMaxSize(),
                videoId = BuildConfig.HOW_TO_MEASURE_VIDEO_ID,
                canPlayVideo = true,
                showControls = true
            )
        }
    }
```

YoutubePlayer.kt
```
@Composable
fun YoutubePlayer(
    modifier: Modifier,
    videoId: String,
    canPlayVideo: Boolean,
    thumbNailUrl: String? = null,
    showThumbNail: Boolean = false,
    loopVideo: Boolean = true,
    showControls: Boolean = false
) {
    var ytPlayer: YouTubePlayer? by remember {
        mutableStateOf(null)
    }

    LaunchedEffect(key1 = canPlayVideo) {
        if (canPlayVideo) {
            ytPlayer?.play()
        } else {
            ytPlayer?.pause()
        }
    }
    DisposableEffect(key1 = Unit) {
        onDispose {
            ytPlayer?.pause()
        }
    }
    Box(modifier = Modifier) {
        AndroidView(
            modifier = modifier,
            factory = {
                val view = YouTubePlayerView(it)
                view.enableAutomaticInitialization = false
                val playerListener = object : AbstractYouTubePlayerListener() {
                    override fun onReady(youTubePlayer: YouTubePlayer) {
                        super.onReady(youTubePlayer)


                        val fListener = object : FullscreenListener{
                            override fun onEnterFullscreen(
                                fullscreenView: View,
                                exitFullscreen: () -> Unit
                            ) {
                                LogUtils.d("Hello fullscreenView")
                            }

                            override fun onExitFullscreen() {
                                LogUtils.d("Hello onExitFullscreen")
                            }

                        }
                        view.addFullscreenListener(fListener)

                        val uiController = DefaultPlayerUiController(view, youTubePlayer)
                        uiController.showUi(showControls)
                        uiController.showDuration(true)
                        uiController.showFullscreenButton(true)
                        uiController.showSeekBar(true)
                        uiController.showBufferingProgress(true)
                        uiController.showCurrentTime(true)
                        uiController.showMenuButton(false)
                        uiController.showPlayPauseButton(true)
                        uiController.showVideoTitle(false)
                        uiController.showYouTubeButton(false)

                        view.setCustomPlayerUi(uiController.rootView)
                        if (canPlayVideo){
                            youTubePlayer.loadVideo(videoId = videoId, 0f)
                        } else {
                            youTubePlayer.cueVideo(videoId = videoId, 0f)
                        }
                        ytPlayer = youTubePlayer
                    }

                    override fun onStateChange(
                        youTubePlayer: YouTubePlayer,
                        state: PlayerConstants.PlayerState
                    ) {
                        super.onStateChange(youTubePlayer, state)
                    }
                }
                val builder = IFramePlayerOptions.Builder()
                    .controls(0)
                    .ccLoadPolicy(0)
                    .rel(0)
                    /*.fullscreen(1)*/
                    .ivLoadPolicy(1)
                val options = builder.build()

                view.initialize(playerListener, true, options)
                LogUtils.d("video:- youtube player- $options")
                view
            },
            update = {
                LogUtils.d("video:- youtube player view update")
            }
        )
    }
}
```

**Comment by PierfrancescoSoffritti** [comment]
With "landscape mode" do you mean when the player enters full screen mode?

**Comment by jimmytrivediuser** [comment]
Yes, the default orientation of my activity is landscape. Kindly check the edited question.

**Comment by PierfrancescoSoffritti** [comment]
`DefaultPlayerUiController` doesn't work in full screen. Can you switch to webui?

**Comment by jimmytrivediuser** [comment]
@PierfrancescoSoffritti Sorry, I did not get your point, can you please elaborate?

**Comment by PierfrancescoSoffritti** [comment]
Why are you using `DefaultPlayerUiController`?

**Comment by jimmytrivediuser** [comment]
Please tell me what should I use? I'm new to YouTube library.

**Comment by jimmytrivediuser** [comment]
Hi @PierfrancescoSoffritti Any update?

**Comment by PierfrancescoSoffritti** [comment]
You can follow the [doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#quick-start) and the [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples) has many examples.


But essentially you can just remove this bit

```kotlin
val uiController = DefaultPlayerUiController(view, youTubePlayer)
uiController.showUi(showControls)
uiController.showDuration(true)
uiController.showFullscreenButton(true)
uiController.showSeekBar(true)
uiController.showBufferingProgress(true)
uiController.showCurrentTime(true)
uiController.showMenuButton(false)
uiController.showPlayPauseButton(true)
uiController.showVideoTitle(false)
uiController.showYouTubeButton(false)

view.setCustomPlayerUi(uiController.rootView)
```

**Comment by jimmytrivediuser** [comment]
I did not get clarity on this. My first requirement is Compose UI and all your example is in XML based. I checked this but it won't fit in my case: https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/fullscreenExample/FullscreenExampleActivity.kt

Can you please provide exact answer?

**Comment by PierfrancescoSoffritti** [comment]
As I said, remove these lines

```
val uiController = DefaultPlayerUiController(view, youTubePlayer)
uiController.showUi(showControls)
uiController.showDuration(true)
uiController.showFullscreenButton(true)
uiController.showSeekBar(true)
uiController.showBufferingProgress(true)
uiController.showCurrentTime(true)
uiController.showMenuButton(false)
uiController.showPlayPauseButton(true)
uiController.showVideoTitle(false)
uiController.showYouTubeButton(false)

view.setCustomPlayerUi(uiController.rootView)
```

**Comment by jimmytrivediuser** [comment]
I remove those line, still same issue.
` Box(modifier = Modifier) {
        AndroidView(
            modifier = modifier,
            factory = {
                val view = YouTubePlayerView(it)
                view.enableAutomaticInitialization = false
                val playerListener = object : AbstractYouTubePlayerListener() {
                    override fun onReady(youTubePlayer: YouTubePlayer) {
                        super.onReady(youTubePlayer)


                        val fListener = object : FullscreenListener{
                            override fun onEnterFullscreen(
                                fullscreenView: View,
                                exitFullscreen: () -> Unit
                            ) {
                                LogUtils.d("Hello fullscreenView")
                            }

                            override fun onExitFullscreen() {
                                LogUtils.d("Hello onExitFullscreen")
                            }

                        }
                        view.addFullscreenListener(fListener)

                       /* val uiController = DefaultPlayerUiController(view, youTubePlayer)
                        uiController.showUi(showControls)
                        uiController.showDuration(true)
                        uiController.showFullscreenButton(true)
                        uiController.showSeekBar(true)
                        uiController.showBufferingProgress(true)
                        uiController.showCurrentTime(true)
                        uiController.showMenuButton(false)
                        uiController.showPlayPauseButton(true)
                        uiController.showVideoTitle(false)
                        uiController.showYouTubeButton(false)

                        view.setCustomPlayerUi(uiController.rootView)*/
                        if (canPlayVideo){
                            youTubePlayer.loadVideo(videoId = videoId, 0f)
                        } else {
                            youTubePlayer.cueVideo(videoId = videoId, 0f)
                        }
                        ytPlayer = youTubePlayer
                    }

                    override fun onStateChange(
                        youTubePlayer: YouTubePlayer,
                        state: PlayerConstants.PlayerState
                    ) {
                        super.onStateChange(youTubePlayer, state)
                    }
                }
                val builder = IFramePlayerOptions.Builder()
                    .controls(0)
                    .ccLoadPolicy(0)
                    .rel(0)
                    /*.fullscreen(1)*/
                    .ivLoadPolicy(1)
                val options = builder.build()

                view.initialize(playerListener, true, options)
                LogUtils.d("video:- youtube player- $options")
                view
            },
            update = {
                LogUtils.d("video:- youtube player view update")
            }
        )
    }`

**Comment by jimmytrivediuser** [comment]
Hi, your solution isn't working, request you to please do not close the issue.
