### ISSUE TITLE
changing YouTube player view on click new video in existing YouTube player view

### ISSUE THREAD

**Issue by edutorappweb** [PierfrancescoSoffritti/android-youtube-player#1068]
# Question / Problem
Hello @PierfrancescoSoffritti .

I made this activity in look wise same as YouTube application.

I have a single player view in my youtubeactivity.java file. 

which is taking one third space of mobile screen and remaining 2/3 part is covered with like, unlike section, description and comment section and below this section there is section for suggested or related videos.

Now when i clicks on any of from suggested video it should be replace to currently running player view and update with this new clicked video.

but it is not replacing currently playing video. all data (likes count ,dislikes count, description, comments etc. ) of clicked suggested video is changing but only currently playing video inside player view is not changing, it's remaining as it is.

### Summary
when I click any video from suggested video than currently running video inside YouTube player view should replace with new clicked video.

### What I've tried
In old deprecated YouTube player API I was using this function to clear old player and initialize new function 

```
private void initYoutubeVideo() {
        m.scrollView.scrollTo(offset, offset);
        if (player != null) {
            oldPlayer.setManageAudioFocus(doNot);
            oldPlayer.setOnFullscreenListener(null);
            oldPlayer.setPlaybackEventListener(null);
            oldPlayer.setPlayerStateChangeListener(null);
            oldPlayer.setPlaylistEventListener(null);
            oldPlayer.release();
            player = null;
        }
}`
```

in this player i have tried to put override onReady function with loadVideo, cueVideo inside initYoutubeVideo() function.

i have tried putting load video , cueVideo direct inside initYoutubeVideo().

tried use of playerUtils 

`getLifecycle().addObserver(m.youtubePlayerView);

        m.youtubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {

            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                super.onReady(youTubePlayer);
                if (videoId != null) {
                    YouTubePlayerUtils.loadOrCueVideo(
                            youTubePlayer,
                            getLifecycle(),
                            videoId,
                            TYPE_0);
                    /*player.loadVideo(videoId, TYPE_0);*/
                }
            }

        });`

also tried use of playerView.release()
then onready...

Hope You understand my problem.

please help me to solve this problem.
because my app with 250k downloaders is stopped without video player and showing error from past some months of deprecated api...

**Comment by Serkali-sudo** [comment]
You don't need to create a new `YoutubePlayerView` for every new video; instead, you can simply use the `youtubePlayer.loadVideo()` method. Just create a global `YoutubePlayer` variable, and when the `onReady` callback is fired, set the `YoutubePlayer` to the instance provided by the callback parameter. Then you will able to call `youtubePlayer.loadVideo()` anywhere you want.
I am pretty sure you can find more in the sample app code or docs.

**Comment by edutorappweb** [comment]
ok thank you issue solved i have made mistake i realize that 
i am not storing youtube player in global variable now solved 
thank you so much...
