### ISSUE TITLE
Is there any method avaliable to hide overflow menu(Share option) hide or click disble? 

### ISSUE THREAD

**Issue by GauravMeghanathiWeDoApps** [PierfrancescoSoffritti/android-youtube-player#1076]
# Question / Problem
Here is my question is Overflow menu which is showing share option I want to hide or click disable if it is possible to do?

**Comment by billdizl** [comment]
you can use custom layout

**Comment by PierfrancescoSoffritti** [comment]
It's not possible to alter the web ui of the player, it is controlled by the IFrame library.
