### ISSUE TITLE
Disable auto-Play (cueVideo) not working

### ISSUE THREAD

**Issue by Norman191** [PierfrancescoSoffritti/android-youtube-player#1078]
Using  _**youTubePlayer.cueVideo(url, 1);**_ in previous projects, it was working great, but few days ago, i tried it and did not work.
the **_youTubePlayer.loadVideo(url, 1);_** still working fine, but i want the video not to auto-play. 

Im using 
implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:12.1.0'

**Comment by PierfrancescoSoffritti** [comment]
Please try to reproduce on the sample app and let me know.

**Comment by IlyaPavlovskii** [comment]
Checked issue. Looks like `loadVideo` script automatically starts a video, doesn't matter what kind of option was passed(autoplay true/false). 
I've found a fix - call `pause` event when on video id received callback.

**Comment by PierfrancescoSoffritti** [comment]
You can use `cueVideo`.
