### ISSUE TITLE
minSdk version to at least 17???

### ISSUE THREAD

**Issue by naguchennai** [PierfrancescoSoffritti/Android-YouTube-Player#108]
minSdk version to at least 17??  Not possible add to most of the my application. sorry bye

**Comment by PierfrancescoSoffritti** [comment]
Hi, I'm not sure I understand what you're saying.
You can have a minSdk higher than 17 in your app, if you need to.

**Comment by naguchennai** [comment]
Lol ... i told you library must support minimum from 14. not from 17.. u need change api to possible support from 14 or 15 not 17 ... if its api level 17 we missed 55% of android mobile for our application installs...
I think u must understand now...

**Comment by PierfrancescoSoffritti** [comment]
Having KitKat as minSdk level is not really a problem anymore, you lose only less than 6% of the total user base. You can see the stats [here](https://developer.android.com/about/dashboards/index.html).

I can't guaranty stability for versions lover than KitKat, therefore I won't lower the min sdk. 
If you need to support versions older thank KitKat i suggest you fork the library and lower the minSdk yourself.

**Comment by naguchennai** [comment]
ok thank u
