### ISSUE TITLE
YoutubeplayerView.loadVideo(Videoid) method in Recyclerview

### ISSUE THREAD

**Issue by sonandur** [PierfrancescoSoffritti/Android-YouTube-Player#109]
Hi Pierfrancesco Soffritti ! 

Thanks for the library.
The library works like charm.
When using with Recyclerview with YourubePlayerView.loadVideo(videoid), playing automatically as it does, but when scroll up and come to the video, it is start playing audio not  video and play button is showing.
When click on play button the video starts playing from starting.
Did I do any mistake?
Please help me..

**Comment by PierfrancescoSoffritti** [comment]
Hi,
you should take a look at the [RecyclerView sample app](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/tree/master/sample/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayersample/examples/recyclerViewExample).

I suggest not using loadVideo when you have multiple players in a RecyclerView. You won't know which one is going to be the last one to start playing, and it will stop all the other players. cueVideo makes more sense for this use case.
