### ISSUE TITLE
How to know when the video is ended?

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#110]
Hi! 

I'm looking inside the wiki and i see [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/Utilities)  that the YoutubePlayer got an utilities that tell the state of player.
Where can i found inside the example project an example of this? And with this method could i know if the single video is ended, if it is part of an array?

Thank's for your time!

**Comment by PierfrancescoSoffritti** [comment]
Hi,
currently there is no example, but it is straight forward to use:

To use it you simply need to create an instance of `YouTubePlayerStateTracker` and add it as listener to the `YouTubePlayer` object you want to track. From there you will be able to get the internal state of the player using your tracker.

> And with this method could i know if the single video is ended, if it is part of an array?

To do that you need to add a `YouTubePlayerListener` to your `YouTubePlayer` and, in its `onStateChange` method, listen for `PlayerConstants.PlayerState.ENDED `
