### ISSUE TITLE
Following playList Works On Youtube PC but not with this library (with this library only the first Video plays)

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1103]
@PierfrancescoSoffritti
I want to report a minor bug about playlist and PierfrancescoSoffritti library 12.1.0
the Following playList Works On Youtube PC but not with this library (with this library only first Video play and then for the next video it give an error that Playback is not activated.
Please reproduce the error with following Playlist Address :
PL-B-NQoSjmF2nc6QT8NOuPtmbW-mYhtdw
Please keep on great work. Thanks
Kindest Regards.

**Comment by PierfrancescoSoffritti** [comment]
The library simply uses the IFrame player from YouTube, if the playlist doesn't work there might be some issue on YouTube's side.

**Comment by PierfrancescoSoffritti** [comment]
You need to test on a mobile device, the result can differ from a desktop browser.
