### ISSUE TITLE
Security Contact Information 

### ISSUE THREAD

**Issue by Sirius-A** [PierfrancescoSoffritti/android-youtube-player#1106]
First of all thank you for the creating and continuous development of this library ❤️ .

## Question

I could not find a preferred communication channel for potential security issues. 
It would be great if you could [enable private advisories](https://docs.github.com/en/code-security/security-advisories/working-with-repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository#enabling-or-disabling-private-vulnerability-reporting-for-a-repository) or document how one should contact you regarding security questions.

Thanks :)

**Comment by PierfrancescoSoffritti** [comment]
Hey, I have enabled private vulnerability reporting :) what issue did you find?

**Comment by Sirius-A** [comment]
Awesome! 

Thank you for the quick reaction 🙏 . I'll submit an advisory so we can check a potential vulnerability together. 

Closing this issue as the question is answered.
