### ISSUE TITLE
Why isn't the player running properly on emulators?

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [PierfrancescoSoffritti/android-youtube-player#112]
Find out exact reason and possible workaround. 

(It may have something to do with graphics drivers/hardware acceleration)

**Comment by PierfrancescoSoffritti** [comment]
Thanks for the help! It never worked for me, I'll try again with api 23!

**Comment by mankidal19** [comment]
I'm having the same issue. Any idea why? Tried with different emulator API

**Comment by mankidal19** [comment]
sorry I take back my word. it works with API 23. but first I need to create a new fresh project. the sample project won't work. IDK why. perhaps gradle version or something?

**Comment by PierfrancescoSoffritti** [comment]
Thanks for the update, I'll check out different resolutions as well. It is probably not a memory issue though, on physical devices everything works well.

**Comment by PierfrancescoSoffritti** [comment]
It works fine on API 28, closing this issue.
