### ISSUE TITLE
Add Spinner or Loading Object while the youtube video is being fetched

### ISSUE THREAD

**Issue by umardar8** [PierfrancescoSoffritti/android-youtube-player#1123]
# Feature Request

### Describe your idea
I am working on an Android App with multiple instances of YoutubePlayerView for multiple videos in the fragments. I noticed that the User Experience can be improved if there was a spinner type of thing shown in the center of YoutubePlayerView as currently it only shows a black blank square (or rectangle) while the video is being fetched.

**Comment by PierfrancescoSoffritti** [comment]
This is already possible, by adding your own custom ui. In the core version of the library we avoid altering the web ui of the player.
