### ISSUE TITLE
Recyclerview and Links definition through the firebase 

### ISSUE THREAD

**Issue by fcknnmrcll** [PierfrancescoSoffritti/android-youtube-player#1131]
I want to know that how am I able to define or change the video link from the firebase or have an infinite Recyclerview by adding the video ids in the firebase database 
waiting for response thanks

**Comment by PierfrancescoSoffritti** [comment]
Thanks for your question but how to use Firebase is outside the scope of this library. I suggested reading Firebase documentation.
