### ISSUE TITLE
Video Unavailable DIA TV 2 Error

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1132]
I'm experiencing a problem with video playlists in the android-youtube-player library. While individual videos and other playlists function normally, specific video playlists encounter errors.

Steps to Reproduce:

Open my Android app that uses the android-youtube-player library.
Navigate to the video playlist section in question.
Attempt to play the video playlist.
Expected Behavior:

The video playlist should play consecutively, transitioning from one video to the next within the playlist.
this is the YouTube playlist which not working with the library.
PLrqEUp1jEA7XmrG4BYftZQXaEr6_DfwJ7
Please kindly find the TV Screenshot Error Attachments. Thanks in advance,
Kindest Regards,
Sincerely,
Pooya M

![IMG_1145](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/64104944/44b0293b-4eb8-4f6f-9352-b57e76891ef1)

**Comment by PierfrancescoSoffritti** [comment]
The error message in your screenshot is explicative, the video can't be played because of copyright issues.
