### ISSUE TITLE
Add showinfo

### ISSUE THREAD

**Issue by JoseLuis201092** [PierfrancescoSoffritti/android-youtube-player#1133]
# Feature Request showinfo

### Describe your idea
Define whether the player should display information such as the video title or the uploader before starting playback.

### Expected behavior and realization
Values: 0 or 1. The default value of the parameter is 1. If you set the value of the parameter to 0, the player does not display information such as the title of the video or the uploader before starting playback.

**Comment by PierfrancescoSoffritti** [comment]
Unfortunately [showinfo has been deprecated](https://developers.google.com/youtube/player_parameters#showinfo), so we can't use it.
