### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Vatsal3009** [PierfrancescoSoffritti/android-youtube-player#1135]
# Question / Problem

### Summary

Hello,

In my project, the requirement is to simply display a YouTube video with a play icon. I believe this feature is not available in the current library.

### What I've tried

Now i just load video using if and pause this video and manage my issue.

**Comment by PierfrancescoSoffritti** [comment]
I don't understand what the issue is. This library provides a Youtube Player to play Youtube videos.

**Comment by MahmoudMabrok** [comment]
@Vatsal3009  do you mean that view initially display play icon, then video starts when user click on play icon ? 
also, you can share a design/screenshot from what exactly needed

**Comment by Vatsal3009** [comment]
![Screenshot from 2024-04-26 16-20-51](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/65881816/5f2c8443-85c7-475c-a353-5474cb80ecfd)

`   binding?.playerView?.addYouTubePlayerListener(object :
                                AbstractYouTubePlayerListener() {
                                override fun onReady(@NonNull youTubePlayer: YouTubePlayer) {
                                    item.source?.let {
                                        youTubePlayer.loadVideo(it, 0f)
                                        youTubePlayer.pause()
                                    }
                                }
                            })
`

I'd like to display a view like this in my RecyclerView using our library, where the video plays automatically. However, I need the ability to pause the video afterward. I've noticed there's an "app:autoPlay=false" attribute, but it doesn't seem to be working. Please let me know if you need any further information from my end. Thank you for your response!

**Comment by MahmoudMabrok** [comment]
@Vatsal3009 
you can use `cueVideo` instead of mix of "load & pause". 

I tried now, and `youTubePlayer.cueVideo(it. 0f)` worked as you want.

**Comment by Vatsal3009** [comment]
![20240429_111021](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/65881816/7dfae4a6-4aa9-461b-b96e-268d52f7f878)

Hello @MahmoudMabrok ,

Thank you for your resposne. I have check with "cueVideo" but as you can see in the screenshort by using this first time it will take 1-2 sec to display image and after scroll the recyclerview and again go bottom to top than it will show error in player view in most of the video. can you help me with this ?
