### ISSUE TITLE
**Feature Request: Subtitle Support** in my Case Persian on android-youtube-player Library

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1141]
**Feature Request: Subtitle Support**

I'd like to propose a new feature for the android-youtube-player library: subtitle support. 

Similar to the recent update on the Youtube native app, allowing users to enable subtitles in various languages would be a valuable addition with some Youtube Settings customizations. In my case, being bilingual in Farsi (my first language) and English (my second language), having access to Farsi subtitles would significantly enhance my experience.

The Youtube native app now offers the ability to customize settings and enable subtitles in multiple languages, including Farsi. Integrating similar functionality into this library would bring it on par with the Youtube app's capabilities.

Thank you for your time and consideration.
Kindest and Warm Regards,
Sincerely and Respectfully,
Pooya M
Pooya Mohammadhossein

**Comment by PierfrancescoSoffritti** [comment]
Hi, the option to enable subtitles is provided through the web interface, no? [see screnshot](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/7457011/f5c664e9-d440-4a4c-89ff-c0624a450f72)

**Comment by PierfrancescoSoffritti** [comment]
I am not sure I understand what you're asking, as shown in the screenshot the feature is already available in the library.

**Comment by PierfrancescoSoffritti** [comment]
What you are asking is not related to the library, it's related to the IFrame player. As long as the YouTube video has subtitles, they should be available to select from the web ui. See above screenshot.
