### ISSUE TITLE
My activity recreate every time upon entering in Picture in Picture mode. I added  android:configChanges to my Activity in manifest due to that you tube stop playing in pip mode , I want video start from that point from where I enter into Picture in Picture mode

### ISSUE THREAD

**Issue by AyeshaFazal** [PierfrancescoSoffritti/android-youtube-player#1143]
# Bug Report

### Environment details

Android Version: 
API Version: 

Tested devices:

Youtube Player Library Version: 

### Steps to reproduce the bug
---
name: Bug report
about: Use this template for reporting bugs
labels: bug
---

 

# Bug Report

### Environment details

Android Version: 
API Version: 

Tested devices:

Youtube Player Library Version: 

### Additional information
<!-- Provide here further information that might help understand the issue or reproduce the bug, e.g. 
- standalone code snippets of implementation that can copy-pasted and work without any missing classes
- screenshot(s) of visualising the bug
- error logs
- any useful background infromation

**Comment by PierfrancescoSoffritti** [comment]
This issue seems to be with Android, not with the library.
