### ISSUE TITLE
Support for YouTube Shorts in YouTube Data API

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1148]
Subject: Support for YouTube Shorts in YouTube Data API

Hi,
I'm reaching out to inquire about the current support for YouTube Shorts within the YouTube Data API.
Current Functionality
While the existing YouTube Data API v3 offers functionalities for managing and retrieving data related to long-form videos, it appears that YouTube Shorts support might not be fully integrated yet.
Enhancement Suggestion
I strongly recommend adding comprehensive support for YouTube Shorts to the YouTube Data API. This would be a significant improvement for developers who want to interact with YouTube Shorts programmatically, enabling them to:
* List Shorts: Retrieve and manage playlists or channels containing YouTube Shorts.
* Get Short Details: Access data specific to Shorts, such as creation time, duration, and associated channels.
* Potentially (Future): Upload, update, and delete Shorts (subject to YouTube's policies and API permissions).
Java Code Example (if applicable)
If YouTube Shorts are currently supported, could you kindly provide a Java code sample demonstrating how to retrieve Shorts using the YouTube Video ID or an alternative identifier?
Thank You
Thank you for your time and consideration. I believe incorporating YouTube Shorts support would be a valuable asset to the YouTube Data API and empower developers to create innovative applications.
Sincerely,
Pooya M.
Pooya Mohammadhossein

Additional Considerations:
* You can check the official YouTube Data API documentation for updates regarding Shorts support:https://developers.google.com/youtube/v3
* If the API doesn't yet support Shorts, consider exploring unofficial solutions or community-developed libraries that might offer workarounds, but use them with caution and stay updated on any potential compatibility issues.
* Keep in mind that YouTube's policies and API permissions might evolve over time, so refer to the official documentation for the latest guidelines.
By providing this well-structured feedback, you can effectively advocate for YouTube Shorts support in the YouTube Data API and potentially receive helpful guidance from the development team.

**Comment by PierfrancescoSoffritti** [comment]
Hi, this library is not the YouTube Data API. I suggest opening a bug on Google's bugaziner.
