### ISSUE TITLE
Please  update the Readme Documentation AND KOTLIN (AND ALSO JAVA YOUTUBE API LIBRARY) PARAGRAPH BY PARAGRAPH DOCUMENTATION and keep saving  it as we like it 👍 

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1155]
Dear @PierfrancescoSoffritti 

It seems the Youtube API  Library Documentation has not been updated for a while because of the most recent developments. I mean the documentation in the ReadMe on Github (I mean this one) [android-youtube-player]
(https://github.com/PierfrancescoSoffritti/android-youtube-player)
this is one of the reference which might need be updated (if ivLoadPolicy is set to 2, what will be happen with this library API ?)  but there are several other similar cases too.:

ivLoadPolicy:
This option controls video annotations.
If set to 1: the player will show annotations.
If set to 3: the player won't show annotations.

![Screenshot 2024-07-01 at 10 07 47 AM](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/64104944/7020450c-6b83-4088-bda1-97f8ce4532f3)

I am sure you are busy with your own life and your family but whenever you have a chance please kindly update the ReadMe Documentation for the future references. Please feel free to ask me any questions and concerns. Thanks in advance,

 PLEASE SEE MY NEXT COMMENTS IN FOLLOWING ABOUT MAKING DOCMENTATION PARAGRAPH BY PARAGRAPH WITH YOUTUBE API (IFramePlayerOptions.KT) KOTLIN FILE AND ALSO JAVA YOUTUBE API LIBRARY.

Kindest and Warm Regards, All the best.
Sincerely and Friendly , Respectfully.

Pooya Mohammadhossein (Ryan)

**Comment by PierfrancescoSoffritti** [comment]
This library is just a wrapper around the IFrame player. The documentation of the IFrame player explains the meaning of those parameters, which is the same when used in this library.
