### ISSUE TITLE
Scroll and Seekbar issue when using viewPager2 horizontally

### ISSUE THREAD

**Issue by berkayertan** [PierfrancescoSoffritti/android-youtube-player#1156]
I'm trying to use horizontal viewpager but when i press the seekbar and try to move forward the video duration it's scrolling the video and also viewpager sample app has the same issue. How can i solve this ?

**Comment by Serkali-sudo** [comment]
I think easiest way to fix it is using the [custom-ui](https://github.com/PierfrancescoSoffritti/android-youtube-player?tab=readme-ov-file#defaultplayeruicontroller). 
Custom ui uses native android views and it works well with viewpager when it comes to scrolling.

**Comment by BerkayErtann** [comment]
@Serkali-sudo Thanks i think best way is the custom ui like u said.

**Comment by PierfrancescoSoffritti** [comment]
You could also prevent clicks from reaching the player while scrolling.

**Comment by Gudauu** [comment]
> You could also prevent clicks from reaching the player while scrolling.

Could you provide more intel on how to achieve this?

**Comment by PierfrancescoSoffritti** [comment]
I think the sample app has a similar solution for recycler view. You can look at that for reference.
