### ISSUE TITLE
How to publish to jitpack.io

### ISSUE THREAD

**Issue by SureshTimma** [PierfrancescoSoffritti/android-youtube-player#1157]
I have done some changes. But Im unable to publish to jitpack.io

**Comment by PierfrancescoSoffritti** [comment]
I don't think I can help you with this, have a look at their documentation :)

**Comment by SureshTimma** [comment]
> I don't think I can help you with this, have a look at their documentation :)

Where you have published this repo?

Now we are using android youtube player dependencies. If I want to use dependencies of after implementing quality option. Where should I publish to get dependencies

**Comment by PierfrancescoSoffritti** [comment]
You need to either publish your fork on jitpack, or build the aar and add
it to your project locally.

**Comment by SureshTimma** [comment]
> You need to either publish your fork on jitpack, or build the aar and add it to your project locally.

@PierfrancescoSoffritti there are lot of build issues when i tying to publish on jitpack.io
