### ISSUE TITLE
I have found youtube player without redirectint to youtube, but it has all necessary features. How to get this player?

### ISSUE THREAD

**Issue by SureshTimma** [PierfrancescoSoffritti/android-youtube-player#1158]
Here is the screen record video 
https://photos.app.goo.gl/jcTcVmjGBsWaSeMD6

I have taken this video from a app called telugu super humans, which is build on popular course creating platform graphy.

App is in live for 3 years now. But not banned.

Will you please provide those player code. Exactly with those features, without title and youtube logo for redirecting to youtube. Please...

@PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
That looks like Youtube's web player. Which is exactly what this library is using. You can read the documentation of this library and of YouTube IFrame player to see how to customize it :)
