### ISSUE TITLE
I found a app using youtube player but having quality changing option but not default iframe player

### ISSUE THREAD

**Issue by SureshTimma** [PierfrancescoSoffritti/android-youtube-player#1162]
App name is: telugu super humans

**Comment by SureshTimma** [comment]
> App name is: telugu super humans

I want that player. How to do that.

**Comment by PierfrancescoSoffritti** [comment]
Can you provide a video showing the player?

**Comment by SureshTimma** [comment]
> Can you provide a video showing the player? and a link to the app.

It's surely a custom youtube player. Please check video and app and tell how to create exact player. Please.

Video Link: https://drive.google.com/file/d/1ulFNg_dQUvn4Qf2cBsmqR-TS3LRbZaRq/view?usp=drivesdk

App Link: https://play.google.com/store/apps/details?id=com.telugusuperhumans.learners

**Comment by PierfrancescoSoffritti** [comment]
They are using the exact same IFrame Player we are using. We also show quality setting, please refer to the sample app.

**Comment by SureshTimma** [comment]
> They are using the exact same IFrame Player we are using. We also show quality setting, please refer to the sample app.

But you sample app having share option. When click on share or youtube logo or title it redirecting to youtube app

**Comment by SureshTimma** [comment]
I want custom ui and quality option. Like the video I have shared

**Comment by PierfrancescoSoffritti** [comment]
They are using the IFrame player, which we are also using. If you want to play around with the IFrame player's settings you can use [options](https://github.com/PierfrancescoSoffritti/android-youtube-player?tab=readme-ov-file#iframeplayeroptions) (more doc [here](https://developers.google.com/youtube/player_parameters)).

They are showing a native overlay ontop of the player, you can do that with regular Android or by adding a custom UI to this player.

**Comment by SureshTimma** [comment]
Im unable to understand. Is it possible to turn off title, youtube logo and share options in iframe player?

**Comment by PierfrancescoSoffritti** [comment]
I don't know, you can try a combination of the options provided in those links. If it's not possible it means that app is using [css tricks](https://github.com/PierfrancescoSoffritti/android-youtube-player?tab=readme-ov-file#remove-annoying-views) to remove the logo.

I don't recommend doing that as it breaks YouTube terms of service.

**Comment by SureshTimma** [comment]
> I don't know, you can try a combination of the options provided in those links. If it's not possible it means that app is using [css tricks](https://github.com/PierfrancescoSoffritti/android-youtube-player?tab=readme-ov-file#remove-annoying-views) to remove the logo.
> 
> I don't recommend doing that as it breaks YouTube terms of service.

Ok
