### ISSUE TITLE
JCenter being shut down

### ISSUE THREAD

**Issue by tkcsam** [PierfrancescoSoffritti/android-youtube-player#1164]
How is this library affected by the JCenter shutdown?  I'm assuming some dependencies are hosted there as now I cannot build

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

   > Could not find com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/pierfrancescosoffritti/androidyoutubeplayer/core/10.0.5/core-10.0.5.pom
       - https://jcenter.bintray.com/com/pierfrancescosoffritti/androidyoutubeplayer/core/10.0.5/core-10.0.5.pom
       - https://repo.maven.apache.org/maven2/com/pierfrancescosoffritti/androidyoutubeplayer/core/10.0.5/core-10.0.5.pom
       - file:/root/.m2/repository/com/pierfrancescosoffritti/androidyoutubeplayer/core/10.0.5/core-10.0.5.pom
       - file:/root/dist/project/android/app/libs/core-10.0.5.jar
       - file:/root/dist/project/android/app/libs/core.jar
       - file:/root/dist/project/android/capacitor-cordova-android-plugins/src/main/libs/core-10.0.5.jar
       - file:/root/dist/project/android/capacitor-cordova-android-plugins/src/main/libs/core.jar
       - https://www.jitpack.io/com/pierfrancescosoffritti/androidyoutubeplayer/core/10.0.5/core-10.0.5.pom

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to update to the latest version: `12.1.0`.
