### ISSUE TITLE
Add OnSwipe Listener

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#117]
Hi!

It's possible add to the YoutubePlayerView a OnSwipeListener?

**Comment by PierfrancescoSoffritti** [comment]
Hi, YouTubePlayerView is a regular View, you can listen for swipes in the same way you do for any other View.

**Comment by PierfrancescoSoffritti** [comment]
mmm that depends on how you handle the full screen logic I guess.
I can guarantee you that on the library's part nothing is being overlapped to the YouTubePlayerView.

**Comment by Trusted97** [comment]
Well I've try with other view and problem it's only on YouTubePlayerView.

**Comment by Trusted97** [comment]
As i said 
`The video in fullscreen is added after the activity is started and on the most top of the view stack so everything is under it.`

Maybe a function like OnVideoStarted like the Api of Youtube where could you add something transparent and add the listener to him could solve the problem

But i think that make a OnSwipeOnYTBView() listener is a more elegant method maybe with the possibility to recognize if is a LeftSwipe or a RightSwipe, it could be useful for example load previous and next video without viewpager.

**Comment by PierfrancescoSoffritti** [comment]
> The video in fullscreen is added after the activity is started and on the most top of the view stack so everything is under it.

I really don't think this is the case, if you're detecting gestures on the view.
It is if you're detecting gestures on other views, maybe even if you're detecting gestures on the Activity. I'm not 100% sure of the last one though.

> But i think that make a OnSwipeOnYTBView() listener is a more elegant method maybe with the possibility to recognize if is a LeftSwipe or a RightSwipe, it could be useful for example load previous and next video without viewpager.

This goes outside the scope of library. I prefer not to add noise to the API. (You don't need to use a ViewPager to change video, you can simply load ore cue a new video in the YouTubePlayer.)

> Maybe a function like OnVideoStarted like the Api of Youtube where could you add something transparent and add the listener to him could solve the problem

You can already listen for "video started" events, just listen to the `@PlayerConstants.PlayerState.State.PLAYING` event in the `onStateChange` of a `YouTubeListener`.


Also, if you need to have more control over the UI, I suggest you take a look at [this alternative](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/Replace-the-player%27s-UI).
