### ISSUE TITLE
Please kindly share either documentation or  the Java code sample for custom-ui

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1172]
my Best Friends,

This is friendly reminder for Please kindly share either documentation or  the Java code sample for custom-ui same as following Kotlin Samples,

https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/custom-ui/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/customui

[](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/custom-ui/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/customui)

Thanks for consideration,
truly yours,
All the Best,
Kindest and Warmest Regards,
Sincerely,
Pooya M (Ryan)

**Comment by PierfrancescoSoffritti** [comment]
[We have documentation](https://github.com/PierfrancescoSoffritti/android-youtube-player?tab=readme-ov-file#defaultplayeruicontroller) for the custom-ui module.
