### ISSUE TITLE
Please kindly share either documentation or  the Java code sample for chromecastsender  

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1173]
Best Friends,

This is friendly reminder for Please kindly share either documentation or  the Java code sample for chromecastsender  same as following Kotlin Samples,

https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-sender/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/chromecast/chromecastsender

[](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-sender/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/chromecast/chromecastsender
)

Thanks for consideration,
truly yours,
All the Best,
Kindest and Warmest Regards,
Sincerely,
Pooya M (Ryan)

**Comment by PierfrancescoSoffritti** [comment]
We have both [documentation](https://github.com/PierfrancescoSoffritti/android-youtube-player?tab=readme-ov-file#chromecast-extension-library) and [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-sender-sample-app) for the chromecast module.
