### ISSUE TITLE
Background play not working

### ISSUE THREAD

**Issue by AsifPatan** [PierfrancescoSoffritti/android-youtube-player#1184]
# Question / Problem
Cannot play video in background @PierfrancescoSoffritti 

Platform used
I used for my Android application using Kotlin

### Summary
Video stops playing when the app is situated into the recent apps on the application losses focus. But if we switch to other application(which is also playing video) from the app then it plays in background 

### What I've tried
lifecycleOwner.getLifecycle().addObserver(youTubePlayerView)
YouTubePlayerView.enableBackgroundPlayback(true).

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to remove the lifecycle observer, then it should work.

Although background playback is against YouTube terms of service, so don't do it if you intend to publish on Google Play.

**Comment by AsifPatan** [comment]
Thanks for your reply. I got it @PierfrancescoSoffritti
