### ISSUE TITLE
Feature Request: Display Video Upload Date and Channel Name

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1187]
Subject: Feature Request: Display Video Upload Date and Channel Name
Dear YouTube Android Player API Team,
I'm writing to suggest a new feature for the YouTube Android Player API: displaying the video's upload date and channel name.
Current Behavior:
Currently, when a video is played using the API, the video title and duration are displayed.
Proposed Feature:
I propose adding the following information to the video player interface:
1. Video Upload Date: Display the date when the video was uploaded to YouTube.
2. Channel Name: Show the name of the channel that uploaded the video, especially during the initial playback.
Rationale:
* Enhanced User Experience: Providing additional context about the video, such as the upload date and channel name, can enrich the user's viewing experience.
* Improved Video Discovery: Users may be more inclined to explore other videos from the same channel or with similar upload dates.
* Better Understanding of Content: Knowing the upload date can give users insights into the relevance and timeliness of the video.
I believe that implementing this feature would significantly enhance the functionality and user experience of the YouTube Android Player API.
Thank you for considering this request.
Sincerely, 
Kindest and Warmest Regards,
Truly Yours,
Pooya Mohammadhossein (Ryan) 
Senior Computer Engineer (Zero)

**Comment by PierfrancescoSoffritti** [comment]
Hi, same as #1183 - this is out of scope.
