### ISSUE TITLE
develop Youtube  Frame player API library

### ISSUE THREAD

**Issue by pooya-mohammadhossein** [PierfrancescoSoffritti/android-youtube-player#1191]
@PierfrancescoSoffritti 

Dear Bestie, (Best of the Best) 

The questions is :  why nobody are not contributing to develop Youtube  Frame player API library?

the second questions is why  IFrame player's library is not open source? as you are aware, if they make it open source then it gets several advantages like more contributing developers are working on both  iframe Library and [PierfrancescoSoffritti] android-youtube-player) Library etc.

also please consider your library and FreeTube Library are open sources and are available on Github. please take a look at following GitHub link : [](https://github.com/FreeTubeApp/FreeTube )

Sincerely ,
truly tours.
Pooya

**Comment by PierfrancescoSoffritti** [comment]
The IFrame Player is developed and owned by YouTube.
