### ISSUE TITLE
Is there a way to ensure that ads are displayed in the player?

### ISSUE THREAD

**Issue by shahwaiz90** [PierfrancescoSoffritti/android-youtube-player#1192]
Is there a way to ensure that ads are displayed in the player? If the library is programmatically removing ads, it would violate YouTube's terms and conditions, making it unsuitable for use or upload to the Play Store

**Comment by shahwaiz90** [comment]
Is there a way to ensure that ads are displayed in the player? If the library is programmatically removing ads, it would violate YouTube's terms and conditions, making it unsuitable for use or upload to the Play Store

**Comment by shahwaiz90** [comment]
I saw a comment from the author from 1 of the issue,  that iframe player decides when to show the ads. Because I could see the ads when I click on the YouTube icon from player, but not from the player it self. So I assume it's the Player which decides when to show ads or not.

**Comment by PierfrancescoSoffritti** [comment]
Correct, it's up to the IFrame player.
