### ISSUE TITLE
Error at com.pierfrancescosoffritti.youtubeplayer.player.YouTubePlayerBridge$1.run(YouTubePlayerBridge.java:68)

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#120]
Hi!
```
public void onInitSuccess(final YouTubePlayer initializedYouTubePlayer) {
                initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {

                        youTubePlayerView.getPlayerUIController().showUI(false); 
                        YouTubePlayerStateTracker tracker = new YouTubePlayerStateTracker();
                        initializedYouTubePlayer.addListener(tracker);
                        loadVideoInPlayer(initializedYouTubePlayer,"-MkClg7XgRI");
```

If i add the listener i got this error 

> E/UncaughtException: java.util.ConcurrentModificationException
>         at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
>         at java.util.HashMap$KeyIterator.next(HashMap.java:885)
>         at com.pierfrancescosoffritti.youtubeplayer.player.YouTubePlayerBridge$1.run(YouTubePlayerBridge.java:68)

It's an error about library, the way of i have declared the tracker or a my error?

**Comment by PierfrancescoSoffritti** [comment]
Hi, thank you for reporting the issue. This error is due to a limitation in the library.
While I fix the error, do this as a workaround: never add a listener inside of a method of another listener.

```
public void onInitSuccess(final YouTubePlayer initializedYouTubePlayer) {

  YouTubePlayerStateTracker tracker = new YouTubePlayerStateTracker();
  initializedYouTubePlayer.addListener(tracker);

  initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
    @Override
    public void onReady() {
      youTubePlayerView.getPlayerUIController().showUI(false);
      loadVideoInPlayer(initializedYouTubePlayer,"-MkClg7XgRI");
    }
  }
}
```

**Comment by Trusted97** [comment]
I've resolved thank's! If you remember about the problem that YoutubeView doesn't recognize swipe gesture? I've resolve add a Relative Layout to the view and set the listener on it

Happy to help !

**Comment by PierfrancescoSoffritti** [comment]
I've just solved this bug, will be fixed in the next version of the library.
