### ISSUE TITLE
It currently does not show buffering white bar please include code to show it

### ISSUE THREAD

**Issue by raghavsatyadev** [PierfrancescoSoffritti/Android-YouTube-Player#121]
This app will be useful for you : https://play.google.com/store/apps/details?id=com.bimilyoncu.sscoderss.floatingplayerforyoutube

**Comment by PierfrancescoSoffritti** [comment]
Hi, what do you mean with "buffering white bar"?

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks for the suggestion. This feature will be added in one of the next versions.

It can be easily implemented using [this function](https://developers.google.com/youtube/iframe_api_reference#getVideoLoadedFraction) in the IFrame Player.

**Comment by raghavsatyadev** [comment]
I was just going to give you the same link ... still thank you for looking into the issue

**Comment by PierfrancescoSoffritti** [comment]
I have just implemented this feature, it will be available in the next version of the library.

**Comment by raghavsatyadev** [comment]
Can I get any ETA on when you are going to update the library?

**Comment by PierfrancescoSoffritti** [comment]
Before the end of next week!

**Comment by raghavsatyadev** [comment]
Asking for a favour, I am in urgent need of that code. If you have successfully implemented with testing then can I get it through some other means?

**Comment by PierfrancescoSoffritti** [comment]
You can use the current version of the lib and update it next week, you will automatically get the new feature. It's just an UI detail, won't have to change anything in your code.

Otherwise you can download the dev branch and use it locally until the next version is out.

**Comment by raghavsatyadev** [comment]
Thank you very much sir.

**Comment by PierfrancescoSoffritti** [comment]
Hi, version 6.0.0 is now available.
