### ISSUE TITLE
Question: Instantiate programmatically?

### ISSUE THREAD

**Issue by hansemannn** [PierfrancescoSoffritti/Android-YouTube-Player#122]
Hey there, great library first of all! 

I am trying to use this library to instantiate a youtube player programmatically (no xml involved). Is this possible? I was trying to simply pass the current activity to its constructor but that did not seem to work. Any help appreciated, thank you!

**Comment by PierfrancescoSoffritti** [comment]
Hi! yes, it is possible. I have just tried, it works for me.

```
@Override
protected void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  setContentView(R.layout.activity_basic_example);
  
  youTubePlayerView = new YouTubePlayerView(this);
  LinearLayout root = findViewById(R.id.root);
  root.addView(youTubePlayerView);
}
```

let me know if this solves your problem.

**Comment by hansemannn** [comment]
Thanks @PierfrancescoSoffritti, that should do it already!
