### ISSUE TITLE
Audio of YouTube Player still running after gone to idle

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#124]
Hi 

I noticed that when i press the power's button and the smartphone go in idle the audio of player still running.

I've already try this ma it's seems don't work. Any idea? Or maybe i need to release the player and not the view?

```
@Override
    protected void onDestroy() {
        super.onDestroy();
        YTBView.release();
    }
```

**Comment by PierfrancescoSoffritti** [comment]
You need to pause the player when the Activity/Fragment stops/pauses.

```
public void onPause() {
  super.onPause();
  youTubePlayer.pause();
}
```

or 

```
public void onStop() {
  super.onStop();
  youTubePlayer.pause();
}
```

or, the optimal way to do this is to register the YouTubePlayerView as a Lifecycle observer. If you do this the library will take care of everything.

`getLifecycle().addObserver(youTubePlayerView);`

**Comment by Trusted97** [comment]
`getLifecycle().addObserver(youTubePlayerView);`
This is not agains the policy of PlayStore?

**Comment by Trusted97** [comment]
And where i got the reference for YoutubePlayer?

**Comment by PierfrancescoSoffritti** [comment]
> getLifecycle().addObserver(youTubePlayerView);
> This is not agains the policy of PlayStore?

why should it be.

You won't need a reference to the YouTubePlayer if you add the observer.
Otherwise just save it in a variable somewhere.

**Comment by Trusted97** [comment]
So if i post this app on the Offial Google Play Store i'll not have problem for this?

**Comment by PierfrancescoSoffritti** [comment]
Of course not. It's an API from the Android SDK. 

I am happy to give you any sort of reasonable help, but (as I told you a few days ago) as a rule of thumb: _do a research on the topic before asking questions_. [Google is your friend](https://www.google.it/search?q=android+getLifecycle()&oq=android+getLifecycle()&aqs=chrome..69i57j0.3400j0j7&sourceid=chrome&ie=UTF-8).

**Comment by Trusted97** [comment]
I'm really sorry for wasting you time...

Thank's again..

**Comment by PierfrancescoSoffritti** [comment]
No worries. Just a general best practice to do well on the internet eheh

**Comment by PierfrancescoSoffritti** [comment]
If, after reading on the topic, you'll have any question left unanswered I'll be happy to help.
