### ISSUE TITLE
Player is not running in background

### ISSUE THREAD

**Issue by gonzalonm** [PierfrancescoSoffritti/android-youtube-player#128]
I want to keep the player alive when the app is in background. I'm getting `unregisterAudioFocusListener...` from logs and the player stops. Are there any ways to keep it alive in background? I tried with a Service but it didn't work.

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes, just don't pause the player when the Fragment/Activity pauses. That means: do not call the `pause()` method on `YouTubePlayer` and/or don't register `YouTubePlayerView` as a lifecycle observer.

Remember that you won't be able to publish on the PlayStore an app with that behavior.

You can read more [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/Useful-info#play-youtube-videos-in-the-background).

Let me know if this helps.

**Comment by gonzalonm** [comment]
Great, thanks for your response. I think it's done now and I can close it

**Comment by PierfrancescoSoffritti** [comment]
You're welcome!

**Comment by divjad---** [comment]
Hello,
I tried with this but the player still stops when app is in the background. I also called play() method in onPause and onStop in Activity, but it is still not working.

**Comment by PierfrancescoSoffritti** [comment]
Don't register `YouTubePlayerView` as lifecycle observable.

**Comment by divjad---** [comment]
Thank you for your quick reply. I have commented the line where
YouTubePlayerView is registered as observable and it still doesn't work. Do
you have any idea why?

V V čet., 12. jul. 2018 ob 20:19 je oseba Pierfrancesco Soffritti <
notifications@github.com> napisala:

**Comment by PierfrancescoSoffritti** [comment]
If you're not calling `pause()` and are not observing lifceycles it should work. Unfortunately I can't say much about your code. Try to debug it and let me know.

**Comment by divjad---** [comment]
Well actually I have just copy pasted the code from github and commented
the line where YouTubePlayerView is registered as observable, so I haven't
made any changes.

**Comment by PierfrancescoSoffritti** [comment]
@divjad--- You're right, it doesn't seem to work anymore. Not sure why. Maybe they changed something in  WebView?

**Comment by PierfrancescoSoffritti** [comment]
Let me know if you discover something new.

**Comment by divjad---** [comment]
Will do, and you please write me an email if you manage to solve the issue.

**Comment by CajetanP** [comment]
Has anyone made any progress on the issue?

**Comment by PierfrancescoSoffritti** [comment]
Hey, unfortunately I haven't had time to look into it yet

**Comment by CajetanP** [comment]
It looks very weird, as if when the activity is paused the WebView completely removed itself. When the activity is resumed the video doesn't even pick up where it left off but goes back to start.

I tried logging to see which methods get called when I pause or stop the activity. No matter what I do I only see the log statements from initWebView, play, pause, initalize and loadVideo while the log statement from destroy never appears, even if I kill the app.
Also tried overriding WebViewYouTubePlayer's onPause to log and see if it gets called when I pause the activity but apparently no, its log statement never appears either.

**Comment by PierfrancescoSoffritti** [comment]
This issue will be fixed in the next release. It will be possible to enable background playback by calling `YouTubePlayerView.enableBackgroundPlayback(true)`. For more info please refer to the doc.

**Comment by devbest555** [comment]
hi @PierfrancescoSoffritti 
I got error when I play the youtube video in background.
here is my test :
1. start the app and then stream plays
2. turn off the screen manually using device button
3. listening the sound for 25/10/5/4 mins.(it is random)
4. stop playing the stream.
