### ISSUE TITLE
seekto more precisely playback position

### ISSUE THREAD

**Issue by 3to15gram** [PierfrancescoSoffritti/Android-YouTube-Player#129]
I added android-youtube-player for improve my own project, and it works so pretty.
I think the function YouTubePlayer.seekto(final int time) has more precisely seek videos.
My suggestion is add method YouTubePlayer.seekTo(final float time) using this;
http://jsfiddle.net/jlmcdonald/sq2dV/1/

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks for using the lib :)

I agree, the time should be converted to a float. Also for a matter of consistency with the other APIs.

**Comment by PierfrancescoSoffritti** [comment]
Fixed, the change will be there in the next version of the library.
