### ISSUE TITLE
Vertical video full screen

### ISSUE THREAD

**Issue by kosdex** [PierfrancescoSoffritti/Android-YouTube-Player#130]
Is it possible set full screen vertical video?  (Portrait orientation)
I have tried and unfortunatly vertical video is not full screen.

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes it is possible. That's actually the default behavior. Right now I m not at my pc, I can send you a code example tomorrow. 

You can see an example in the Custom UI example in the sample app. Obviously the ui has been changed there, but if you press the "exit/enter full-screen" button you ll see the player going full screen in portrait mode.

**Comment by PierfrancescoSoffritti** [comment]
Oh i see, you have a vertical video and you want that to be full screen. That behavior is not supported at the moment. But I'll definitely look into it. Feel free to send a pull request yourself!

**Comment by kosdex** [comment]
Oh, I changed a test video and got full screen of vertical video.  I don't know why, but some videos are ok, some are not full screen. For example this https://www.youtube.com/watch?v=tIIii02sL6s is OK.

**Comment by PierfrancescoSoffritti** [comment]
Can you send me the link of the video that wasn't going full screen as expected?

**Comment by kosdex** [comment]
This one doesn't fit full screen https://www.youtube.com/watch?v=p9J2lrgxSoE

**Comment by PierfrancescoSoffritti** [comment]
The second video hasn't been recorded in portrait mode. It has the usual ratio and two black bars on the sides. 

Open them in the YouTube app to see that they are different.

**Comment by ghozien** [comment]
how to fullscreen in landscap mode?

**Comment by PierfrancescoSoffritti** [comment]
@ghozien you can start by looking at how it is implemented in the [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/basicExample/BasicExampleActivity.java#L117).

**Comment by shatil-zz** [comment]
> Is it possible set full screen vertical video? (Portrait orientation)
> I have tried and unfortunatly vertical video is not full screen.

Is this issue solved?
I can not show vertical videos in full screen. There is always black side bars and the actual video looks very small in both portrait and landscape mode

**Comment by EpariNigam** [comment]
I also want to center Fit / center Crop  the video. Is there any solution for this yet?

**Comment by malliaridis** [comment]
@shatil-zz Have you checked out the [complete example](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample)?
There you can just comment out the line 107 from [CompleteExampleActivity.java](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample/CompleteExampleActivity.java) where you force landscape orientation. 
```java
// This line can be commented out
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
```
That way you achieve a full screen for portrait videos. A dynamic recognition of video aspect ratioformat seems not feasible yet.

**Comment by malliaridis** [comment]
@EpariNigam does that maybe provide a solution / workaround for your problem too?
