### ISSUE TITLE
Additional IFrame sources

### ISSUE THREAD

**Issue by JmoodUSA** [PierfrancescoSoffritti/Android-YouTube-Player#131]
This lib is actually really cool. If I want to use it to show different sources how hard would it be to fork your repo and make the relevant changes. As an example if I had an embedded link for another IFrame how hard would it be to modify your library to accommodate this source aswell and use your player?

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks! 
I'm not sure I understand your question, what do you mean with "an embedded link for another IFrame"?

**Comment by JmoodUSA** [comment]
Hi Sorry dont think I explained my question very well.

Am I correct in assuming this library take an IFrame of a youtube video, serves it in a webview on the device but then you hide the webview and uses a custom player to show the iframe content instead? If so my question is given any random IFrame (not youtube iframe) can I modify this library to work with any iframe content?

**Comment by PierfrancescoSoffritti** [comment]
> Am I correct in assuming this library take an IFrame of a youtube video, serves it in a webview on the device but then you hide the webview and uses a custom player to show the iframe content instead

This library uses the [YouTube IFrame API](https://developers.google.com/youtube/iframe_api_reference), the player you see is the IFrame player. I hide and replace the UI of the IFrame player with a native UI.

> my question is given any random IFrame (not youtube iframe) can I modify this library to work with any iframe content?

I suppose the other random IFrame would be another media player of some sort. The answer is yes, provided that you can listen to its internal events and call its methods via Javascript (play/pause, volume changes etc).

**Comment by JmoodUSA** [comment]
I may take a crack at it and let you know how it goes :) time to look through your code and understand how it works :D

**Comment by PierfrancescoSoffritti** [comment]
Sure, feel free to ask any question about the code, if you have any!
Also consider leaving a star on GitHub if you like the library :)

**Comment by JmoodUSA** [comment]
left a star :) Could you just direct me to 

1) the main class that shows the player, 2) hiding the player 3) where you call the js functions. Then I will take .a look at modifying it myself.

Do you think it will be much work? I definitely am going to try it regardless.

**Comment by PierfrancescoSoffritti** [comment]
1. The main Android class of the library is [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayerView.java)
2. The webview/player is [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/WebViewYouTubePlayer.java)
3. Javascript function and IFrame player are [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/res/raw/youtube_player.html)
4. Java-Javascript bindings are [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayerBridge.java)

Examples of usage are in the [sample module](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/tree/master/sample).
