### ISSUE TITLE
Floating Player

### ISSUE THREAD

**Issue by gonzalonm** [PierfrancescoSoffritti/Android-YouTube-Player#133]
I want to replicate a similar behavior like this one: https://github.com/advaita13/YouTubeFloatingPlayer Keep video playing in a small view (without stop video in transition). Are there any way to do that behavior?

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes, the YouTubePlayerView is just a View, you can do whatever you want with it.

I remember seeing a library (unfortunately I don't remember its name) implementing the "swipe down behavior" from the YouTube app, you could use that or [implement the animation yourself](https://github.com/burhanrashid52/YoutubeUX).

**Comment by gonzalonm** [comment]
Great!! Thanks for you quick response!!

**Comment by gonzalonm** [comment]
I think this is the library (https://github.com/pedrovgs/DraggablePanel) unfortunately it was deprecated :(

**Comment by PierfrancescoSoffritti** [comment]
mm it may be. You could try to implement it yourself, it shouldn't be too complicated. You have the example from that library ;)

**Comment by gonzalonm** [comment]
Yes, I'm working on that! Thanks again

**Comment by PierfrancescoSoffritti** [comment]
You're welcome :)
