### ISSUE TITLE
Error when I try to build apk after implementing the code and the library

### ISSUE THREAD

**Issue by leketemi** [PierfrancescoSoffritti/Android-YouTube-Player#134]
I implemented the code according to the instruction in the tutorial but when I tried to build the apk it shows the following error:
Error:(20, 26) error: cannot access LifecycleObserver
class file for android.arch.lifecycle.LifecycleObserver not found

**Comment by PierfrancescoSoffritti** [comment]
Hi, is your activity extending AppCompatActivity?

You don't usually need to import any library, but just in case you can import it as explained [here](https://developer.android.com/topic/libraries/architecture/adding-components).

Or, if you don't want to add the player as a lifecycle observer you can just not register it and call destroy and pause yourself, as explained [here](https://developer.android.com/topic/libraries/architecture/adding-components).

**Comment by leketemi** [comment]
Thanks for the reply. Yes, my activity extended  AppCompatActivity.

**Comment by PierfrancescoSoffritti** [comment]
which version of appcompat are you using?

**Comment by leketemi** [comment]
'com.android.support:appcompat-v7:25.3.1'. 
I think it's going to work. I'll like to make a request from you, I don't know if you can be like a mentor to me because I'm still a begininer in android. So if you like to help me please give me your twitter and whatsApp(for direct comminucation) address, or send it to my mail: leketemi@gmail.com. Thanks.

**Comment by PierfrancescoSoffritti** [comment]
You need to updated app compat to its last version `com.android.support:appcompat-v7:27.1.1`. If you use the last version you won't need any extra library to use lifecycle observers.

Regarding your request: I am quite busy and therefore won't be able to help you in real time, also this days it's quite easy to learn Android development on the internet (that's how I've learned some years ago). But feel free to ask specific questions if you have any, you can find my email on my github profile.

I will be able to answer only **questions you have already researched on your own** and asked in a **clear and specific format**.

**Comment by leketemi** [comment]
Thanks.
