### ISSUE TITLE
Consider replacing PlayerConstants primitive values with enums

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [PierfrancescoSoffritti/Android-YouTube-Player#137]

**Comment by UGhari** [comment]
Wouldn't this be a bad idea? To my understanding Enums aren't great for Android apps, and take up a lot more memory space in comparison to your current implementation

**Comment by PierfrancescoSoffritti** [comment]
Yeah, enums do take more space than primitives. This optimization made more sense a few years ago than now though. In 2018 this isn't much of an issue anymore, it starts to feel like a micro optimization.

Using enums would improve readability, without significant downsides.

I'll have a look at what other libraries are doing, to get a sense of what is the most common practice for open source code!
