### ISSUE TITLE
Video Mute

### ISSUE THREAD

**Issue by pushkarhike** [PierfrancescoSoffritti/Android-YouTube-Player#141]
Is there a video mute option available?

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes: [`YouTubePlayer.setVolume(0)`](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayer.java#L26)
