### ISSUE TITLE
How To Get The Stream URL Of The Video Being Loaded/Cued?

### ISSUE THREAD

**Issue by naseemali925** [PierfrancescoSoffritti/Android-YouTube-Player#142]
Is There Any Way This Library Can Get us The Stream URL Of The Video Being Played?

**Comment by PierfrancescoSoffritti** [comment]
What do you mean with "stream URL"? A url to the mp4 video?

**Comment by naseemali925** [comment]
YouTube Video Link : https://www.youtube.com/watch?v=qYAiAivwTvc

Stream URL For The Video Is Below.
https://r1---sn-4g5e6n7d.googlevideo.com/videoplayback?source=youtube&mv=m&ms=au%2Conr&mt=1527245466&key=yt6&ip=148.251.121.25&lmt=1516263545752992&c=WEB&initcwndbps=1251250&fvip=1&mm=31%2C26&itag=22&mime=video%2Fmp4&id=o-AJreR2h8PA2k659nFIOXRvi6W2V5xcbHiaxeBrTGaRNn&mn=sn-4g5e6n7d%2Csn-5hne6nlr&dur=194.676&requiressl=yes&expire=1527267201&sparams=dur%2Cei%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ei=IOsHW_zdOcyc1gK1gJygDA&ipbits=0&ratebypass=yes&pl=21&signature=918E822B01DF7865789B04C773138D4711CF9279.C49350C3DB6970C27976BD33BB162CD2E8898B6F&video_id=qYAiAivwTvc&title=Coca+Cola+Tu+-+Tony+Kakkar+ft.+Young+Desi

**Comment by PierfrancescoSoffritti** [comment]
No, this feature won't be added to the library. The scope of this library is only to play YouTube videos. If this functionality is needed it can be implemented outside of the player.
