### ISSUE TITLE
Youtube watermark logo doesnot respond to click action

### ISSUE THREAD

**Issue by rajeefmk** [PierfrancescoSoffritti/Android-YouTube-Player#146]
Since this comes as part of the iframe, I'm not sure if the library can do anything about it. I was wondering would this violate youtube's policy of not to disable default click actions. 

Any thoughts on this ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, does such a policy exists? never heard of it.
In any case, I'm quite sure it's not an issue.

**Comment by rajeefmk** [comment]
@PierfrancescoSoffritti Sorry I couldn't post back earlier. So I was referring to this doc https://developers.google.com/youtube/terms/developer-policies#g-distribution-and-commercial-use

But since your sample app is on the playstore for all this while and it also behaves the same ( ie the watermark is disabled), I guess it's safe. 

Thanks.

**Comment by PierfrancescoSoffritti** [comment]
Are "default click actions" mentioned somewhere? I've not been able to find it.

**Comment by rajeefmk** [comment]
@PierfrancescoSoffritti You're right. I was reading the following (2.c Branding) and must have misinterpreted it. 

_You and your API Clients must not, and must not encourage, enable or require others to, directly or indirectly, interfere with or obscure any attribution provided by YouTube, including attribution provided via or shown in embedded YouTube players. Your API Clients must display applicable YouTube Brand Features and any other YouTube-provided attribution on all types of devices._

**Comment by PierfrancescoSoffritti** [comment]
Yeah, that shouldn't be an issue! thanks anyway for pointing it out :)
