### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/Android-YouTube-Player#147]
@PierfrancescoSoffritti : 
Hi, first of all I wanted to congratulate you.

Let's start with the questions:
1) it would be possible to use your module also with normal videos, not just those of youtube.
if so how can I do?
2) You can add the thing of the division of the screen, that if you click on the video on the right / left you can go back / forward in the video.
I would like to do something like this: https://drive.google.com/file/d/1Vg-C_LYVvCW9gqXpfGPB5Fg6h_ekAx29/view
3) I tried apk, I do not know if a bug or not, in the basic example version.
As it is on full screen there is both the stop button and the player button.
4) I tried apk, the pictureInPicture, but I did not understand what it does.
5) it would be possible to give the possibility to change the color of the loading, of the time bar of the video and of the advancing ball.

I'll ask you all these questions, for point 1), because I would like to create a bridge for react-native.

**Comment by PierfrancescoSoffritti** [comment]
Hi,
1. This is a YouTube player, it works only with YouTube videos. If you need to play something else through a web-based player, feel free to fork the library and apply the required changes.
2. Issue #132.
3. It's to showcase a feature of the player, you can add more actions other than play/pause.
4. [Picture In Picture](https://developer.android.com/guide/topics/ui/picture-in-picture). Google is everybody's friend.
5. You can already do that. The color of those Views is the accent color of your app.

**Comment by Angelk90** [comment]
@PierfrancescoSoffritti: 
I tried to take a quick look at the code, are you telling me that there is something under the web that makes everything work for youtube and I do not talk about the bees?

**Comment by PierfrancescoSoffritti** [comment]
This library is built on top of the [YouTube IFrame API](https://developers.google.com/youtube/iframe_api_reference).

**Comment by Angelk90** [comment]
@PierfrancescoSoffritti : 
2)
How can I try it?
How did you implement it graphically?

I was thinking of using exoplayer, but I do not know how to graphically implement the part of the screen in two.
For the moment I did this: https://pastebin.com/riXk9GHN
Can you give me some advice?

**Comment by PierfrancescoSoffritti** [comment]
You need two Views, each view has to cover one half of the screen. From there is just a matter of detecting a double tap on each view.

I'm going to implement it in the library, as soon as I'll have some free time.

**Comment by Angelk90** [comment]
@PierfrancescoSoffritti :  Can I contact you privately?

**Comment by PierfrancescoSoffritti** [comment]
If you have questions about the library, open issues on GitHub, they may be helpful for other people as well.

If the questions are not related to the library, send me an email.
