### ISSUE TITLE
Added OnSwipeTouchListener

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#148]
I've got some problem when i try to make a pull request, i hope to help you and solve the [Issues #117 ](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/issues/117)

OnSwipeTouchListener Class: https://pastebin.com/KZtiK42Z

```

YTBLayout.setOnTouchListener(new OnSwipeTouchListener(YourActivity.this) {
            @Override
            public boolean onSwipeRight() {
                Toast.makeText(YourActivity.this, "right", Toast.LENGTH_SHORT).show();
                return true;
            }
            @Override
            public boolean onSwipeLeft() {
                Toast.makeText(YourActivity.this, "left", Toast.LENGTH_SHORT).show();
                return true;
            }
        });

```

**Comment by PierfrancescoSoffritti** [comment]
Hi! thanks for the help! but as mentioned in the issue you referenced:

> > But i think that make a OnSwipeOnYTBView() listener is a more elegant method maybe with the possibility to recognize if is a LeftSwipe or a RightSwipe, it could be useful for example load previous and next video without viewpager.

> 
> This goes outside the scope of library. I prefer not to add noise to the API.

I don't think adding a swipe listener to the library is a good idea. The YouTubePlayerView is a View, therefore users of the library are free to implement listeners on their own code.

Starting from version 5.0.0 it's also possible to [completely customize the player's UI](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/Replace-the-player%27s-UI), that reduces even more the need to have specific UI features implemented in the library.
