### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by JRascagneres** [PierfrancescoSoffritti/Android-YouTube-Player#149]
Hello,
Is there a way to make the player become full screen - It just seems to fill its current parent whereas I want it to fill the entire screen. Is this possible?
Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi,
1st approach:  yes, make the parent full screen. In Android a View can only fit its parent (I recommend doing this).
2nd approach: you may try to find the size of the screen and manually set it to the AndroidPlayerView.

If you find the library useful, consider leaving a star on GitHub :)

**Comment by Abdul-Aziz-Niazi** [comment]
How will I receive if full screen button is pressed?

**Comment by PierfrancescoSoffritti** [comment]
You can use `PlayerUIController.setCustomFullScreenButtonClickListener`,
