### ISSUE TITLE
Why the Sample Project APK is removed from play store ?

### ISSUE THREAD

**Issue by thatsankur** [PierfrancescoSoffritti/Android-YouTube-Player#150]
Hi Pierfrancesco,

Why the Sample Project APK is removed from play store ?

is there any policy violation issue ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, no policy violation. 

The sample is temporarily down because the name of the app didn't explicitly stated that it was not affiliated with YouTube (the company) and therefore got removed. Nothing to do with the player.
The name should be something like: "{name of the app} **for YouTube**"

I will re upload it soon, with a different name.

**Comment by thatsankur** [comment]
Thanks for clarification 👍

**Comment by ambiguous1991** [comment]
Sorry to barge in.
Should my final app, which is using your library, state that it is not
affiliated with YouTube in, say, the description?
Thanks

sob., 16 cze 2018, 07:44 użytkownik Pierfrancesco Soffritti <
notifications@github.com> napisał:

**Comment by PierfrancescoSoffritti** [comment]
**Just to clarify: this has nothing to do with this library, you are required to do the same if you're using the official YouTube Player API.**

To answer your question: you have to say it in the description, but most importantly in the name of the app. As I'm doing [here](https://play.google.com/store/apps/details?id=com.pierfrancescosoffritti.shuffly&hl=en).

[This page](https://play.google.com/about/ip-impersonation/impersonation/) may be useful.

**Comment by PierfrancescoSoffritti** [comment]
New sample app published here: https://play.google.com/store/apps/details?id=com.pierfrancescosoffritti.aytplayersample

**Comment by uzaysan** [comment]
Do i have to add youtube to end of the name.Can my app name be just "mountain" for example?
