### ISSUE TITLE
not working by videoid include special character

### ISSUE THREAD

**Issue by hairgely** [PierfrancescoSoffritti/Android-YouTube-Player#151]
I try play video.
there are two youtube videos.

 - https://www.youtube.com/watch?v=ieNDZQosCNk
 - https://www.youtube.com/watch?v=G6HX9m_ileY&t=28s

[ieNDZQosCNk] is ok. 
but [G6HX9m_ileY&t=28s] is not working.

If the VIDEO_ID contains a special character, it will not play. 

Is there a solution?

**Comment by PierfrancescoSoffritti** [comment]
Hi, "&t=28s" is not a special character. It tells YouTube to start playing the video from second 28.
The id of the video is just "G6HX9m_ileY". 

When you play a video (with loadVideo or cueVideo), you need to pass the start time as the second parameter of the method. In this cast it would be: `loadVideo("G6HX9m_ileY", 28f)`

**Comment by hairgely** [comment]
Thank you for your reply. And you're right.
It was not a special character. It was a parameter.
Thank you. Thanks to you.

**Comment by PierfrancescoSoffritti** [comment]
You're welcome! If you're finding the library to be useful, feel free to leave star on GitHub :)
