### ISSUE TITLE
Play multiple YouTubePlayerViews at once

### ISSUE THREAD

**Issue by y2dak** [PierfrancescoSoffritti/android-youtube-player#157]
### Question
Hi! I love this library. Is there a way to enable multiple video players playing at the same time? So that when I press play on a second player, the first one isn't paused? Thanks!

**Comment by PierfrancescoSoffritti** [comment]
Hi, I think it should be doable, considering that the player is just running in a WebView. Unfortunately at the moment I don't really know how to do it.
Feel free to fork the library and explore, any contribution is welcomed :)
