### ISSUE TITLE
RecyclerView Auto play Video

### ISSUE THREAD

**Issue by girubhai** [PierfrancescoSoffritti/android-youtube-player#158]
First thanks to have great library to play youtube videos in RecyclerView.

As I have seen that in RecyclerView example there is an option to **cuevideo** and when I changed it to **loadVideo** it start auto play but unfortunately it play first then stop it and immediately start second video(below in list).

So is there any option to not start second video if first video is playing/buffering ? Thanks !!

**Comment by PierfrancescoSoffritti** [comment]
Hi, Android automatically stops a player when a new one starts playing. It's up to you to write code to make sure that `loadVideo` is called on one player only.

**Comment by girubhai** [comment]
@PierfrancescoSoffritti  Thanks to reply.
In RecyclerView items, YoutubePlayer have one instance per item and for each item there are different states like Playing, Buffering etc.

So can you please elaborate how can we maintain states of recyclerView ViewHolder item's YoutubePlatyer that next item video will not play if current video is playing.

Thanks !!

**Comment by PierfrancescoSoffritti** [comment]
That's not related to the library. You have to find a way to make sure that you call `loadVideo` only on one player.  I'm not going to write the code for you, I know about this as much as you do :)

good luck!

**Comment by AdamSHurwitz** [comment]
@girubhai - You can keep a variable in your ViewModel to check whether another video is playing.

**Comment by qadeerhm92** [comment]
how to do this in RecyclerView getLifeCycle().addObserver(); can anyone share the code

**Comment by PierfrancescoSoffritti** [comment]
@qadeerhm92 RecyclerView doesn't have a lifecycle. You need to use your activity or fragment lifecycle. If you have more questions about this topic, please open a separate issue. Your problem has nothing to do with this issue.
