### ISSUE TITLE
Getting an error - android.webkit.SafeBrowsingResponse

### ISSUE THREAD

**Issue by equistar** [PierfrancescoSoffritti/android-youtube-player#159]
Device Android 8.0.0

Rejecting re-init on previously-failed class java.lang.Class<vp>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/SafeBrowsingResponse;

07-08 21:15:47.676 25535-25535/com.test.sampleapp I/zygote64: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.webkit.SafeBrowsingResponse" on path: DexPathList[[zip file "/data/app/com.android.chrome-Vm8hy8_u1-Dy5WC4ctZXkQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-Vm8hy8_u1-Dy5WC4ctZXkQ==/lib/arm64, /data/app/com.android.chrome-Vm8hy8_u1-Dy5WC4ctZXkQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]

**Comment by PierfrancescoSoffritti** [comment]
Hi, I'm sorry its hard to say anything with so little information.

**Comment by equistar** [comment]
Hi,

I Really Appreciate the immediate response. Very less people are so fast. I
implemented your library the way you've shown it. It seems that on Android
Oreo you need to use view.getSettings().setSafeBrowsingEnabled(false);
function in iFrames.

Source :
https://stackoverflow.com/questions/49633271/what-is-android-webkit-safebrowsingresponse-error

Can you please check this one and let me know if there is a fix. Also, You
have not asked for the google developer key which is generated from the
developer console. I hope we dont need that.

let me know if you need any specific logs.

Warm Regards,
Vineet Kamath.

**Comment by PierfrancescoSoffritti** [comment]
>  It seems that on Android Oreo you need to use view.getSettings().setSafeBrowsingEnabled(false);
I never had an issue with that, I'll check in a few minutes.

> You have not asked for the google developer key which is generated from the developer console. I hope we dont need that.
This library doesn't need any key.

**Comment by PierfrancescoSoffritti** [comment]
Just tested on Oreo, works fine for me. Which phone are you using?

**Comment by equistar** [comment]
I tried on an lg v30+ and a redmi note 4. The player just keeps loading.
Its 1am at the moment here. Ill make a sample app tomorrow, try it on a few
more devices and if the issue reproduces ill send you that project.

**Comment by PierfrancescoSoffritti** [comment]
Perfect, thanks!

**Comment by PierfrancescoSoffritti** [comment]
Did you manage to solve the issue?

**Comment by equistar** [comment]
Hi Pierfrancesco,

I just solved the issue yesterday. It was giving me an error when I was
calling it in the background Async task in the onPostExecute function while
making a volley request.
So i created a small constructor and then passed the parameters and it
worked out.

Warm Regards,
Vineet Kamath.

**Comment by PierfrancescoSoffritti** [comment]
nice!

feel free to leave a star on GitHub if the library is useful to you :)
