### ISSUE TITLE
new logo/icon

### ISSUE THREAD

**Issue by mansya** [PierfrancescoSoffritti/android-youtube-player#160]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by PierfrancescoSoffritti** [comment]
Hi, actually this project has [a logo](https://raw.githubusercontent.com/PierfrancescoSoffritti/android-youtube-player/master/pics/android-youtube-player_512x512.png). What do you think?

**Comment by mansya** [comment]
can i see it ?

**Comment by PierfrancescoSoffritti** [comment]
It's linked in my previous message. You can also find it in the Readme.

**Comment by mansya** [comment]
give me a time. I will try to make it more interesting again. what do you think?

**Comment by PierfrancescoSoffritti** [comment]
If you have ideas, you're welcome to try :)

**Comment by mansya** [comment]
I have design logo for this project. what dou you think ? do you like it ?


![android youtube player](https://user-images.githubusercontent.com/33461607/42726607-67a8ef0e-87c1-11e8-82ca-e29913741563.png)

I designed it to be interesting and not generic. I designed using a logo like youtube because this project is based youtube. so I only design similar but with different art. for this logo to look unique. sorry for being late

**Comment by PierfrancescoSoffritti** [comment]
Hi, well done :) thanks for putting in the effort. I think I will keep the current icon though! feels more aligned with what the library is. 

thanks anyway :)
