### ISSUE TITLE
YoutubePlayerView not shown in second fragment

### ISSUE THREAD

**Issue by saneef3006** [PierfrancescoSoffritti/android-youtube-player#161]
Hi,

I have fragment which contains the youtubePlayerView. The youtubePlayerView shows fine. But when another instance of the same fragment to the same container in which the previous fragment is displayed, The second fragment does not show the youtubePlayerView. When i press back button, the video which was supposed to be played in the second fragment is being played in the first fragment. Is there any way to solve this issue? I called youtubePlayerView.release() in the first fragment before showing the second fragment.

**Comment by PierfrancescoSoffritti** [comment]
Hi, different instances of YouTubePlayerView are not related. Therefore there should be no issue. Are you sure you are handling your Fragment transactions correctly?

**Comment by saneef3006** [comment]
Sorry. It was an issue with my fragment transactions. Previously I was using add fragment to display fragments. In that scenario,  the playerview is not shown. But when I used replaceFragment() method to display the fragments, it is working properly.

**Comment by PierfrancescoSoffritti** [comment]
Perfect!
