### ISSUE TITLE
Embed Youtube video

### ISSUE THREAD

**Issue by mavyasoni786** [PierfrancescoSoffritti/android-youtube-player#162]
Is this library supported embed youtube urls. Please let me know so we can use your library in android. If yes the provide me some basic details. So i can implement it.

Url : https://www.youtube.com/embed/ynRCYGowBOw?start=60&end=180

Please help me. Thanks in advance.

**Comment by Kostyshina** [comment]
I think that embed it's `embed/ynRCYGowBOw?start=60&end=180`

**Comment by PierfrancescoSoffritti** [comment]
thanks! I don't understand what that has to do with the library though
