### ISSUE TITLE
 Didn't find class "android.webkit.SafeBrowsingResponse" 

### ISSUE THREAD

**Issue by vinayjaiswal** [PierfrancescoSoffritti/android-youtube-player#163]
Didn't find class "android.webkit.SafeBrowsingResponse" on path: DexPathList[[zip file "/data/app/com.android.chrome-lqiQuG606jNbHpnIzq5Eqg==/base.apk"],nativeLibraryDirectories=[/data/app/com.android.chrome-lqiQuG606jNbHpnIzq5Eqg==/lib/x86, /data/app/com.android.chrome-lqiQuG606jNbHpnIzq5Eqg==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
.....................................................................................................................

com.pierfrancescosoffritti.youtubeplayer.player.WebViewYouTubePlayer.<init>(android.content.Context, android.util.AttributeSet, int) (WebViewYouTubePlayer.java:44)

Getting error in run time, please resolve this.

**Comment by PierfrancescoSoffritti** [comment]
Hi, same error as #159.

Refer to that issue or provide more info, I can't say much with so little information.

**Comment by PierfrancescoSoffritti** [comment]
Also, I suggest trying to run the sample app. It should work. If it does, use it as reference to understand what you are doing wrong. If it doesn't, let me know.

**Comment by vinayjaiswal** [comment]
Yes i have run the sample app, but still giving this issue in logcat....video is playing , app is not crashing but you can found the error verbose in logcat. please search with "Safebrowsing" in logcat. I hope you will solve soon.
