### ISSUE TITLE
Repeat video

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#164]
Hi @PierfrancescoSoffritti, Is there a way to repeat the same video as soon as it finishes?

**Comment by PierfrancescoSoffritti** [comment]
Yes, keep track of the state of the player, when it is `ENDEND` just play it again from time 0.

SeekTo 0 and then play should work fine.

All this is explained in the documentation :)

**Comment by Angelk90** [comment]
@PierfrancescoSoffritti : 
We assume that I start from this configuration: https://pastebin.com/aXExMX3g

a) There is a way to do something like this:
`youtubePlayerView.getPlayerUIController().showYouTubeButton(false).showFullscreenButton(false);
`
example a Build method?

the showVideoTitle method does not seem to work.

b) In the documentation I am not able to understand if it is possible to change the color of the seekbar.
  I tried with colorAccent, but it does not change.

c) How can I remove the youtube image (logo) when the video is paused?

d) Considering this post and the post #165 , I'm trying with the onCurrentSecond method, but it seems like I'm doing something wrong?

**Comment by PierfrancescoSoffritti** [comment]
Please open separate issues for separate questions. Just a good practice the keep the issues clean.

**Comment by dhdbseh** [comment]
private float duration2 = 0f;

youTube.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onVideoDuration(@NotNull YouTubePlayer youTubePlayer, float duration) {
                        super.onVideoDuration(youTubePlayer, duration);
                        duration2 = duration;
                    }

                    @Override
                    public void onReady(@NotNull YouTubePlayer youTubePlayer) {
                        super.onReady(youTubePlayer);
                        String url = {your url}
                        youTubePlayer.cueVideo(url, 0); 
                    }

                    @Override
                    public void onCurrentSecond(@NotNull YouTubePlayer youTubePlayer, float second) {
                        super.onCurrentSecond(youTubePlayer, second);
                        if (second >= duration2){
                            youTubePlayer.seekTo(0);
                        }
                    }
                });

**Comment by Alex-rcq** [comment]
@dhdbseh ???
```kotlin
youTubePlayerView.addYouTubePlayerListener(object : AbstractYouTubePlayerListener() {
            override fun onStateChange(youTubePlayer: YouTubePlayer, state: PlayerConstants.PlayerState) {
                if (state == PlayerConstants.PlayerState.ENDED){
                    youTubePlayer.seekTo(0F)
                }
            }
        })
