### ISSUE TITLE
Start the video at a certain minute and let it end in a given minute

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#165]
Hi @PierfrancescoSoffritti, There is a way to start the video at a certain minute and let it end in a given minute?

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes, you can pass the start time of the video as the second parameter of `loadVideo` and `cueVideo`.

To stop the video at a certain time, just keep track of the current time using [`YouTubePlayerListener.onCurrentSecond`](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/player/listeners/YouTubePlayerListener.java#L43) and stop it when it reaches a certain value.
