### ISSUE TITLE
Change the color of the seekbar

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#166]
@PierfrancescoSoffritti : In the documentation I am not able to understand if it is possible to change the color of the seekbar.
I tried with colorAccent, but it does not change.

**Comment by PierfrancescoSoffritti** [comment]
Hi, no, at the moment is not possible to change the color of the seekbar. Could add the feature in the next version.

**Comment by mohitfindoriya** [comment]
It can be change from main.dart
by changing  primaryswatch color in themedata with any material color
