### ISSUE TITLE
Build method

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#168]
@PierfrancescoSoffritti : There is a way to do something like this:
youtubePlayerView.getPlayerUIController().showYouTubeButton(false).showFullscreenButton(false);
example a Build method?

**Comment by PierfrancescoSoffritti** [comment]
Not possible at the moment. Could be considered as an addition for the next version.

**Comment by PierfrancescoSoffritti** [comment]
This won't be implemented, for now.
