### ISSUE TITLE
ShowVideoTitle method does not seem to work.

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#169]
@PierfrancescoSoffritti : I'm not able to make the video name appear in the player.

**Comment by PierfrancescoSoffritti** [comment]
You should set the title of the video, like I'm doing in the sample app. [doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#show-video-title)

**Comment by taimur113311** [comment]
Hi @PierfrancescoSoffritti 

How to hide the video title? 
`        playerView.getPlayerUiController().showVideoTitle(false);
`

i am using above line of code to hide the video title but it does not work for me. Please help

**Comment by PierfrancescoSoffritti** [comment]
It's not possible to remove it from the web player.

**Comment by taimur113311** [comment]
@PierfrancescoSoffritti What do you mean by Web Player? Your plaer is not native one like Android Offical player?

**Comment by PierfrancescoSoffritti** [comment]
> To interact with YouTube the library uses the IFrame Player API, inside of a WebView, therefore the YouTube app is not required on the user's device and there are no issues with YouTube Terms of Service.

please read the doc
