### ISSUE TITLE
Repeat video with start and end time

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#170]
@PierfrancescoSoffritti : We assume that I start from this configuration: https://pastebin.com/aXExMX3g

I'm trying with the onCurrentSecond method, but it seems like I'm doing something wrong?

**Comment by PierfrancescoSoffritti** [comment]
Is this related to #164 ?

I suggest printing the value of of `second` in the logcat to better understand what to do.

**Comment by mavyasoni786** [comment]
I need same functionality. for example We have 10 mins video.  but I want to play only between 2:10mins to 3:15mins. 

This type of functionality can we get by using your library.
