### ISSUE TITLE
getFrameAtTime: videoFrame is a NULL pointer

### ISSUE THREAD

**Issue by zhangming170622** [PierfrancescoSoffritti/android-youtube-player#174]
Hi, Thank you very much for you library!
Now I was debugging example application in android studio.(Android Studio3.1.3)
Video was playing.
By the way, messages show when I tap 'stop app' icon in Android Studio.
Message show "Unfortunately, AndroidYouTubePlayer has stopped ".
I want to your detailed answer.

**Comment by PierfrancescoSoffritti** [comment]
Hi, sorry I don't quite understand the issue. Provide more details if you can.
