### ISSUE TITLE
Initialisation taking time 

### ISSUE THREAD

**Issue by mavyasoni786** [PierfrancescoSoffritti/android-youtube-player#176]
We are facing some issue in initialisation. It is taking some to load youtube video.
Please help us. 

```
 youTubeView.initialize({ initializedYouTubePlayer ->
initializedYouTubePlayer.addListener(object : AbstractYouTubePlayerListener() {
                        override fun onReady() {
                            initializedYouTubePlayer.loadVideo(youtubeId, startTime.toFloat())
                        }
})
},true)
```

**Comment by PierfrancescoSoffritti** [comment]
Hi, the code you posted looks fine. I suggest comparing your app's start time with the start time of the sample app. If they are sensibly different look at the sample app's code to understand what you're doing wrong.
