### ISSUE TITLE
The video sound gets very soft

### ISSUE THREAD

**Issue by mavyasoni786** [PierfrancescoSoffritti/android-youtube-player#177]
I have compared the sounds with YouTube Application.  Sound is working fine in youtube application but in your library it is getting very slow. 
Please help me.

**Comment by mavyasoni786** [comment]
It is low. 
I have used youTubePlayer.setVolume(100) as well. But no effect. :(

**Comment by PierfrancescoSoffritti** [comment]
There's not much I can say, have you tried on different devices?

**Comment by PierfrancescoSoffritti** [comment]
related to #79

**Comment by mavyasoni786** [comment]
Yeah I have tried it but same result. :(

**Comment by PierfrancescoSoffritti** [comment]
I've never faced this issue, let me know if you manage to find a solution!

**Comment by ghozien** [comment]
can it set volume more than 100% ?

**Comment by PierfrancescoSoffritti** [comment]
@ghozien no.

**Comment by ghozien** [comment]
i compare this library volume is 50% low than with youtube app

**Comment by PierfrancescoSoffritti** [comment]
Where does the 50% measurements comes from? On my devices they have the same volume.
