### ISSUE TITLE
Youtube Terms of service violation

### ISSUE THREAD

**Issue by zhangming170622** [PierfrancescoSoffritti/android-youtube-player#178]
Hi, I always appreciate you.
I would like to hear your advice.
Is this method completely legal or does it violate any of youtube's policies and terms of service? Especially considering the webview url contains a proxy link to youtube and not the actual link itself.

**Comment by PierfrancescoSoffritti** [comment]
This is just a wrapper around the YouTube IFrame API, no violations.
