### ISSUE TITLE
Save current Second & the Duration of the video when orientation change

### ISSUE THREAD

**Issue by KostasAnagnostou** [PierfrancescoSoffritti/android-youtube-player#182]
Hello, 

I would like to ask you how can i setup the saved state of the current second and the duration of the video when an activity-fragment is re-created (orientation change).  I use the onStateChange() to get the current second of the video and the video duration (and i'm storing them inside the onSaveInstanceState), but still when the orientation changes the video starts from 0 and after that is going to the saved current Video Second. 

I tried to use youtubePlayer.seekTo(videoSecond) method to set the current second immediately, but without success.. 

Futhermore, i want to setup too the saved video Duration immediately when the orientation changes, but i can't find the way... 

Here is the method inside the Fragment: 

    private void initYouTubePlayerView() {        
        getLifecycle().addObserver(youtubePlayerView);

        youtubePlayerView.initialize(youTubePlayer -> {
            youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                @Override
                public void onReady() {                   
                        loadVideo(youTubePlayer, mSuggestionYoutubeId);                    
                }
            });
            mTracker = new YouTubePlayerTracker();
            youTubePlayer.addListener(mTracker);
            youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                @Override
                public void onStateChange(@NonNull PlayerConstants.PlayerState state) {
                    super.onStateChange(state);
                    videoSecondFloat = mTracker.getCurrentSecond();
                    videoDuration = mTracker.getVideoDuration();                  
                }
            });
        }, true);

        fetchVideoTitle();
    }

Here is the loadVideo Method: 

```
 private void loadVideo(YouTubePlayer youTubePlayer, String videoId) {
        if(getLifecycle().getCurrentState() == Lifecycle.State.RESUMED)
            youTubePlayer.loadVideo(videoId, videoSecondFloat);
        else
            youTubePlayer.cueVideo(videoId, videoSecondFloat);
    }
```

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to manually handle orientation changes, so that the Activity is not recreated. You can read more here #156.

**Comment by KostasAnagnostou** [comment]
Thank you very much for the prompt reply! Yes, this Actvity attribute in the manifest is a solution:
```
android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout" 
```
The thing is that i want to recreate the activity and initialize the video with the saved values (videoSecond + videoDuration) on the PlayerView from the onSaveInstanceState()... 

Thanks again and keep the good work.

**Comment by PierfrancescoSoffritti** [comment]
Oh i see, did you manage to solve the issue? i think you can just save the current time of the player and then cue/load the video by passing the start time as second parameter.

**Comment by KostasAnagnostou** [comment]
Yes, i tried this approach but probably i cannot do exactly the thing i want... It seems to work partially: When the activity is recreated the video goes to 0 second when initialized, right before the onReady() method which sets the saved values. So, when i rotate my phone, the current second goes to 0 for 1-3 secs and when the onReady() triggered, then the video loads to the saved video second. 

I tried to use the  youtubePlayer.seekTo(videoSecond) before the onReady() to set the saved value, but it's not working... I have this 1-3 secs gap between the 0 and the saved second value.

And as far as i understand you cannot set the video second (or video duration) outside of the onReady()... 

```
getLifecycle().addObserver(youtubePlayerView);
        youtubePlayerView.initialize(youTubePlayer -> {
          // tried to set the saved value here
            youTubePlayer.seekTo(videoSecondFloat);
            youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                @Override
                public void onReady() {                   
                        loadVideo(youTubePlayer, mSuggestionYoutubeId);                    
                }
            });
```

**Comment by PierfrancescoSoffritti** [comment]
> And as far as i understand you cannot set the video second (or video duration) outside of the onReady()

You cannot do it before onReady is called.

Ok, so everything is working ok, the problem is that the user would see the time at 0 for a few seconds? what about hiding the currentSecond TextView in the UI until the time is updated?

**Comment by KostasAnagnostou** [comment]
Yes... I did that and it's working... 
```
 youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                @Override
                public void onStateChange(@NonNull PlayerConstants.PlayerState state) {
                    super.onStateChange(state);                  
                    if (state == PlayerConstants.PlayerState.PLAYING || state == PlayerConstants.PlayerState.PAUSED) {
                       // unhide the start time
                        videoIsReady();
                    }                    
                    videoSecondFloat = mTracker.getCurrentSecond();                    
                }
            });
        }, true);
```

**Comment by PierfrancescoSoffritti** [comment]
Nice!
