### ISSUE TITLE
Listener for fullscreen is not invoked.

### ISSUE THREAD

**Issue by NmdOfficial** [PierfrancescoSoffritti/android-youtube-player#183]
I tried to detect when the player is in fullscreen mode or normal.
In "Fullscreen" is a alert which shows me true or false.

I dont get any alert.

My code is following:

`youTubePlayerView.addFullScreenListener(new YouTubePlayerFullScreenListener() {
            @Override
            public void onYouTubePlayerEnterFullScreen() {
                Fullscreen(true);
            }

            @Override
            public void onYouTubePlayerExitFullScreen() {
                Fullscreen(false);
            }

        });`

**Comment by NmdOfficial** [comment]
I have testet it but it is not working for me.

The crazy thing:
`youTubePlayerView.isFullScreen();`
works without problem.

Only the listener works not for me.
Can you look if it is the same for you?
Thank you.

**Comment by PierfrancescoSoffritti** [comment]
It does work for me. You just need to build and run the sample app to verify it yourself: as you can see from the code, the orientation is changed to landscape onEnterFullScreen and to portrait on exitFullScreen.

**Comment by NmdOfficial** [comment]
Did this line https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/0905f20af1de975a18688154903e8d95f01585e6/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/basicExample/BasicExampleActivity.java#L122

notify that `youTubePlayerView.isFullScreen();` method?
I ask because in my example I just use the `YouTubePlayerFullScreenListener` interface

**Comment by PierfrancescoSoffritti** [comment]
That's for hiding showing views. You can read the source code in the sample app.

**Comment by NmdOfficial** [comment]
I know.
I only ask because we already have by default in YouTubePlayerView.java the fullScreenHelper.

But in your example app you use a second fullScreenHelper.
So why?

Why use a second one if the YouTubePlayerView.java already uses by default that helper?

**Comment by Nithinpj** [comment]
on manifest add 
android:configChanges="orientation|keyboardHidden|screenSize"
