### ISSUE TITLE
Video keeps playing after YouTubePlayerView is scrolled out of the display 

### ISSUE THREAD

**Issue by gokmev** [PierfrancescoSoffritti/android-youtube-player#184]
Hi, first of all thank you as this is very useful.

It may be something simple that I am not able to find. I am dynamically adding YouTubePlayerView in a NestedScrollView. I cannot find a way to pause the video when the YouTubePlayerView is scrolled out of the screen.

**Comment by PierfrancescoSoffritti** [comment]
Hi, this issue is not related to the player. You need to understand when a View becomes not visible while scrolling the scroll view. When you know it, just call `player.pause()` there.
