### ISSUE TITLE
Allow to get the current playback time programmatically

### ISSUE THREAD

**Issue by VeegaP** [PierfrancescoSoffritti/android-youtube-player#187]
It would be nice to be able to get the current playback time directly from the player, instead of needing to subscribe to playback time changes and updating a "support" variable every time.

This is useful for implementing methods like `skip(seconds: Float)` where you need the current time of the player and call `seek` to seek to the desired point.

This would basically mean bridging the `player.getCurrentTime()` function from the js implementation.

**Comment by PierfrancescoSoffritti** [comment]
Hi, you can use [YouTubePlayerTracker](https://github.com/PierfrancescoSoffritti/android-youtube-player#youtubeplayertracker) for doing that. Let me know if it helps.

**Comment by VeegaP** [comment]
YoutubePlayerTracker somewhat does what I asked, although I'd consider implementing it by default inside the player itself. Closing for now.

**Comment by PierfrancescoSoffritti** [comment]
I'd rather not add noise to the API of the player. If a getter is added for the current time it would end up being added for every other property of the player. `YouTubePlayerTracker` keeps things clean.

**Comment by foal** [comment]
YouTubePlayerTracker returns incorrect time in case of seek paused video.

**Comment by PierfrancescoSoffritti** [comment]
Hi, what do you mean? I think you should open a separate issue for this.

**Comment by foal** [comment]
Done. https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/411
