### ISSUE TITLE
Webview memory leak

### ISSUE THREAD

**Issue by BrookMezgu** [PierfrancescoSoffritti/android-youtube-player#190]
This app contains a memory leak that's caused by adding webview in the xml

**Comment by PierfrancescoSoffritti** [comment]
Hi, could you provide more information?

**Comment by BrookMezgu** [comment]
[Image_here](https://imgur.com/a/z5YJsPc)

**Comment by BrookMezgu** [comment]
I haven't used anything related to TextToSpeech... but it's leaking my activity... and the only thing am using in that activity is this lib... which is Awesome btw... great work

**Comment by PierfrancescoSoffritti** [comment]
thank you for the help, but there's nothing related to this library in that image.

**Comment by BrookMezgu** [comment]
Yes, i was just wondering if this could be caused from the webview within this lib...

**Comment by PierfrancescoSoffritti** [comment]
No, I don't think this is the cause of you memory leak.

**Comment by BrookMezgu** [comment]
Okay thanks for your reply. Maybe its caused from adding the Views in the xml... i will try passing the applicationContext

**Comment by BrookMezgu** [comment]
Will that do any harm?

**Comment by PierfrancescoSoffritti** [comment]
You're welcome! If you create the `YouTubePlayerView` as explained in the documentation you won't have any issue.

I suggest not using the application context.

If you're finding the library useful consider leaving a star on GitHub :)
