### ISSUE TITLE
How to hide all controls?

### ISSUE THREAD

**Issue by harry248** [PierfrancescoSoffritti/android-youtube-player#191]
Is there a way to hide really every ui control of the player? I have already inflated a custom player ui (just an empty FrameLayout) but the Play/Pause-Button and Youtube-Logo are still being displayed.

**Comment by PierfrancescoSoffritti** [comment]
> When inflating a custom player ui I have to disable touches on the player view, otherwise play/pause buttons are still visible.

It's visible only when you click. Yes, you need to do something to prevent the web player from intercepting clicks.

>  I thought the YouTube logo can be hidden too via the modestbranding parameter (https://developers.google.com/youtube/player_parameters?hl=en#modestbranding)? Would be nice if there was a way to pass some custom parameters.

I'll do some tests tonight, or you can do it now yourself by forking the library and enabling modest branding. If it works feel free to send in a pull request.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I have tried enabling modestbranding, can't see any difference unfortunately.
