### ISSUE TITLE
Accepting on google play .

### ISSUE THREAD

**Issue by muhammedrizwan** [PierfrancescoSoffritti/android-youtube-player#193]
PlayerStatus Example has a UI that has no buttons that redirect to youtube app . Will it be a problem if I use it my app ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, no, won't be a problem.

Consider leaving a star on GitHub if you're finding the library to be useful :)

**Comment by muhammedrizwan** [comment]
Sure
