### ISSUE TITLE
Some videos receive "invalid parameters".

### ISSUE THREAD

**Issue by saulosvieira** [PierfrancescoSoffritti/android-youtube-player#195]
Hi guys, sorry for my english... 

Congratulations for the lib, is awsome. I use the lib in one project and works fine, but in some videos the player show "invalid parameters" and not display de video.

Can you help me?

**Comment by saulosvieira** [comment]
Yes, the id is -> TmZG2y7SllU

**Comment by PierfrancescoSoffritti** [comment]
Does it work in your browser? with so little information I can't say much unfortunately.

**Comment by saulosvieira** [comment]
Yes, work. In Android Studio show this message -> E/libEGL: validate_display:99 error 3008 (EGL_BAD_DISPLAY)
But i don't know if this message is about the problem.

**Comment by PierfrancescoSoffritti** [comment]
I doubt they are related.

**Comment by saulosvieira** [comment]
Many other videos works fine in the app, this video and others 7 show the message.

**Comment by PierfrancescoSoffritti** [comment]
I'll try playing it in the app later in the evening.

**Comment by PierfrancescoSoffritti** [comment]
works fine for me.

**Comment by isheraz** [comment]
I encountered this error too. The Error Comes when I try to get the String Like this
`videoID = String.valueOf(R.string.video_id);`
but will work fine if I put the ID like `videoID = "SOME ID"`

**Comment by PierfrancescoSoffritti** [comment]
Use the getString method. You can't use valueOf for resources.
