### ISSUE TITLE
onInitSuccess triggerred issue 

### ISSUE THREAD

**Issue by aydemir39** [PierfrancescoSoffritti/android-youtube-player#198]
Hi,
i have been researching what the issue is for a while. But i cant find any solution.
i even could not able to understand what was going on. When i play a video for first time there is no problem as far as i understand. 
But when i close the activity or fragment where the videoplayer placed, onInitSucces method does not triggered sometimes. so i can not watch the video. i am just waiting and waiting. Nothing happens.
Sometimes no problem, but after some "close open" activity tries, i can face the issue again.
i also pay attention to release youtubeView in destroy method of the activity or fragment.
Could you give an opinion what this issue is.
here is my class below.
thanks in advance

public class HistoryFragment extends DialogFragment {

    ImageView imageV_close_fr_history;
    View view;
    YouTubePlayerView youTubePlayerView;
    YouTubePlayer youTubePlayerMainCopy;
    Video video;

    public HistoryFragment() {
    }

    public static HistoryFragment newInstance() {
        HistoryFragment historyFragment = new HistoryFragment();
        Bundle args = new Bundle();
        // args.putString("title", title);
        historyFragment.setArguments(args);
        return historyFragment;
    }

    @Nullable
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, Bundle savedInstanceState) {
        view = inflater.inflate(R.layout.fragment_history, container, false);
        init();
        registerHandlers();
        initPlayer(video);
        return view;
    }

    void init() {
        imageV_close_fr_history = view.findViewById(R.id.imageV_close_fr_history);
        youTubePlayerView = view.findViewById(R.id.yyy);
    }

    void registerHandlers() {
        imageV_close_fr_history.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                dismiss();
            }
        });
    }

    @Override
    public void onDismiss(DialogInterface dialog) {
        super.onDismiss(dialog);
        //youTubePlayerMainCopy.pause();
        youTubePlayerView.release();
    }

    @Override
    public void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            video = getArguments().getParcelable("video");
        }
    }

    @Override
    public void onActivityCreated(Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);
        getDialog().getWindow().getAttributes().windowAnimations = R.style.DialogAnimation;
    }

    void initPlayer(final Video video) {
        try {
            youTubePlayerView.initialize(new YouTubePlayerInitListener() {

                @Override
                public void onInitSuccess(final com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayer youTubePlayer) {
                    youTubePlayerMainCopy = youTubePlayer;

                    youTubePlayer.addListener(new YouTubePlayerListener() {
                        @Override
                        public void onReady() {
                            youTubePlayer.loadVideo(video.id, 0);
                            //loadVideo(youTubePlayer,video.id);
                        }

                        @Override
                        public void onStateChange(@NonNull PlayerConstants.PlayerState state) {
                            // youtubePlayerStateMainCopy = state;

                        }

                        @Override
                        public void onPlaybackQualityChange(@NonNull PlayerConstants.PlaybackQuality playbackQuality) {

                        }

                        @Override
                        public void onPlaybackRateChange(@NonNull PlayerConstants.PlaybackRate playbackRate) {

                        }

                        @Override
                        public void onError(@NonNull PlayerConstants.PlayerError error) {
                            Log.i("errorn", String.valueOf(error));
                        }

                        @Override
                        public void onApiChange() {

                        }

                        @Override
                        public void onCurrentSecond(float second) {

                        }

                        @Override
                        public void onVideoDuration(float duration) {

                        }

                        @Override
                        public void onVideoLoadedFraction(float loadedFraction) {

                        }

                        @Override
                        public void onVideoId(@NonNull String videoId) {

                        }
                    });
                }

            }, true);
            getLifecycle().addObserver(youTubePlayerView);
        } catch (Exception e) {
            Log.i("exception", e.getMessage());
        }
        youTubePlayerView.getPlayerUIController().showMenuButton(false);
        youTubePlayerView.getPlayerUIController().showYouTubeButton(false);
    }
}

**Comment by PierfrancescoSoffritti** [comment]
Hi, I'm not sure, it's hard to tell from here. Have you downloaded the sample app? i suggest using that as an example.

**Comment by PierfrancescoSoffritti** [comment]
You may have problems due to replacing the old fragment with the new one, i don't think this issue is related to the library.

**Comment by aydemir39** [comment]
hi again :) thanks for your interest.
i just created a new project and two activities which are MainActivity and VideoDenemeActivity. 
i click the button in main activity, then VideoDenemeActivity starts.
i copied paste the code below from basic example to VideoDenemeActivity.And i just simplyfied the code. and problem goes on. that is annoying :) 


public class VideoDenemeActivity extends AppCompatActivity {

    YouTubePlayerView youTubePlayerView;
    Video value;
    private String[] videoIds = {"6JYIGclVQdw", "LvetJ9U_tVY"};

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_video_deneme);
      //  value = getIntent().getExtras().getParcelable("video");
        youTubePlayerView = findViewById(R.id.youtube_player_view_deneme);
        initYouTubePlayerView();
    }

    private void initYouTubePlayerView() {
        initPlayerMenu();
        getLifecycle().addObserver(youTubePlayerView);
        youTubePlayerView.initialize(new YouTubePlayerInitListener() {
            @Override
            public void onInitSuccess(@NonNull final YouTubePlayer youTubePlayer) {
                youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {
                        loadVideo(youTubePlayer, videoIds[0]);
                    }
                });
            }
        }, true);
    }

    private void initPlayerMenu() {
        youTubePlayerView.getPlayerUIController().showMenuButton(true);
    }

    private void loadVideo(YouTubePlayer youTubePlayer, String videoId) {
        if (getLifecycle().getCurrentState() == Lifecycle.State.RESUMED)
            youTubePlayer.loadVideo(videoId, 0);
        else
            youTubePlayer.cueVideo(videoId, 0);
    }
}

**Comment by PierfrancescoSoffritti** [comment]
I suggest comparing your code with the sample app and looking for the differences.

**Comment by aydemir39** [comment]
i actualy copy pasted basic example and recyclerview example. same again. thanks
Actually sometimes the app crashs like this.
Here is the another error:
E/chromium: [ERROR:aw_browser_terminator.cc(86)] Render process (9645) kill (OOM or update) wasn't handed by all associated webviews, killing application.

**Comment by aydemir39** [comment]
I solved the problem.
I realized that the issue is about chrome browser. i deleted and reinstalled chrome in my phone, then it s okay.
thanks for your interest
