### ISSUE TITLE
Is it possible to set video quality for live video?

### ISSUE THREAD

**Issue by mankidal19** [PierfrancescoSoffritti/android-youtube-player#201]
Hi. I am currently trying to build an Android TV app using your library. The app has several live video selections that user can choose and watch. It works well on emulator, and also the smart TV. One thing tho, most of the times, on TV, the video suddenly cropped incorrectly (moving to the left). I got this error in Android Studio logcat:

> Wrong cropped rect (0, 0) - (1280, 720) vs. frame (854, 480)

So I am currently guessing, this is due to the video quality suddenly dropped (perhaps due to slow internet connection). This is just my guess. That's why I am asking is there a way for me to set the video quality.

Or do you have any idea why this error occurs?

Thanks.

**Comment by mankidal19** [comment]
Thanks a lot for the reply! It's ok, I've tried to find the cause of the problem and fix it. Now I do agree it isn't because the change in resolution. Rather than that, currently I think this is due to youtubePlayerView declared was not released properly, as I get this error from the logcat when trying to close the current video playing:

> callback not found for RELEASED message

This is my current bet, but I am not really sure too. Still trying to figure things out. By the way, if you're interested in seeing the video shifting as I mentioned earlier, you can have a look it here:
[https://drive.google.com/open?id=1LW7ASh3HqAWc_PxSuElaEh7RDv5oehOn](bug on TV app)

**Comment by PierfrancescoSoffritti** [comment]
mmm not sure how could this be related to releasing the view.

It looks like it has some problems fitting on the screen, maybe the layout doesn't know how to measure the view properly?

**Comment by mankidal19** [comment]
> mmm not sure how could this be related to releasing the view.
> 
> It looks like it has some problems fitting on the screen, maybe the layout doesn't know how to measure the view properly?

I see. If that's the case, is there any way I can manually set the view with & height?

Currently this is my layout .xml file:
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".sample.LiveActivity">


    
    <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginTop="27dp"
        android:layout_marginBottom="27dp"
        android:layout_marginLeft="48dp"
        android:layout_marginRight="48dp">

        

        <com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />

    </RelativeLayout>


</RelativeLayout>`

Should I just change the` android:layout_width` & `android:layout_height` at the YouTubePlayerView here?

**Comment by PierfrancescoSoffritti** [comment]
What you have there is good. The YouTubePlayerView won't be fullscreen though.

I am not sure the issue is in the library, I've never seen this happen. Could the problem be in your code?

**Comment by mankidal19** [comment]
Hi. Regarding the video not playing properly on Android TV app, it seems like it isn't a layout problem. I've tried playing around with padding & margin, both on layout file & java file itself. Also tried in your sample app, by changing the padding in youtube_player.html. These doesn't fix the bug.

Then I researched deeper and tried to make changes in **WebViewYouTubePlayer.java**. And suprisingly I managed to solve the problem by adding few lines and changed a bit. Below is the code I've changed (inside initWebView()).

```java

private void initWebView() {
        WebSettings settings = this.getSettings();
        settings.setJavaScriptEnabled(true);

        //change cache mode to default
        settings.setCacheMode(WebSettings.LOAD_DEFAULT);
        settings.setMediaPlaybackRequiresUserGesture(false);

        //call these 2 extra methods
        settings.setDomStorageEnabled(true);
        settings.setPluginState(WebSettings.PluginState.ON);



        this.addJavascriptInterface(new YouTubePlayerBridge(this), "YouTubePlayerBridge");

        //set webchrome client first, before loading the URL
        // if the video's thumbnail is not in memory, show a black screen
        this.setWebChromeClient(new WebChromeClient() {
            @Override
            public Bitmap getDefaultVideoPoster() {
                Bitmap result = super.getDefaultVideoPoster();

                if(result == null)
                    return Bitmap.createBitmap(1, 1, Bitmap.Config.RGB_565);
                else
                    return result;
            }
        });

        this.loadDataWithBaseURL("https://www.youtube.com", readYouTubePlayerHTMLFromFile(), "text/html", "utf-8", null);

    }
```

Unfortunately, currently your **WebViewYouTubePlayer.java** class is not public, therefore I can't simply extend it to implement the solution locally to my project.

**Comment by PierfrancescoSoffritti** [comment]
Interesting. Why do you think these lines
```java
settings.setCacheMode(WebSettings.LOAD_DEFAULT);
settings.setDomStorageEnabled(true);
settings.setPluginState(WebSettings.PluginState.ON);
```
solve the cropped/scaled video problem? I'm struggling to find a connection.

If this makes sense to enable for everyone, you could add this yourself with a pull request!

**Comment by mankidal19** [comment]
I myself not quite sure how they actually works. But these solutions are suggested at [here](https://stackoverflow.com/questions/19246615/html-video-not-playing-in-android-webview) & [here](https://stackoverflow.com/questions/8122298/youtube-embed-videos-not-working-in-webview-whats-wrong-with-this-code). 

Although there were extra lines of code suggested there, but the ones working with me are as suggested above.

I'm not sure if anyone trying to implement this library on Android TV app will have same problem with me or not, as I only have 1 smart TV to test the app I'm developing. Will make a pull request though.

Cheers & thanks a lot.

**Comment by PierfrancescoSoffritti** [comment]
Ok, before making the PR it would be nice to understand what those settings actually do. I am quite busy right now, will be able to look into it in a couple of weeks! In the meantime feel free to help with that :)
