### ISSUE TITLE
Cannot play some videos.

### ISSUE THREAD

**Issue by zhangming170622** [PierfrancescoSoffritti/android-youtube-player#202]
I cannot play some videos. The video id is "XWo627F7CeU".
Error code is 3. But I cant play in Youtube.
I want to your help.

**Comment by PierfrancescoSoffritti** [comment]
Hi, error code 3 doesn't exist. [List of error codes](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/player/PlayerConstants.java#L13).

**Comment by zhangming170622** [comment]
I'm sorry. The correct error code is VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER.
The error message is follow as "This video contains content from Aves Inc., who has blocked it from display on this website or application. Watch on Youtube";

**Comment by PierfrancescoSoffritti** [comment]
I think the message is quite self explanatory. You can't play that video with an embedded player.

**Comment by zhangming170622** [comment]
I don't understand your advice.
Please give me detailed explanation.

**Comment by PierfrancescoSoffritti** [comment]
You can't play that video outside of the YouTube website.

**Comment by JeffZane** [comment]
I also encountered this error(VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER).
I tried to play it in the official sdk player and Chrome, It's correct.
The video id is nICSRQxKSmU.

**Comment by JeffZane** [comment]
> I also encountered this error(VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER).
> I tried to play it in the official sdk player and Chrome, It's all correct.
> The video id is nICSRQxKSmU.

Finally, I solved my problem by calling 'cueVideo' instead of 'loadVideo'.

**Comment by p32929** [comment]
I'm also having the same issue. It works in debug APK but not in release. It shows VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER error. Any solution?
Thanks...

**Comment by joseAugustoCR** [comment]
I'm also having this error. It happens only in some devices, and I wasn't able to reproduce it in my phone.
There is nothing wrong with the video, it's working fine embedded in my website.

Calling 'cueVideo' as suggested didn't help me.

Looking forward for a solution.

**Comment by p32929** [comment]
I found a temporary solution for VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER. If I use a VPN, the error doesn't show.

**Comment by davidgalarza** [comment]
Any update I'm facing the same issue.

**Comment by PierfrancescoSoffritti** [comment]
Sorry but I have even less context than you have, can't really say much. But I think it's a restriction from YouTube's side and not a problem with the player.

**Comment by joseAugustoCR** [comment]
Does anyone have any idea of why this problem is happening?

Is it some kind of Youtube restriction that I'm not seeing?
My video allows embedding and I didn't set any kind of restriction to it.

**Comment by p32929** [comment]
It seems to be working now. It just got fixed autommatically? :/

**Comment by joseAugustoCR** [comment]
@p32929 still not working for me. Can you elaborate how is it working for you?

**Comment by p32929** [comment]
@joseAugustoCR I really don't know. It wasn't working for some days but suddenly its working now

**Comment by joseAugustoCR** [comment]
The error is not related to the library!

When I receive the VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER error in the app I'm opening the external browser with a webpage that tries to play the same video (using videojs or plyr.io). On the webpage, I am receiving the following error: " Playback on other Websites has been disabled by the video owner."

The video is public, has no restrictions and the embedding is allowed.  How can the same video be playable for one user and not playable for another if both are using the same app in the same place? It seems like a Youtube bug!

**Comment by Mostafa-SA-developer** [comment]
> @joseAugustoCR I really don't know. It wasn't working for some days but suddenly its working now

also me

**Comment by hsumyatyehtet-mmds** [comment]
VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER and VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER

**Comment by davidgalarza** [comment]
Any update I'm facing the same issue.

**Comment by Ryanauger95** [comment]
@PierfrancescoSoffritti I realize this is likely a YT issue but do you have any idea how to solve it? We are using an embedded player on iOS and having no issues.

Thanks!
