### ISSUE TITLE
I cannot play some videos.

### ISSUE THREAD

**Issue by zhangming170622** [PierfrancescoSoffritti/android-youtube-player#203]
I read your message.
But please refer to https://github.com/JackDinealKIM/youtube-android-player-helper.
This library play video of problem.
The video id is “XWo627F7CeU, rpFUNMmKIlg, dhA5D7qkHwA….”.
I want to use your library.
Your’s is very comfortable.
I want to wait for your answer.

**Comment by PierfrancescoSoffritti** [comment]
Interesting. I won't be able to do any testing any time soon, it s quite a busy period.
Try to see what's different between the two implementations, a pull request would be very welcomemed :)

**Comment by zhangming170622** [comment]
I found differences.
I modified " WebViewYouTubePlayer.java".The main section is initWebView().
I replaced "https://www.youtube.com" to ""http://jaedong.net/youtube"".
I want to your advice.

**Comment by PierfrancescoSoffritti** [comment]
I don't know what that url is. Doesn't seem like a very good idea though.
