### ISSUE TITLE
 How to decrease or fix video quality ?

### ISSUE THREAD

**Issue by AmitPrajapati1902** [PierfrancescoSoffritti/android-youtube-player#204]
Is there any way, that i can set "small" quality for video.

Right now i am facing problem like. when i am play any video use large data internet, play one video it take 100MB

I have try statically "small" in this object, but not working.

    private static final String QUALITY_SMALL = "small";
    private static final String QUALITY_MEDIUM = "medium";
    private static final String QUALITY_LARGE = "large";
    private static final String QUALITY_HD720 = "hd720";
    private static final String QUALITY_HD1080 = "hd1080";
    private static final String QUALITY_HIGH_RES = "highres";
    private static final String QUALITY_DEFAULT = "default";

how can i access this "sendPlaybackQualityChange" method for it ?

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Duplicate #27.

Unfortunately it's currently not possible to change videos quality :/
