### ISSUE TITLE
Player not working

### ISSUE THREAD

**Issue by mateineagu** [PierfrancescoSoffritti/android-youtube-player#208]
I tried using your player in an android app but the video seems to never load.
I installed your last version of app(sample v0.15.apk) and it doesn't load the video either.

The app on the market works though..
Is this a issue you are aware of?

**Comment by mateineagu** [comment]
Yes, i did. It must have been an initialization ( or the @NotNull from before final YouTubePlayer initializedYouTubePlayer).

PS: is there an example showing how I can catch the end of a video in order to start another one using the YouTubePlayerTracker (or any other method)? Thank you!

**Comment by PierfrancescoSoffritti** [comment]
Yes: https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/playerStatusExample/PlayerStatusActivity.java
