### ISSUE TITLE
Show Thumbnail using Picasso/Glide/Fresco instead of Progress Bar

### ISSUE THREAD

**Issue by vivekkiran** [PierfrancescoSoffritti/Android-YouTube-Player#21]
Show Thumbnail using Picasso/Glide/Fresco instead of Progress Bar, Progress Bar/ Buffering Status can be shown on clicking in it to play.

**Comment by PierfrancescoSoffritti** [comment]
It's probably best to do it from outside the library.

**Comment by bryan-ibrahim** [comment]
> Show Thumbnail using Picasso/Glide/Fresco instead of Progress Bar, Progress Bar/ Buffering Status can be shown on clicking in it to play.

Here's the solution -> https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/135#issuecomment-402082281
