### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "util.CastOptionsProvider"

### ISSUE THREAD

**Issue by mateineagu** [PierfrancescoSoffritti/android-youtube-player#211]
Hi, I have a problem using the cast to Chromecast option.

When I call:
`PlayServicesUtils.checkGooglePlayServicesAvailability(this, googlePlayServicesAvailabilityRequestCode, this::initChromecast);`

I receive the error:

> java.lang.ClassNotFoundException: Didn't find class "util.CastOptionsProvider"

That is caused by - 
```
private Unit initChromecast() {
        new ChromecastYouTubePlayerContext(
                CastContext.getSharedInstance(this).getSessionManager(),
                new SimpleChromecastConnectionListener()
        );

        return Unit.INSTANCE;
    }
```

More precisely by CastContext.getSharedInstance.

I have to mention that if I remove the cast button, the player works just fine. Am i missing something?

I have to mention that in my build.gradle I have those lines:
```
implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:8.0.1'
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:chromecast-sender:0.15'

    implementation 'com.android.support:mediarouter-v7:26.1.0'
    implementation 'com.google.android.gms:play-services-cast-framework:15.0.1'

    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.50'
```

Thank you!

PS: the cast doesn't work from the app existing in play store either. I have tested with youtube and I can cast to my Chromecast directly from their app.

**Comment by mateineagu** [comment]
Later edit:

The code never enters onActivityResult  
`public void onActivityResult(int requestCode, int resultCode, Intent data) `

This is the definition of the class
`public class ProgramTvActivity extends YouTubeBaseActivity implements LifecycleObserver  `

**Comment by PierfrancescoSoffritti** [comment]
Hey, thank you for reporting the issue. The chromecast extension is not finalized yet, unfortunately this summer I moved to another city and didn't have access to a chromecast to properly complete it. It was working well last time I tried though.

From next week I will be back home and I will be able to see what is happening. I think Google may have updated their chromecast library and broke something for the custom stuff I have built on top of it!

sorry for the issue, I'll get back to you in a couple of weeks :)

In the meantime feel free to investigate your self! pull requests are always welcomed!

**Comment by mateineagu** [comment]
No worries - I am looking into it.

**Comment by PierfrancescoSoffritti** [comment]
Hey, just tested the chromecast library again, everything works fine for me. Make sure to have your chromecast registered on the dev console!

**Comment by juanvictorbascopecastro** [comment]
Hello I have the same problem in java, I have the application in Google Cast SDK Developer Console. I throw the error E/CastContext: Failed to load module from Google Play services. Cast will not work properly. Might due to outdated Google Play services. Ignoring this failure silently. I'm new to learning. And I loved this library where you can control everything congratulations.
