### ISSUE TITLE
Is it allowed by play store to publish app 

### ISSUE THREAD

**Issue by omkar1707** [PierfrancescoSoffritti/android-youtube-player#213]
I have developed an app which shows youtube video and a recycler view with subtitles for that video.
If I click on subtitle it will play only that part in the youtube player (between the start and end time of subtitle)

1. Can it be possible using this player?
2. Is there any issue if I use this player while publishing an app to play store?

**Comment by PierfrancescoSoffritti** [comment]
1. It depends on you I guess :) this is a YouTube player library, it's up to you what to do with it.
2. No issues.

**Comment by omkar1707** [comment]
Is there any method available to play only part of a video? 
Example - for given subtitle, play video between the start and end time of subtitle.

**Comment by PierfrancescoSoffritti** [comment]
Every time you load/cue a video you need to specify the start time. You can listen for the video's current time to decide when to stop. 

Everything is explained in the [documentation](https://github.com/PierfrancescoSoffritti/android-youtube-player).

**Comment by omkar1707** [comment]
Thanks for quick replay 👍

**Comment by PierfrancescoSoffritti** [comment]
You're welcome!

Feel free to leave a star on GitHub if you find the library to be useful :)
