### ISSUE TITLE
App using your library

### ISSUE THREAD

**Issue by ambiguous1991** [PierfrancescoSoffritti/android-youtube-player#214]
Hi there!
Would you mind adding my app to list of applications using your library? We use it quite extensively, and it might be a good example use case.
You can find it here https://play.google.com/store/apps/details?id=com.tmdb.themoviedatabase
Cheers and thanks for the library.

By the way do you want me to add an about section and link your github repo inside the app?

**Comment by ambiguous1991** [comment]
Huh that's weird, never happened to me. But I'll check it out while adding the about section. Thank you for the feedback :)

**Comment by PierfrancescoSoffritti** [comment]
Oh, if you want to add the app to the list, you could do it yourself :) just send a pull request on the dev branch! or I'll do it later myself.

**Comment by ambiguous1991** [comment]
I'll make a pull request then.

By the way, about the problem you've experienced, the playback should stop automatically, when the video is scrolled off screen. If you don't mind answering, does it keep playing when you move down and completely scroll it away, or are you referring to the fact that it's playing while it's partially visible? Is that still against the rules?

**Comment by PierfrancescoSoffritti** [comment]
Yes, it always plays for me.
And yes, technically the player should stop as soon as something covers it.

**Comment by Dookong** [comment]
Hello! I released my app using your library. Would you mind adding my app to list of applications using your library? The app is Overwatch Video Lecture: [https://play.google.com/store/apps/details?id=dk.overwatch.lecture&hl=en]

Your libray was very useful and I appreciate so much. Thanks a lot!!

**Comment by PierfrancescoSoffritti** [comment]
@Dookong well done! I'll take a look at the app! :)
