### ISSUE TITLE
How check if a video is live or not

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/android-youtube-player#217]
If you want check you can make a request to this url 

> https://www.googleapis.com/youtube/v3/videos?id=[YOUTUBE-ID]&part=snippet,contentDetails&key=[YOUR-API-KEY]

 and in the [response](https://pastebin.com/exYuyaHM) there is the key _liveBroadcastContent_

if this value is equal to **live** is a live video otherwhise if value will be equal to **none** is not a live video.

Only problem is that you need a ytb api key...

**Comment by PierfrancescoSoffritti** [comment]
Hi, sorry I don't understand what this issue is about.

**Comment by PierfrancescoSoffritti** [comment]
That is not done intentionally, it's outside the scope of the library. It would require adding YouTube Data APIs and other stuff to the lib.
