### ISSUE TITLE
Video not showing...

### ISSUE THREAD

**Issue by hitesh-dhamshaniya** [PierfrancescoSoffritti/android-youtube-player#223]
I have been trying from yesterday to integrate that lib, I got success in first attempt but afterward I had change videoids, some how it not showing video, there is only sound come out than I have try many different video from youtube but same problem happens with all video.  I have done basic implementation which you shown your example. 

And seekbar also not work as video play

Any clue ?

**Comment by PierfrancescoSoffritti** [comment]
Hey, sorry can't say much with so little information. 
Could you show me your code?

**Comment by hitesh-dhamshaniya** [comment]
Here is my implementation
```
        getLifecycle().addObserver(mRootView.youtube_player_view);

        mRootView.youtube_player_view.initialize({ initializedYouTubePlayer ->
            initializedYouTubePlayer.addListener(object : AbstractYouTubePlayerListener() {
                override fun onReady() {
                    val videoId = "6JYIGclVQdw"
                    initializedYouTubePlayer.loadVideo(videoId, 0f)
//                    initializedYouTubePlayer.loadVideo(VIDEO_ID, 0f)
                }
            })
        }, true)
```

XML part 

```
<com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />
```

**Comment by PierfrancescoSoffritti** [comment]
This looks good. On what device are you testing?

**Comment by hitesh-dhamshaniya** [comment]
I am testing on RedMi Note 5 pro, OS 8.0.1

**Comment by ghozien** [comment]
Video not showing when i use android simulator.

**Comment by PierfrancescoSoffritti** [comment]
@ghozien refer to issue #112

**Comment by MunishThakurCrossOver** [comment]
Video is not showing for me as well. I tested on Emulator API 28, Poco f1, Lenovo Note 5, Redmi 4 and Samsung Device.

**Comment by PierfrancescoSoffritti** [comment]
@MunishThakurCrossOver do you hear only the sound?

**Comment by MunishThakurCrossOver** [comment]
Yes Only Sound

**Comment by MunishThakurCrossOver** [comment]
> @MunishThakurCrossOver do you hear only the sound?

Yes Only Sound

**Comment by PierfrancescoSoffritti** [comment]
What does Samsung Device stands for? excluding the emulator what APIs have you tested?

**Comment by MunishThakurCrossOver** [comment]
> What does Samsung Device stands for? excluding the emulator what APIs have you tested?

APIs 26, 28 I have tested

**Comment by PierfrancescoSoffritti** [comment]
Which device?

**Comment by SyedTahaAlam** [comment]
i am receiving net  error 101 network reset error
