### ISSUE TITLE
videos in recyclerview it overlap

### ISSUE THREAD

**Issue by FOUADFAISAL** [PierfrancescoSoffritti/android-youtube-player#224]
hi ...  good morning
i see your you-tube player library for android on GitHub website....
thank you for your efferot to build this library
 but ... i try to use library in my android app
when i try to put videos in recyclerview it overlap
please support me to solve

**Comment by PierfrancescoSoffritti** [comment]
Hi, you can see how to use it with recycler view [in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/recyclerViewExample).

**Comment by FOUADFAISAL** [comment]
this sample app is not covered every thing ,
when i try to put videos in recycler view it overlap
can you help me please to solve 
why videos is overlap , is this is memory problem ??
how i clear memory for every new instance of video ???
please update me ASAP

**Comment by PierfrancescoSoffritti** [comment]
I doubt it's a memory problem. It is working in the sample app, therefore you can find the answer there.

**Comment by FOUADFAISAL** [comment]
is possible display images video thumbnails by this library ???

**Comment by PierfrancescoSoffritti** [comment]
You can display the thumbnail in the player if you cue (instead of load) videos.
