### ISSUE TITLE
Lean back mode

### ISSUE THREAD

**Issue by clint22** [PierfrancescoSoffritti/android-youtube-player#225]
I have implemented a toolbar on top of the video player. What I need to do is that the toolbar must hide and show itself as the default controls in the player. Like, it must hide and show itself on each tap only. I have tried many methods but for some reason, the player doesn't detect any click or gesture on it. Is there any workaround on this issue? Thanks in advance.

**Comment by PierfrancescoSoffritti** [comment]
Hey, I suppose you are using `inflateCustomPlayerUI`. By default the player absorbs every click. To intercept them you need to add a transparent clickable view as the base of your custom UI. You can than use that to detect clicks.

**Comment by clint22** [comment]
> Hey, I suppose you are using `inflateCustomPlayerUI`. By default the player absorbs every click. To intercept them you need to add a transparent clickable view as the base of your custom UI. You can than use that to detect clicks.

Like I add a textview or any other kind of view which covers the whole player? Like that ?

**Comment by PierfrancescoSoffritti** [comment]
Well, your toolbar is probably inside a ViewGroup of some sort (LinearLayout, FrameLayout ecc), just make that full screen. Or add just a View.
I don't recommend using a TextView for intercepting clicks.

**Comment by clint22** [comment]
> Well, your toolbar is probably inside a ViewGroup of some sort (LinearLayout, FrameLayout ecc), just make that full screen. Or add just a View.
> I don't recommend using a TextView for intercepting clicks.

`<FrameLayout
        android:id="@+id/frame_video_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">





        <com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content" />
        

        <include
            android:id="@+id/toolbar"
            layout="@layout/transparent_toolbar"/>


    </FrameLayout>`
This is my layout looks like. Could you please write it programmatically what you are trying to explain? I put the listener on the frame layout too. But that too in vain.

**Comment by PierfrancescoSoffritti** [comment]
You are not using `inflateCustomPlayerUI`?

**Comment by clint22** [comment]
> inflateCustomPlayerUI

No, I guess.

**Comment by PierfrancescoSoffritti** [comment]
I suggest you do.

Also, I m not really sure why you want to use a toolbar, you could instead add individual icons to the top of the player.

**Comment by clint22** [comment]
> I suggest you do.
> 
> Also, I m not really sure why you want to use a toolbar, you could instead add individual icons to the top of the player.

Even in that case too. I'll have to detect the touch on the Player right? So in case, I use the custom player, the default methods like play/pause and scroll video options will not be available, right? I'll have to create all the views from the scratch then. Also, I found that the Lean back full-screen mode option is not implemented in the player. So, if I could detect the click I'll be able to display the toolbar according to it. And in full-screen mode, I'll be able to use the lean back option.

**Comment by PierfrancescoSoffritti** [comment]
> I'll have to create all the views from the scratch
correct.

I don't know what you mean with "lean back mode".

Again: I m not really sure why you want to use a toolbar, you could instead add individual icons to the top of the player. ([doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#custom-actions))
