### ISSUE TITLE
how to pause or start programmatically?

### ISSUE THREAD

**Issue by uzaysan** [PierfrancescoSoffritti/android-youtube-player#227]
I'm using your library in recycler view but i cant pause or starts video with code.

How to do that?

**Comment by PierfrancescoSoffritti** [comment]
You can call `play` and `pause` on `YouTubePlayer`.

**Comment by uzaysan** [comment]
I know that functions but they dont come up?

picture:

https://imgur.com/a/ebZcEgR

**Comment by PierfrancescoSoffritti** [comment]
You are using a `YouTubePlayerView`, not a `YouTubePlayer`. [Quick Start](https://github.com/PierfrancescoSoffritti/android-youtube-player#quick-start), [YouTubePlayerView](https://github.com/PierfrancescoSoffritti/android-youtube-player#quick-start), [YouTubePlayer](https://github.com/PierfrancescoSoffritti/android-youtube-player#youtubeplayer).

**Comment by uzaysan** [comment]
But whenever i want to play/pause video i have to re-intialize the video? am i right?

If i'm wrong can you give me an example code?

I'm sorry if this questions are dump but i'm a newbie and my english is not so well.

**Comment by PierfrancescoSoffritti** [comment]
No worries.

No, you don't need to re initialize every time you play/pause.
You can find a RecyclerView example [here in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/recyclerViewExample).

**Comment by uzaysan** [comment]
that helped a lot thanks.

**Comment by PierfrancescoSoffritti** [comment]
You're welcome!

If you find the library to be helpful consider leaving a star on GitHub :)
