### ISSUE TITLE
`showinfo` is now ignored, update readme

### ISSUE THREAD

**Issue by Apsaliya** [PierfrancescoSoffritti/android-youtube-player#228]
Due to recent changes in player apis, `showinfo=0` is now completely ignored. Which means it will now always show title of the video at top. Should `Show video title` section of readme be updated?

**Comment by PierfrancescoSoffritti** [comment]
Yeah, I will update the readme and the app soon.

Unfortunately the current behavior is not what I wanted though. I'll have to see if there are possible alternatives.

**Comment by Apsaliya** [comment]
Yeah I don't like it either. I tried looking around a bit for any alternative but wasn't able to find any :(. Let me know if you find anything. :)

**Comment by PierfrancescoSoffritti** [comment]
I will 👍
