### ISSUE TITLE
What value does "state.compareTo(PlayerConstants.PlayerState.PLAYING)" returns?

### ISSUE THREAD

**Issue by uzaysan** [PierfrancescoSoffritti/android-youtube-player#229]
I'm using youtubeplayer listener and i want to get youtube player state i want something like this;

```
if(state.compareTo(PlayerConstants.PlayerState.PLAYING)){
    youtubeplayer.pause();
}
```

**Comment by PierfrancescoSoffritti** [comment]
`PlayerConstants` are all enums, therefore you can just do: 

```if(state == PlayerConstants.PlayerState.PLAYING) { }```

if that's what you're asking.

**Comment by PierfrancescoSoffritti** [comment]
If the library is useful to you, consider leaving a star on GitHub 👍
