### ISSUE TITLE
How to autoplay/pause player?

### ISSUE THREAD

**Issue by uzaysan** [PierfrancescoSoffritti/android-youtube-player#230]
Like autopause when player is not visible i want auto play player how to do that?

I tried loadvideo method instead of cuevideo but it messed up.

is there any way to do that?

And i have second question.I know player stops itself when its not visible anymore.But it only stops itself if its view is 100% invisible.How to pause like when its 70% invisible?

**Comment by PierfrancescoSoffritti** [comment]
You have to do both manually. Write your own logic to auto play/pause whenever you need.
