### ISSUE TITLE
Manifest merger failed 

### ISSUE THREAD

**Issue by naveenthontepu** [PierfrancescoSoffritti/android-youtube-player#231]
In my application i want use `android:allowBackup="false"` but i getting a build error saying 

```
Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:9:9-36
	is also present at [com.pierfrancescosoffritti.androidyoutubeplayer:core:8.0.1] AndroidManifest.xml:15:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:7:5-52:19 to override.
```

I can simply add `tools:replace="android:allowBackup"`. But why is your library using `allowBackup`?

**Comment by PierfrancescoSoffritti** [comment]
Hey, thanks for reporting it. It was just automatically added by AndroidStudio and i forgot to remove it.

Will be removed in the next version.
