### ISSUE TITLE
How to remove the youtube app launcher icon from the player?

### ISSUE THREAD

**Issue by Navneet7k** [PierfrancescoSoffritti/android-youtube-player#233]
Is there a way by which i could remove(or disable) the youtube app launcher icon located next to the seekbar. I basically don't want my app users to go to the youtube app. Is there a solution for this ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to use PlayerUIController for controlling the UI of a YouTubePlayerView, [as explained in the documentation](https://github.com/PierfrancescoSoffritti/android-youtube-player#playeruicontroller).

`youtubePlayerView.getPlayerUIController().showYouTubeButton(false)`

**Comment by PierfrancescoSoffritti** [comment]
If this library is useful to you, consider leaving a star on GitHub, thanks!!

**Comment by JosiYosi** [comment]
Ok, removing a YouTube icon using UI controller class works good. How about removing YouTube logo that displayed at the bottom right corner for fraction of seconds, but it fades away with in seconds. It looks like that YouTube logo has already embedded with the video to show users that the video belongs to YouTube and powered by YouTube. I don't think there is a way to remove that logo though. Unless there is any other means to remove that YouTube logo .

**Comment by PierfrancescoSoffritti** [comment]
Hi, you should enable webUi. Of update to version 11 where webUi is the
default.

**Comment by JosiYosi** [comment]
thanks for your response . . . What do you mean When you say Update to version 11? Is there any specific YouTube player updated version or you are referring to your GitHub updated version?

**Comment by PierfrancescoSoffritti** [comment]
I meant v11 of the library.

**Comment by JosiYosi** [comment]
Thanks for letting me know that. I am using version 11, yes it removes that YouTube logo, but the problem is that  when I try to play around customizing the player's controls, It does play the video, but it is not disabling or enabling  ui buttons like for example:
 `defaultPlayerUiController = new DefaultPlayerUiController(youTubePlayerView, youTubePlayer);
                defaultPlayerUiController.showSeekBar(true);
                    //show current time view when video starts to play or pause
                    defaultPlayerUiController.showCurrentTime(true);
                    //show total duration time view when it starts to play or pause
                    defaultPlayerUiController.showDuration(true);

`

**Comment by JosiYosi** [comment]
Now I got a solution still using old version 10.0.5 in order to take care of customization of other controls, and also in order to remove that YouTube logo from the video. I did a minor change of parameter value in the IFramePlayerOptions class of the older version that I am using. In version 10.0.5 default control value is declared as the following: 
                            `companion object {
                                          val default = Builder().build()
                                }`

In version 11, default control value is declared as the following: 
                                `companion object {
                                             val default = Builder().controls(1).build()
                                   }`
Declaring default value as 
                                `val default = Builder().controls(1).build()`
in the old version removing the logo completely. Finally, I want to say thank you for your libraries. It helps me solving and learning many things about YouTube player.

**Comment by PierfrancescoSoffritti** [comment]
No problem, i'm glad you found a solution!

**Comment by priyanshuborole** [comment]
@PierfrancescoSoffritti is there any option to hide the youtube logo and menu which share the youtube video link in the latest version - 12.1.0

**Comment by PierfrancescoSoffritti** [comment]
Hi, which menu logo? can you provide a screenshot?

**Comment by priyanshuborole** [comment]
Hello, Thanks for the quick reply. I want to hide these 3 components of the view. 

Full view - 
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/69722542/f733e113-c9f3-4c8f-b0c2-0c57a0420768)

Three components -
Video title - 
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/69722542/445d6aa1-0713-4443-8afa-b484f0b13ee0)

Youtube logo -
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/69722542/356ec7dd-4cb5-4be7-ad06-abd69da79cb2)

Menu - 
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/69722542/01217368-1773-4a35-b5a8-a53e37d0641f)

**Comment by PierfrancescoSoffritti** [comment]
Unfortunately it's not possible. The IFrame player does not allow it.

**Comment by priyanshuborole** [comment]
yup, for the older version of the library, it was working fine but it was having full-screen mode issues.

**Comment by PierfrancescoSoffritti** [comment]
It was not possible in the old version too.

**Comment by priyanshuborole** [comment]
yes, it was not possible to hide them but we were able to make it non-clickable with the help of - 
getPlayerUiController().showPlayPauseButton(true) 
getPlayerUiController().setVideoTitle("")
getPlayerUiController().showVideoTitle(false)
 getPlayerUiController().showMenuButton(false)
 
 The same use case can be done in the new version?

**Comment by PierfrancescoSoffritti** [comment]
[You can still use custom-ui](https://github.com/PierfrancescoSoffritti/android-youtube-player#defaultplayeruicontroller). Although it's not recommended.
