### ISSUE TITLE
Chromecast receiver as an Android application

### ISSUE THREAD

**Issue by mankidal19** [PierfrancescoSoffritti/android-youtube-player#234]
Hi. One question, is it possible to create a Chromecast receiver app using your API? For example, by creating an Android app with webview directing to my server where I put all the receiver API files provided by your library.

Thanks.

**Comment by PierfrancescoSoffritti** [comment]
That's what the [extension library is for](https://github.com/PierfrancescoSoffritti/android-youtube-player#chromecast-support).

**Comment by mankidal19** [comment]
> That's what the [extension library is for](https://github.com/PierfrancescoSoffritti/android-youtube-player#chromecast-support).

I see. Missed the point there. Thought it only can be used as a web application.

Anyway thanks again!

**Comment by PierfrancescoSoffritti** [comment]
You're welcome. Let me know if you have other questions/problem with it. Could be useful for improvements.

**Comment by mankidal19** [comment]
> You're welcome. Let me know if you have other questions/problem with it. Could be useful for improvements.


Hi. Another quick question. Do you have a working cast receiver sample application for testing purposes?

**Comment by PierfrancescoSoffritti** [comment]
You can test the receiver in both sample applications. [core sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/chromecastExample) [chromecast sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-sender-sample-app).

The code of the receiver is [here](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-receiver).

**Comment by mankidal19** [comment]
Yes I understand that. But what I mean is that a working receiver
application. I've uploaded the sample application into my server but as I
haven't registered mine to Google, I can't make it to work.

On Oct 24, 2018 11:35 AM, "Pierfrancesco Soffritti" <
notifications@github.com> wrote:

You can test the receiver in both sample applications. core sample app
<https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/chromecastExample>
chromecast
sample app
<https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-sender-sample-app>
.

The code of the receiver is here
<https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-receiver>
.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/234#issuecomment-432500701>,
or mute the thread
