### ISSUE TITLE
Sound is mono (not stereo)

### ISSUE THREAD

**Issue by ghozien** [PierfrancescoSoffritti/android-youtube-player#236]
I using this player for playing karaoke YouTube video, but there's no vocal, only music i can hear.
Can this player play stereo music?

**Comment by PierfrancescoSoffritti** [comment]
Hey, if the problem is the player not being mono you should hear both channels overlapped, right?

**Comment by ghozien** [comment]
The problem is the player not stereo.

**Comment by PierfrancescoSoffritti** [comment]
Yeah sorry, I meant stereo.

**Comment by ghozien** [comment]
How to make both channels overlapped?

**Comment by PierfrancescoSoffritti** [comment]
Well, that's what should happen if the problem is that the sound is not stereo.
What I'm trying to understand is if that's really the problem you're having.

**Comment by ghozien** [comment]
I use this video https://youtu.be/PdXljK7LRKU with your YouTube player library, but no vocal, only music i can hear.
You can try.

**Comment by PierfrancescoSoffritti** [comment]
Sounds very weird. I can't think of any reason for this to happen. Vocals and music are part of the same audio stream. Unless your phone has 2 speakers and one of the two is broken.

**Comment by ghozien** [comment]
Ok, can this player change aspect ratio of YouTube video? Example: from 4:3 to 16:9

**Comment by PierfrancescoSoffritti** [comment]
This is a different question. To keep everything in order I suggest opening a new issue for it.

**Comment by ghozien** [comment]
When i using official YouTube app the sound is stereo, but when i play YouTube using web/browser on my phone, the sound is mono.

**Comment by PierfrancescoSoffritti** [comment]
Can't say much if I'm not able to replicate the issue.
