### ISSUE TITLE
Aspect ratio

### ISSUE THREAD

**Issue by ghozien** [PierfrancescoSoffritti/android-youtube-player#238]
can this player change aspect ratio of YouTube video? Example: from 4:3 to 16:9
Or change scaleType like an imageView?

**Comment by PierfrancescoSoffritti** [comment]
You can set the `YouTubePlayerView` dimensions using `android:layout_width` and `android:layout_height`, like you would do with any other View.

**Comment by ghozien** [comment]
Ok, i have try but the video aspect ratio has not change.

**Comment by PierfrancescoSoffritti** [comment]
You want to see how to do it programmatically you can look at the [onMeasure method of YouTubePlayerView](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/player/YouTubePlayerView.java#L64).

**Comment by ghozien** [comment]
Ok thank you
