### ISSUE TITLE
Possible violation of YouTube Terms of Service

### ISSUE THREAD

**Issue by Mischmo** [PierfrancescoSoffritti/android-youtube-player#243]
Hello. Are you sure your player can use custom controls? I found this document

https://developers.google.com/youtube/terms/required-minimum-functionality#overlays-and-frames

where you can find this paragraph: “_You must not display overlays, frames, or other visual elements in front of any part of a YouTube embedded player, including player controls. Similarly, you must not use overlays, frames or other visual elements to obscure any part of an embedded player, including player controls._”

**Comment by PierfrancescoSoffritti** [comment]
Hi, that shouldn't be an issue because the player controls are not always visible, they automatically disappear after a while.

The player has been used by published apps for years now, it's quite safe.

**Comment by PierfrancescoSoffritti** [comment]
Yeah, I understand your concerns.
But considering the state of the official API this is pretty much the only way to play YouTube videos on Android. Also there's tons of apps on the store using a webview-based player with custom controls, even [some very popular apps](https://play.google.com/store/apps/details?id=com.djit.apps.stream).
Unfortunately that's the best we can have for now 😅
