### ISSUE TITLE
Disable autoplay

### ISSUE THREAD

**Issue by houssemnjim** [PierfrancescoSoffritti/android-youtube-player#245]
Hello,
Thanks for this library

I want to know if i can disable auto start of video when the view is created 
I tried to add youtubePlayer.pause() in the onReady Callback and it seems to pause it but there's an infinit loader on start button on the player

Is there another method to do so? 
thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, you should use `youtubePlayer.cueVideo()` instead of `loadVideo()`.
