### ISSUE TITLE
Infinite Loader Issue (When playing with chromecast)

### ISSUE THREAD

**Issue by aman01894** [PierfrancescoSoffritti/android-youtube-player#247]
Video only play when I am not using chrome cast. But when I try to play using chrome cast it shows me loader for infinite state.

**Comment by PierfrancescoSoffritti** [comment]
Hi, you should provide more info.
Where does it shows the infinite loading? on your phone or on Chromecast?

**Comment by aman01894** [comment]
infinite loading show in my phone and Chromecast is connected but not play video.

**Comment by PierfrancescoSoffritti** [comment]
If you use the sample app, does it work with your chromecast?

**Comment by aman01894** [comment]
No.

**Comment by PierfrancescoSoffritti** [comment]
Then you probably haven't registered your chromecast as a dev device. Read [here](https://github.com/PierfrancescoSoffritti/android-youtube-player#registration).

**Comment by aman01894** [comment]
i am already registered my device and device is working for another app.but sample app video not play.

**Comment by aman01894** [comment]
Device is always connected with sample app but video not play ,when i am connected with chrome cast and  play infinite loading show in my phone and cast icon show in cast screen device.
i am using this id =
 String receiverId = CastMediaControlIntent.DEFAULT_MEDIA_RECEIVER_APPLICATION_ID ;

Please help.

**Comment by aman01894** [comment]
https://www.dropbox.com/s/tzq3y73gap7wv8z/0.png?dl=0 please check this is a link of  my mobile screen shot image

**Comment by PierfrancescoSoffritti** [comment]
Ok, thanks. I'll do some tests by the end of this or next week.

**Comment by aman01894** [comment]
Thanks for your quick response, I really want to finish my work as soon as possible as my client is now in panic mode. It will be really helpful if you can help me as early as possible.

Need your help and kind support.

Regards,
Aman Rai

**Comment by PierfrancescoSoffritti** [comment]
Just tested on chromecast, everything works fine. Try updating to the next version of the library once it's out.
