### ISSUE TITLE
FullScreenHelper Issue

### ISSUE THREAD

**Issue by utkuakgungor** [PierfrancescoSoffritti/android-youtube-player#249]
Hi 
First of all thanks for your work.It helps me a lot. I make an Android app and i use your library. I can play videos very well but i can't make them fullscreen. I look at the sample app codes, i try them but codes doesn't work in my app. It getting error when i define FullScreenHelper(private FullScreenHelper fullScreenHelper=new FullScreenHelper(this)). Error appear in "this" part. I use player in a fragment and an activity. They have same design and nearly same codes. I use androidx. The error is "FullScreenHelper() in FullScreenHelper cannot be applied to (com.utkuakgungor.filmtavsiye.details.DetailsActivity)"

Fragment Code:

    
    public class HomeFragment extends Fragment{
    public FirebaseDatabase database;
    private DatabaseReference reference;
    TextView textFilmYili,textPuan,textOzet,textSure,textTur,textOyuncular,textYonetmen;
    CollapsingToolbarLayout textFilmAdi;
    ImageView imageView;
    FloatingActionButton fab;
    YouTubePlayerView youTubePlayerView;
    **private FullScreenHelper fullScreenHelper=new FullScreenHelper(this);**

    public HomeFragment() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View v=  inflater.inflate(R.layout.fragment_home, container, false);

        database = FirebaseDatabase.getInstance();
        reference=database.getReference("Filmler");
        reference.keepSynced(true);
        textFilmYili=v.findViewById(R.id.homeYilDegisken);
        textPuan = v.findViewById(R.id.homePuan);
        textOzet =v.findViewById(R.id.homeOzet);
        imageView=v.findViewById(R.id.homeImage);
        textSure= v.findViewById(R.id.homeSureDegisken);
        textTur=v.findViewById(R.id.hometur);
        textOyuncular=v.findViewById(R.id.homeOyuncular);
        textYonetmen=v.findViewById(R.id.homeyonetmen);
        fab=v.findViewById(R.id.homeFab);
        textFilmAdi=v.findViewById(R.id.collapsing_toolbar);
        youTubePlayerView=v.findViewById(R.id.youtube_player_view);

        updateList();

        return v;
    }

    private boolean KontrolFavori(String ad,View v){
        Favorites favori = new Favorites(v.getContext());
        SQLiteDatabase db = favori.getWritableDatabase();
        Cursor cursor = null;
        String sql ="SELECT * FROM filmler WHERE film_adi='"+ad+"'";
        cursor= db.rawQuery(sql,null);

        if(cursor.getCount()>0){
            cursor.close();
            return false;
        }else{
            cursor.close();
            return true;
        }
    }

    public void updateList() {
        reference.limitToLast(1).addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {
                final Movie movie = dataSnapshot.getValue(Movie.class);
                if(Objects.equals(Locale.getDefault().getDisplayLanguage(),"English" )){
                    textSure.setText(movie.film_sure_eng);
                    textOzet.setText(movie.film_ozet_eng);
                    textTur.setText(movie.film_tur_eng);
                }
                else {
                    textOzet.setText(movie.ozet);
                    textSure.setText(movie.sure);
                    textTur.setText(movie.film_tur);
                }
                if(Objects.equals(movie.text_color,"evet")){
                    int color = Color.parseColor("#000000");
                    textFilmAdi.setExpandedTitleColor(color);
                }
                textYonetmen.setText(movie.film_yonetmen);
                textOyuncular.setText(movie.film_oyuncular);
                textFilmAdi.setTitle(movie.film_adi);
                textFilmYili.setText(movie.film_yili);
                textPuan.setText(movie.film_puani);
                Picasso.get().load(movie.image).networkPolicy(NetworkPolicy.OFFLINE).into(imageView, new Callback() {
                    @Override
                    public void onSuccess() {

                    }

                    @Override
                    public void onError(Exception e) {
                        Picasso.get().load(movie.image).into(imageView);
                    }
                });
                **getLifecycle().addObserver(youTubePlayerView);
                //youTubePlayerView.getPlayerUIController().showFullscreenButton(false);
                youTubePlayerView.initialize(new YouTubePlayerInitListener() {
                    @Override
                    public void onInitSuccess(@NonNull final YouTubePlayer initializedYouTubePlayer) {
                        initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                            @Override
                            public void onReady() {
                                initializedYouTubePlayer.cueVideo(movie.youtube,0);
                            }
                        });
                        Listener();
                    }
                }, true);**

                fab.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(final View v) {
                        final Favorites favorites = new Favorites(v.getContext());
                        if (KontrolFavori(movie.film_adi,v)){
                            favorites.ekle(movie.film_adi,movie.film_yili,movie.film_puani,movie.image,movie.youtube,movie.ozet,movie.sure,movie.film_ozet_eng,movie.film_sure_eng,movie.text_color,movie.film_oyuncular,movie.film_tur,movie.film_tur_eng,movie.film_yonetmen);
                            favorites.close();
                            Snackbar.make(v,getResources().getString(R.string.favoriekle),Snackbar.LENGTH_LONG).show();
                        }else {
                            AlertDialog.Builder builder = new AlertDialog.Builder((Activity) v.getContext());
                            builder.setTitle(v.getResources().getString(R.string.favoriuyari));
                            builder.setMessage(v.getResources().getString(R.string.favoricikarma));
                            builder.setPositiveButton(v.getResources().getString(R.string.evet), new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface dialog, int which) {
                                    favorites.deleteData(movie.film_adi);
                                    Snackbar.make(v,getResources().getString(R.string.favoricikti),Snackbar.LENGTH_LONG).show();
                                }
                            });
                            builder.setNegativeButton(v.getResources().getString(R.string.hayir), new DialogInterface.OnClickListener() {
                                @Override
                                public void onClick(DialogInterface dialog, int which) {
                                }
                            });
                            builder.show();
                        }
                    }
                });

            }

            @Override
            public void onChildChanged(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onChildRemoved(@NonNull DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(@NonNull DataSnapshot dataSnapshot, @Nullable String s) {

            }

            @Override
            public void onCancelled(@NonNull DatabaseError databaseError) {

            }
        });
    }

    **private void Listener(){
        youTubePlayerView.addFullScreenListener(new YouTubePlayerFullScreenListener() {
            @Override
            public void onYouTubePlayerEnterFullScreen() {
                getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                fullScreenHelper.enterFullScreen();
            }

            @Override
            public void onYouTubePlayerExitFullScreen() {
                getActivity().setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                fullScreenHelper.exitFullScreen();
            }
        });
    }**
    }

Fragment Layout:

            <?xml version="1.0" encoding="utf-8"?>
            <androidx.coordinatorlayout.widget.CoordinatorLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:app="http://schemas.android.com/apk/res-auto"
            xmlns:tools="http://schemas.android.com/tools"
            android:id="@+id/homeCoordinator"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_marginBottom="50dp">
            <com.google.android.material.appbar.AppBarLayout
                android:id="@+id/appbar"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:fitsSystemWindows="true"
                android:theme="@style/AppTheme.AppBarOverlay">

                <com.google.android.material.appbar.CollapsingToolbarLayout
                    android:id="@+id/collapsing_toolbar"
                    android:layout_width="match_parent"
                    android:layout_height="580dp"
                    android:fitsSystemWindows="true"
                    android:theme="@style/ThemeOverlay.AppCompat.Dark"
                    app:contentScrim="?attr/colorPrimaryDark"
                    app:expandedTitleMarginEnd="72dp"
                    app:expandedTitleMarginStart="16dp"
                    app:layout_scrollFlags="scroll|exitUntilCollapsed">

                    <ImageView
                        android:id="@+id/homeImage"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:fitsSystemWindows="true"
                        android:transitionName="cardPicture"
                        android:scaleType="centerCrop"
                        app:layout_collapseMode="parallax"
                        android:adjustViewBounds="true"/>

                    <androidx.appcompat.widget.Toolbar
                        android:id="@+id/home_toolbar"
                        android:layout_width="match_parent"
                        android:layout_height="?attr/actionBarSize"
                        app:layout_collapseMode="pin"
                        app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

                </com.google.android.material.appbar.CollapsingToolbarLayout>
            </com.google.android.material.appbar.AppBarLayout>

            <com.google.android.material.floatingactionbutton.FloatingActionButton
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:src="@drawable/ic_like"
                app:fabSize="normal"
                app:layout_anchor="@id/appbar"
                app:layout_anchorGravity="bottom|end"
                android:layout_marginEnd="15dp"
                android:id="@+id/homeFab"
                app:elevation="8dp"/>
            <androidx.core.widget.NestedScrollView
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:layout_behavior="@string/appbar_scrolling_view_behavior">

                <androidx.cardview.widget.CardView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:cardUseCompatPadding="true"
                    app:cardElevation="8dp"
                    >

                    <RelativeLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:orientation="vertical"
                        android:paddingStart="15dp"
                        android:paddingEnd="16dp"
                        android:paddingTop="16dp">
                        <TextView
                            android:id="@+id/homeYil"
                            android:text="@string/detayyil"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:textStyle="bold"/>
                        <TextView
                            android:id="@+id/homeYilDegisken"
                            android:layout_toEndOf="@id/homeYil"
                            android:text="@string/degisken"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            />
                        <ImageView
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:id="@+id/homeStar"
                            android:layout_below="@id/homeYil"
                            android:src="@drawable/ic_star"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="10dp"
                            android:contentDescription="@string/film_puani_yildiz"
                            />
                        <TextView
                            android:id="@+id/homePuan"
                            android:layout_toEndOf="@id/homeStar"
                            android:layout_below="@id/homeYil"
                            android:text="@string/degisken"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="10dp"
                            android:textColor="@color/colorBlack"
                            android:transitionName="cardPuan"
                            />
                        <TextView
                            android:id="@+id/homeSure"
                            android:layout_below="@id/homeStar"
                            android:text="@string/detay_sure"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:textStyle="bold"/>
                        <TextView
                            android:id="@+id/homeSureDegisken"
                            android:text="@string/degisken"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:layout_below="@id/homeStar"
                            android:layout_toEndOf="@id/homeSure"
                            />

                        <TextView
                            android:id="@+id/homeYonetmenbaslik"
                            android:layout_below="@id/homeSure"
                            android:text="@string/detayYonetmenbaslik"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:textStyle="bold"/>
                        <TextView
                            android:id="@+id/homeyonetmen"
                            android:text="@string/degisken"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:layout_below="@id/homeSure"
                            android:layout_toEndOf="@id/homeYonetmenbaslik"
                            />
                        <TextView
                            android:id="@+id/homeTurbaslik"
                            android:layout_below="@id/homeYonetmenbaslik"
                            android:text="@string/detayFilmtur"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:textStyle="bold"/>
                        <TextView
                            android:id="@+id/hometur"
                            android:text="@string/degisken"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="15dp"
                            android:textColor="@color/colorBlack"
                            android:layout_below="@id/homeYonetmenbaslik"
                            android:layout_toEndOf="@id/homeTurbaslik"
                            />
                        **<com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView
                            android:id="@+id/youtube_player_view"
                            android:layout_width="match_parent"
                            android:layout_height="wrap_content"
                            android:layout_marginTop="14dp"
                            android:layout_below="@id/hometur"/>**

                        <TextView
                            android:layout_below="@id/youtube_player_view"
                            android:id="@+id/homeOyuncularbaslik"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:text="@string/detayOyuncularbaslik"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="10dp"
                            android:textColor="@color/colorBlack"
                            android:textStyle="bold"
                            />
                        <TextView
                            android:id="@+id/homeOyuncular"
                            android:layout_below="@id/homeOyuncularbaslik"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:text="@string/degisken"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="10dp"
                            android:textColor="@color/colorBlack"
                            />
                        <TextView
                            android:layout_below="@id/homeOyuncular"
                            android:id="@+id/homeOzetBaslik"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:text="@string/detayozetbaslik"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="10dp"
                            android:textColor="@color/colorBlack"
                            android:textStyle="bold"
                            />
                        <TextView
                            android:id="@+id/homeOzet"
                            android:layout_below="@id/homeOzetBaslik"
                            android:layout_width="wrap_content"
                            android:layout_height="wrap_content"
                            android:textSize="18sp"
                            android:text="@string/degisken"
                            android:layout_marginTop="14dp"
                            android:layout_marginStart="10dp"
                            android:textColor="@color/colorBlack"
                            android:paddingBottom="15dp"
                            />
                    </RelativeLayout>

                </androidx.cardview.widget.CardView>

            </androidx.core.widget.NestedScrollView>
        </androidx.coordinatorlayout.widget.CoordinatorLayout>

Activity Code:

    public class DetailsActivity extends AppCompatActivity {

    YouTubePlayerView youTubePlayerView;
    String ad,yil,puan,image,youtube,ozet,sure,ozet_eng,sure_eng,textcolor,oyuncular,tur,tur_eng,yonetmen;
    TextView textFilmYili,textPuan,textOzet,textSure,textTur,textOyuncular,textYonetmen;
    CollapsingToolbarLayout textFilmAdi;
    ImageView imageView;
    FloatingActionButton fab;
    **private FullScreenHelper fullScreenHelper=new FullScreenHelper(this);**

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_detay);

        getIncomingIntent();
        final Favorites favorites = new Favorites(DetailsActivity.this);
        youTubePlayerView=findViewById(R.id.youtube_player_view);
        textFilmYili=findViewById(R.id.detayYilDegisken);
        textPuan = findViewById(R.id.detayPuan);
        textOzet =findViewById(R.id.detayOzet);
        imageView=findViewById(R.id.detayImage);
        textSure= findViewById(R.id.detaySureDegisken);
        textTur=findViewById(R.id.detaytur);
        textOyuncular=findViewById(R.id.detayOyuncular);
        textYonetmen=findViewById(R.id.detayyonetmen);
        fab=findViewById(R.id.detayFab);
        textFilmAdi=findViewById(R.id.collapsing_toolbar);

        if(Objects.equals(Locale.getDefault().getDisplayLanguage(),"English" )){
            textSure.setText(sure_eng);
            textOzet.setText(ozet_eng);
            textTur.setText(tur_eng);
        }
        else {
            textOzet.setText(ozet);
            textSure.setText(sure);
            textTur.setText(tur);
        }
        if(Objects.equals(textcolor,"evet")){
            int color = Color.parseColor("#000000");
            textFilmAdi.setExpandedTitleColor(color);
        }
        textYonetmen.setText(yonetmen);
        textOyuncular.setText(oyuncular);
        textFilmAdi.setTitle(ad);
        textFilmYili.setText(yil);
        textPuan.setText(puan);
        Picasso.get().load(image).networkPolicy(NetworkPolicy.OFFLINE).into(imageView, new Callback() {
            @Override
            public void onSuccess() {

            }

            @Override
            public void onError(Exception e) {
                Picasso.get().load(image).into(imageView);
            }
        });
        **getLifecycle().addObserver(youTubePlayerView);
        //youTubePlayerView.getPlayerUIController().showFullscreenButton(false);
        youTubePlayerView.initialize(new YouTubePlayerInitListener() {
            @Override
            public void onInitSuccess(@NonNull final com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayer initializedYouTubePlayer) {
                initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {
                        initializedYouTubePlayer.cueVideo(youtube, 0);
                    }
                });
                Listener();
            }
        }, true);**
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(final View v) {
                if (KontrolFavori(ad,v)){
                    favorites.ekle(ad,yil,puan,image,youtube,ozet,sure,ozet_eng,sure_eng,textcolor,oyuncular,tur,tur_eng,yonetmen);
                    favorites.close();
                    Snackbar.make(v,getResources().getString(R.string.favoriekle),Snackbar.LENGTH_LONG).show();
                }else {
                    AlertDialog.Builder builder = new AlertDialog.Builder((Activity) v.getContext());
                    builder.setTitle(v.getResources().getString(R.string.favoriuyari));
                    builder.setMessage(v.getResources().getString(R.string.favoricikarma));
                    builder.setPositiveButton(v.getResources().getString(R.string.evet), new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                            favorites.deleteData(ad);
                            Snackbar.make(v,getResources().getString(R.string.favoricikti),Snackbar.LENGTH_LONG).show();
                        }
                    });
                    builder.setNegativeButton(v.getResources().getString(R.string.hayir), new DialogInterface.OnClickListener() {
                        @Override
                        public void onClick(DialogInterface dialog, int which) {
                        }
                    });
                    builder.show();
                }
            }
        });
    }

    private void getIncomingIntent(){

        if(getIntent().hasExtra("sure") && getIntent().hasExtra("ad") && getIntent().hasExtra("yil") && getIntent().hasExtra("puan")
                && getIntent().hasExtra("image") && getIntent().hasExtra("youtube") && getIntent().hasExtra("ozet")
                && getIntent().hasExtra("ozet_eng") && getIntent().hasExtra("sure_eng") && getIntent().hasExtra("color")
                && getIntent().hasExtra("oyuncular") && getIntent().hasExtra("tur") && getIntent().hasExtra("yonetmen")
                && getIntent().hasExtra("tur_eng")){

            ad = getIntent().getStringExtra("ad");
            yil=getIntent().getStringExtra("yil");
            puan=getIntent().getStringExtra("puan");
            image = getIntent().getStringExtra("image");
            youtube = getIntent().getStringExtra("youtube");
            ozet = getIntent().getStringExtra("ozet");
            sure=getIntent().getStringExtra("sure");
            ozet_eng=getIntent().getStringExtra("ozet_eng");
            sure_eng=getIntent().getStringExtra("sure_eng");
            textcolor=getIntent().getStringExtra("color");
            oyuncular=getIntent().getStringExtra("oyuncular");
            tur=getIntent().getStringExtra("tur");
            tur_eng=getIntent().getStringExtra("tur_eng");
            yonetmen=getIntent().getStringExtra("yonetmen");

        }
    }

    **private void Listener(){
        youTubePlayerView.addFullScreenListener(new YouTubePlayerFullScreenListener() {
            @Override
            public void onYouTubePlayerEnterFullScreen() {
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);

                fullScreenHelper.enterFullScreen();
            }

            @Override
            public void onYouTubePlayerExitFullScreen() {
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
                fullScreenHelper.exitFullScreen();
            }
        });
    }**

    private boolean KontrolFavori(String ad,View v){
        Favorites favori = new Favorites(v.getContext());
        SQLiteDatabase db = favori.getWritableDatabase();
        Cursor cursor = null;
        String sql ="SELECT * FROM filmler WHERE film_adi='"+ad+"'";
        cursor= db.rawQuery(sql,null);

        if(cursor.getCount()>0){
            cursor.close();
            return false;
        }else{
            cursor.close();
            return true;
        }
    }
    }

Activity Layout:

      <?xml version="1.0" encoding="utf-8"?>
      <androidx.coordinatorlayout.widget.CoordinatorLayout
      xmlns:android="http://schemas.android.com/apk/res/android"
      xmlns:app="http://schemas.android.com/apk/res-auto"
      xmlns:tools="http://schemas.android.com/tools"
      android:id="@+id/detailCoordinator"
      android:layout_width="match_parent"
      android:layout_height="match_parent"
      android:fitsSystemWindows="true"
      tools:context=".details.DetailsActivity">
      <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:fitsSystemWindows="true"
        android:theme="@style/AppTheme.AppBarOverlay">

        <com.google.android.material.appbar.CollapsingToolbarLayout
            android:id="@+id/collapsing_toolbar"
            android:layout_width="match_parent"
            android:layout_height="580dp"
            android:fitsSystemWindows="true"
            android:theme="@style/ThemeOverlay.AppCompat.Dark"
            app:contentScrim="?attr/colorPrimaryDark"
            app:expandedTitleMarginEnd="72dp"
            app:expandedTitleMarginStart="16dp"
            app:layout_scrollFlags="scroll|exitUntilCollapsed">

            <ImageView
                android:id="@+id/detayImage"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:fitsSystemWindows="true"
                android:transitionName="cardPicture"
                android:scaleType="centerCrop"
                app:layout_collapseMode="parallax"
                android:adjustViewBounds="true"/>

            <androidx.appcompat.widget.Toolbar
                android:id="@+id/detay_toolbar"
                android:layout_width="match_parent"
                android:layout_height="?attr/actionBarSize"
                app:layout_collapseMode="pin"
                app:popupTheme="@style/ThemeOverlay.AppCompat.Light" />

        </com.google.android.material.appbar.CollapsingToolbarLayout>
    </com.google.android.material.appbar.AppBarLayout>

    <com.google.android.material.floatingactionbutton.FloatingActionButton
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_like"
        app:fabSize="normal"
        app:layout_anchor="@id/appbar"
        app:layout_anchorGravity="bottom|end"
        android:layout_marginEnd="15dp"
        android:id="@+id/detayFab"
        app:elevation="8dp"/>
    <androidx.core.widget.NestedScrollView
        android:id="@+id/scrollview"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <androidx.cardview.widget.CardView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:cardUseCompatPadding="true"
            app:cardElevation="8dp"
            android:id="@+id/cardview"
            >

            <RelativeLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                android:paddingStart="15dp"
                android:paddingEnd="16dp"
                android:paddingTop="16dp"
                android:id="@+id/cardRelative">
                <TextView
                    android:id="@+id/detayYil"
                    android:text="@string/detayyil"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:textStyle="bold"/>
                <TextView
                    android:id="@+id/detayYilDegisken"
                    android:layout_toEndOf="@id/detayYil"
                    android:text="@string/degisken"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    />
                <ImageView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/detayStar"
                    android:layout_below="@id/detayYil"
                    android:src="@drawable/ic_star"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="10dp"
                    android:contentDescription="@string/film_puani_yildiz"
                    />
                <TextView
                    android:id="@+id/detayPuan"
                    android:layout_toEndOf="@id/detayStar"
                    android:layout_below="@id/detayYil"
                    android:text="@string/degisken"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="10dp"
                    android:textColor="@color/colorBlack"
                    android:transitionName="cardPuan"
                    />
                <TextView
                    android:id="@+id/detaySure"
                    android:layout_below="@id/detayStar"
                    android:text="@string/detay_sure"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:textStyle="bold"/>
                <TextView
                    android:id="@+id/detaySureDegisken"
                    android:text="@string/degisken"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:layout_below="@id/detayStar"
                    android:layout_toEndOf="@id/detaySure"
                    />

                <TextView
                    android:id="@+id/detayYonetmenbaslik"
                    android:layout_below="@id/detaySure"
                    android:text="@string/detayYonetmenbaslik"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:textStyle="bold"/>
                <TextView
                    android:id="@+id/detayyonetmen"
                    android:text="@string/degisken"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:layout_below="@id/detaySure"
                    android:layout_toEndOf="@id/detayYonetmenbaslik"
                    />
                <TextView
                    android:id="@+id/detayTurbaslik"
                    android:layout_below="@id/detayYonetmenbaslik"
                    android:text="@string/detayFilmtur"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:textStyle="bold"/>
                <TextView
                    android:id="@+id/detaytur"
                    android:text="@string/degisken"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="15dp"
                    android:textColor="@color/colorBlack"
                    android:layout_below="@id/detayYonetmenbaslik"
                    android:layout_toEndOf="@id/detayTurbaslik"
                    />
                **<com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView
                    android:id="@+id/youtube_player_view"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginTop="14dp"
                    android:layout_below="@id/detaytur"/>**
                <TextView
                    android:layout_below="@id/youtube_player_view"
                    android:id="@+id/detayOyuncularbaslik"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:text="@string/detayOyuncularbaslik"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="10dp"
                    android:textColor="@color/colorBlack"
                    android:textStyle="bold"
                    />
                <TextView
                    android:id="@+id/detayOyuncular"
                    android:layout_below="@id/detayOyuncularbaslik"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:text="@string/degisken"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="10dp"
                    android:textColor="@color/colorBlack"
                    />
                <TextView
                    android:layout_below="@id/detayOyuncular"
                    android:id="@+id/detayOzetBaslik"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:text="@string/detayozetbaslik"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="10dp"
                    android:textColor="@color/colorBlack"
                    android:textStyle="bold"
                    />
                <TextView
                    android:id="@+id/detayOzet"
                    android:layout_below="@id/detayOzetBaslik"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textSize="18sp"
                    android:text="@string/degisken"
                    android:layout_marginTop="14dp"
                    android:layout_marginStart="10dp"
                    android:textColor="@color/colorBlack"
                    android:paddingBottom="15dp"
                    />
            </RelativeLayout>

        </androidx.cardview.widget.CardView>

    </androidx.core.widget.NestedScrollView>
    </androidx.coordinatorlayout.widget.CoordinatorLayout>

**Comment by PierfrancescoSoffritti** [comment]
Hi, the constructor of `FullScreenHelper` doesn't take any argument. You are passing `this`.

**Comment by utkuakgungor** [comment]
I try it before. When i did like you said it give another error. 

> error: method enterFullScreen in class FullScreenHelper cannot be applied to given types;
required: View
found: no arguments
reason: actual and formal argument lists differ in length

My code:
private FullScreenHelper fullScreenHelper=new FullScreenHelper();


    youTubePlayerView.addFullScreenListener(new YouTubePlayerFullScreenListener() {
            @Override
            public void onYouTubePlayerEnterFullScreen() {
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
                fullScreenHelper.enterFullScreen();
            }

            @Override
            public void onYouTubePlayerExitFullScreen() {
                setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
                fullScreenHelper.exitFullScreen();
            }
        });

**Comment by PierfrancescoSoffritti** [comment]
The error is quite explicit, you need to pass views to enter and exit full screen. [source code](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/player/playerUtils/FullScreenHelper.java)
