### ISSUE TITLE
Open player from fragment

### ISSUE THREAD

**Issue by NetRally** [PierfrancescoSoffritti/android-youtube-player#250]
Hi!
I tried to open player activity from fragment, not fragment transaction, standalone activity,  player shut down immediatly. When I open it from a simple activity, no problem, player working. What did I wrong, or what else can I do to repair?

**Comment by PierfrancescoSoffritti** [comment]
Hi, hard to tell with so little information. But the player is just a View, therefore it works the same on Activities and Fragments.

**Comment by PierfrancescoSoffritti** [comment]
The logcat doesn't help much. I suggest you look at how it's done in the sample app, you must be doing something wrong in the Fragment.
