### ISSUE TITLE
Does the live stream embed livechat? 

### ISSUE THREAD

**Issue by douglasalipio** [PierfrancescoSoffritti/android-youtube-player#252]
I'd like to know if the lib support embeds LiveChat cause I've played with the demo and it seems doesn't support that feature. Does [this](https://support.google.com/youtube/answer/2524549?hl=en) approch work for the lib?

> Live chat is enabled by default and will appear to the right of the video player when your live stream is active. After your live stream ends, viewers will see a replay of live chat when they watch the stream archive. The Live chat module only exists on the YouTube watch pages — it does not follow embedded players. Watch the video [demo](https://www.youtube.com/watch?v=OfZukI05vHg).

**Comment by PierfrancescoSoffritti** [comment]
Hi, no. As far as I know a live chat api doesn't exist.
