### ISSUE TITLE
YoutubePlayerView cannot be casted to LifeCycleObserver // Cannot Resolve Symbol "WebviewYoutubePlayer"

### ISSUE THREAD

**Issue by zafarsk227** [PierfrancescoSoffritti/android-youtube-player#255]
I faced this error
"java.lang.RuntimeException: Unable to start activity ComponentInfo{com.za4tech.android.customyoutube/com.za4tech.android.customyoutube.MainActivity}: java.lang.ClassCastException: com.pierfrancescosoffritti.androidyoutubeplayer.player.YouTubePlayerView cannot be cast to android.arch.lifecycle.LifecycleObserver"
when i went to check YoutubePlayerView implementations I found "Canon resolve symbol 'WebviewYoutubePlayer'" error is the culprit. But now I have no idea how to solve this. Please Help
 
![error](https://user-images.githubusercontent.com/45010641/48428305-c1f27780-e790-11e8-9cca-3c18e05ec1ec.png)

**Comment by PierfrancescoSoffritti** [comment]
Which version of the library are you using?

**Comment by zafarsk227** [comment]
> Which version of the library are you using?

9.0.0
  "implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:9.0.0'"

**Comment by PierfrancescoSoffritti** [comment]
Do you have the same problem with 8.0.1?

**Comment by zafarsk227** [comment]
NO, Now the Issue is totally solved. 
Thanks a Lot Friend

**Comment by PierfrancescoSoffritti** [comment]
Ok, I guess you are still using the old support libraries. To use version 9+ you need to be using the androidx libraries.

**Comment by zafarsk227** [comment]
> Ok, I guess you are still using the old support libraries. To use version 9+ you need to be using the androidx libraries.

a new issue has just occured with the fullscreen view. It looks like this now.( I copied the code from core-sample-app)
![screenshot_20181114-001839_custom youtube](https://user-images.githubusercontent.com/45010641/48435747-38987080-e7a3-11e8-987b-5d5af3398d82.jpg)

**Comment by PierfrancescoSoffritti** [comment]
The library doesn't handle full screen. It's up to you. I suggest you look at how it's done in the [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/basicExample/BasicExampleActivity.java).

**Comment by zafarsk227** [comment]
> The library doesn't handle full screen. It's up to you. I suggest you look at how it's done in the [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/basicExample/BasicExampleActivity.java).

Sorry for disturbing friend. I have resolved the issue and Thanks a lot for helping me out. I will never forget your help.

**Comment by PierfrancescoSoffritti** [comment]
You're welcome, feel free to leave a star to the library on GitHub.

**Comment by zafarsk227** [comment]
> You're welcome, feel free to leave a star to the library on GitHub.

Already Done Friend. but Friend where have you handle the toolbar.I need to remove the toolbar settings otherwise if I am selecting NoTitleBar.Fullscreen theme the app get crashed.

**Comment by PierfrancescoSoffritti** [comment]
Use a [NoActionBar style](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/res/values/styles.xml) if you want to remove the toolbar.

**Comment by zafarsk227** [comment]
> Use a [NoActionBar style](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/res/values/styles.xml) if you want to remove the toolbar.

Yes!! It has worked. thanks again mate. Friend, one last one please. Can we remove the youtube button from the player?

**Comment by PierfrancescoSoffritti** [comment]
Use the PlayerUIController. It's all in the doc.

**Comment by ghozien** [comment]
compileSdkVersion 28
