### ISSUE TITLE
Placeholder Image

### ISSUE THREAD

**Issue by ghozien** [PierfrancescoSoffritti/android-youtube-player#256]
How to add a placeholder image to youTubePlayerView ?
Placeholder image to show when youTubePlayerView is loading & buffering.

**Comment by bryan-ibrahim** [comment]
Incase you don't want to go through the hassle of integrating the YoutubeData API, you can load out the thumbnail using this workaround -> [Using Glide & Picasso](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/135#issuecomment-402082281)
