### ISSUE TITLE
custom action issue

### ISSUE THREAD

**Issue by ghopretz** [PierfrancescoSoffritti/android-youtube-player#262]
This is my code of custom action:

![screenshot 112](https://user-images.githubusercontent.com/8053983/48911575-a892af00-eea5-11e8-8838-a32c76594e3c.png)

but the result of custom action icon is not match with my code:

![screenshot_1542900460 2](https://user-images.githubusercontent.com/8053983/48911740-2fe02280-eea6-11e8-8307-ba90aa4e9d26.png)

**Comment by PierfrancescoSoffritti** [comment]
You are setting `customAction1` twice.
