### ISSUE TITLE
Duplication pause icons in landscape mode

### ISSUE THREAD

**Issue by giperwlad** [PierfrancescoSoffritti/android-youtube-player#263]
Hello.
Duplication pause icons in BasicExample, while landscape mode is active. 
![2018-11-23 12 50 24](https://user-images.githubusercontent.com/20104243/48937193-66f21a80-ef1e-11e8-8e90-2a169c526796.jpg)

This bug reproduced on Samsung s6. Also on sample app from google play.

**Comment by PierfrancescoSoffritti** [comment]
Hi, thank you, but it's not a bug. It's there to show an example of how to use custom actions. I will replace the pause button with something else, to make it more explicit.
