### ISSUE TITLE
Recyclerview Autoplay onscroll

### ISSUE THREAD

**Issue by shreyan007** [PierfrancescoSoffritti/android-youtube-player#264]
On scroll I can get the scrolled item position from that I can get the youTubePlayerView but I cannot access the play function as I cannot access the youTubePlayer interface.

How can I achieve that?

Thanks in advance

This is my code
```
recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                int currentPosition = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
                if (currentPosition == 0|currentPosition > 0){
                    RecyclerView.ViewHolder firstViewHolder = recyclerView.findViewHolderForLayoutPosition(currentPosition);
                    View itemView = Objects.requireNonNull(firstViewHolder).itemView;
                    YouTubePlayerView youTubePlayerView = itemView.findViewById(R.id.youtube_player_view);
                    
                }
            }
        });
```

**Comment by shreyan007** [comment]
How do I get that in scroll listener

**Comment by PierfrancescoSoffritti** [comment]
Your question was: _how do I access the YouTubePlayer from my View holder_

The answer is there. Save a reference to your YouTubePlayer in the view holder, then Just keep doing what you're doing and instead of using the reference to YouTubePlayerView use the reference to YouTubePlayer.

**Comment by shreyan007** [comment]
Tried but don't know the method to get reference to it

**Comment by PierfrancescoSoffritti** [comment]
You get the reference when the [initialization is successful](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/recyclerViewExample/RecyclerViewAdapter.java#L58).

**Comment by shreyan007** [comment]
Yes but what will be the code to get the reference cause
```YouTubePlayerView` youTubePlayerView = itemView.findViewById(R.id.youtube_player_view);```
I can get the view by it but how do I get the youtube player

**Comment by PierfrancescoSoffritti** [comment]
I have highlighted row 58 in the previous link.

**Comment by shreyan007** [comment]
actually I need the code that i would put here

```recyclerView.addOnScrollListener(new RecyclerView.OnScrollListener() {
            @Override
            public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
                super.onScrolled(recyclerView, dx, dy);
                int currentPosition = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
                if (currentPosition == 0|currentPosition > 0){
                    RecyclerView.ViewHolder firstViewHolder = recyclerView.findViewHolderForLayoutPosition(currentPosition);
                    View itemView = Objects.requireNonNull(firstViewHolder).itemView;
                    YouTubePlayerView youTubePlayerView = itemView.findViewById(R.id.youtube_player_view);
                    
                }
            }
        });```

**Comment by shreyan007** [comment]
can you help me out with the code please I'm very new to this

**Comment by PierfrancescoSoffritti** [comment]
The problem you're having is not related to the library, I suggest taking some time to learn how RecyclerView works.
You can learn more about RecyclerView, ViewHolders etc and how to use them by reading the [documentation](https://developer.android.com/guide/topics/ui/layout/recyclerview). Good luck!

**Comment by shreyan007** [comment]
See I can get reference to any view but I cannot get reference to the YoutubePlayer Preference. 
```@Override
           public void onScrolled(@NonNull RecyclerView recyclerView, int dx, int dy) {
               super.onScrolled(recyclerView, dx, dy);
               int currentPosition = linearLayoutManager.findFirstCompletelyVisibleItemPosition();
               if (currentPosition == 0|currentPosition > 0){
                   RecyclerView.ViewHolder firstViewHolder = recyclerView.findViewHolderForLayoutPosition(currentPosition);
                   View itemView = Objects.requireNonNull(firstViewHolder).itemView;
                   **YouTubePlayerView youTubePlayerView = itemView.findViewById(R.id.youtube_player_view);**
                   
               }
           }
       });

**Comment by shreyan007** [comment]
See my player code is initialized in the recycler adapter and I want to get the reference of the player in the main activity and the event is on scroll recyclerview.. There I can get the youtubeplayer view soI can re intitialize it but I need the player to just call play

**Comment by shreyan007** [comment]
See my player code is initialized in the Recycler adapter and I want to get the reference of the player in the main activity and the event is on scroll recyclerview.. 
There I can get the YoutubePlayerView so can re-initialize it but I need the player to just call play.

Please help me out with this..
