### ISSUE TITLE
Can we change the thumbnail of video to show at the beginning / pause of video

### ISSUE THREAD

**Issue by nguyenhuutinh** [PierfrancescoSoffritti/android-youtube-player#265]
Hi,

Can we change the thumbnail of video to show at the beginning / pause of video.
Because it show Youtube logo and AddHistory/share icon when pause video or loading video.
Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, this issue is a duplicate of #242. Unfortunately no, it's not possible. YouTube changed things in their player and now there is not way to remove them.
