### ISSUE TITLE
Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 2716 (Thread-221) in Genymotion

### ISSUE THREAD

**Issue by Neha1904** [PierfrancescoSoffritti/android-youtube-player#266]
@PierfrancescoSoffritti I tried demo app and it crashes for me.

Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 2716 (Thread-221) in Genymotion

Genymotion device details: Custom phone with API 21(768*1280)

Is it due to the hardware limitation on the genymotion emulator?

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes, I suggest using a real device. Even the official emulator gives problems sometimes.

**Comment by PierfrancescoSoffritti** [comment]
👍 if you're using the library, a star on GitHub would be much appreciated :)
