### ISSUE TITLE
Recycler view issue

### ISSUE THREAD

**Issue by girimavin** [PierfrancescoSoffritti/android-youtube-player#269]

**Comment by PierfrancescoSoffritti** [comment]
Hi, I suggest looking at how the [sample app is using RecyclerView](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/recyclerViewExample). For specific behaviors (like the one you described) it's up to you.
