### ISSUE TITLE
Add support for changing playback quality

### ISSUE THREAD

**Issue by harshallele** [PierfrancescoSoffritti/android-youtube-player#27]
The iframe api supports setting playback quality. Can you add support for that in this library?

**Comment by PierfrancescoSoffritti** [comment]
Hi, automatic quality works quite well.
But that would be a useful feature, without any doubt. Unfortunately in this period I'm busy working on other projects, I won't have time to implement the feature in the short term. But if you want to do something: pull requests are well accepted :)

**Comment by PierfrancescoSoffritti** [comment]
I have tried implementing this feature but there are problems with it in the YouTube Iframe API, it doesn't seem to work very well.

**Comment by pralgomathic** [comment]
This is a must need feature in some cases, please add this if possible. thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi @pralgomathic it doesn't seem possible at the current state of the YouTube IFrame API.

Feel free to investigate, pull requests are welcomed.

**Comment by pralgomathic** [comment]
How this android app implemented those features [
Free music for YouTube: Stream
](https://play.google.com/store/apps/details?id=com.djit.apps.stream&hl=en). Hope it's possible and off course I will try to investigate. :)

**Comment by PierfrancescoSoffritti** [comment]
Interesting. Maybe using only HD and small (see [here](https://developers.google.com/youtube/iframe_api_reference#Playback_quality)) it works? not sure.
Let me know if you find something 👍

**Comment by pralgomathic** [comment]
Would you please explain what are the problems you've encountered to add Change Videoplayback quality?

**Comment by PierfrancescoSoffritti** [comment]
I noticed that for most videos the method `setPlaybackQuality` didn't have any effect. Some of the solutions suggested [here](https://stackoverflow.com/questions/8802498/youtube-iframe-api-setplaybackquality-or-suggestedquality-not-working) are quite hacky (in particular the accepted answer). I'd rather not use any hack in a library that other people have to use.

**Comment by PierfrancescoSoffritti** [comment]
After looking further into the issue I've found [this issue](https://issuetracker.google.com/issues/70440398#comment7) on Google's issue tracker.

> due to changes in our player infrastructure, the player will no longer honor requests to set a manual playback quality via the API. As documented, the player has always made a "best effort" to respect the requested quality. 
> 
> The documentation will be updated in the future to indicate this call is no longer supported, though it will still be available as a "no-op" for compatibility purposes.

Apparently the method `setPlaybackQuality` is meant to do nothing.

**Comment by raghavsatyadev** [comment]
have you got any solution for quality control? I looked into your HTML file and saw that you implemented something for it but not using it

**Comment by PierfrancescoSoffritti** [comment]
No, at the moment it's not possible to programmatically change playback quality with the IFrame Player API.

**Comment by JmyW** [comment]
Sorry for old question: 
In this thread, I'm seeing you mentioned "automatic quality works quite well". Could you explain what is "auto quality"? means automatically pull highest quality? or automatically select quality depend on screen resolution?

**Comment by PierfrancescoSoffritti** [comment]
I assume the IFrame API selects the quality of the video based on screen resolution and connection quality. You may find more information on the [docs](https://developers.google.com/youtube/iframe_api_reference).

**Comment by JmyW** [comment]
Got it, thanks

**Comment by bishiboosh** [comment]
One possibility my iOS colleagues found is to stop the video, and restart it at the stopped moment with the new quality.

However, this means calling `loadVideoById` (or `cueVideoById`) with the quality parameter. I can try to make a PR with this change if you want, it's a workaround but could work

**Comment by PierfrancescoSoffritti** [comment]
Not sure I want to incorporate a workaround in the API, what if it stops working at some point?

**Comment by bishiboosh** [comment]
The underlying method in the API is not a workaround. What I was proposing with my PR was to allow the choice of quality when launching the video.

The workaround is the fact that stopping the video and relaunching it at the same timestamp with a different quality can be considered an "alternative" way to change quality.

(you wouldn't expressely specify this method in the README, but the possibility would be there)

I've made a PR, look at it just in case, if you don't think it's necessary I''l use my fork, no worries :)

**Comment by bishiboosh** [comment]
(see documentation here for the cue and load functions in the JS interface : https://developers.google.com/youtube/iframe_api_reference#Video_Queueing_Functions)

**Comment by muankit** [comment]
How to set playback quality always to high or a specific quality ?

**Comment by PierfrancescoSoffritti** [comment]
@muankit At the moment: you can't.

**Comment by rahulsain-ingeniumedu** [comment]
> @muankit At the moment: you can't.

can we use this feature now?

**Comment by PierfrancescoSoffritti** [comment]
It looks like [YouTube official deprecated the ability to set and retrieve video quality](https://developers.google.com/youtube/iframe_api_reference#october-24,-2019). This makes it impossible for this library to do it. 

Closing the issue as this is unfeasible.

**Comment by rahulsain-ingeniumedu** [comment]
@PierfrancescoSoffritti This library is fetching different video qualities
https://github.com/HaarigerHarald/android-youtubeExtractor

**Comment by PierfrancescoSoffritti** [comment]
That library is doing something different, it's not a video player. Also it's breaking YouTube terms of service.

**Comment by rahulsain** [comment]
> That library is doing something different, it's not a video player. Also it's breaking YouTube terms of service.

oh Okay

**Comment by PierfrancescoSoffritti** [comment]
However using webUi it's possible to set the video quality from the UI. Not programmatically.

**Comment by rahulsain-ingeniumedu** [comment]
can we customise webUi?

**Comment by PierfrancescoSoffritti** [comment]
No. WebUI is the UI of the IFrame player.

Also FWY, i am working on an update for the lib, and webUi will become the default ui.

**Comment by Serkali-sudo** [comment]
You can set quality by changing localStorage value of javascript
(local storage is like shared preferences on java)
Heres steps:
1. Enable domStorage of player webview like this (if you dont enable it localStorage functions will be null so you wont able to acess it):
```kt
 settings.domStorageEnabled = true
```
2.Get available quality like this:
```js
JSON.stringify(player.getAvailableQualityLevels())
//eg result : "["hd1080","hd720","large","medium","small","tiny","auto"]"
```
3.Set quality with the result from second step( like: hd1080, hd720, large ,medium, small, tiny, auto )
```js
function setPlaybackQuality(playbackQuality) {
        if (playbackQuality == "auto") {
            //this will make quality auto
            localStorage.removeItem("yt-player-quality");
        } else {
            var now = Date.now();
            //this will set quality of your choice and it will be saved and be default for every video until expires:)
            localStorage.setItem("yt-player-quality", JSON.stringify({
                data: playbackQuality,
                creation: now,
                expiration: now + 2592000000
            }));
        }
        //after you set value you have to reload the player to see the effect.
        //so this method reloads the video where you left it so it is kinda seemless
        if (player) {
            var currentTime = player.getCurrentTime();
            player.loadVideoById(player.getVideoData().video_id, currentTime, playbackQuality);
        }
    }
```

**Comment by Serkali-sudo** [comment]
@PierfrancescoSoffritti 
You can set quality by changing localStorage value of javascript
(local storage is like shared preferences on java)
Heres steps:
1. Enable domStorage of player webview like this (if you dont enable it localStorage functions will be null so you wont able to acess it):
```kt
 settings.domStorageEnabled = true
```
2.Get available quality like this:
```js
JSON.stringify(player.getAvailableQualityLevels())
//eg result : "["hd1080","hd720","large","medium","small","tiny","auto"]"
```
3.Set quality with the result from second step( like: hd1080, hd720, large ,medium, small, tiny, auto )
```js
function setPlaybackQuality(playbackQuality) {
        if (playbackQuality == "auto") {
            //this will make quality auto
            localStorage.removeItem("yt-player-quality");
        } else {
            var now = Date.now();
            //this will set quality of your choice and it will be saved and be default for every video until expires:)
            localStorage.setItem("yt-player-quality", JSON.stringify({
                data: playbackQuality,
                creation: now,
                expiration: now + 2592000000
            }));
        }
        //after you set value you have to reload the player to see the effect.
        //so this method reloads the video where you left it so it is kinda seemless
        if (player) {
            var currentTime = player.getCurrentTime();
            player.loadVideoById(player.getVideoData().video_id, currentTime, playbackQuality);
        }
    }
```

**Comment by PierfrancescoSoffritti** [comment]
I'm glad this workaround works. It can't be merged into the lib though, as with any update YouTube might break it, and our library with it.

This library can only depend on public APIs from the IFrame player.

**Comment by amrashraf1992** [comment]
Hi all,

We need to make sure of quality as most of time video opens with Data saver

![WhatsApp Image 2023-05-11 at 13 33 33](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/37484843/b00c7635-dc05-4963-b0f0-3182ac58b3a0)

We need to change it Higher picture quality

**Comment by sasi2006166** [comment]
So, I suppose we still don't have a solution for this? Note that most methods in the wiki are missing using the java api, I'm not gonna restart the whole project to kotlin.
What can I do about that?

**Comment by PierfrancescoSoffritti** [comment]
Kotlin is interoperable with Java, you can use the library in your Java project.

**Comment by sasi2006166** [comment]
As far I know, yeah, but I'm not able to use methods such as youtubePlayer#setPlaybackQuality.

**Comment by Nayeem0072** [comment]
> @PierfrancescoSoffritti You can set quality by changing localStorage value of javascript (local storage is like shared preferences on java) Heres steps:
> 
> 1. Enable domStorage of player webview like this (if you dont enable it localStorage functions will be null so you wont able to acess it):
> 
> ```kotlin
>  settings.domStorageEnabled = true
> ```
> 
> 2.Get available quality like this:
> 
> ```js
> JSON.stringify(player.getAvailableQualityLevels())
> //eg result : "["hd1080","hd720","large","medium","small","tiny","auto"]"
> ```
> 
> 3.Set quality with the result from second step( like: hd1080, hd720, large ,medium, small, tiny, auto )
> 
> ```js
> function setPlaybackQuality(playbackQuality) {
>         if (playbackQuality == "auto") {
>             //this will make quality auto
>             localStorage.removeItem("yt-player-quality");
>         } else {
>             var now = Date.now();
>             //this will set quality of your choice and it will be saved and be default for every video until expires:)
>             localStorage.setItem("yt-player-quality", JSON.stringify({
>                 data: playbackQuality,
>                 creation: now,
>                 expiration: now + 2419200000
>             }));
>         }
>         //after you set value you have to reload the player to see the effect.
>         //so this method reloads the video where you left it so it is kinda seemless
>         if (player) {
>             var currentTime = player.getCurrentTime();
>             player.loadVideoById(player.getVideoData().video_id, currentTime);
>         }
>     }
> ```

Hello, does this still work? I tried this code but seems to me if I use Youtube iframe API it does not work, since this `yt-player-quality` is set to localstorage under the parent site domain, not under the youtube.com domain, where it is supposed to be set.
