### ISSUE TITLE
The sound runs before the image of the video

### ISSUE THREAD

**Issue by Namdh1212** [PierfrancescoSoffritti/android-youtube-player#270]
In my app. The sound runs before the image of the video. 
The reason appears to be at slower images. 
I tried on devices Smart TV Android and Emulator Android TV (720p). 

If I changed code then the application runs normally but app not show full screen :(

`      
    		player = new YT.Player('youTubePlayerDOM', {	
                height: '75%',
    			width: '75%',
`

**Comment by PierfrancescoSoffritti** [comment]
Interesting. Could it be that the device you're using isn't performant enough? Try to play a YouTube video on the web, in full screen and see what happens there.
