### ISSUE TITLE
Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.pierfrancescosoffritti.androidyoutubeplayer:core:9.0.0.

### ISSUE THREAD

**Issue by HDharmesh** [PierfrancescoSoffritti/android-youtube-player#272]

**Comment by PierfrancescoSoffritti** [comment]
Hi, have you follow the [download instructions](https://github.com/PierfrancescoSoffritti/android-youtube-player#download)?

**Comment by PierfrancescoSoffritti** [comment]
Also, double check that you have this 
```
allprojects {
    repositories {
        jcenter()
    }
}
```

in your project-level gradle file.

**Comment by HDharmesh** [comment]
yes i also integrated all your instruction

**Comment by HDharmesh** [comment]
owk thank you for your fast response.   i will try to start from first

**Comment by PierfrancescoSoffritti** [comment]
I suggest creating a new empty project and trying there. Also make sure you're connected to the internet.

**Comment by HDharmesh** [comment]
yes sir.

**Comment by PierfrancescoSoffritti** [comment]
As it says in the link i gave you: "your app needs to be using the androidx libraries instead of the old support libraries."

**Comment by HDharmesh** [comment]
can you send me zip file for this project?

**Comment by PierfrancescoSoffritti** [comment]
Just look at the [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app).

**Comment by HDharmesh** [comment]
thank you sir,
