### ISSUE TITLE
Connectivity change listener

### ISSUE THREAD

**Issue by ghopretz** [PierfrancescoSoffritti/android-youtube-player#273]
Can you add connectivity change listener to detect where device is online or offline?

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks for the suggestion. I will consider it for one of the upcoming releases.

**Comment by ghopretz** [comment]
Thank you. I wait for it.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I am not going to add a listener for connectivity changes. I don't think emitting network events should be a responsibility of `YouTubePlayerView`.

If you are interested in listening to those events, you should initialize the player with `youTubePlayerView.initialize(youtubePlayerListener, false)` and handle connectivity changes with your own code.
