### ISSUE TITLE
Smart wrap_content

### ISSUE THREAD

**Issue by Anton721** [PierfrancescoSoffritti/android-youtube-player#277]
Can you please add wrap_content support depending from video ratio (18:9, 18.5:9 etc)?
I try to put View inside cardview without black lines, and it is unreal

**Comment by PierfrancescoSoffritti** [comment]
Hi, there is already an issue to add support for 18:9 screens, issue #71.
You can also manually specify the size of the player, instead of using wrap_content.

**Comment by Anton721** [comment]
Thank you, but I try to make video player for different videos with various properties

**Comment by PierfrancescoSoffritti** [comment]
Sorry, I think I don't understand.

**Comment by Anton721** [comment]
If I manually set 18:9 ratio I will have vertical black lines in 16:9 videos
And inversely)

**Comment by PierfrancescoSoffritti** [comment]
It's not possible. I'm afraid you will have to find a way to do it [using the Data API](https://stackoverflow.com/questions/5010495/how-to-get-youtube-video-aspect-ratio).
