### ISSUE TITLE
viewing full screen to exit swipe down from the top got it message

### ISSUE THREAD

**Issue by aliakkawi** [PierfrancescoSoffritti/android-youtube-player#278]
Hello and thanks for the library,
when entering full screen mode in some device a pop message is displayed: "viewing full screen to exit swipe down from the top got it", the cause the player to exit full screen, is there a way to get rid of this message?
Thanks
<img width="389" alt="screen shot 2019-01-07 at 20 42 50" src="https://user-images.githubusercontent.com/14969941/50786667-d77dac80-12bc-11e9-949d-c946f89e0ea7.png">

**Comment by PierfrancescoSoffritti** [comment]
Hi, this message is shown by Android, not by the library. I think it is shown only the first time (ever) a user enters full screen mode.

The library itself doesn't handle full screen, it is supposed to be handled by the developer using it. So it's up to you to implement the proper logic.
