### ISSUE TITLE
Chromecast not just on youtube videos

### ISSUE THREAD

**Issue by Angelk90** [PierfrancescoSoffritti/android-youtube-player#279]
Hi @PierfrancescoSoffritti , I read the article on medium, I wondered if it was possible to do the same thing with non-youtube videos, such as video .mp4.
Do you think in the future to be able to implement such a thing?

**Comment by PierfrancescoSoffritti** [comment]
Hi, it is definitely possibile, but the feature won't be added to the library.

The goal of this library is to provide an alternative way to play YouTube videos on Android (and some enhancements, like chromecast playback). Playing videos in general is out of scope.

But feel free to fork the project and adapt the code to better fit your use case!

**Comment by Angelk90** [comment]
@PierfrancescoSoffritti : In fact I was wondering if you had in mind to create a special library, it would be very useful.
Only way to contact you was here.
The part that takes care of this is all inside: chromecast-sender, right?

**Comment by PierfrancescoSoffritti** [comment]
I have no plans to build a separate library, at the moment.

You can find the Android code in the `chromecast-sender` module and the chromecast code in the `chromecast-receiver` module.

Also I remember seeing online a tutorial from Google about casting mp4 videos, you may want to search that first.
