### ISSUE TITLE
setSurface method

### ISSUE THREAD

**Issue by ghopretz** [PierfrancescoSoffritti/android-youtube-player#282]
Can this YoutubePlayerview using setSurface method likes MediaPlayer?

**Comment by PierfrancescoSoffritti** [comment]
Hi, what does `setSurface` do?

**Comment by ghopretz** [comment]
I want to use YouTubePlayerView for replacing MediaPlayer in Vuforia Video Playback App.

**Comment by PierfrancescoSoffritti** [comment]
This library can only play YouTube videos, not other videos.
