### ISSUE TITLE
Load only the thumbnail

### ISSUE THREAD

**Issue by hivian** [PierfrancescoSoffritti/android-youtube-player#283]
Hello,

When I want to initialize a youtube video, I see only two functions: loadvideo() and cueVideo(). But It would be great if I could only load the thumbnail without loading the video.

The problem is when the video is initialised in a RecyclerView ViewHolder, the YoutubePlayer is reload each time onBind() is called, whereas I'd like the video to load only when I click on it.

**Comment by PierfrancescoSoffritti** [comment]
Hi, you can look at the [RecyclerView example in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/recyclerViewExample).

Calling `cueVideo()` will load the thumbnail without playing the video.

**Comment by amirdora** [comment]
> Hi, you can look at the [RecyclerView example in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/aytplayersample/examples/recyclerViewExample).
> 
> Calling `cueVideo()` will load the thumbnail without playing the video.

link is broken

**Comment by PierfrancescoSoffritti** [comment]
https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/recyclerViewExample
