### ISSUE TITLE
Not able to import the library in gradle file

### ISSUE THREAD

**Issue by abdulsattar-sit** [PierfrancescoSoffritti/android-youtube-player#288]
Whenever I try to import the lib from jcenter()

like implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:9.0.1' I am facing the below issue 

Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.pierfrancescosoffritti.androidyoutubeplayer:core:9.0.1.

below is my gradle fine content 

**Application gradle file:**

apply plugin: 'com.android.application'

android {
    compileSdkVersion 28
    defaultConfig {
        applicationId "com.example.myapplication"
        minSdkVersion 19
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:9.0.1'
}

**Project gradle file:**

buildscript {
    
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.google.com' }
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        mavenCentral()
        maven { url 'https://maven.google.com' }
        maven { url 'https://maven.fabric.io/public' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

Please help to resolve the issue

**Comment by abdulsattar-sit** [comment]
Hi,

Issue resolved. It was my proxy issue

**Comment by PierfrancescoSoffritti** [comment]
Ah, nice. Well done!

if the library is useful to you consider leaving a star on GitHub :)
