### ISSUE TITLE
Videos in RecyclerView refuse to play next video after it ends

### ISSUE THREAD

**Issue by HalfMillennium** [PierfrancescoSoffritti/android-youtube-player#291]
I've been trying to get this to work for a while, and this is probably an issue for me because of my unfamiliarity with RecyclerViews. However, this code only works for the first video (plays the second video after it has completed), which I don't understand, since the `onBindViewHolder()` method is clearly being iterated through because of the `position` variable. Does anyone know how I'd get this to work for every video in the RecyclerView? Here is the code for my onBindViewHolder method:

```
@Override
    public void onBindViewHolder(@NonNull ViewHolder viewHolder, int position) {
        viewHolder.cueVideo(videoIds[position]);
        viewHolder.youTubePlayerView.initialize(initializedYouTubePlayer ->
                initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {
                        viewHolder.youTubePlayer = initializedYouTubePlayer;
                        viewHolder.youTubePlayer.cueVideo(videoIds[position], 0);
                    }
                    // playNext() instead
                    @Override
                    public void onStateChange(@NonNull PlayerConstants.PlayerState state) {
                        if(state.equals(PlayerConstants.PlayerState.ENDED))
                        {
                            Log.d("nextId_mod", orderInt.get(position+1));
                            if(position+1 < videoListSize) {
                                viewHolder.youTubePlayer.loadVideo(orderInt.get(position+1), 0);
                                Log.d("nextVid", orderInt.get(position+1));
                            }
                        }
                    }

                    @Override
                    public void onPlaybackQualityChange(@NonNull PlayerConstants.PlaybackQuality playbackQuality) { }

                    @Override
                    public void onPlaybackRateChange(@NonNull PlayerConstants.PlaybackRate playbackRate) { }

                    @Override
                    public void onError(@NonNull PlayerConstants.PlayerError error) { }

                    @Override
                    public void onApiChange() { }

                    @Override
                    public void onCurrentSecond(float second) { }

                    @Override
                    public void onVideoDuration(float duration) { }

                    @Override
                    public void onVideoLoadedFraction(float loadedFraction) { }

                    @Override
                    public void onVideoId(@NonNull String videoId) { }
                }), true);
    }
```

**Comment by PierfrancescoSoffritti** [comment]
Hey, if I understand correctly this issue is not related to the library. I suggest opening a question on StackOverflow. Also, you didn't explain what you're trying to do.

**Comment by HalfMillennium** [comment]
I'm sorry? Isn't the function of the 'youtubePlayer' method exclusive to this library? Also, I did explain what I was trying to do, which is to play the next video after the current one ends.

**Comment by HalfMillennium** [comment]
Yes, the next video in the RecyclerView. I apologize for not making that clear initially. My goal is for the whole thing to behave like a playlist.

**Comment by PierfrancescoSoffritti** [comment]
Ok, then you're code is not correct. If I understand correctly you're trying to play the next video from the same YouTubePlayerView. You should instead find a way to get the next YouTubePlayerView (and call play on it) when the currently playing player stops playing.

As I mentioned before the issue here is not with the library, I suggest you [read more about RecyclerView](https://developer.android.com/guide/topics/ui/layout/recyclerview) and practice the basics before trying more advanced stuff.

Good luck :)

**Comment by HalfMillennium** [comment]
Yeah, thanks for your help, man. Again, you answered my question within the scope of the library. As it turns out, I misunderstood what the 'youtubePlayer' was vs. the 'youtubePlayerView'. I wasn't trying to say there was something wrong with your work, as you correctly changed the issue to a question.

I understand that I am not super familiar with RecyclerViews, but you don't have to remind me of that. I know you didn't mean your comment to be condescending, but it definitely came out that way.

**Comment by HalfMillennium** [comment]
Ah, nevermind, you were just trying to help. Sorry about that.
