### ISSUE TITLE
Recycler view full screen mode (Question)

### ISSUE THREAD

**Issue by AlexFedorenko** [PierfrancescoSoffritti/android-youtube-player#311]
Hello
I'm trying to use full screen mode from recycler
For do that i change recycler view item height and width when go to full screen, hide all other recycler view item and hide all in fragment and activity
That's wright or may be was simple way to do this?
I have to many code for hiding and changing layuot params

**Comment by AlexFedorenko** [comment]
Maybe you have some examples how better to hide other elements in recycler view

**Comment by PierfrancescoSoffritti** [comment]
Hi, that sounds about right!

**Comment by geekhack** [comment]
@AlexFedorenko How did you hide other items to get full screen, having the same issue but working with expandablelistview
