### ISSUE TITLE
Video restarts on orientation Change - ExpandableListView

### ISSUE THREAD

**Issue by geekhack** [PierfrancescoSoffritti/android-youtube-player#312]
I have attached a video inside the getChildView of an expandablelistview and works fine until the orientation change.
@Override 
public View getChildView(final int groupPosition, final int childPosition,
                             boolean isLastChild, View convertView, ViewGroup parent){
final Info childText = (Info) getChild(groupPosition, childPosition);
youTubePlayerView=convertView.findViewById(R.id.youtube_player_view);
youTubePlayerView.initialize(new YouTubePlayerInitListener(){
@Override     
public void onInitSuccess(final YouTubePlayer initializedYouTubePlayer){
                initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener(){
                    @Override public void onReady(){
                        String videoId = child.getYoutube_url();
                        initializedYouTubePlayer.cueVideo(videoId, 0);
                        initializedYouTubePlayer.play();
}
                });
}
}, true);
}
The video restarts.I have used the listview inside a fragment.

**Comment by PierfrancescoSoffritti** [comment]
Hi, by default Activities are destroyed and restarted when the orientation changes. [Read here](https://stackoverflow.com/questions/4568558/how-to-avoid-restarting-activity-when-orientation-changes-on-android).

**Comment by geekhack** [comment]
I have actually set the orientation within the manifest file.When orientation moves to landscape, the video plays until when i touch the screeen, it restarts.This only happens for the video only.The other items in the other expandable items are not affected with the orientation changes.

**Comment by PierfrancescoSoffritti** [comment]
I'm sorry I don't have enough information to help you.

**Comment by geekhack** [comment]
Thanks Pier for the support and here is what I have done so far:
**in AndroidManifest.xml**
<activity
            android:name=".MainActivity"
            android:label="@string/title_activity_landing"
            android:resizeableActivity="true"
            android:supportsPictureInPicture="true"
            android:theme="@style/AppTheme.NoActionBar"
            android:configChanges="screenSize|orientation/>

**in fragment**
@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
                View v=inflater.inflate(R.layout.pfragment, container, false);
               expandableListView = v.findViewById(R.id.list);
               expandableAdapter =new ExpandableAdapter(this, listDataGroup, listDataChild);
             
return v;
}

**In  the expandableAdapter**
@override
public View getChildView(final int groupPosition, final int childPosition,boolean isLastChild, View convertView, ViewGroup parent){
                final Info childText = (Info) getChild(groupPosition, childPosition);
                youTubePlayerView=convertView.findViewById(R.id.youtube_player_view);

               youTubePlayerView.initialize(new YouTubePlayerInitListener(){
                @override
                public void onInitSuccess(final YouTubePlayer initializedYouTubePlayer){
                            initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener(){
                            @override public void onReady(){
                              String videoId = child.getYoutube_url();
                              initializedYouTubePlayer.cueVideo(videoId, 0);
                              initializedYouTubePlayer.play();
                          }
                   });
   }
}, true);
}
