### ISSUE TITLE
AppCompat issue

### ISSUE THREAD

**Issue by yoonusc** [PierfrancescoSoffritti/android-youtube-player#318]
Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
  	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
  	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:12:5-125:19 to override.

**Comment by PierfrancescoSoffritti** [comment]
This is not very useful. Are you using appcompat? you should use androidx instead.

**Comment by yoonusc** [comment]
Thanks for your fast response any way I found another smilers library
that's worked well
