### ISSUE TITLE
Manifest merger failed 

### ISSUE THREAD

**Issue by advancedgithubuser** [PierfrancescoSoffritti/android-youtube-player#319]
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:22:5-349:19 to override.

**Comment by PierfrancescoSoffritti** [comment]
Hi, are you using appcompat? you should use androidx instead.

**Comment by abahl817** [comment]
@PierfrancescoSoffritti buddy I understand that its good to switch to AndroidX. It might have its advantages, but as is the case with the other Google implementations, this one is also not done properly. I tried migrating to AndroidX but it just broke my code left, right and center. It is not possible for me to switch at this moment in time. However, I want to request you to please release a separate version of your code with older support libraries.

**Comment by PierfrancescoSoffritti** [comment]
Hi, the support libraries are not supported anymore by Google itself. So going forward Androidx is going to be mandatory. I don't see any really good reason to release a new version of the lib based on the support libraries.

The migration tool in Android AStudio may miss something but it should be fairly trivial to fix by hand the resulting compilation errors. What problem are you having exactly?

Version 8.0.1 of the lib was the last one based on the support libraries, you can use that, but its not going to be up to date.

**Comment by abahl817** [comment]
Hey, I am caught up in the middle of a release cycle and my project has a really huge codebase and even after using the migration technique where I set jetifier = true, there were a lot of errors. So I just skipped doing it for now and thought of doing it after the release. 
Also, I couldn't find the migration tool in Android Studio. Please reply with the steps for the same.

**Comment by PierfrancescoSoffritti** [comment]
Everything is explained [here](https://developer.android.com/jetpack/androidx/migrate). Good luck!

**Comment by abahl817** [comment]
Hey buddy, thank you for that link you shared. I read the web page thoroughly and found out an option in Android Studio which helped a bit. I still had to fix and refactor the code manually but it was a good exercise and trip down the memory lane ;p.

Thanks a lot!

**Comment by PierfrancescoSoffritti** [comment]
You're welcome, I'm glad you made it :)
