### ISSUE TITLE
if we put you tube video id with hyphen then it gives crash android pie  https:\/\/www.youtube.com\/watch?v=PVaho9L-dic

### ISSUE THREAD

**Issue by reeteshfarmstock** [PierfrancescoSoffritti/android-youtube-player#322]
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter videoId

**Comment by PierfrancescoSoffritti** [comment]
Hi, hyphens are not an issue, i just tested. This is the id 'PVaho9L-dic', not the whole url.
