### ISSUE TITLE
Live stream Video ID update issue

### ISSUE THREAD

**Issue by zeeshanTEO** [PierfrancescoSoffritti/android-youtube-player#324]
I'm streaming Live video using **PierfrancescoSoffritti-android-youtube-player** but video id changes after every 2-3 days.. Could you please guide me whether I've to pay to YouTube or to respective channel to retain same video ID.

**Comment by PierfrancescoSoffritti** [comment]
Hi, you probably need to use the YouTube Data API to always get the newest video.
