### ISSUE TITLE
Playback quality

### ISSUE THREAD

**Issue by DimitrisStaratzis** [PierfrancescoSoffritti/android-youtube-player#325]
Hello,
Thank for the library, it works pretty well. Is it possible to add the ability for the user to manually select the quality of the video as it happens in the Android YouTube API. I don’t mean setting the quality programmatically but manually when the video plays.

**Comment by PierfrancescoSoffritti** [comment]
No, unfortunately at the moment it's not possible to change the quality with the IFrame Player API. See issue #27

**Comment by AaravTim** [comment]
Hello,
Thank for the library, it is possible can in enable the menu option of youtube player in your library
