### ISSUE TITLE
unable to resolve with android latest version 

### ISSUE THREAD

**Issue by abdulrahmanmajeed** [PierfrancescoSoffritti/Android-YouTube-Player#33]
hi, i've updated my app and getting error after upgrading from 25 to 26, please help me to sort out this issue

compileSdkVersion 26
buildToolsVersion "26.0.1"

![untitled](https://user-images.githubusercontent.com/4646811/30404146-9161966e-98fe-11e7-891a-4bf8f1b50b98.png)

**Comment by PierfrancescoSoffritti** [comment]
I'm not sure this is an issue with the library. Could you send me your gradle file (app level)?

**Comment by abdulrahmanmajeed** [comment]
![untitled](https://user-images.githubusercontent.com/4646811/30404350-c9232224-98ff-11e7-92c7-86531bced22f.png)

**Comment by PierfrancescoSoffritti** [comment]
uhm.. maybe you can try to download the library, updated its dependencies and build your app using the local library. 
Let me know if you still have problems after trying that, if everything works a pull request is more than welcome :)

**Comment by amit13091992** [comment]
@PierfrancescoSoffritti Hi, can u please tell me the latest version for this dependency as I am getting an error while adding the dependency in build.gradle:
ERROR: Failed to resolve: com.pierfrancescosoffritti.androidyoutubeplayer:core:1.0.2

Thanks in advance.

**Comment by hannojg** [comment]
It’s 1.0.3 :)

**Comment by amit13091992** [comment]
I am getting error while using 
1. getLifeCycle().addObserver(youtubePlayerView); 

And 

2. Youtubeplayerview.addyoutubeplayerListener( new ...)

In 1st its saying that lifecycleobserver can't be applied to youtubeplayerview

In 2nd .addYouTubePlayerListener() method doesn't exist.

Can u plz help me out about these 2 errors plz.

**Comment by PierfrancescoSoffritti** [comment]
@amit13091992 please open separate issues for each of your problems.

**Comment by amit13091992** [comment]
> @amit13091992 please open separate issues for each of your problems.

Sure. Just created a new issue.
