### ISSUE TITLE
how did you manage to remove webUI?

### ISSUE THREAD

**Issue by heeyounglee** [PierfrancescoSoffritti/android-youtube-player#330]
Thank you so much for the library.
I'd like to customize youtube UI in iframe on web version / ios,
but don't understand how you manage to remove the youtube web UI (title, watch later, share).
I'm not familiar with android, so it's hard to understand how this works.
Is such functionality available for android (e.g., loadDataWithBaseURL only load video but not load UI)?
Is it possible to do this on web version or ios WkWebView too?

**Comment by PierfrancescoSoffritti** [comment]
Hi, it's not possible to remove the title, watch later and share buttons from the Iframe player without using hacks. If you check the sample app, they are there.

**Comment by crearo** [comment]
Oh man. This sucks :(
And YouTube probably wouldn't be happy if I used a hack.

**Comment by PierfrancescoSoffritti** [comment]
Correct, I think it goes against their terms of service.
