### ISSUE TITLE
Resize PIP rectangle to match screen width(Question) 

### ISSUE THREAD

**Issue by DoM4** [PierfrancescoSoffritti/android-youtube-player#331]
Hi, 
thanks for this amazing library.
I was wondering if there's a way to make the rectangle in PIP mode to match the screen width, so far I've tried to change the aspectRatio with PictureInPictureParams but it can't go over a specific number.
Ideally I'd like to have it like Whatsapp PIP size, but I don't know if is possible.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I'm not sure if there's a way to do it, but the library is definitely not limiting the size of the rectangle, since the player always fills the whole space.
