### ISSUE TITLE
Is there any option to change youtube play to my own customized icon

### ISSUE THREAD

**Issue by mohanvthink** [PierfrancescoSoffritti/android-youtube-player#333]
I used youTubePlayer.cueVideo() to show youtube video without playing the video, in this state youtube play icon is showing, is there any option to change youtube play to my own customized icon,

**Comment by mohanvthink** [comment]
<img width="191" alt="Capture" src="https://user-images.githubusercontent.com/13622163/54992925-9f962380-4fe6-11e9-90b3-18485755284e.PNG">
You can find youtube play in the center of the image

**Comment by PierfrancescoSoffritti** [comment]
No unfortunately that icon is not customizable, since it is part of the IFrame player.
