### ISSUE TITLE
Issue since version 10.0.2 stopping playback

### ISSUE THREAD

**Issue by hannojg** [PierfrancescoSoffritti/android-youtube-player#334]
Hey,

I have mentioned that the library updated to 10.0.2 and tested it. Unfortunately, as soon as I try to play the video it plays for half of a second and then stops automatically. I think this is related to the `canPlay` attribute in `LegacyYouTubePlayerView` somehow that seems to be bound to some sort of lifecycle of the player. I do not bind any life cycle in my use case.
So, `canPlay` stays false and blocks the playback. This is the only idea I have why it doesn't work. 

If you think it is an implementation issue on my side and my assumption is wrong, please let me know.
(As my usage/implementation is a bit complicated I currently try to find a pattern on how to reproduce this issue.)

Thank you for your time!

**Comment by PierfrancescoSoffritti** [comment]
Hey, thank you for reporting the bug. You are right, the logic is not implemented correctly. I suggest you roll back to version 10.0.1 until this will be fixed in version 10.0.3! thanks for the help!

**Comment by hannojg** [comment]
Okay, glad to hear that I didn't mess up any listeners in my implementation 😄 thank you!

**Comment by PierfrancescoSoffritti** [comment]
Bug fixed. But I'll do some further testing before releasing the patch!

**Comment by PierfrancescoSoffritti** [comment]
Version 10.0.3 released. Thanks for the help!
