### ISSUE TITLE
Is it possible to play private videos using auth 2.0 or youtube api key?

### ISSUE THREAD

**Issue by rakeshdausa** [PierfrancescoSoffritti/android-youtube-player#336]
I want to play some tutorial videos in my app but I don't want expose these videos out side the app. So can I play private videos using some kind of auth mechanism like Auth2.0 or youtube api key?

**Comment by PierfrancescoSoffritti** [comment]
You probably should use auth with the YouTube Data API, and get the video IDs from there. The player has no concept of authentication. Let me know if it works!

**Comment by rakeshdausa** [comment]
No it doesn't work it shows **This video is unavailable**.

**Comment by PierfrancescoSoffritti** [comment]
Ok, I am currently traveling. I'll do some tests when I get home!

**Comment by NeilKerman** [comment]
> Ok, I am currently traveling. I'll do some tests when I get home!

Hi have you tested it out?

**Comment by PierfrancescoSoffritti** [comment]
No, haven't had time for this yet.

**Comment by anthony3444** [comment]
Hi there!

Is there any news about this test and the possibility to play private videos?

Thank you very much!

**Comment by PierfrancescoSoffritti** [comment]
Hi, this is still not supported.

**Comment by TheMohitRao** [comment]
Any update here ?

**Comment by PierfrancescoSoffritti** [comment]
There are no plans to add support for this, authentication is outside the scope of the library.
