### ISSUE TITLE
AbstractYouTubePlayerListener onReady() not called

### ISSUE THREAD

**Issue by hayton** [PierfrancescoSoffritti/android-youtube-player#339]
I am using the player in a fragment with the simplest implementation.

`<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
                `<addr><br>`android:id="@+id/youtubePlayer"
                `<addr><br>`android:layout_width="match_parent"
                `<addr><br>` android:layout_height="wrap_content"/>`

`youtubePlayer.addYouTubePlayerListener(object: AbstractYouTubePlayerListener(){`<br>`
                    `<addr>`override fun onReady(youTubePlayer: YouTubePlayer) {`<br>`
                       `<addr>` `<addr>`val videoUri = Uri.parse("https://www.youtube.com/embed/myVideoId?feature=oembed")`<br>`
                        `<addr>` `<addr>`youTubePlayer.cueVideo(videoUri.pathSegments[1], 0f)`<br>`
                        `<addr>` `<addr>`Log.d(TAG, "ytplayer; onready videoid= ${videoUri.pathSegments[1]} for url= `<addr>` `<addr>`$videoUri")`<br>`
                        super.onReady(youTubePlayer)`<br>`
                    }`<br>`
                })`

I have a RecyclerView showing a list of youtube url. Let's say from 'Url1" to "Url10".
Url1
Url2
.
.
Url10

When I click on the "Url1", the app opens a fragment containing the YouTube player, resulting a successful load and the video can be played without any issue. I can see the log message in the console But when I click on "Url2", the YouTube player stays on a black screen with a loading circle, and I see no log in the console. If I click on the same link (i.e. Url2) again, the player is able to load the video and the log appears in the console.

**Comment by PierfrancescoSoffritti** [comment]
Hi, it's hard for me to say anything with so little information. From your description I can only assume that you're doing something wrong in the Fragment logic.
