### ISSUE TITLE
Single player instance and reuse in multiple views

### ISSUE THREAD

**Issue by Sp4Rx** [PierfrancescoSoffritti/android-youtube-player#340]
Is it possible to create a single instance of the player and dynamically add it in different views? To be specific a frame layout in a recyclerView. And can also have to option to play with different ids.

**Comment by PierfrancescoSoffritti** [comment]
mm maybe if you initialise and release it each time it could work, but I'm not sure. I suggest trying building a simple demo. Let me know how it goes!

**Comment by Sp4Rx** [comment]
Sure I will revert back in some time

**Comment by PierfrancescoSoffritti** [comment]
Yeah that makes sense. Glad you figured it out :)

**Comment by yasahmed** [comment]
@Sp4Rx  did you find any solution ?

**Comment by Sp4Rx** [comment]
@yasahmed Hey I used it long back, I even forgot in which project I have used it 🥺. Please tell me your problem, or what you have done. May be I can help

**Comment by yasahmed** [comment]
@Sp4Rx thank's for your time, i created a single instance of YouTubePlayerView object and i would like to reuse it in multiple views if is it possible

**Comment by PierfrancescoSoffritti** [comment]
> i created a single instance of YouTubePlayerView object and i would like to reuse it in multiple views if is it possible

It's not possible. Unless you manually remove it and add it to each view.

**Comment by Sp4Rx** [comment]
Yes that's what I did I think @PierfrancescoSoffritti.

And @yasahmed  Add a frame layout in the xml. Then on activity get the instance of the frame layout using `findViewById` on any other method. Now lets assume your Youtube instance name is `youtubePlayer` and frame layout name is `frameLayout`.
So to add the view you can do `framelayout.addView(youtubePlayer)` later remove it from this frame layout before adding to other views else it will throw error.

Tips: Use a handler for view operations. Also use weak reference of context if you are making the youtubePlayer singleton 

I just wanted to make you understand the logic. If you find this difficult I will try to create a small demo.

**Comment by yasahmed** [comment]
@PierfrancescoSoffritti removing it and add it to a new view stop the player.

**Comment by yasahmed** [comment]
@PierfrancescoSoffritti @Sp4Rx this is my question on stackOverflow with an example : 

https://stackoverflow.com/questions/68509357/android-youtube-player-video-playing-stopped-when-i-remove-youtubeplayerview-v


the same question on github : 

https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/761

Thank's for your time guys

**Comment by yasahmed** [comment]
@Sp4Rx Thank you

**Comment by PierfrancescoSoffritti** [comment]
> removing it and add it to a new view pause the player

there's no way around that, i believe

**Comment by yasahmed** [comment]
@PierfrancescoSoffritti Thank you very much :)
