### ISSUE TITLE
How to add custom seekbar and play/pause button when useWebUi is true

### ISSUE THREAD

**Issue by Praveena0989** [PierfrancescoSoffritti/android-youtube-player#342]
Because in the document I can see that showSeekBar attribute does nothing if useWebUi is true. I want to listen to seeking event so I am trying to create own seekbar

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to [create your own custom ui](https://github.com/PierfrancescoSoffritti/android-youtube-player#create-your-own-custom-ui). Consider using the [provided seekbar](https://github.com/PierfrancescoSoffritti/android-youtube-player#youtubeplayerseekbar).

**Comment by Praveena0989** [comment]
@PierfrancescoSoffritti  but that is not hiding existing seek bar

**Comment by PierfrancescoSoffritti** [comment]
You need to disable (or just not enable) web ui.

**Comment by Praveena0989** [comment]
In native UI are you using native youtube library?  I am moving to your library just because of native youtube library has so many glitches which make apps keep on crashing.

**Comment by Praveena0989** [comment]
Got it. According to the doc native means native UI but youtube still plays webview. Please correct me here If I am wrong here

**Comment by PierfrancescoSoffritti** [comment]
Yes, this library always uses the IFrame (web) player. But you can decide if you want to use the web ui or a native ui.

**Comment by Praveena0989** [comment]
Thank you.

**Comment by Praveena0989** [comment]
Totally unrelated to this issue but is there any way to hide related videos shown in the end?

**Comment by PierfrancescoSoffritti** [comment]
No, unfortunately it is not possible. The IFrame API forces it to be visible.

**Comment by Praveena0989** [comment]
I still don't understand how come airtime app guys managed to do it

**Comment by PierfrancescoSoffritti** [comment]
it looks like they are not using the web player, but directly getting the video stream from YouTube.

**Comment by Praveena0989** [comment]
I thought that's against TOS of youtube

**Comment by PierfrancescoSoffritti** [comment]
It probably is!
