### ISSUE TITLE
Playback delay after orientation change.

### ISSUE THREAD

**Issue by Praveena0989** [PierfrancescoSoffritti/android-youtube-player#343]
I am handling orientation change properly and activity is not recreating even android-youtube-player is not starting again from 0th second but it is rebuffering the video. I guess it's because of webview's dimension change. I tried playing youtube videos in my own webview with fixed dimension(using CSS) then rebuffering did not happen on rotation but as soon I change dimension to 100% video will re-buffer on orientation change. Is there any fix for this?

**Comment by PierfrancescoSoffritti** [comment]
Hi, orientation changes don't give any problems [in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample). Could you please check if you're doing something wrong?

**Comment by Praveena0989** [comment]
@PierfrancescoSoffritti  Even sample has this problem. I recorded my screen while using the sample app [Here you go](https://drive.google.com/file/d/15GZGhMz1__wnuILwwUqN_wv3G6HdAwBq/view?usp=sharing)

**Comment by PierfrancescoSoffritti** [comment]
Ah, that's weird. It doesn't happen on my phones. What phone and version of Android are you using?

It is not re-buffering. There is just a big delay.

**Comment by Praveena0989** [comment]
Brand=asus model= ASUS_X00TD SDK level=27  RAM = 6GB

**Comment by Praveena0989** [comment]
Hi @PierfrancescoSoffritti  it is indeed buffering not delay. You can check in your player state example. I have setup toast message for the player state in my app and it is entering the buffering state. Also, it is happening in all my emulator also(nexus and pixels)

**Comment by PierfrancescoSoffritti** [comment]
Hey, unfortunately I'm not able to reproduce this issue. Can't say much about it. Could you make a simple example project to replicate the problem?

I checked the player state example in the same app, on my phone it does not enter buffering state on orientation changes.

If you have an issue with `match_parent`, could it be that the parent is being resized?

**Comment by Praveena0989** [comment]
I guess no point in creating example app as your example app only not working on my phone then there must be something wrong with my phone.

**Comment by PierfrancescoSoffritti** [comment]
Ah, right. Let me know you make any progress, pull requests are very welcome :)

**Comment by Praveena0989** [comment]
@PierfrancescoSoffritti  I guess sample works fine only on your phone. I just checked the same app on one plus 3t and it rebuffers on orientation change

**Comment by hannojg** [comment]
Just an idea, but isn’t it possible that it is somehow related to the webview? 
In my implementation I do some “transformations” to the player view and sometimes receiving on some devices pause and buffer states when doing these “transformations”, which could also be orientation changes as the view gets recreated.

**Comment by Praveena0989** [comment]
@PierfrancescoSoffritti  Did you get time to check on mobile other than yours? Which phone do you use? I will test it on that phone. I tested the sample app on - one plus 3t, Asus m1, and nexus 5x,6p, pixel emulators  and video rebuffers on orientation change

**Comment by PierfrancescoSoffritti** [comment]
@Praveena0989 I have tried on a Galaxy S2, nexus 5 and pixel 2 xl. It works fine for me.

**Comment by Praveena0989** [comment]
That's interesting. Even on emulators?

**Comment by PierfrancescoSoffritti** [comment]
Haven't tried on emulator for a while, but there you should be using only the latest stable versions of Android.
