### ISSUE TITLE
Issues with Moto E

### ISSUE THREAD

**Issue by JohScho** [PierfrancescoSoffritti/android-youtube-player#344]
Hey, 
i've noticed some bugs on API levels lower than 23.
On api 17 my player doesnt scroll with a scroll view or recycler view, instead just stays at the same place that it is initialized.

On api 19 i cant load any video, in the logcat i get the error appended. [Api_19.txt](https://github.com/PierfrancescoSoffritti/android-youtube-player/files/3053843/Api_19.txt)

On api 21 videos are just stuck loading without any error log.

Additionally there appears a second loading circle out of nowhere on all those Api's.
All these bugs are also present when using the WebUi.

I would be really glad if you can help me with these problems.

**Comment by hannojg** [comment]
Hey, 
have you Hardware accelerating activated in your activity? If not, does it give you different output if you activate.

**Comment by JohScho** [comment]
I have it activated, after a little more browser in the issues here i have found out it might be the emulators problem. The problem for api 21 for example works fine on a real device. The problem here is that i dont have enough real devices to test all api levels i want to release for.

**Comment by vickyv363** [comment]
Even i am facing the same issue in Api version 19. 

1) Video load got stuck 
2) A progress bar appears suddenly and remaining forever. It got stuck in buffering state. The same is working fine in api version 9.0.1

**Comment by PierfrancescoSoffritti** [comment]
Hey, the library doesn't work well on old version of Android in the emulator. See issue #112. It does work on real devices.

**Comment by vickyv363** [comment]
Hi, 

For me it is not working on both emulator and real device...

Here is the Device info:

Name: Moto E
OS: Kitkat 4.4.4
Ram: 1GB
Internal Storage: 4GB
Processor: Snapdragon 200,  Dual-core 1.2 GHz Cortex-A7

**Comment by PierfrancescoSoffritti** [comment]
Have you tried running the [sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/apk) on your physical device? Does it work?

**Comment by vickyv363** [comment]
I tried just now. These are my observations in kitkat device.

1) In the sample app i chose custom UI example.
2) In this case, once the youtube player is ready it start to show the progress bar by itself. 
3) When the data is buffering, press home button and return to app.
4) Now the player is stuck in the buffering state even in high speed internet connection.

**Comment by PierfrancescoSoffritti** [comment]
Ok. I don't have any Kitkat device but I'll see what I can do. If you want to look into the source code and fix the issue,  feel free to send a pull request!

**Comment by JohScho** [comment]
Alrighty, i have managed to gather a few real devices with different apis and it really seems to work on them. Thanks for the answer!

**Comment by vickyv363** [comment]
@JohScho Is it... I will try with some other device then... 

@PierfrancescoSoffritti  Sure... Will try to reproduce in other devices too... If it persists will make the change and send the pull request.. Thanks for the api !!!

**Comment by vickyv363** [comment]
@PierfrancescoSoffritti  I have tested the scenario in few other devices, It is working fine as expected. It seems to be an issue with that Moto E device alone.

**Comment by PierfrancescoSoffritti** [comment]
@vickyv363 thanks for the update!
