### ISSUE TITLE
There is a small red dot positioned under the seekbar

### ISSUE THREAD

**Issue by Keesdil** [PierfrancescoSoffritti/android-youtube-player#347]
Hi sir,

Your library works great!
Only i find a small red dot right under the seekbar. It can be moved on the screen but does not change the display, so its meaning is not clear to me.
How can i get rid of it?

**Comment by PierfrancescoSoffritti** [comment]
Hi, could you please share a screenshot?

**Comment by Keesdil** [comment]
Find here the a screenshot !
![Screenshot_20190410-154328](https://user-images.githubusercontent.com/16447657/55884527-85dd0a80-5ba8-11e9-9c5a-992af52444e9.png)
See the white field under the picture, containing the lower seekbar, the function of which is not clear to me.
Thanks in advance!

**Comment by PierfrancescoSoffritti** [comment]
Interesting. Could you share your xml file and Java/Kotlin code?

**Comment by Keesdil** [comment]
Sorry, my error!
Presuming that a seekbar had to be added to the YouTubePlayerView, 
i had my own seekbar in the xml file and was calling that with a seekbar listener in my java file!

**Comment by PierfrancescoSoffritti** [comment]
Ah ok, thanks for the update!

**Comment by PierfrancescoSoffritti** [comment]
Ah ok, thanks for the update!
