### ISSUE TITLE
Add support for playing playlists

### ISSUE THREAD

**Issue by JoseMarioPerezCotes** [PierfrancescoSoffritti/android-youtube-player#348]
hello pierfrancesco, I want know if is posible to play a playlist just like the official youtube api?

**Comment by PierfrancescoSoffritti** [comment]
Hi, currently the only way to play a playlist is to play new videos each time one finishes.

A future improvement for the library could be implementing the [playlist](https://developers.google.com/youtube/player_parameters#playlist) parameter in [IFramePlayerOptions](https://github.com/PierfrancescoSoffritti/android-youtube-player#iframeplayeroptions).

**Comment by acrolink** [comment]
That would be a great enhancement.

**Comment by mumenAlmadaineh** [comment]
Was this feature added? -If yes, how can I add a playlist to API (Android Studio)

**Comment by PierfrancescoSoffritti** [comment]
There is no support for playlists.

**Comment by mumenAlmadaineh** [comment]
😥

**Comment by PierfrancescoSoffritti** [comment]
thanks to @flauschtrud playlists are now supported in the library :)
