### ISSUE TITLE
I want to display the video with centerCrop scaleType

### ISSUE THREAD

**Issue by duy07t1k23cht** [PierfrancescoSoffritti/android-youtube-player#350]
I want to display the video with scaleType like centerCrop in ImageView.

I've try to change the size of the view by using `android:layout_width` and `android:layout_height`. But the video was also resized.

**Comment by PierfrancescoSoffritti** [comment]
Hi,

> I want to display the video with scaleType like centerCrop in ImageView.

I'm not sure what you mean, cold you clarify?

**Comment by duy07t1k23cht** [comment]
When I resize the YouTubePlayerView

What it was:
![lisano](https://user-images.githubusercontent.com/28984578/56213466-4588fb00-6086-11e9-9838-6b1d622e2f3b.png)
What I want:
![lisayes](https://user-images.githubusercontent.com/28984578/56213479-4de13600-6086-11e9-8310-3b1fff0cdd8c.png)

**Comment by duy07t1k23cht** [comment]
Before I resize, i set:
`android:layout_width="match_parent"` and `android:layout_height="200dp"`

It looked like this:
![lisa](https://user-images.githubusercontent.com/28984578/56215212-7880be00-6089-11e9-961b-8d3f163f7355.png)

**Comment by PierfrancescoSoffritti** [comment]
The IFrame player (web player) is made to always fit the screen. 
One way to do what you want is to fork the library and play with the css. Like changing it at runtime. This is just off the top of my head, let me know if you find better ways to do it.

**Comment by duy07t1k23cht** [comment]
OK, Thank you!
