### ISSUE TITLE
YouTubePlayerView setOnClickListener and setOnLongClickListener not working 

### ISSUE THREAD

**Issue by KaranMavadhiya** [PierfrancescoSoffritti/android-youtube-player#352]
The click events are never fired. If I put a transparent view in front of my youtube view, the click event is fired for that transparent view, but then that transparent view steals the click event from the youtube seekbar, play, fullscreen button etc.

Any suggestions?

binding.youtubePlayerView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                   // TODO : need to perform some event 
                }
            });

binding.youtubePlayerView.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    // TODO : need to perform some event 
                    return true;
                }
            });

**Comment by PierfrancescoSoffritti** [comment]
Please refer to issue #105. Pull requests are welcome!
