### ISSUE TITLE
Unable to click on related videos  

### ISSUE THREAD

**Issue by priyanallan** [PierfrancescoSoffritti/android-youtube-player#353]
Hi the related videos shown during pause or end of the video are not clickable. How do i enable this? Thanks in advance

**Comment by PierfrancescoSoffritti** [comment]
Hi, use the [web-based UI](https://github.com/PierfrancescoSoffritti/android-youtube-player#web-based-ui).

**Comment by priyanallan** [comment]
Sure. Does any of your samples shows how to handle this scenario?

**Comment by PierfrancescoSoffritti** [comment]
Yes. [webui example](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/webUiExample).

**Comment by priyanallan** [comment]
Thanks for the quick response, will check it
