### ISSUE TITLE
how to simultaneously play 2 videos on "Recycler"?

### ISSUE THREAD

**Issue by kenmobi** [PierfrancescoSoffritti/android-youtube-player#358]
Hi!
I have created a "recycler" list but I cannot play 2 videos at a time on the list

Hope everybody help please. thank

**Comment by PierfrancescoSoffritti** [comment]
Hi, Android by default only allows one source of audio at a time.

**Comment by kenmobi** [comment]
> Hi, Android by default only allows one source of audio at a time.

hi!
Thanks I know. so I edited the video volume at 0 level (setVolume (0)) but it still doesn't work

**Comment by PierfrancescoSoffritti** [comment]
I assume that the level of the volume doesn't really matter, what matters is the number of media sources playing at the same time.

**Comment by kenmobi** [comment]
> I assume that the level of the volume doesn't really matter, what matters is the number of media sources playing at the same time.

thanks

**Comment by PierfrancescoSoffritti** [comment]
Let me know if you find a way to solve the problem!
