### ISSUE TITLE
addYouTubePlayerListener() cannot resolve the method.

### ISSUE THREAD

**Issue by amit13091992** [PierfrancescoSoffritti/android-youtube-player#359]
getLifecycle().addObserver(youTubePlayerView); //In this line its giving error as lifecycleobserver can't be applied to youtubeplayerview.

```
 youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady() {
                super.onReady();
                youTubePlayer.loadVideo(videoId, 0);
            }
```
and here in above code block its giving  .addYouTubePlayerListener() method doesn't exist. error. Can u please help me out reolving these two errors.

**Comment by PierfrancescoSoffritti** [comment]
You need to use [androidx](https://developer.android.com/jetpack/androidx/migrate). The old support libraries are not supported anymore. This should fix at least the first problem.

**Comment by aymenjegham** [comment]
The method addYouTubePlayerListener doesn't exist at all in source code, that's very strange

**Comment by PierfrancescoSoffritti** [comment]
This issue refers to an old version of the library. Now you should use `addListener`. You can find everything in the doc.
