### ISSUE TITLE
How can I cast video from multiple sources

### ISSUE THREAD

**Issue by stoddayy** [PierfrancescoSoffritti/android-youtube-player#360]
I have an app that uses videos from 2 sources, some videos are from YouTube and some are hosted on AWS and played using exoplayer, I’ve been looking in to chrome cast and it looks like you can only register one receiver for the app, is there a way I would be able to use your method for casting the YouTube videos and casting the hosted videos in the same app using one receiver?

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes. You need to take [the sample receiver](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-receiver) I wrote and and extra logic to handle videos coming from AWS.
