### ISSUE TITLE
Set full screen control flags

### ISSUE THREAD

**Issue by priyanallan** [PierfrancescoSoffritti/android-youtube-player#361]
Hi,

I want to control the automatic behaviour of fullscreen toggle using this https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer#setFullscreenControlFlags(int) so that i can set a custom layout on fullscreen. 

Is there a way to access this in your library? Thank you.

**Comment by PierfrancescoSoffritti** [comment]
Hi, this library doesn't use the YouTubePlayer API. Therefore you cannot access that method.

**Comment by priyanallan** [comment]
Can we achieve this in any other way using the API you used? Any suggestions?

**Comment by PierfrancescoSoffritti** [comment]
Well first of all understand exactly what that function does. It seems like it changes stuff on Android itself instead of on the player, therefore you can easily replicate it using Android APIs.
