### ISSUE TITLE
One video never player that having a problem of unavailable 

### ISSUE THREAD

**Issue by SidhuPawandeep** [PierfrancescoSoffritti/android-youtube-player#362]
I am facing one problem while playing a video. if i hit same url play  on browser but it doesn't play in my apps. Unable to identify the exact problem.

Please help  me.
```
   binding.youtubePlayerView.initialize(initializedYouTubePlayer -> initializedYouTubePlayer.addListener(
                new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {
                   /*     if (mFilePath.startsWith("https") || mFilePath.startsWith("http"))
                            initializedYouTubePlayer.loadVideo(Utils.extractYTId(mFilePath), bundle.getIntExtra(Constants.VIDEO_SEEK, 0));
                        else
                            initializedYouTubePlayer.loadVideo(mFilePath, bundle.getIntExtra(Constants.VIDEO_SEEK, 0));
                  */
                        initializedYouTubePlayer.loadVideo("o4Smy6aW5Ik", 0);

                    }
                }), true);


        binding.youtubePlayerView.enterFullScreen();
```

**Comment by PierfrancescoSoffritti** [comment]
Hard to tell from this, I suggest looking at the [same app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample) for examples.

**Comment by SidhuPawandeep** [comment]
Thanks for your response.

Actually given video is restricted by video owner. so it doesn't play in any other application rather than youtube app.

**Comment by PierfrancescoSoffritti** [comment]
Ah ok, makes sense. Thanks for the update!

**Comment by markeins** [comment]
> Thanks for your response.
> 
> Actually given video is restricted by video owner. so it doesn't play in any other application rather than youtube app.

Hi there, how did you find out that the video was **restricted by video owner**?

Thanks in advance!

**Comment by sdarshn** [comment]
@markeins the listener would trigger `onError(youTubePlayer: YouTubePlayer, error: PlayerConstants.PlayerError) `function and Error has this name "VIDEO_NOT_PLAYABLE_IN_EMBEDDED_PLAYER" . Using this you can provide alternate solution in your app
