### ISSUE TITLE
Audio Video Sync issue when played to android 5 or lower device.(mainly in aosp devices)

### ISSUE THREAD

**Issue by adhirupak** [PierfrancescoSoffritti/android-youtube-player#363]
Audio is playing faster than video .video is slow in compare to audio.How to fix ?

**Comment by hannojg** [comment]
Do you experience the same issues with the sample app? Please try if you haven’t already. 

It is hard to find the issue with so few information.

**Comment by adhirupak** [comment]
Yes in I tried with sample app also , there is also same problem audio playing faster video is quite slow so audio video not sync in android api level 21 and lower  devices

**Comment by PierfrancescoSoffritti** [comment]
Most likely this is a problem of the IFrame player API in WebView on the device you're using. If that's the case there's not much we can do, unfortunately.
