### ISSUE TITLE
Taking a screenshot of the view

### ISSUE THREAD

**Issue by crearo** [PierfrancescoSoffritti/android-youtube-player#365]
Here's my hierarchy:
```
CardView
     |
     -> ImageView
```
When I call 
```
Bitmap bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888);
            Canvas canvas = new Canvas(bitmap);
            view.layout(0, 0, view.getMeasuredWidth(), view.getMeasuredHeight());
            view.draw(canvas);
```

it dumps the `cardview` and its contents into the bitmap just how I'd like it.
After replacing the `imageview` with the `youtubeplayerview`, all i get is a black screen. On setting `drawingCacheEnabled()`, the controls of the video show up, but the video part remains black. Any clue why?

**Comment by PierfrancescoSoffritti** [comment]
Hi, I don't understand.

**Comment by crearo** [comment]
Basically I want to capture the view containing the videoview and save it as a bitmap. 
What the app looks like when playing the video.
![Screenshot_2019-05-06-10-19-41-945_rish crearo lifehacks](https://user-images.githubusercontent.com/10224559/57211403-d3526900-6fe8-11e9-89fd-32a01ccc5ba2.png)
What the app looks like when the video is paused.
![Screenshot_2019-05-06-10-19-44-549_rish crearo lifehacks](https://user-images.githubusercontent.com/10224559/57211404-d3526900-6fe8-11e9-8fe3-fd96733ce745.png)
What happens when I'm sharing the image.
![Screenshot_2019-05-06-10-19-59-543_com whatsapp](https://user-images.githubusercontent.com/10224559/57211405-d3526900-6fe8-11e9-95ce-312c0676ee71.png)

**Comment by PierfrancescoSoffritti** [comment]
How are you saving the image? I've never done anything similar, I'm not sure I can provide help.

**Comment by crearo** [comment]
Ah alright. 
Once I have the bitmap, it's fairly straightforward. All I have to do is save the bitmap to png. 
I'm not sure, but I think the `WebView` you're using uses a `SurfaceView` to render, which doesn't come under the CardView hierarchy. 
Anyway, thanks!

**Comment by PierfrancescoSoffritti** [comment]
Let me know if you find a solution, could be useful to other users in the future :)

**Comment by Devrath-cnx** [comment]
@crearo ... Were you able to resolve this ? ..... How did you take the pitchure. ?
.
I am trying I am also getting the blank image

**Comment by crearo** [comment]
I don't remember what I did but it did work. 
Do try. If you can't I'll try digging up the source for what I did

**Comment by victor22325** [comment]
@crearo  I cannot take the picture, please share your method let me know. thanks

**Comment by mariuspena** [comment]
@crearo please share the solution. we are also stuck
