### ISSUE TITLE
Youtube shows strange green areas 

### ISSUE THREAD

**Issue by sergiambel** [PierfrancescoSoffritti/android-youtube-player#366]
In some devices users play the youtube videos perfectly but, after few seconds, the video player starts showing really strange mode.

Take a look to the screenshot: [Screenshot](https://imgur.com/GwXsHoC)

I bet the issue is in youtube side but, do you have any idea how to fix? maybe enabling/disabling hardware acceleration o something similar?

I've attached how we enable your view in our layout:

```
 <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@color/black">

    <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:showFullScreenButton="false"
        app:showYouTubeButton="false"
        app:useWebUi="false" />

 </androidx.constraintlayout.widget.ConstraintLayout>

```

**Comment by sergiambel** [comment]
After some tests we have found the issue happen when YouTubePlayerView size is big. I mean, if we define layout_width and layout_height as 300dp and 200dp the video plays perfect, when bigger (or fullscreen mode) starts to appear as in the screenshot.

**Comment by PierfrancescoSoffritti** [comment]
Is this issue happening on Android TV?

**Comment by sergiambel** [comment]
yes it is

**Comment by sergiambel** [comment]
We'll follow the progress in the related issue

**Comment by acrolink** [comment]
> Is this issue happening on Android TV? Could this be related to #351?

On Fujicom and Peerless Android 8.0 based systems it does not happen. On some TV boxes, yes it does.
