### ISSUE TITLE
Crash if adding from xml

### ISSUE THREAD

**Issue by Faiyyaz** [PierfrancescoSoffritti/android-youtube-player#367]
Hey thank you for such a great library.

I m facing an issue where if I use youtubeplayerview from xml then it crash saying class not found but if I m adding the view programmatically it works fine & also the video is playing but not rendering properly

**Comment by PierfrancescoSoffritti** [comment]
Hey, I need more information to provide useful help. Eg. what version of the lib are you using, your build.gradle file and xml layout.

**Comment by Faiyyaz** [comment]
I don't know but now it's working fine thanks for the help☺
