### ISSUE TITLE
Show video title before video is played?

### ISSUE THREAD

**Issue by gajicm93** [PierfrancescoSoffritti/android-youtube-player#370]
Hi, is there a way to show the video title (official YouTube title, not custom one), even before the video is played? Currently it looks like the screen in the center here: https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/images/showcase.jpg

**Comment by PierfrancescoSoffritti** [comment]
It's not possible with the library. You can download the title of the video using the [YouTube Data API](https://developers.google.com/youtube/v3/) and then show it.

**Comment by gajicm93** [comment]
Ok thanks.
