### ISSUE TITLE
ChromeCast does not end when Android app was killed

### ISSUE THREAD

**Issue by quangnguyen511** [PierfrancescoSoffritti/android-youtube-player#371]
I found many sources and they said there is no callback when app was killed.
So that i decide to stop the Casting video when user go back to my app, but i can't find any methods or source code to get the playing cast session to stop, should I initialize it again or i have to do something ?

Please help
And thank you for your contribution for this library

**Comment by PierfrancescoSoffritti** [comment]
Hi, a cast session is not supposed to finish when the app gets killed. I am pretty sure you can programmatically terminate it though. Have you looked at chromecast's doc?

**Comment by quangnguyen511** [comment]
Thanks for you response, i tried the default sender from Google, it ended itself by default.
I can't end current session in your library because when user go back to the app everything is null , i want to get the current session to stop it. 
Do you have any suggestion ?

**Comment by PierfrancescoSoffritti** [comment]
If you go back to the app while a cast session is in progress the library recognises it, therefore if everything is null you must be doing something wrong. I suggest you take a look at the [chromecast sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/chromecast-sender-sample-app) to see how it's done there.

> i tried the default sender from Google, it ended itself by default
What I meant is that the cast session should not terminate when the app is killed. For reference see how YouTube is doing it.

**Comment by quangnguyen511** [comment]
"If you go back to the app while a cast session is in progress the library recognises it"
Could you please tell me the library recognize depend on what object or method ?
