### ISSUE TITLE
How can I show thumbnails in a recyclerview similar to the official youtube api? Or can I use this part of the official api?

### ISSUE THREAD

**Issue by jonasxd360** [PierfrancescoSoffritti/android-youtube-player#374]
How can I show thumbnails in a recyclerview similar to the official youtube api? Or can I use this part of the official api while using your player?

I want users to be able to search for a video and then select one from that search. I would then get the "id" of the video to use it in a later step in the app. Is this possible with this api? 

Thank you!

**Comment by PierfrancescoSoffritti** [comment]
To download thumbnails (and other data) of YouTube videos you need to use the [YouTube Data API](https://developers.google.com/youtube/v3/).

**Comment by jonasxd360** [comment]
Thank you

**Comment by thawri1** [comment]
use this url :
https://img.youtube.com/vi/<VIDEO ID HERE>/0.jpg
