### ISSUE TITLE
remove player ui on custom ui

### ISSUE THREAD

**Issue by zynth17** [PierfrancescoSoffritti/android-youtube-player#376]
hi, i want to ask about completely custom ui
i have check the tutorial you made and even the sample apps
all i want to do is removing all default ui from the youtube player and replace it with my own ui
when i follow the tutorial it can implement my custom ui but the default ui wont hide
like this picture below : 

![Screenshot_2019-05-28-13-57-06-260_com matali spikchat](https://user-images.githubusercontent.com/45350572/58457487-081d9000-8151-11e9-85ad-004ee56ea554.png)

as you can see that the title of the video, the menu and the youtube button is still showing
please help me, thankyou

here is my xml 

>  ``` xml
> 
> <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:layout_centerInParent="true"
>         android:id="@+id/yt_player_view">
>     </com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView>
> 
>  ```

here is my code

> ```kotlin 
> val customUiView = youtubeView.inflateCustomPlayerUi(R.layout.youtube_custom_player_ui)
>        youtubeView.addYouTubePlayerListener(object : AbstractYouTubePlayerListener(){
>             override fun onReady(youTubePlayer: YouTubePlayer) {
>                 super.onReady(youTubePlayer)
>                 val customPlayerUiController = CustomPlayerUiController(activity.applicationContext,customUiView,youTubePlayer,youtubeView)
>                 youTubePlayer.addListener(customPlayerUiController)
>                 youTubePlayer.loadVideo(videoID,videoTime.toFloat())
>             }
>         })

**Comment by PierfrancescoSoffritti** [comment]
Hi, the [web UI of the IFrame player](https://github.com/PierfrancescoSoffritti/android-youtube-player#web-based-ui) cannot be removed, unfortunately. If that's what you mean.

**Comment by eneim** [comment]
> Hi, the [web UI of the IFrame player](https://github.com/PierfrancescoSoffritti/android-youtube-player#web-based-ui) cannot be removed, unfortunately. If that's what you mean.

Hi, regarding the web UI, I wonder if it can be "removed" by adding CSS rules to your raw html? Have no idea if we can do this trick on the iframe. 

(I saw your web experience and I guess you have thought about this, so just in case it is a new thing).

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes it can be done. But unfortunately it's an hack and Google won't be happy about it :) so I am not going to do it in the library. But feel free to fork it and apply the changes to your own branch!

**Comment by zynth17** [comment]
> > Hi, the [web UI of the IFrame player](https://github.com/PierfrancescoSoffritti/android-youtube-player#web-based-ui) cannot be removed, unfortunately. If that's what you mean.
> 
> Hi, regarding the web UI, I wonder if it can be "removed" by adding CSS rules to your raw html? Have no idea if we can do this trick on the iframe.
> 
> (I saw your web experience and I guess you have thought about this, so just in case it is a new thing).

hi can you help how can i add css to remove this ui?

**Comment by eneim** [comment]
@zynth17 it is just my idea and due to the same reason @PierfrancescoSoffritti mentioned above I will never try that. Please figure out by yourself.

**Comment by PierfrancescoSoffritti** [comment]
@zynth17 you can take a look at [this pull request](https://github.com/PierfrancescoSoffritti/android-youtube-player/pull/254).

**Comment by developerAnkit** [comment]
> @zynth17 you can take a look at [this pull request](https://github.com/PierfrancescoSoffritti/android-youtube-player/pull/254).

@zynth17 does this worked for you?

**Comment by LetrixZ** [comment]
> > @zynth17 you can take a look at [this pull request](https://github.com/PierfrancescoSoffritti/android-youtube-player/pull/254).
> 
> @zynth17 does this worked for you?

It worked for me, although the logo, ending cards and related videos still there and don't know how to remove them.
