### ISSUE TITLE
Module 'com.github.PierfrancescoSoffritti:AndroidYouTubePlayer:8.0.1' depends on one or more Android Libraries but is a jar

### ISSUE THREAD

**Issue by rohitgarg29** [PierfrancescoSoffritti/android-youtube-player#377]
Hi @PierfrancescoSoffritti 

I am getting this issue:

Module 'com.github.PierfrancescoSoffritti:AndroidYouTubePlayer:8.0.1' depends on one or more Android Libraries but is a jar

is there reason why i am getting this?

Regards,
Rohit

**Comment by PierfrancescoSoffritti** [comment]
Can I see your build.gradle file?

**Comment by rohitgarg29** [comment]
that issue is resolved but i can not migrate the whole project for AndroidX, is there way to use it without migration ?

**Comment by PierfrancescoSoffritti** [comment]
No. I suggest you [migrate your app](https://developer.android.com/jetpack/androidx/migrate). The old support libraries are not supported anymore.

**Comment by rohitgarg29** [comment]
but you mentioned in one of your comments that we will not require that with 8.0.1 version. Isn't it?

**Comment by PierfrancescoSoffritti** [comment]
Well sure, if you want to use an old version of the library :) not recommended though. You will have to migrate to AndroidX at some point. Better soon than later.

**Comment by rohitgarg29** [comment]
yes, i am using 8.0.1 and i can not migrate for now, but will plan in future for the same. Can you please tell me which old version should i use?

**Comment by PierfrancescoSoffritti** [comment]
yes, 8.0.1.

**Comment by rohitgarg29** [comment]
but for this as well, at runtime, it is giving me below issue, 

error: cannot access LifecycleObserver
class file for android.arch.lifecycle.LifecycleObserver not found

**Comment by rohitgarg29** [comment]
i added the dependency compile 'android.arch.lifecycle:common:1.1.0@jar'

this resolved my issue, i think its correct to do??

**Comment by PierfrancescoSoffritti** [comment]
Yes. Or use app compat.
