### ISSUE TITLE
Loading previous video when playing from list.

### ISSUE THREAD

**Issue by kunwarshekhar** [PierfrancescoSoffritti/android-youtube-player#378]
Using version: 8.0.1

When I am playing video from the list, first video play properly but when you select other videos it stills plays the same old playing video from start.

Log.e("Playing Video",videoId);
youTubePlayer.loadVideo(videoId,0);

I put a log just before loading video to the player and I got all the videos ids I tried to play.
After tapping on three different videos from the list I got this log for the last tap:

Playing Video: Ek17-Sh7jtA
Playing Video: rJqX-YUZddc
Playing Video: _cPHiwPqbqo

the first video tapped was rJqX-YUZddc
the last video tapped was  Ek17-Sh7jtA

**Comment by PierfrancescoSoffritti** [comment]
From what you are describing it looks like there is some bug in your code.

**Comment by kunwarshekhar** [comment]
I am directly using this 

    public void playVideo(final String videoId , String song_name)
    {

        tv_song_name.setText(song_name);

        playerView.initialize(new YouTubePlayerInitListener() {
            @Override
            public void onInitSuccess(@NonNull final YouTubePlayer youTubePlayer) {
                youTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {
                        Log.e("Playing Video",videoId);
                        youTubePlayer.loadVideo(videoId,0);
                    }
                });
            }
        }, true);
    }


when tapping on the list which is passing videoid and name to this function.

**Comment by PierfrancescoSoffritti** [comment]
Why are you initializing the player each time. You should initialize it just the first time and then call `loadVideo`.

**Comment by kunwarshekhar** [comment]
How can I use youTubePlayer directly from outside.

**Comment by Cortlandd** [comment]
Lol what you just asked was basically my question.
My code looks like the following.:

```
// Global
var initializedYouTubePlayer: YouTubePlayer? = null

override fun onCreate() {
    initYoutubePlayerView()
}

private fun initYoutubePlayerView() {

        playerView = findViewById(R.id.player_view)
        lifecycle.addObserver(playerView!!)

        playerView?.addYouTubePlayerListener(object: AbstractYouTubePlayerListener() {
            override fun onReady(youTubePlayer: YouTubePlayer) {
                super.onReady(youTubePlayer)
                initializedYouTubePlayer = youTubePlayer
                initializedYouTubePlayer!!.addListener(tracker)
            }
      }
}
```


Pass initializedYouTubePlayer anywhere to play video now.

**Comment by PierfrancescoSoffritti** [comment]
Thanks @Cortlandd !

**Comment by kunwarshekhar** [comment]
Thanks, it helped.
