### ISSUE TITLE
Some video cannot play?

### ISSUE THREAD

**Issue by JmyW** [PierfrancescoSoffritti/android-youtube-player#379]
I test this video “ gdwjXjGkZ1A ” but couldn’t play. Does anyone know why?

**Comment by greatwayedge** [comment]
For this specefic video the publisher chose to not make it playable outside youtube website, so it can't be played through the api. There are other kind of restrictions in some cases for instance the video is restricted for some countries.

**Comment by JmyW** [comment]
I think so too. Thanks a lot.
