### ISSUE TITLE
Prevent the default progress bar

### ISSUE THREAD

**Issue by Cortlandd** [PierfrancescoSoffritti/android-youtube-player#380]
Is there any way to remove the default progress bar the shows inside the player? 

I'm thinking it could potentially confuse users of the App to think something is loading.

**Comment by PierfrancescoSoffritti** [comment]
Hi, unfortunately it's not possible to remove basic components from the web UI.

**Comment by Cortlandd** [comment]
Thanks mate!

**Comment by Cortlandd** [comment]
Thanks mate!
