### ISSUE TITLE
Recommendation on pause 

### ISSUE THREAD

**Issue by ketankmr** [PierfrancescoSoffritti/android-youtube-player#382]
![Capture](https://user-images.githubusercontent.com/25217497/59489762-b25f1c80-8ea0-11e9-8952-1b6e550e4a0c.PNG)

Recommendations come up when video is paused and it takes you to web view.
Is there a way to disable this?

**Comment by PierfrancescoSoffritti** [comment]
Hi, no unfortunately the IFrame API doesn't allow it.

**Comment by ketankmr** [comment]
is there a way to handle the link internally and not open web view

**Comment by PierfrancescoSoffritti** [comment]
There should be a way to handle clicks on a WebView, I suggest you take a look at the doc.
