### ISSUE TITLE
Not possible to set origin in IFramePlayerOptions

### ISSUE THREAD

**Issue by kpiskur** [PierfrancescoSoffritti/android-youtube-player#389]
It should be possible to setup custom ORIGIN because my app uses videos which are whitelisted only for it and without setting up my origin I can't play videos.

This would be really great if you fix that.

**Comment by PierfrancescoSoffritti** [comment]
Hey, what do you mean? from what I understand the origin parameter is useful only on the web, to tell the API from what  domain are the video being played. Am I wrong?

**Comment by kpiskur** [comment]
Actually, you are correct. I pulled your code and did some test, changing origin doesn't really change anything. 

But I found where is the problem. It's in the WebViewYouTubePlayer in the method loadDataWithBaseURL(...), the baseUrl should be changeable because with changing the baseUrl to my domain the video started to play.

**Comment by PierfrancescoSoffritti** [comment]
What do you mean with "your domain"? aren't the videos hosted on YouTube?

**Comment by kpiskur** [comment]
Yes, they are. But publishers can whitelist just specific apps (urls?) to use their youtube embed videos. So other apps wouldn't use them. And that's why _origin_ is used. The _**origin**_ parameter identifies the widget provider's domain (more explanation [here](https://developers.google.com/youtube/player_parameters)).

I don't really understand why setting _origin_ doesn't work in this library. But for sure does the work the _baseUrl_ in _loadDataWithBaseURL_ method.

**Comment by PierfrancescoSoffritti** [comment]
Ah I see. I'll do some tests with the YouTube console to better understand this whitelist concept. Thanks for reporting the issue :)

Also, feel free to send a pull request that fixes the problem!

**Comment by PierfrancescoSoffritti** [comment]
Hey, I'm looking at the YouTube console. I'm not able to find any option to white list apps or urls. Can you tell me where can I find it?

**Comment by kpiskur** [comment]
In practice I don't really know how to do it, because our customer did it. But I found this [support page](https://support.google.com/youtube/answer/6301625?hl=en) where is written how to do it.

**Comment by PierfrancescoSoffritti** [comment]
Ok, I'll follow the instructions in the link :+1:

**Comment by PierfrancescoSoffritti** [comment]
In a few hours i'll release a new version of the library where you will be able to set origins.
