### ISSUE TITLE
Audio is working, but no video

### ISSUE THREAD

**Issue by rjsuzuki** [PierfrancescoSoffritti/android-youtube-player#392]
Currently using android databinding and a fragment to initialize and load the youtubeplayerView. I can load the video with a key, but only the audio is playing. Black/grey-ish screen is present in full screen. Not sure if this is a configuration problem on my end or a compatibility issue. Please advise :)

TargetSdk 28
MinSdk 22
AndroidX 
and Leanback TV library

**Comment by PierfrancescoSoffritti** [comment]
Hi, are you testing it on an emulator?

**Comment by rjsuzuki** [comment]
yes, with api 25. Are there known problems with emulators?

**Comment by PierfrancescoSoffritti** [comment]
Yes, there are problems with graphics drivers. I suggest trying on a real device.

**Comment by rjsuzuki** [comment]
Ok, I can confirm it's working via a real TV - used ADB with a Fire TV stick. However, I tried to run the same app through several real phones but ran into the same issue as the original post. Is that normal?

**Comment by kusharora20** [comment]
I am having the same problem, hence following this conversation. Please do advise :)

**Comment by Amuri-Bonface** [comment]
Hello there, am using my phone is API level 27. Am having the same problem with video display. The player is launched successfully but its only the audio that's playing.

Am using a real device. 

 minSdkVersion 17
 targetSdkVersion 28

Any help will be highly appreciated.
