### ISSUE TITLE
Re initialize youtube player

### ISSUE THREAD

**Issue by malvinpatrick** [PierfrancescoSoffritti/android-youtube-player#394]
I have initialized youtube, let's say "ABCDE" url video. I want to reinitialize for "FGHIJ". How can I do this problem??
I have tried to release then initialize but didn't work

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to use `YouTubePlayer#loadVideo` or `YouTubePlayer#cueVideo`.

**Comment by malvinpatrick** [comment]
I had tried to reinitialize, but doesn't work. I'd like to load another
video URL, which one I should use ? Initialize or addYoutubePlayerListener?

**Comment by PierfrancescoSoffritti** [comment]
You don't need to reinitialize. As I've said above, you need to use `YouTubePlayer#loadVideo` or `YouTubePlayer#cueVideo`.

**Comment by SNNafi** [comment]
How can I do this ? If you don 't mind, can you please give me an example ?

**Comment by TarunPal3551** [comment]
is any way to check player view is initialized already or not because I want to add player view in recyclerview with having auto play according to userprefence

**Comment by nicolasmanurung** [comment]
> 

Do you have an example for this?

**Comment by nicolasmanurung** [comment]
> How can I do this ? If you don 't mind, can you please give me an example ?
> 
> **Thanks solved after going through sample**

@SNNafi do you have an example for this?

**Comment by ikhayat** [comment]
> > How can I do this ? If you don 't mind, can you please give me an example ?
> > **Thanks solved after going through sample**
> 
> @SNNafi do you have an example for this?

Same

**Comment by jeffmoreta** [comment]
@ik

> Cómo puedo hacer esto ? Si no te importa, ¿puedes darme un ejemplo?
> 
> **Gracias resuelto después de pasar por la muestra.**

Me too

**Comment by jeffmoreta** [comment]
> 

I need too
