### ISSUE TITLE
touch event question

### ISSUE THREAD

**Issue by JeffZane** [PierfrancescoSoffritti/android-youtube-player#395]
First of all, thank you very much for your contribution to this open source library, and now I have a problem.
I put the YouTubePlayerView on top of my RecyclerView. How to avoid RecyclerView's touchevent(ACTION_MOVE) not to be intercepted.
For example, finger slips past the RecyclerView, My expectation is that the RecyclerView can scroll normally.

I've tried to remove the click listener of panel view, but it's not working.

**Comment by PierfrancescoSoffritti** [comment]
mm I'm not sure what do you mean, but have you seen the [recycler view example](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/recyclerViewExample)?

**Comment by JeffZane** [comment]
Yes, I've already seen it.
Unlike the example, the list in my project has only one player.

**Comment by JeffZane** [comment]
When the finger starts to touch from the player, the list can not scroll.
I want the player to scroll with the list. My another player works right now.
