### ISSUE TITLE
Using fragment and the sample fullscreen code is giving me a blank screen 

### ISSUE THREAD

**Issue by Arogyathegreat** [PierfrancescoSoffritti/android-youtube-player#398]
Hey, I am having an issue with the fullscreen stuff. I have added the fullscreenlistener like below:
`
youTubePlayerView.addFullScreenListener(new YouTubePlayerFullScreenListener() {
            @Override
            public void onYouTubePlayerEnterFullScreen() {

                fullScreen.enterFullScreen();

            }

            @Override
            public void onYouTubePlayerExitFullScreen() {
                fullScreen.exitFullScreen();
            }
        });
`
I dont know if I doing something wrong while calling the fullscreen function. I am calling it like this,

`        final FullScreen fullScreen = new FullScreen(getActivity(), rootView);
`
where rootview is 
`final View rootView = inflater.inflate(R.layout.fragment_video_player, container,false);
        final YouTubePlayerView youTubePlayerView = rootView.findViewById(R.id.youtube_player_view);`

It works fine but when I click the fullscreen button, the audio is still playing but there is no video view. Since I am doing a single activity app with bottomnavigationview, there is a blank screen with the navigation on the bottom but no video. Hope you can help with this..

Edit: Unlike a previous issue, I am not using an emulator. Also tested this out in an activity instead of fragment, didnt work then either..

**Comment by PierfrancescoSoffritti** [comment]
Have you checked how it is done [in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample/CompleteExampleActivity.java)? This sounds more like an issue in your code than in the lib.

**Comment by Arogyathegreat** [comment]
Yeah the problem was with the code thank you!
