### ISSUE TITLE
After playing the youtube player in fullscreen for 20+ minutes it crashes

### ISSUE THREAD

**Issue by R01NDev** [PierfrancescoSoffritti/android-youtube-player#399]
So I am using 2 fragments for the YouTube player, one for the small view, the other for full screen, every time the full-screen button gets pressed I set all views to GONE and then I pass an array list of YouTube IDs I wanna play in sequence to the full screen fragment which uses a player with dimensions that match the whole screen. I am also listening to "ENDED" state and I am passing the player a new ID every time it is reaching that state. After around 20+ minutes, sometimes takes around an hour to happen, the app crashes with the following log. Note that I have an exo player as well for HLS streams that uses the same methods im calling in the youtube player to fetch data on ENDED and it plays for 6 hours without a hiccup. I am posting here because I am not sure what is causing this problem and it's very confusing. Apologies in advance if I am missing something and this is not an issue with the player and as always thanks for your help and your great work!

Here is a pastebin with the crash (too huge to post here)  https://pastebin.com/M2CMXe2V

**Comment by PierfrancescoSoffritti** [comment]
This log is not very helpful (and a bit too much :)), I don't think the issue is with the player, but it's hard to tell for sure.

**Comment by R01NDev** [comment]
What log do I need to send so we can figure this out.

**Comment by acrolink** [comment]
I am facing the same issue with Android 8.0 based Smart TV.
