### ISSUE TITLE
Some Video not working

### ISSUE THREAD

**Issue by bhavikgandhi007** [PierfrancescoSoffritti/Android-YouTube-Player#4]
hello, 
i interegrate library and there is some issue 
some time player not load video,
and some channel video not loading like : "hEZ4UMr37yg" this youtube video not loading

**Comment by PierfrancescoSoffritti** [comment]
Hi, some videos are not available world-wide. For example the video you provided (https://www.youtube.com/watch?v=hEZ4UMr37yg) is not available in my country. Therefore the player can't play it. 
As soon as I'll have some time I'll write code to handle these cases gracefully.

**Comment by bhavikgandhi007** [comment]
where to change any idea?

**Comment by PierfrancescoSoffritti** [comment]
take a look at this comment http://stackoverflow.com/questions/32614246/youtube-iframe-api-play-state-for-unavailable-in-region-videos#comment53103832_32614246

Try checking the error code and then skip the video.

**Comment by rahul260792** [comment]
I had same problem. Make sure you have checked the box **Allow Embed** checkbox in youtube  video settings in case you are the owner of the videos.  If the checkbox is not checked the video won't work.
