### ISSUE TITLE
how to use getLifecycle().addObserver(youTubePlayerView) in adapter for RecyclerView

### ISSUE THREAD

**Issue by mirajas** [PierfrancescoSoffritti/android-youtube-player#400]
This might be a stupid question but I can't find a way to use getLifecycle().addObserver(youTubePlayerView) in adapter for RecyclerView.

**Comment by PierfrancescoSoffritti** [comment]
`RecyclerView` doesn't have a lifecycle. You need to get the lifecycle from your Activity/Fragment.

**Comment by Hamza-Ali333** [comment]
can you tell me how to get lifecycle form activity or fragment inside recyclerView Adapter.?

**Comment by Hamza-Ali333** [comment]
actully what i wanna do is video should not play automatically i added autoplay="false" in XML but it's not work in the adapter yes it's work in activity. Please tell me the solution if you. i m new in android

**Comment by UzBestDeveloper** [comment]
> play

https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/recyclerViewExample/RecyclerViewAdapter.java
