### ISSUE TITLE
android youtube player life cycle

### ISSUE THREAD

**Issue by princehum101** [PierfrancescoSoffritti/android-youtube-player#401]
how do you add youtubeplayer as a lifecycle in the activity/fragment i have tried adding but am getting an error of a NullPointexception.
 private Lifecycle getLifecycle() {
        return null;
    }

**Comment by PierfrancescoSoffritti** [comment]
You need to add it as lifecycle observer, please [read the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#quick-start).
