### ISSUE TITLE
YouTubePlayer seekTo does not work properly when it is paused  

### ISSUE THREAD

**Issue by JackLauu** [PierfrancescoSoffritti/android-youtube-player#402]
We are realizing the forward and rewind function to YouTubePlayerView. We use youtubeplayer seekto function to do this, when the player is playing, all is ok. But when it is paused, seekto will not work. I don't know what the problem is. Can you give some suggestion?

**Comment by PierfrancescoSoffritti** [comment]
What do you mean "it doesn't work"? what happens? it seems to be working for me.

**Comment by JackLauu** [comment]
Sorry, I didn't describe clearly. When the player is paused, and when I
called seek to, and then play, it seems OK. But when I call seekto multiple
times, also the player is paused. And when I let the player play again, the
player will go to the first seekto position but not the last result. So the
forward and rewind button are not working regularly.

Pierfrancesco Soffritti <notifications@github.com> 于 2019年7月29日星期一 22:47写道：
