### ISSUE TITLE
After notifyDataSetChanged() on adapter removes existing videos from view.

### ISSUE THREAD

**Issue by mirajas** [PierfrancescoSoffritti/android-youtube-player#403]
I am trying to load array list into adapter page wise. When I call notifyDataSetChanged() after adding new set of data into adapter, previous videos items are not working properly. Some items which contain video continuously loads while some items exchanges their videos.

**Comment by PierfrancescoSoffritti** [comment]
Most likely (from what i can infer from your description) the issue is in your code.

**Comment by mirajas** [comment]
The array list contain images also. The image items with imageviews stays as expected but it only affects video items and thats only after applying notifyDataSetChanged(). When I hard code the video ids into YouTubePlayerView it works fine.

**Comment by mirajas** [comment]
I am trying for workarounds but **many time** 

> **public void onReady(YouTubePlayer youTubePlayer)**

 does not fire. I highlited **many time** because on many occasion it fires.
Anyway to trace why not firing? I tried with android studio debug mode and it goes inside 

> **addYouTubePlayerListener(new AbstractYouTubePlayerListener()**
but never goes inside 
> **public void onReady(YouTubePlayer youTubePlayer)**
