### ISSUE TITLE
how to intialize video after getting url from webservice....app crashes.. only works when the youtube video is loaded during create event

### ISSUE THREAD

**Issue by skdhruv** [PierfrancescoSoffritti/android-youtube-player#406]

**Comment by PierfrancescoSoffritti** [comment]
I am not sure what do you mean, please read the documentation and follow the examples.

**Comment by skdhruv** [comment]
Good day

1 Actually issue I am facing is that the   library is working ok if use it
during oncreate of activity

2. Now when the activity is loaded and then there is process of volley to
get link from webservice.  Now when get success in volley and get the I'd
of YouTube and when we try.to use.the library to view video it crashed
