### ISSUE TITLE
Rejected from Google Play for library use

### ISSUE THREAD

**Issue by rajtechi** [PierfrancescoSoffritti/android-youtube-player#408]
In 2018 , when i have used this library my app got rejected and after explaing about the app they approved .

In 2019, I haven't changed anything in apk file . Just updated icon in store listing and my app got rejected saying.. 

Issue: Violation of Device and Network Abuse policy

Every time when i'm updating and submitting for approval , i'm facing challenges about the youtube policy violations. Please let me know how to handle this..

**Comment by hannojg** [comment]
Show the icon if you like. Most likely it is too similar to a different service or something. That’s also a reason for google to remove apps.

**Comment by PierfrancescoSoffritti** [comment]
"Violation of Device and Network Abuse policy" - how is this related to the YouTube player?

**Comment by rajtechi** [comment]
Please check the App Icon in Playstore - https://play.google.com/store/apps/details?id=com.rs.wstatus

**Comment by rajtechi** [comment]
> Show the icon if you like. Most likely it is too similar to a different service or something. That’s also a reason for google to remove apps.
> […](#)
> Am 09.08.2019 um 08:05 schrieb Rajesh Lakkakula ***@***.***>: In 2018 , when i have used this library my app got rejected and after explaing about the app they approved . In 2019, I haven't changed anything in apk file . Just updated icon in store listing and my app got rejected saying.. Issue: Violation of Device and Network Abuse policy Every time when i'm updating and submitting for approval , i'm facing challenges about the youtube policy violations. Please let me know how to handle this.. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

Please check the app icon in playstore - https://play.google.com/store/apps/details?id=com.rs.wstatus

**Comment by rajtechi** [comment]
> this doesn't seem related to the YouTube player.

But they are saying its an issue with youtube player policy issues

**Comment by PierfrancescoSoffritti** [comment]
Can you please share the full message then?

**Comment by rajtechi** [comment]
> Can you please share the full message then?
**Mail From Google -**
Thanks again for contacting Google Play Developer Support. 
As much as I'd like to help, I’m not able to provide any more information or a better answer to your question. In our previous email, I made sure to include all the information available to me.

You should be able to find more information about your issue here:
Device and Network Abuse policy

**Background play is the ability to play Youtube videos when an app is either not active or while the device is locked.** 

If you have a different question about the Play Developer Console, please let me know.

I'm not allowing to play the videos background to play and its default handled by the library.

**Comment by PierfrancescoSoffritti** [comment]
mmh it looks like the issue is with background playback. Can you send me your apk?

**Comment by rajtechi** [comment]
> mmh it looks like the issue is with background playback. Can you send me your apk?

**Apk Link :**
https://play.google.com/store/apps/details?id=com.rs.wstatus

**Comment by PierfrancescoSoffritti** [comment]
Ok, i'll check it out.
Btw, the app is available on the PlayStore, what's the issue then?

**Comment by rajtechi** [comment]
> Ok, i'll check it out.
> Btw, the app is available on the PlayStore, what's the issue then?

Thanks a lot . please check and let me know asap...
Yes its available in playstore
My Update is rejected . Until this issue is resolved i can't go for further updates

**Comment by PierfrancescoSoffritti** [comment]
Well then I should see the rejected apk, not the one on the PlayStore. 

But if the app is on the PlayStore you must be doing something wrong in the new version.

**Comment by rajtechi** [comment]
> Well then I should see the rejected apk, not the one on the PlayStore.
> 
> But if the app is on the PlayStore you must be doing something wrong in the new version.

There is not change in rejected and available in play store app both are same. I haven't changed anything in code . i updated my playstore icon which got rejected saying this is the reason...

**Comment by PierfrancescoSoffritti** [comment]
Ah  right, I forgot that part.

**Comment by rajtechi** [comment]
> Ah right, I forgot that part.

yeah

**Comment by PierfrancescoSoffritti** [comment]
When scrolling the list the video keeps playing even while being partially outside of the screen. That's probably why they are complaining.

**Comment by rajtechi** [comment]
> When scrolling the list the video keeps playing even while being partially outside of the screen. That's probably why they are complaining.

How to handle this?

**Comment by PierfrancescoSoffritti** [comment]
Well you need to figure out when the View in the list is partially covered and call pause. It's up to you how you do it.

**Comment by rajtechi** [comment]
> Well you need to figure out when the View in the list is partially covered and call pause. It's up to you how you do it.

ok Thanks..
