### ISSUE TITLE
How to set matchparent? after exitFullScreen();

### ISSUE THREAD

**Issue by eggham0518** [PierfrancescoSoffritti/android-youtube-player#409]
Thank you for creating a wonderful library. I'm Korean. I am not good at writing English, so please understand.

After called exitFullScreen();

It is automatically reduced in size.

It is uncomfortable to watch a video in a vertical direction.
e.g) https://www.youtube.com/watch?v=h-4hpyOkFtg

What I've tried

     `  public void addFullScreenListenerToPlayer(final YouTubePlayerView youTubePlayerView) {
        youTubePlayerView.addFullScreenListener(new YouTubePlayerFullScreenListener() {
            @Override
            public void onYouTubePlayerEnterFullScreen() {
               activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
    

            }

            @Override
            public void onYouTubePlayerExitFullScreen() {
                activity.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
          
                youTubePlayerView.removeFullScreenListener(this);
                youTubePlayerView.enterFullScreen();  / can't go back.
                 //youTubePlayerView.setLayoutParams(layoutParams); 

            }
        });
    }`

**Comment by PierfrancescoSoffritti** [comment]
Hey, have you checked the sample app?
