### ISSUE TITLE
Issue if video is stream

### ISSUE THREAD

**Issue by mdtuyen** [PierfrancescoSoffritti/Android-YouTube-Player#41]
When the video is stream type, time for it is wrong. 

How to hiden the time and show that it is live.

**Comment by PierfrancescoSoffritti** [comment]
Hi, thank you for reporting the issue, I'm currently rewriting/improving the library, I will test this use case. I will let you know.

**Comment by PierfrancescoSoffritti** [comment]
I've just solved the issue, from the next version of the player will be possible to manually change the UI for live videos.

**Comment by PierfrancescoSoffritti** [comment]
Version 1.0.0 is out, read [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/PlayerUIController#live-videos) to know how to enable live indicator.
