### ISSUE TITLE
How do I use the android library in a nativescript project?

### ISSUE THREAD

**Issue by johnny-stevie** [PierfrancescoSoffritti/android-youtube-player#412]
I have looked at nativescript-angular docs to find a way to implement a native android library and use in my js code but it's very confusing because different articles list different things to do.
for example, when i try :

implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:chromecast-sender:0.21'

in my build.gradle, i get the error:

Could not find method implementation() for arguments 
[com.pierfrancescosoffritti.androidyoutubeplayer:chromecast-sender:0.21] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Any ideas of how to implement?
Thanks,
Any help is appreciated.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I have no knowledge about nativescript-angular, can't help you with that.

**Comment by johnny-stevie** [comment]
Understood. I will ask around in the nativescript forums. I will see if i can use this library in the future. Thank you anyway and great job on circumventing the Youtube API!

**Comment by PierfrancescoSoffritti** [comment]
Let us know if you make progress.
