### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by vijayakumarksv** [PierfrancescoSoffritti/android-youtube-player#413]
This is not work for me, i mean in my project gradle is not sync 
  implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.3'

**Comment by PierfrancescoSoffritti** [comment]
There must be an issue with your build.gradle files or some other configuration.

**Comment by vijayakumarksv** [comment]
i got this issue 
![Uploading image.png…]()

**Comment by PierfrancescoSoffritti** [comment]
No very useful.
