### ISSUE TITLE
New Issue 

### ISSUE THREAD

**Issue by vijayakumarksv** [PierfrancescoSoffritti/android-youtube-player#414]
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
  android:id="@+id/youtube_player_view"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"

  app:useWebUi="true" />

this is not too my project, how to resolve this issue 

![image](https://user-images.githubusercontent.com/50190122/63099870-85f47900-bf93-11e9-9387-39ad04e84317.png)

I need above flow. so please help me to fix this issue

**Comment by PierfrancescoSoffritti** [comment]
I don't understand what you're asking.

**Comment by vijayakumarksv** [comment]
> I don't understand what you're asking.

even i can't able to mute the video when i am open the app and play mute mode not for unmute at the time when user click the volume buttom then only mute will change to unmute mode. how to do this tutorial?

**Comment by PierfrancescoSoffritti** [comment]
Sorry, I don't understand.

**Comment by vijayakumarksv** [comment]
Default i need to play video as mute mode. don't want sound

**Comment by PierfrancescoSoffritti** [comment]
`youtubePlayer.setVolume(0)`.
