### ISSUE TITLE
Not able to stop the Video

### ISSUE THREAD

**Issue by vijayakumarksv** [PierfrancescoSoffritti/android-youtube-player#415]
Hi, When i scrolling the listview position not able to pause or stop the video. how to resolve this issue.
for example, now i have to play the one video and move to next video means, previous video not able to pause it. how to fix this issue?

**Comment by PuruPanda1** [comment]
Why this issue is closed? I still not working. How to pause or stop the video in viewpager or recyclerview.

To Recreate the issue:

  1. Call the video listener in the adapter
  2. fastly swipe 2 or 3 videos and now 3 videos will play together

**Comment by PierfrancescoSoffritti** [comment]
I suggest pasting a code snippet/trying to recreate the issue in the sample app.
