### ISSUE TITLE
Init listener not working

### ISSUE THREAD

**Issue by tanweilong** [PierfrancescoSoffritti/android-youtube-player#416]
Hi there, I had tested and used YoutubePlayerView before and the player was working fine. Out of sudden, the player is not working. I found out that the onReady listener is never fire. Can you check this problem for me?

**Comment by tanweilong** [comment]
It's works back on already just a few moments ago without even change my code for the player. Can you double confirm for the problem I just occurred? Or is it something wrong during the init process?

**Comment by PierfrancescoSoffritti** [comment]
It works for me. I suggest taking a look at the sample app.

**Comment by tanweilong** [comment]
I keep on testing on it..I found that sometimes the player able to init successfully but sometimes no..I can only share partially of the app as this project is still under dev..

**Comment by tanweilong** [comment]
Sorry for the late reply. I found the main cause for this problem. When I try to setSelected = true for other views before init the player, the player will not able to init. I am not sure this is a bug or not. I just highlighted here for your information. Thanks!
