### ISSUE TITLE
youtube core playerview 

### ISSUE THREAD

**Issue by vijayakumarksv** [PierfrancescoSoffritti/android-youtube-player#417]
Hi,
    implementation "com.psoffritti.librarysampleapptemplate:core:$versions.sampleAppTemplate"
this library is not working for me. plz help me for this.

**Comment by PierfrancescoSoffritti** [comment]
What do you mean? Why do you need it?

**Comment by vijayakumarksv** [comment]
Because, i want to implement the volume icon. show that ask with you. i did't use the web Ui 
ex: 
       youTubePlayerView.initializeWithWebUi();

**Comment by PierfrancescoSoffritti** [comment]
You need to use androidx, yes. librarysampleapptemplate:core has nothing to do with the YouTube player.
