### ISSUE TITLE
Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView

### ISSUE THREAD

**Issue by Hasan-Mahmud** [PierfrancescoSoffritti/android-youtube-player#419]
I got Error:
android.view.InflateException: Binary XML file line #24: Error inflating class com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
![p](https://user-images.githubusercontent.com/40826552/63406423-a6955680-c40b-11e9-8e0f-2c013c93a516.JPG)

I use 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.3'

**Comment by Yagnesh123456** [comment]
i got same error when xml file without videoId

**Comment by PierfrancescoSoffritti** [comment]
[It doesn't make sense to set autoplay to true without providing a video id](https://github.com/PierfrancescoSoffritti/android-youtube-player#autoplay).

**Comment by Hasan-Mahmud** [comment]
> 
> 
> i got same error when xml file without videoId .if you want solve this error then set autoplay false or set video id in xml file

Thanks for your solution. It works now.

**Comment by SergioFuchs** [comment]
I´m having the same problem with API 21, on API 27, 28 the problem doesn´t happen. Only on old ones ... 

 <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
                android:id="@+id/youtube_player_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:videoId="I08i3ztnJdE"
                app:autoPlay="false"
                app:showFullScreenButton="true" />

**Comment by PierfrancescoSoffritti** [comment]
I doubt this is related to API level. Are you sure this is the issue you're having?

**Comment by SergioFuchs** [comment]
> I doubt this is related to API level. Are you sure this is the issue you're having?

I´ts a very simple page and it´s working on API 27, 28 simulator and real devices.
But if open this Activity on API 21 I got the error above. 
If I remove the YouTubePlayerView from the Activity it opens with no erros.
I´m already using Androidx library
Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hey, I'm currently traveling and don't have my personal laptop with me. I can try fixing #430 today but won't have time for #491 (at least for the next week). Feel free to send pull requests.

**Comment by SJOwl** [comment]
```
internal class WebViewYouTubePlayer constructor(
    context: Context,
    attrs: AttributeSet? = null,
    defStyleAttr: Int = 0
) : WebView(context.applicationContext, attrs, defStyleAttr),
    YouTubePlayer,
    YouTubePlayerBridge.YouTubePlayerBridgeCallbacks {
```

**Comment by PierfrancescoSoffritti** [comment]
So this seems to be an issue with androidx.appcompat version 1.1.0. I think the best solution is to wait for the Android team to fix it.

In the meantime [this is a temporary solution](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/461#issuecomment-550050683).

**Comment by jonherbla** [comment]
I tried [this solution](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/461#issuecomment-550050683) and not work for me, but when I add the following code in the activity where I inflate YouTubePlayerView it's worked:

`override fun applyOverrideConfiguration(overrideConfiguration: Configuration) {
        if (Build.VERSION.SDK_INT in 21..22) {
            return
        }
        super.applyOverrideConfiguration(overrideConfiguration)
}`

I found the solution here: https://stackoverflow.com/a/58695635/7212836, thanks to @SJOwl

**Comment by Nadeembhat** [comment]
i am using this lib on my android api level 28 but it seems not working , did it mean that it doesnt have backward compatibility i am getting an error like:
       android.view.InflateException: Binary XML file line #7: Error inflating class 
        com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView

and i am using it in fragment where youtubePLayerView.addYoutubeListner is not importing

**Comment by gustavobnmx** [comment]
> [It doesn't make sense to set autoplay to true without providing a video id](https://github.com/PierfrancescoSoffritti/android-youtube-player#autoplay).

It does make sense if you're just getting started and refactoring from old Youtube lib code. It would be smarted to check for this within the lib, since most use cases will use dynamic Youtube Video Ids

**Comment by PierfrancescoSoffritti** [comment]
I agree, the current way of handling incorrect xml attributes is not great.

**Comment by mirzauzairshahid** [comment]
Some isue is android:autoplay="true" inflate xml give error and change this line to android:autplay="false"

**Comment by PierfrancescoSoffritti** [comment]
It's not an error. It is supposed not to work.
