### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by vijayakumarksv** [PierfrancescoSoffritti/android-youtube-player#420]
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
                        android:id="@+id/youtube_view"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        app:useWebUi="true" />

I need to set as default mute mode and then when user click the volume speaker icon should be unmute ? how to resolve this issue.

**Comment by PierfrancescoSoffritti** [comment]
You can [set the volume programmatically](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/YouTubePlayer.kt#L29).
