### ISSUE TITLE
Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by charan15923** [PierfrancescoSoffritti/android-youtube-player#421]
Is there any workaround for these kind of youtube videos where playback has been disabled by user?

**Comment by PierfrancescoSoffritti** [comment]
I would assume not.

**Comment by JmyW** [comment]
I found some apps as following that can play those videos. How do they make it work?

[These apps can play]
* Play Tube (https://play.google.com/store/apps/details?id=com.mta.videotube.playtube)
* Float Tube (https://play.google.com/store/apps/details?id=com.xpp.tubeAssistant)
* Play Tube Block Ads for Video (https://play.google.com/store/apps/details?id=com.free.playtube.videotube.musictube)

[These Videos are disabled playback on other websites]
* https://www.youtube.com/watch?v=_mZeJ9-uVQs
* https://www.youtube.com/watch?v=mk6hfhs8Vwo
