### ISSUE TITLE
youtube player bug

### ISSUE THREAD

**Issue by yangshulin2019** [PierfrancescoSoffritti/android-youtube-player#422]
I found that youtuber player will stuck when I call youtubeplayer.pause before it begin to play. The play state should be : unstarted -- buffering -- unstarted.
This bug will easily to happen when I enter to another Activity by share intent or other method before youtube player begin to play.
I fix it by adding a condition of duration > 0 before pausing, I don't know is it a good method and what is the cause.

**Comment by PierfrancescoSoffritti** [comment]
Hey, thanks for reporting the issue! I'll take a look when I'll have some free time.

**Comment by PierfrancescoSoffritti** [comment]
I have not been able to reproduce the issue. If I pause the player before it starts playing everything works as expected.

**Comment by yangshulin2019** [comment]
You can easily reproduce the bug in a youtube listener, when the play state is BUFFERING, just call youtubeplayer.pause. It is seems a bug for youtube iframe.

**Comment by PierfrancescoSoffritti** [comment]
Ok, I'll try again over the weekend.

**Comment by mandeepsangwan21** [comment]
i'm also facing same issue and video won't play again.

**Comment by codefury** [comment]
Hi @PierfrancescoSoffritti, you just closed this? Any update on how to fix this?

**Comment by Pushpendracolourmoon** [comment]
I am also facing the same issue. Is there any solution for this?
