### ISSUE TITLE
youtubePlayer pause when app close

### ISSUE THREAD

**Issue by sunndayy** [PierfrancescoSoffritti/android-youtube-player#426]
I use your library to implement a music app. I use foreground service to hold youtubePlayer and allow activity bind it to get player. I have issue that when activity bind to service and when I close app, youtubePlayer pause automatically. Can you help me for this issue?

**Comment by PierfrancescoSoffritti** [comment]
Hi, you can find the info you need [in the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#play-youtube-videos-in-the-background).
