### ISSUE TITLE
App Crashes with latest androidx.appcompat:appcompat:1.1.0

### ISSUE THREAD

**Issue by adwiv** [PierfrancescoSoffritti/android-youtube-player#430]
When upgrading to the recently released appcompat 1.1.0, app started crashing with the following error.
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{.......}:
android.view.InflateException: Binary XML file line #10: Error inflating class 
com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
...
...
...
Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x2040003
```

I can confirm that the `core-sample-app` also crashes when the appcompat version is updated in dependencies.gradle and recompiled.

This is the same issue as the comment posted by @gajicm93 in https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/419#issuecomment-530714754_, however, the conclusion seems to be wrong. This isn't an old bug, but something new.

**The resolution for now is to keep using appcompat 1.0.2 till this is fixed in the player library.**

**Comment by gajicm93** [comment]
+1 thanks for the info! Looking forward to the fix.

**Comment by PierfrancescoSoffritti** [comment]
Hey, thanks for reporting the issue. I'll try to fix it today.

**Comment by PierfrancescoSoffritti** [comment]
I've tried but failed. I'm traveling and don't have my main SIM card with me, meaning: two factor authentication locks me out of my accounts. I'll do everything next week when I'll be back home.

**Comment by muhammednasimda** [comment]
just add `app:videoId="S0Q4gqBUs7c"` to the layout. It solved For Me.

**Comment by PierfrancescoSoffritti** [comment]
I have just tried running the sample app using appcompat version 1.1.0, everything works fine.

**Comment by PierfrancescoSoffritti** [comment]
Are you sure you're using the player correctly? if autoplay is set to true you need to provide a videoid.

**Comment by adwiv** [comment]
With 1.1.0, Crashes for me on API 22 emulator, works fine on API 28 emulator.

**Comment by PierfrancescoSoffritti** [comment]
Ok, it does crash on api 22. I'll release the new version in a few hours.

**Comment by PierfrancescoSoffritti** [comment]
It looks like it's a bug with appcompat itself: [issues/141132133](https://issuetracker.google.com/issues/141132133). I think we'll have to wait for Google to fix it.

**Comment by brookmg** [comment]
Is this bug solved in 10.0.4?

**Comment by PierfrancescoSoffritti** [comment]
The bug is not in android-youtube-player but in appcompat 1.1.0.

**Comment by brookmg** [comment]
I get that, am asking if the version of appcompat is downgraded in 10.0.4
to 1.0.2

**Comment by PierfrancescoSoffritti** [comment]
No, the library is fine. You have a problem if you use 1.1.0 yourself.

**Comment by brookmg** [comment]
Got it. Thanks

Thank you,
Brook Mezgebu

**Comment by frett** [comment]
it looks like `appcompat:1.2.0-alpha02` fixes the WebView related crash
