### ISSUE TITLE
Question about background play

### ISSUE THREAD

**Issue by yangshulin2019** [PierfrancescoSoffritti/android-youtube-player#431]
Hello, thanks for your nice project.
I want to know something about background play. When a Activity finished, the youtube player is still playing, it is background play. But when I put youtube player view in a scrollview or recyclerview and scroll youtube player view out of the screen when it is still playing, is it a background play? When I use google native YouTubePlayerView, when YouTubePlayerView is out of screen or overlay by other view, it will stop.

**Comment by PierfrancescoSoffritti** [comment]
Playing in the background means that the Activity/Fragment is in the background.
