### ISSUE TITLE
If YouTube advertisement is blocked 

### ISSUE THREAD

**Issue by yangshulin2019** [PierfrancescoSoffritti/android-youtube-player#435]
Hello, I found that I can't see the YouTube advertisement by using android-youtube-player to play some videos contain ads. I can see it on iOS youtube player. So I want to check it out why. I am afraid it is violate the terms of YouTube.

**Comment by PierfrancescoSoffritti** [comment]
Hey, android-youtube-player is just a wrapper over the YouTube IFrame API.
Therefore there's no issue with terms of service.

**Comment by yangshulin2019** [comment]
You mean you did nothing about YouTube advertisement.

**Comment by yangshulin2019** [comment]
By the way, as YouTube terms of use said, "If you use the Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the YouTube website." Our youtube player blocks the web buttons by panel view and add some native UIs, does it mean block and build upon?

**Comment by PierfrancescoSoffritti** [comment]
> You mean you did nothing about YouTube advertisement?

correct.

> By the way, as YouTube terms of use said, "If you use the Embeddable Player on your website, you may not modify, build upon, or block any portion or functionality of the Embeddable Player, including but not limited to links back to the YouTube website." Our youtube player blocks the web buttons by panel view and add some native UIs, does it mean block and build upon?

You can use webui in android-youtube-player if you want to be 200% safe.
