### ISSUE TITLE
Playing sound but not the video ??

### ISSUE THREAD

**Issue by anandprimus** [PierfrancescoSoffritti/android-youtube-player#436]
I am using player webview when I am doing so sound of the video is coming but no visuals.

Please help.

**Comment by PierfrancescoSoffritti** [comment]
Hi, are you using an emulator?

**Comment by anandprimus** [comment]
no testing in the device ??

**Comment by anandprimus** [comment]
what could be the possible issue??

**Comment by PierfrancescoSoffritti** [comment]
Not sure, maybe you have an old/weird device?

**Comment by RofieSagaraAMK** [comment]
i have problem like that too.
i tested with android 8 (Redmi 5A), android 9 (Redmi 4 Prime Custom Room), android 9 (Asus Zenfrome Max M1) they got blank screen sometime white but the voice is play

**Comment by IlaxoRiyazat** [comment]
Playing sound but not the video ??

**Comment by shivamgupta** [comment]
I am getting blue screen instead of the video, audio is fine though.
Happens with 90% of the YouTube videos.
How can I fix this?

**Comment by jerbotron** [comment]
Also experiencing this issue on both emulator and real device.

Using lib version 10.0.5. Did anyone happen to find any solutions?

**Comment by kinsog** [comment]
the same issue here too,  it worked at first even when I try my older apk, but later; it might be a problem of compatibility with other dependencies.

**Comment by StefanVanStaden** [comment]
@PierfrancescoSoffritti Like how you close this issue with no solution. Also experiencing same issue on all devices (5K + devices). If anyone finds a workaround please contact me.

**Comment by Alpesh-Android** [comment]
I also fetch this in project. previously this was working fine but now not working only video sound is playing but not video is streaming. i am waiting for your response

**Comment by amirdora** [comment]
I have the same issue. Setting `hardwareAcceleration` set to `true` seems to solve it but slows down the app experience.

**Comment by JagadishaIncture** [comment]
android:hardwareAccelerated="true" in manifest worked
