### ISSUE TITLE
Time format in YouTubePlayerSeekBar is not regular when time exceed 1 hour

### ISSUE THREAD

**Issue by yangshulin2019** [PierfrancescoSoffritti/android-youtube-player#438]
Hello, I find that the time format display in YouTubePlayerSeekBar is not regular when the duration exceed 1 hour. For example, 1 hour and 30 minutes should display as 1:30:00, but YouTubePlayerSeekBar will display as 90:00.
And I have a implement used in my project, 
```
public static String secondsToHms(int totalSecs) {
    int minutes = (totalSecs % 3600) / 60;
    int seconds = totalSecs % 60;

    if (totalSecs >= 3600) {
        int hours = totalSecs / 3600;
        return String.format("%02d:%02d:%02d", hours, minutes, seconds);
    } else {
        return String.format("%02d:%02d", minutes, seconds);
    }
}
```

**Comment by PierfrancescoSoffritti** [comment]
Thanks for the suggestion, we could pass an optional string formatter to YouTubePlayerView to do that.
