### ISSUE TITLE
Media continue play after close application

### ISSUE THREAD

**Issue by mdtuyen** [PierfrancescoSoffritti/Android-YouTube-Player#44]
In my code:
        if (youtubePlayer.isPlaying()) {
            youtubePlayer.pause();
        }
when fragment onPause and release after onDestroyView. but media contine play, even when the application is turned off.

**Comment by PierfrancescoSoffritti** [comment]
Hi, try to remove the if statement.

```
onPause() {
   youtubePlayer.pause();
}
```

**Comment by PierfrancescoSoffritti** [comment]
any progress?

**Comment by mdtuyen** [comment]
Hi @PierfrancescoSoffritti 
Thanks for your support.
I'm testing.
Sometime I see that function pause in YoutubePlayer class have crash nullpointerexception:

```
 protected void pause() {
        mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                    loadUrl("javascript:pauseVideo()");
            }
        });
    }
```
webview have been destroy before loadUrl call.

**Comment by PierfrancescoSoffritti** [comment]
Are you calling `release` on your YouTubePlayerView before destroying the Activity?

```
@Override
    public void onDestroy() {
        super.onDestroy();

        youTubePlayerView.release();
    }
```

**Comment by mdtuyen** [comment]
I called youTubePlayerView.release() on onDestroyView of fragment.
