### ISSUE TITLE
WebUI lack fullscreen feature

### ISSUE THREAD

**Issue by yangshulin2019** [PierfrancescoSoffritti/android-youtube-player#440]
Hello, I find that when the player is in WebUI mode,  the fullscreen button is not seen, does iframe in Android not support fullscreen?

**Comment by PierfrancescoSoffritti** [comment]
Correct. You can do it programmatically, add a button outside of the player or add a button inside the player by using custom UI.

**Comment by yangshulin2019** [comment]
I found this app: https://play.google.com/store/apps/details?id=freetube.com embedded fullscreen button in iframe.

**Comment by PierfrancescoSoffritti** [comment]
This app is just opening the YouTube website.
