### ISSUE TITLE
move Interfaces to Java

### ISSUE THREAD

**Issue by tieskedh** [PierfrancescoSoffritti/android-youtube-player#448]
Kotlin has [SAM-conversion for Java-interfaces](https://kotlinlang.org/docs/reference/java-interop.html#sam-conversions):

```kotlin
getYouTubePlayerWhenReady(object : YouTubePlayerCallback {
    override fun onYouTubePlayer(youTubePlayer: YouTubePlayer) {
       youTubePlayer.doSomething()
    }
})
//will become
getYoutubePlayerWhenReady(YoutubePlayerCallBack{
    it.doSomething()
})
``` 

Therefor my request: can you move the functional interfaces to Java?

**Comment by PierfrancescoSoffritti** [comment]
Hi, that's how Kotlin works, I think we'll have to deal with it :)

**Comment by tieskedh** [comment]
We don't, but you decided to 😛
But I agree, as otherwise you get an inconsistent API...
And by adding extension-functions, I can make it even more idiomatic.
Thanks for your time!

**Comment by PierfrancescoSoffritti** [comment]
thanks to you for the suggestion :)
