### ISSUE TITLE
Can't init to play when update 

### ISSUE THREAD

**Issue by mdtuyen** [PierfrancescoSoffritti/Android-YouTube-Player#45]
Some my device can't play  video because onYouTubeIframeAPIReady() not call so that Youtube player view not init success.

Log:
`SelfBrailleClient: Failed to bind to service`

**Comment by PierfrancescoSoffritti** [comment]
Which devices? and which version of Android/WebView?

**Comment by mdtuyen** [comment]
Hi @PierfrancescoSoffritti , I use HTC Desire 620G dual sim, Android 4.4.2
Before I use version of this library with file html player.html in raw folder, this error no occurs

**Comment by PierfrancescoSoffritti** [comment]
I'm also having problems on KitKat, I will investigate. 
I'm pretty sure it's related to the fact that [WebView ](https://play.google.com/store/apps/details?id=com.google.android.webview&hl=en) is updated through the store only for Lollipop+.

**Comment by mdtuyen** [comment]
I'm not sure because the previous version work fine. 
I need resolve this issue to release app today.
Please help me.

**Comment by PierfrancescoSoffritti** [comment]
Today? 😄 you can use the old version if you are in a hurry.
Can you please let me know which version is working?

**Comment by mdtuyen** [comment]
Yes, I revert to old version. I user new code on your lib not gradle lib with control file is player.html not youtube_player.html.

**Comment by PierfrancescoSoffritti** [comment]
Can you please let me know which version is working?

**Comment by mdtuyen** [comment]
Hi, I check with device and see that the library working file with code submit before 10/3/2017

**Comment by PierfrancescoSoffritti** [comment]
solved, see #59
