### ISSUE TITLE
Play video when it's already loaded

### ISSUE THREAD

**Issue by cuong292** [PierfrancescoSoffritti/android-youtube-player#453]
First of all,thanks for your hard work to create this video.I have a problem ( not really is,but it make the view not friendly),if i rotate the screen -> recreate activity -> the videoview is re-create and also reload the video from begin even when i loaded all (or part of the video).So is there any way to caching or continue load the last part without reload everything?

**Comment by PierfrancescoSoffritti** [comment]
Yes, you need to [handle orientation changes](https://stackoverflow.com/questions/15632360/android-manual-screen-orientation-without-restarting-the-activity).
