### ISSUE TITLE
YouTubePlayerUtils VideoIdsProvider are not recognized  

### ISSUE THREAD

**Issue by Antroid** [PierfrancescoSoffritti/android-youtube-player#454]
Hey guys, 

I'm trying to use this library using Kotlin, unfortunately I was trying to create a custom layout for the media controllers it not recognize YouTubePlayerUtils & VideoIdsProvider classes.

I'm using the latest version 10.0.5. I tried several dependencies from what I found in the sample application without any luck.

` implementation "android.arch.lifecycle:extensions:1.1.1"
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5'
    implementation "com.psoffritti.librarysampleapptemplate:core:1.0.2"
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:chromecast-sender:0.23'`

I also tried to put packagingOptions in the main build.gradle without success.

`packagingOptions {
        exclude 'META-INF/core_release.kotlin_module'
    }`

**Comment by PierfrancescoSoffritti** [comment]
VideoIdsProvider is a utility class that I'm using in the sample app. It's not part of the library.
