### ISSUE TITLE
Violation: API client cannot change the visual content, features of user upload data

### ISSUE THREAD

**Issue by eggham0518** [PierfrancescoSoffritti/android-youtube-player#456]
Thank you for making this library,

I received this e-mail from YouTube api team. But I don't know what to change.
Do you have any idea? Please help me.

----------------------------------------------------------------------------------------------------
Thanks for working with us on the YouTube API Services Compliance Review. We have reviewed your Audit form and so far, have found that your API Client(s) are out of compliance on the following violation:

[Policy #: III.F.1 (YouTube Look and Feel) (link)]

https://drive.google.com/file/d/1Pf9vWtQq7CsBgLf8_HO62ocmtSQkocwy/view?usp=sharing

Violation: API client cannot change the visual content, features of user upload data. YouTube actions should be clearly identifiable, until unless a YouTube written approval.

You have seven (7) days to bring your API Client into compliance with the YouTube API Services Terms and Policies.

**Comment by PierfrancescoSoffritti** [comment]
[Use the web UI(https://github.com/PierfrancescoSoffritti/android-youtube-player#web-based-ui).
