### ISSUE TITLE
BUG: Player not able to play this videoId format: b4TP3-MQqZg&t=13s

### ISSUE THREAD

**Issue by wolasoft** [PierfrancescoSoffritti/android-youtube-player#458]
BUG: video player is not able to play video Id containing: =
Example:
videoId=b4TP3-MQqZg&t=13s
What I do wrong?

**Comment by PierfrancescoSoffritti** [comment]
You need to manually set the time. This is the id: b4TP3-MQqZg the time is not part of it.

**Comment by wolasoft** [comment]
It works.
Thanks
