### ISSUE TITLE
Red band Line on the player (maybe the seekbar)

### ISSUE THREAD

**Issue by didiosn** [PierfrancescoSoffritti/Android-YouTube-Player#46]
Hi, Everything it's working fine, except the player seekbar is too large, looking like a red band at the bottom of the player. 

Check screeshot : https://www.screencast.com/t/Xqtg4onv

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, in order to solve the issue it'd be useful for me to be able to replicate it, could you give me some info about your system/how you're running the app? Version of Android, phone, are you running it in full screen, orientation of the device..

Also, could you try to run the [sample app](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/sample/sample-debug.apk?raw=true) and see if there problem is there as well?

thanks!

**Comment by didiosn** [comment]
Hi, sorry i'm late. 
I tested on  Zenfone 2 Z00AD, with a custom xosp rom running Android 6. 
The Youtubeplayervieew is on an activity opening in fullscreen mode and landscape orientation. 

I've tried your sample app, it's works fine, no red band problem

**Comment by PierfrancescoSoffritti** [comment]
Can i see the xml file of your Activity? [this the one of the sample app.](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/sample/src/main/res/layout/activity_main.xml)

**Comment by didiosn** [comment]
the xml : 

```
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:background="@color/white"
    android:id="@+id/realtiv"
    android:layout_height="match_parent">
        <VideoView
            android:id="@+id/myvideoview"
            android:layout_width="match_parent"
            android:layout_gravity="center"
            android:layout_height="match_parent"
            android:layout_alignParentLeft="true" android:layout_alignParentStart="true"
            android:layout_alignParentRight="true" android:layout_alignParentEnd="true"
            android:layout_alignParentBottom="true"
            android:layout_alignParentTop="true"
            />

        <com.pierfrancescosoffritti.youtubeplayer.player.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:visibility="gone"
            android:layout_alignParentLeft="true" android:layout_alignParentStart="true"
            android:layout_alignParentRight="true" android:layout_alignParentEnd="true"
            android:layout_alignParentBottom="true"
            android:layout_alignParentTop="true"/>
</RelativeLayout>
```

On the activity, I hide videoview if the video the user is gonna play is from youtube. 

(Sorry for bad english)

**Comment by PierfrancescoSoffritti** [comment]
I have tried but I have not been able to replicate the issue.
If you can find what's the difference between my sample app and your app that is causing the problem, let me know, I'd be happy to help you out :)
Right now there's not much I can do, without seeing all your code.

**Comment by didiosn** [comment]
Hi i'm back. I found what's wrong.
The problem is in the declaration of the activity which is handling the youtubeview : 

`android:theme="@android:style/Theme.NoTitleBar.Fullscreen"`

If i remove it, it's all fine. But i need that declaration. Have you a way to open the activity in fullscreen and landscape mode with the youtubeview in fullscreen too ?

**Comment by PierfrancescoSoffritti** [comment]
Ok, is best to use AppCompat theme.

> Have you a way to open the activity in fullscreen and landscape mode with the youtubeview in fullscreen too ?

If you want to do it programmatically you can use this code in the onCreate method of your Activity

```
setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
fullScreenManager.enterFullScreen();
youTubePlayerView.enterFullScreen();
```
FullScreenManager is this class [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/sample/src/main/java/com/pierfrancescosoffritti/youtubeplayersample/FullScreenManager.java).

**Comment by didiosn** [comment]
Hi. I fix it. 
I create a new style : 

```
<style name="Theme.AppCompat.Light.NoActionBar.FullScreen" parent="@style/Theme.AppCompat.Light">
        <item name="windowNoTitle">true</item>
        <item name="windowActionBar">false</item>
        <item name="android:windowFullscreen">true</item>
        <item name="android:windowContentOverlay">@null</item>
    </style>
```
and use it in the manifest : 

```
<activity
            android:name=".VideoPlayer"
            android:label="@string/app_name"
            android:launchMode="singleTask"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar.FullScreen">
        </activity>
```

For orientation i use this : 

`setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);`

**Comment by PierfrancescoSoffritti** [comment]
perfect, I'm glad you figured it out :)
