### ISSUE TITLE
Add support for looping video playback

### ISSUE THREAD

**Issue by markproxy** [PierfrancescoSoffritti/android-youtube-player#460]
According to official YouTube documentation, we should be able to add loop and playlist variables to playerVars to enable automatic looping of video playback: https://developers.google.com/youtube/player_parameters#loop

The android-youtube-player API does not support this, and it would be great if it did.

Note: I have experimented with this locally, by modifying `IFramePlayerOptionsExampleActivity` and `IFramePlayerOptions.kt` to send in the loop and playlist variables, and I was unable to get it working. Then I modified `WebViewYouTubePlayer.loadVideo()` to call `"javascript:loadPlaylist('$videoId',0, $startSeconds)"` instead of `"javascript:loadVideo('$videoId', $startSeconds)"`, and looping started working. Of course, this also caused the YouTube UI to show an additional control for the playlist (even though there was only one video), so this would not be an acceptable solution.

I'll give some thought to how best to handle the scenario where we want to loop playback on a single video. One option would be for `WebViewYouTubePlayer` to keep a reference to the `IFramePlayerOptions` passed into `initialize()`, and then call `loadPlaylist()` when the `loop` option has been set to 1.

**Comment by markproxy** [comment]
I'm unable to create a branch to push a commit and open a PR, so I'm attaching a patch file that shows one way to add support for looping, which can be applied locally via `git apply patch.txt`.

[patch.txt](https://github.com/PierfrancescoSoffritti/android-youtube-player/files/3757761/patch.txt)

**Comment by markproxy** [comment]
I'm unable to create a branch to push a commit and open a PR, so I'm attaching a patch file that shows one way to add support for looping, which can be applied locally via `git apply patch.txt`.

[patch.txt](https://github.com/PierfrancescoSoffritti/android-youtube-player/files/3757777/patch.txt)

**Comment by PierfrancescoSoffritti** [comment]
Hey, why is it a problem to loop the video manually? (manually restart after it ends)

**Comment by markproxy** [comment]
When I briefly experimented with YouTube's built-in looping, it seemed a
little smoother than calling seek to zero and play when the ENDED event is
received.

It also seems like it's something the library should support, since the
YouTube iframe API supports it.

Perhaps a generic means of passing in playerVar settings would be a better
approach, to give access to options not explicitly supported by this
library?

**Comment by PierfrancescoSoffritti** [comment]
Hey, sorry these days I don't have much time to work on the library. Feel free to send a pull requests, if you have ideas we can discuss them there.

**Comment by PierfrancescoSoffritti** [comment]
This will be available in version 12.1.0 which releases sometimes this week.
