### ISSUE TITLE
Video is not displaying in full screen.

### ISSUE THREAD

**Issue by VamsiKonanki** [PierfrancescoSoffritti/android-youtube-player#462]
Hi, 

I was mentioned `app:showFullScreenButton="true"` in xml, after clicking the full screen icon nothing happened. 

I placed "YouTubePlayerView" inside RecyclerView.

Thanks in advance.
Vamsi K

**Comment by PierfrancescoSoffritti** [comment]
That just shows the button. It's up to you to handle it. See the documentation and sample app for more info and examples.

**Comment by varun7952** [comment]
Then how to get button on click event. Please help on this thing
