### ISSUE TITLE
Suggested Videos not playing,

### ISSUE THREAD

**Issue by mrkamiali** [PierfrancescoSoffritti/android-youtube-player#464]
Hi, @PierfrancescoSoffritti I want to hide the suggested videos when I pause video it shows me a list of videos at the bottom and when the video ends its shows suggested videos in grid, 
If it's possible to hide please let me know and also I am not getting any click of suggested videos click neither it plays by itself.

**Comment by PierfrancescoSoffritti** [comment]
It's not possible to remove suggested videos. If you want to click them you need to use web-based ui.

**Comment by mrkamiali** [comment]
Alrgiht! I have enabled web Ui, and on click of any video in the list it redirects to youtube app, is there any work around to handle it @PierfrancescoSoffritti Please make it fast reply I have to stop it to redirect to youtube app.Thanks

**Comment by PierfrancescoSoffritti** [comment]
I guess you can try to intercept the events from the WebView. I've never done it though.

**Comment by mrkamiali** [comment]
> I guess you can try to intercept the events from the WebView. I've never done it though.

WHERE do I get event in project.

**Comment by mrkamiali** [comment]
@PierfrancescoSoffritti I have restricted app to open youtube app. Should I put a pull request.

**Comment by PierfrancescoSoffritti** [comment]
Sure, I'd like to see it.

**Comment by mrkamiali** [comment]
> Sure, I'd like to see it.

I have already pushed the code and it merged in #463

**Comment by PierfrancescoSoffritti** [comment]
Please do it in a separate pull request.

**Comment by mrkamiali** [comment]
> Please do it in a separate pull request.

I've pushed my code and it merged automatically here in #463

**Comment by PierfrancescoSoffritti** [comment]
You should create a new local branch, do the change there and then send a separate pull request.

A pull request should be about a single change, not multiple.

**Comment by mrkamiali** [comment]
> You should create a new local branch, do the change there and then send a separate pull request.
> 
> A pull request should be about a single change, not multiple.

:( It is already pushed .

**Comment by PierfrancescoSoffritti** [comment]
Remove the change and push again.
