### ISSUE TITLE
How to add LifeCycle Observer to youtubePlayer if it is in adapter of recycler view?

### ISSUE THREAD

**Issue by pritish12** [PierfrancescoSoffritti/android-youtube-player#466]
I have defined `com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView` inside adapter layout of my `recyclerview` and I am not able to figure out how to add `lifecycleobserver` to the view.  I am passing context in the adapter of my recyclerview but I can't access `lifecycleobserver`

**Comment by coreform** [comment]
Add an extra contstructor argument and pass a lifecycleoberver in there, or add a public method and pass a lifecycleobserver using it after constructing.

**Comment by PierfrancescoSoffritti** [comment]
You can get the lifecycle from an Activity or Fragment.
