### ISSUE TITLE
Consider using android.webkit

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [PierfrancescoSoffritti/android-youtube-player#467]
See [video](https://www.youtube.com/watch?v=7Wq8Lwt_Cbg).

**Comment by cuongnb96** [comment]
hi,i fix the issues of #461,so how can i create a pull request?.i tryed but all is no permission.thanks @PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
Why are you leaving a comment in this issue if it's about issue 461?

**Comment by PierfrancescoSoffritti** [comment]
In any case, you don't need permission to send a pull request.

**Comment by cuongnb96** [comment]
so sorry,deleted

**Comment by PierfrancescoSoffritti** [comment]
No need. androidx.webkit is meant to be used to add backward compatibility.
