### ISSUE TITLE
Codec problem with MiBox 4S

### ISSUE THREAD

**Issue by alextfos** [PierfrancescoSoffritti/android-youtube-player#469]
Hi!

We have a problem using the component in a AndroidTV app. The major part of videos are showing with a green layer. The device is a MiBox 4S. Do you know if can we modify that configuration?

Same implementation works with another devices.

Thank you!

**Comment by PierfrancescoSoffritti** [comment]
Hi, it's probably an issue with WebView or graphics processor on that device.
