### ISSUE TITLE
Quality of video not good

### ISSUE THREAD

**Issue by mdtuyen** [PierfrancescoSoffritti/Android-YouTube-Player#47]
In some device, quality of video not good: video lag and noise 
I think you need setting for YoutubePlayer webview

**Comment by PierfrancescoSoffritti** [comment]
Which settings are you referring to? 
It's probably a problem with WebView on old devices. I'm think about changing the min supported sdk to Lollipop.

**Comment by mdtuyen** [comment]
I need run app from sdk 15

**Comment by mdtuyen** [comment]
Hi @PierfrancescoSoffritti , this issue occur by device not sdk version. All device of me sdk >= 4.4

**Comment by PierfrancescoSoffritti** [comment]
This issue is related to #2
