### ISSUE TITLE
Video shows blank screen while audio and controls work

### ISSUE THREAD

**Issue by jerbotron** [PierfrancescoSoffritti/android-youtube-player#474]
Hello, I promise I've read all the threads on issues related to this and I've tried all the suggested remedies but still experiencing the following issues.

This is the screen that I see, the video view is basically a blank screen but the audio and controls work.
<img width="378" alt="Screen Shot 2019-11-11 at 3 53 10 PM" src="https://user-images.githubusercontent.com/4398877/68570508-dba9c600-049b-11ea-8d5b-62f2caf1c944.png">

Here is my resource file, copied straight from the sample app:

`
<LinearLayout android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android">

        <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:autoPlay="true"
            app:videoId="YE7VzlLtp-4"
            app:showYouTubeButton="false"
            app:showSeekBar="false" />

</LinearLayout >
`

Here is my Activity code:

`
override fun onCreate(state: Bundle?) {
        super.onCreate(state)
        setContentView(R.layout.activity_ads_video_detail)
        playerView = findViewById(R.id.youtube_player_view)
        lifecycle.addObserver(playerView)
}
`

The environment I'm testing on:
- Lib version: 10.0.5
- Kotlin
- Pixel 2 Emulator, API 23, x86_64
- Also reproduced on real Pixel 3 Device running API 28
- Also tried setting hardwareAccelerated=true in the manifest

I don't think it's a code related issue, but I'm running out of ideas on what to try next... please help! Thank you!

**Comment by PierfrancescoSoffritti** [comment]
It is expected not to work on emulators, should work fine on pixel 3 though.

**Comment by jerbotron** [comment]
But the sample app works on the same emulator? 

> It is expected not to work on emulators, should work fine on pixel 3 though.

**Comment by jerbotron** [comment]
Repros also on a real device (OnePlus) 

![IMG_1782](https://user-images.githubusercontent.com/4398877/68728738-1a0dc500-0603-11ea-8d91-97e65b265d09.PNG)

**Comment by PierfrancescoSoffritti** [comment]
Do you have the same problem with the sample app? if not there must be something wrong with the way you're using the library.

**Comment by CandinhoX** [comment]
Hello, I'm having this same issue did you managed to solve it?

**Comment by brookmg** [comment]
I'm also stuck with this problem, tried everything but still no luck.

**Comment by brookmg** [comment]
@AbelTesfaye found the solution for this. Turns out I didn't enable hardware acceleration in the manifest. Thanks

**Comment by vikasjplutus** [comment]
> @AbelTesfaye found the solution for this. Turns out I didn't enable hardware acceleration in the manifest. Thanks
> 
> in the `AndroidManifest.xml`
> 
> ```
> <application
>         ...
>         android:hardwareAccelerated="true">
>         ...
> </application>
> ```

Its working awesome...Like a magic...
Thanks a lot...

**Comment by kinsog** [comment]
> @AbelTesfaye found the solution for this. Turns out I didn't enable hardware acceleration in the manifest. Thanks
> 
> in the `AndroidManifest.xml`
> 
> ```
> <application
>         ...
>         android:hardwareAccelerated="true">
>         ...
> </application>
> ```

thank you too!! (thanks to the owner too @PierfrancescoSoffritti )
that solution works

**Comment by StefanVanStaden** [comment]
> @AbelTesfaye found the solution for this. Turns out I didn't enable hardware acceleration in the manifest. Thanks
> 
> in the `AndroidManifest.xml`
> 
> ```
> <application
>         ...
>         android:hardwareAccelerated="true">
>         ...
> </application>
> ```

Was the solution for me as well. @PierfrancescoSoffritti Can you please mark this as the solution as I have seen this in closed tickets as well as a lot of comments regarding this issue.

**Comment by PierfrancescoSoffritti** [comment]
It's already [in the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#hardware-acceleration).

**Comment by KumarVelu** [comment]
> It is expected not to work on emulators, should work fine on pixel 3 though.

@PierfrancescoSoffritti 
Yes, facing the same problem in emulator
Why doesn't it work in emulators ?  I am running it in the android tv emulator and having this issue of screen being blank, while the video is getting played. 
Currently have no real tv device to test it out.

**Comment by PierfrancescoSoffritti** [comment]
I suspect it has to do with webview/hardware acceleration on the emulators.

**Comment by KumarVelu** [comment]
> I suspect it has to do with webview/hardware acceleration on the emulators.

Thanks for your quick reply.
I have added the android:hardwareAccelerated="true" in emulator and yet this error happens.

**Comment by ParthP8399** [comment]
Oh my god thank you so much. I spend around 1 day trying to solve the black screen


> > @AbelTesfaye found the solution for this. Turns out I didn't enable hardware acceleration in the manifest. Thanks
> > in the `AndroidManifest.xml`
> > ```
> > <application
> >         ...
> >         android:hardwareAccelerated="true">
> >         ...
> > </application>
> > ```
> 
> Was the solution for me as well. @PierfrancescoSoffritti Can you please mark this as the solution as I have seen this in closed tickets as well as a lot of comments regarding this issue.

**Comment by PierfrancescoSoffritti** [comment]
https://github.com/PierfrancescoSoffritti/android-youtube-player#hardware-acceleration
