### ISSUE TITLE
I need to check quality periodically 

### ISSUE THREAD

**Issue by amrashraf1992** [PierfrancescoSoffritti/android-youtube-player#477]
let's say i need to check quality every 1 sec

**Comment by PierfrancescoSoffritti** [comment]
Why do you need to do that? onPlaybackRateChange is called when quality changes, so no need to periodically check?

**Comment by amrashraf1992** [comment]
We use your library for Video Quality testing

**Comment by amrashraf1992** [comment]
We need a way to get Quality without certain Event

**Comment by PierfrancescoSoffritti** [comment]
What do you mean exactly that you use it for quality testing?

`onPlaybackRateChange` is called every time quality changes, you can keep track of it with your own code. You may want to extend [YouTubePlayerTracker](https://github.com/PierfrancescoSoffritti/android-youtube-player#youtubeplayertracker) to handle that. Or do something similar.
