### ISSUE TITLE
Video reload after rotate Activity contain YoutubePlayerView 

### ISSUE THREAD

**Issue by mdtuyen** [PierfrancescoSoffritti/Android-YouTube-Player#48]
I config for Activity not recreate when rotate in Manifest and when check:
- Activity not recreate
- YoutubePlayerView not recreate
- YoutubePlayer not recreate 
But js recall ready function so that youtubeplayerview will reload the id of youtube and youtube will restart.

**Comment by jaypatel9912** [comment]
@mdtuyen I am facing similar issue. How you have solved it?
