### ISSUE TITLE
Does showing a panel over the player violate YouTube's terms?

### ISSUE THREAD

**Issue by ltomov** [PierfrancescoSoffritti/android-youtube-player#486]
Hi, I noticed the sample CustomPlayerUiController places a panel with a transparent background over the player and this way preventing the user from being able to click on it: 
https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/50c249915ef73c7c3d3b6769ce3d3441ac46cc25/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/customUiExample/CustomPlayerUiController.java#L79

Is this ok with YouTube's terms? The official player has a feature where if it detects an element over the player - the playback is stopped.

I'm looking for a way to hide the video title and the only way I see is to place some element on top of it, but fear this will violate the terms.

Thanks!

**Comment by PierfrancescoSoffritti** [comment]
Hi, it's ok if the view is transparent. Not ok if the view is actually hiding portions of the player.
