### ISSUE TITLE
Randomly playing Bonobo Kerala video

### ISSUE THREAD

**Issue by tanmaygr** [PierfrancescoSoffritti/android-youtube-player#487]
```
  @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                YouTubePlayerUtils.loadOrCueVideo(
                        youTubePlayer,
                        getLifecycle(),
                        "PJGVDaSaQWQ",
                        0f
                );
```

I have used this function to play a specific video but The player alternately plays this youtube video and the Bonobo Kerala video. I have searched all the non-project files also of the player but couldn't find the youtube link of Bonobo video. So I am not able to understand how is that video playing. I even cleaned the project and tried it on different android devices.
So kindly resolve this issue.

**Comment by PierfrancescoSoffritti** [comment]
It is definitely an issue in your code :)

**Comment by Berkay92** [comment]
I've face the same issue. Then I realized that I copied YouTubePlayerView component from "Quick Start" section example in README.md. This example contains static video id "app:videoId="S0Q4gqBUs7c" which refers to that video you mentioned. Just delete this line to resolve the inconsistencies.

**Comment by tanmaygr** [comment]
Thank you so much, found the issue.

**Comment by thejogsa** [comment]
@tanmaygrover98  What was the issue in this ? I'm facing same problem

**Comment by anirudhajith** [comment]
@thejogsa Remove the attributes 'autoPlay' and 'videoId' from the xml. This fixed the issue for me.
