### ISSUE TITLE
Unwanted Permission Exception

### ISSUE THREAD

**Issue by shubhamR1997** [PierfrancescoSoffritti/android-youtube-player#489]
While playing youtube video through this library it is throwing unwanted permission exceptions E.g
"W/CameraBase: An error occurred while connecting to camera 1: Status(-8): '1: validateClientPermissionsLocked:913: Caller "com.my_packagename" (PID 10380, UID 13672) cannot open camera "1" without camera permission' "

An error like failed to connect to camera service and all. Why this permission needed when it's had nothing to do with camera or all. I am using core library not even that chromecast so why these all exceptions occurring?

**Comment by PierfrancescoSoffritti** [comment]
I doubt that message is coming from the library.
