### ISSUE TITLE
Please add fullscreen button option "fs" to IFramePlayerOptions

### ISSUE THREAD

**Issue by uenx** [PierfrancescoSoffritti/android-youtube-player#491]
When useWebUi is true, the fullscreen button is hidden by default.
I think it is better to provide an method for passing custom flag when building IFramePlayerOptions.
Thank you for your consideration.

**Comment by PierfrancescoSoffritti** [comment]
The point of using web ui is that there is not UI overlay over the YouTube player. Adding a full screen button would go against this idea. 
Your problem can be easily solved by building your own custom UI.
