### ISSUE TITLE
play a list of videos

### ISSUE THREAD

**Issue by maxvuluy** [PierfrancescoSoffritti/android-youtube-player#499]
I'm developing an app to play a list of videos. It seems that loadVideo (or cueVideo) accept one video one time.
Is it possible to provide a function like [loadVideos](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer#loadVideos(java.util.List<java.lang.String>,%20int,%20int)) of [YouTube Android Player API](https://developers.google.com/youtube/android/player/reference/com/google/android/youtube/player/YouTubePlayer) to play a list of videos in sequence? Thanks.

**Comment by PierfrancescoSoffritti** [comment]
I don't have plans for implementing that, I suggest you build your own utility function.
