### ISSUE TITLE
Always autoplay

### ISSUE THREAD

**Issue by yasfdany** [PierfrancescoSoffritti/Android-YouTube-Player#50]
how to prevent view to autoplay the video?

**Comment by PierfrancescoSoffritti** [comment]
Hi, see [here](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayer.java) the difference from `cueVideo` and `loadVideo`.

`loadVideo` automatically plays the video, `cueVideo` doesn't.
