### ISSUE TITLE
Video is not showing in API 27

### ISSUE THREAD

**Issue by SMARTVIK** [PierfrancescoSoffritti/android-youtube-player#501]
I am not able to see the video in API 27, only audio is playing.

**Comment by PierfrancescoSoffritti** [comment]
Are you using an emulator? if yes, this is a known issue, use the latest API or a real device.

**Comment by SMARTVIK** [comment]
@PierfrancescoSoffritti Yes, I was using the Emulator. One More Thing, My App from the play store is removed by saying that the app is violating YouTube policies. Can you guide me regarding this?

**Comment by PierfrancescoSoffritti** [comment]
Are you covering the player with other Views? If yes, you shouldn't. Another thing you could try is to enable web ui in the library.
