### ISSUE TITLE
API 'variantOutput.getPackageLibrary()' is obsolete ... It will be removed at the end of 2019.

### ISSUE THREAD

**Issue by JmyW** [PierfrancescoSoffritti/android-youtube-player#503]
Hi
I download whole package and manually added in my project. It works fine but keep seeing a warming message as following in Build window. It has been closed to the end of 2019. I'm worrying. Is there anyone know how to fix it? or this library should be updated to getPackageLibraryProvider() ?

API 'variantOutput.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.

**Comment by PierfrancescoSoffritti** [comment]
I don't think this is going to be an issue going forward.
That said it would be nice to remove the warning. I assume is because of some dependency the library is using.

**Comment by JmyW** [comment]
Got it, thanks for prompt feedback.

**Comment by JmyW** [comment]
Got it, thanks for prompt feedback.
