### ISSUE TITLE
Not playing a lot of videos

### ISSUE THREAD

**Issue by bernaferrari** [PierfrancescoSoffritti/android-youtube-player#505]
I've been a long time user of (https://github.com/HaarigerHarald/android-youtubeExtractor). Except recently it completely stopped working in a lot of videos. Then I went to the rescue, started using your library (fantastic API, BTW) and... pikachu_surprised, same issue in same videos:

![image](https://user-images.githubusercontent.com/351125/71548584-76e4f500-298f-11ea-89d4-3b5a65cb8e9e.png)

For reference, here one of the URLs: https://www.youtube.com/watch?v=RykN4GemMc8

Is there anything I'm not getting right? It works in some videos, just not in a lot.

**Comment by PierfrancescoSoffritti** [comment]
Did you close the issue because you solved the problem?

**Comment by bernaferrari** [comment]
Yes. Weirdly, this only happened in emulator AND youtube's own app was incapable of reproducing it for mysterious reasons. In device, however, worked fine.
