### ISSUE TITLE
When in full screen mode, I want to change the screen to horizontal mode.

### ISSUE THREAD

**Issue by warrenth** [PierfrancescoSoffritti/android-youtube-player#506]
It's a really useful open source, and I'm grateful for it.
When in full screen mode, I want to change the screen to horizontal mode.
I look forward to hearing from you.

**Comment by warrenth** [comment]
sorry. I solved it.

**Comment by warrenth** [comment]
Please allow me to getFullscreenControlFlags to interface YouTubePlayer.

**Comment by PierfrancescoSoffritti** [comment]
You should do that in your Android app, it has nothing to do with the library. Look into changing the orientation of the screen.
