### ISSUE TITLE
How to change videoId?

### ISSUE THREAD

**Issue by theforec** [PierfrancescoSoffritti/android-youtube-player#507]
I developing app like this https://youtu.be/eouC8RUmHh8
when new video selected, videoid has changed but nothing happen. 
how can i do? Thanks

**Comment by PierfrancescoSoffritti** [comment]
I don't understand.

**Comment by theforec** [comment]
![image](https://user-images.githubusercontent.com/38517373/71894432-d5288980-3180-11ea-8bee-fbcaeffb4805.png)

when I change **videoId**, youTubePlayerView not change
It seems that cueVideo accept one video one time.

**Comment by PierfrancescoSoffritti** [comment]
cueVideo is meant to accept one video at a time.

**Comment by theforec** [comment]
yep. how to change youTubePlayerView display when I change **videoId**?
i tried all abtract listener but didn't work

**Comment by PierfrancescoSoffritti** [comment]
Just call cueVideo with the new video id and the new video will start playing.

**Comment by theforec** [comment]
example: i have youTubePlayerView and button.
i init youTubePlayerView first like this 
![image](https://user-images.githubusercontent.com/38517373/71909331-65c39180-31a2-11ea-9448-fdf5fbfd573d.png)

and button 
![image](https://user-images.githubusercontent.com/38517373/71909400-8ee42200-31a2-11ea-9f7b-fa9e5942236b.png)

but when i click button, youTubePlayerView change nothing (thumbnail or click play ...)

**Comment by PierfrancescoSoffritti** [comment]
That's wrong, you need to keep track of the first `YouTubePlayer` and call `cueVideo` on that.

**Comment by vishalkumarsinghvi** [comment]
> YouTubePlayer

Thanks, I resolved my problem with the help of this comment

**Comment by reatline** [comment]
How can I change the video id? I would really appreciate if you help.
