### ISSUE TITLE
Video is blur when it is played on Android TV

### ISSUE THREAD

**Issue by yangshulin2019** [PierfrancescoSoffritti/android-youtube-player#509]
Hello, when I use YouTubePlayerView to play video on Android TV, the video resolution is very low, it seems only about 480p, it is very low on Android TV, which can be 1080p and the videos are blur when they are playing. Do you have any suggestion to solve this problem?

**Comment by PierfrancescoSoffritti** [comment]
Hi, unfortunately video quality is handled automatically by the JavaScript player.
