### ISSUE TITLE
Autoplay video

### ISSUE THREAD

**Issue by yasfdany** [PierfrancescoSoffritti/Android-YouTube-Player#51]
how to prevent view to autoplay the video?

**Comment by PierfrancescoSoffritti** [comment]
Please, pay attention to the issue you have already open. #50

**Comment by yasfdany** [comment]
Im sorry, i think my quetion is deleted

I new on github

Pada tanggal 11 Nov 2017 11.15 PM, "Pierfrancesco Soffritti" <
notifications@github.com> menulis:
