### ISSUE TITLE
Is there a way to hide youtubePlayer button, menu icon and title? 

### ISSUE THREAD

**Issue by Dcosta2205** [PierfrancescoSoffritti/android-youtube-player#513]
I wanted to hide the youtube button , menu and title . I tried to hide them using the provided APi's but it doesn't seem to work.
`     youTubePlayerView.getPlayerUIController().showVideoTitle(false);
                        youTubePlayerView.getPlayerUIController().showMenuButton(false);
                        youTubePlayerView.getPlayerUIController().showYouTubeButton(false);
`
Is there any other way to do it ?

**Comment by PierfrancescoSoffritti** [comment]
That's the correct way of doing it.

**Comment by amitimg29** [comment]
youTubePlayerView.getPlayerUIController().showVideoTitle(false); youTubePlayerView.getPlayerUIController().showMenuButton(false); youTubePlayerView.getPlayerUIController().showYouTubeButton(false);

these options are not working.

**Comment by samatzhusup** [comment]
> youTubePlayerView.getPlayerUIController().showVideoTitle(false); youTubePlayerView.getPlayerUIController().showMenuButton(false); youTubePlayerView.getPlayerUIController().showYouTubeButton(false);
> 
> these options are not working.

for hide youtube icon in player add xml file app:showYouTubeButton="false"
if u found how to hide title and share icon can u me help me ?

**Comment by amitimg29** [comment]
> > youTubePlayerView.getPlayerUIController().showVideoTitle(false); youTubePlayerView.getPlayerUIController().showMenuButton(false); youTubePlayerView.getPlayerUIController().showYouTubeButton(false);
> > these options are not working.
> 
> for hide youtube icon in player add xml file app:showYouTubeButton="false"
> if u found how to hide title and share icon can u me help me ?


still struggling with this buddy.

**Comment by PierfrancescoSoffritti** [comment]
You can't remove them from the web player, only from native ui.

**Comment by forceporquillo** [comment]
> You can't remove them from the web player, only from native ui.

Does this count with inflating customUiPlayer?

**Comment by PierfrancescoSoffritti** [comment]
Same, it is explained in the doc. Unfortunately YouTube made changes to the web library, and those UI components can't be removed anymore.

Both native UI and custom UI add a view ontop of the webview, preventing the web buttons from being clicked.

**Comment by forceporquillo** [comment]
Oh, I see. I already figured out in my use case, adding custom anamorphic crop bars will do the trick.~
