### ISSUE TITLE
White screen before loading

### ISSUE THREAD

**Issue by ilpelatodijavascript** [PierfrancescoSoffritti/android-youtube-player#514]
Hi, I'm creating a dialog and inside it's view I'm using a YouTubePlayerView.
When I show the dialog, the view has a white background before loading the actual Youtube player.
I was wondering if it is possible to change that background from white to black, because white doesn't fit with the colors of my app.
Thanks

**Comment by PierfrancescoSoffritti** [comment]
Hi, the background should be black. I have never tried in a dialog, but I assume it should be the same as the other use cases.

**Comment by ilpelatodijavascript** [comment]
Well, its white for 2/3 seconds, than it turns black with the progressbar loading

**Comment by VolodymyrMachekhin** [comment]
It is not the library problem. While loading a WebView is empty for a moment and you can see it's own background. The solution is to set the background to the WebView 
`    fun ViewGroup.disableWebViewsBackground() {
        children.forEach { child ->
            when (child) {
                is WebView -> child.setBackgroundColor(Color.TRANSPARENT)
                is ViewGroup -> child.disableWebViewsBackground()
            }
        }
    }`

and then 
`youtubePlayerView.disableWebViewsBackground()`

**Comment by ilpelatodijavascript** [comment]
> It is not the library problem. While loading a WebView is empty for a moment and you can see it's own background. The solution is to set the background to the WebView
> 
> ```
> fun ViewGroup.disableWebViewsBackground() {
>         children.forEach { child ->
>             when (child) {
>                 is WebView -> child.setBackgroundColor(Color.TRANSPARENT)
>                 is ViewGroup -> child.disableWebViewsBackground()
>             }
>         }
> }
> ```
> 
> and then
> `youtubePlayerView.disableWebViewsBackground()`

It worked this way! Thanks!

**Comment by quiKsilverItaly** [comment]
how can I fix this issue in Java?

**Comment by ilpelatodijavascript** [comment]
> how can I fix this issue in Java?
> 
> edit: i just installed kotlin now in my project, but i guess due to the nature of extensions exclusive in kotlin it's harder to fix in java i assume

Java:
```
youtubePlayerView = (YouTubePlayerView) findViewById(R.id.youtubePlayerView);
disableWebViewBackground((ViewGroup)youtubePlayerView);
//Do this in onCreate
```
function is like this
```
private void disableWebViewBackground(ViewGroup viewGroup){
        int childCount = viewGroup.getChildCount();
        for(int i=0; i<childCount; i++){
            if(viewGroup.getChildAt(i) instanceof WebView){
                viewGroup.getChildAt(i).setBackgroundColor(Color.TRANSPARENT);
            }else if(viewGroup.getChildAt(i) instanceof ViewGroup){
                disableWebViewBackground((ViewGroup)viewGroup.getChildAt(i));
            }
        }
    }
```

**Comment by ThirupathiMukkera** [comment]
And after the white screen youtube logo is showing in the center. How to remove  that youtube logo?
