### ISSUE TITLE
Title is very wired it must have option to set text size and other watch more and share options 

### ISSUE THREAD

**Issue by zaryab-ops** [PierfrancescoSoffritti/android-youtube-player#516]
![Screenshot_20200203-180614](https://user-images.githubusercontent.com/60610155/73655904-d7630280-46b0-11ea-96a1-3c7e248c5eaf.jpg)

**Comment by PierfrancescoSoffritti** [comment]
Unfortunately that's part of the web player, ie the library has not control over it.
