### ISSUE TITLE
Playing FullScreen Video in Fragments like a Signle Screen

### ISSUE THREAD

**Issue by Nadeembhat** [PierfrancescoSoffritti/android-youtube-player#519]
I am Using framents horizantally three like ----> |1|2|3|  and in each fragment the video is not playing full screen if i set fullscreen the frist fragment gets full rest two will be playing videos in background.

**Comment by AbelTesfaye** [comment]
Hi @Nadeembhat ,

The way the player view is set to fullscreen is by changing **both** the height and width layout params to `MATCH_PARENT` [see here](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/eb337094862369587d8d68fb10211c4f4fac895d/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/utils/FullScreenHelper.kt#L17)

That explains why setting the first fragment to full screen will "hide" the other views (they get pushed out by the first fragment). If you're looking to make all 3 views fullscreen at the same time, consider setting **just** the height layout param of all the player views to `MATCH_PARENT`
