### ISSUE TITLE
 I touch the button to put it in full screen but the screen doesn’t expand  Does anyone know how to resool this?

### ISSUE THREAD

**Issue by emanoel2712** [PierfrancescoSoffritti/android-youtube-player#528]
I touch the button to put it in full screen but the screen doesn’t expand

Does anyone know how to resol this?

**Comment by AbelTesfaye** [comment]
Hi @emanoel2712,

Can you please send the layout and code files you're using?

**Comment by PierfrancescoSoffritti** [comment]
Hi, the library doesn't handle full screen logic, that's up to you. For an example of how to do it you can look at the sample app.
