### ISSUE TITLE
Youtube player not expanding to fullscreen in Recyclerview

### ISSUE THREAD

**Issue by varun7952** [PierfrancescoSoffritti/android-youtube-player#530]
recently i shifted to this plugin to play youtube videos in recycler view without using google official API.
It works as expected but i am having issue in making make youtube player into full screen.

Recylerview Adapter for youtube video.
` holderYoutube.player.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onError(YouTubePlayer youTubePlayer, PlayerConstants.PlayerError error) {
                        super.onError(youTubePlayer, error);
                        Log.d(TAG,"On Error = "+error);
                    }

                    @Override
                    public void onReady(YouTubePlayer youTubePlayer) {
                        super.onReady(youTubePlayer);
                        youTubePlayer.cueVideo (wrapper.getUSER_MESSAGE(),0);
                    }

                    @Override
                    public void onStateChange(YouTubePlayer youTubePlayer, PlayerConstants.PlayerState state) {
                        super.onStateChange(youTubePlayer, state);
                        Log.d(TAG, "onStateChange: "+state);

                    }

                    @Override
                    public void onVideoDuration(YouTubePlayer youTubePlayer, float duration) {
                        super.onVideoDuration(youTubePlayer, duration);
                    }

                    @Override
                    public void onVideoId(YouTubePlayer youTubePlayer, String videoId) {
                        super.onVideoId(youTubePlayer, videoId);
                    }
                });`

Layout for youtube video
```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_marginTop="@dimen/list_item_spacing"
    android:layout_marginBottom="@dimen/list_item_spacing"
    android:layout_marginRight="50dp"
    android:layout_marginEnd="50dp">

    <de.hdodenhof.circleimageview.CircleImageView
        android:id="@+id/userImage"
        android:layout_width="40dp"
        android:layout_height="40dp"
        android:layout_marginLeft="2dp"
        android:layout_marginStart="2dp"
        android:src="@drawable/common_google_signin_btn_text_dark"
        />


        <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_toRightOf="@id/userImage"
            android:layout_marginStart="10dp"
            android:layout_toEndOf="@id/userImage"
            android:id="@+id/youtubePlayer"
            app:autoPlay="false"
            app:showFullScreenButton="true"
            app:enableLiveVideoUi="true"

            />



    <TextView
        android:id="@+id/YoutubeTimeStamp"
        android:layout_below="@id/youtubePlayer"
        android:layout_toRightOf="@id/userImage"
        android:layout_toEndOf="@id/userImage"
        android:layout_marginTop="10dp"
        android:layout_marginLeft="10dp"
        android:layout_marginStart="10dp"
        android:textColor="@color/darkGrey"
        android:textSize="12sp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        />
</RelativeLayout>
```

**Comment by PierfrancescoSoffritti** [comment]
The library doesn't handle full screen logic, that's up to you.
