### ISSUE TITLE
It is empty screen, only with chromecast icon

### ISSUE THREAD

**Issue by alex89607** [PierfrancescoSoffritti/android-youtube-player#531]
When I tried to use Chromecast extension (compile of example) and start on Android 7 it is not working propertly. I watch only icon of Chromecast button. When button was tapped - is able to select chromecast device, but its all. Nothing happened, video does not start, empty screen.

Attempt to start usual version (without chromecast) is successful - video was started successfully. Give me advice, please, whats wrong in my actions with chromecast?

**Comment by NanyangTaiji** [comment]
I have the same issue with Android 29 device now. Image loaded but video does not play. The play/pause button no effect while "next video " and MediaRouter button work.

**Comment by PierfrancescoSoffritti** [comment]
Hi, please refer to the sample app. It works there.
