### ISSUE TITLE
Change videoID in the same YouTubePlayerView

### ISSUE THREAD

**Issue by DorenBoust** [PierfrancescoSoffritti/android-youtube-player#534]
Hello,

I made have fitness application.
In the app have Activity of exercises.

When it init first he show the first exercise.
When i click on "next button" all the exercise change (image, title, youtube video).

I have addYouTubePlayerListener(new AbstractYouTubePlayerListener) and the method "onReady" there the videoID change to the correct video of the exercise.

When the Activity just start and he take the first exercise onReady change to the correct video.

I put on the "next button" also addYouTubePlayerListener(new AbstractYouTubePlayerListener) and the method "onReady" and then i put the new videoID but its still show me the first video.

What i miss here?

thanks

**Comment by vishalkumarsinghvi** [comment]
I am also facing same problem

**Comment by shamshadpattani** [comment]
send your code

**Comment by vishalkumarsinghvi** [comment]
Hey thanks for reply using same instant I resolve my problem !!.

**Comment by batoan2898** [comment]
I don't understand how to do. Can u explain the way you did ?

**Comment by vishalkumarsinghvi** [comment]
@batoan2898 I am giving my piece of code might be it will help you have to use single youtube player instance and use cue method:-
`  class VideoViewHolder extends RecyclerView.ViewHolder {

    private YouTubePlayerView youTubePlayerView;

    VideoViewHolder(@NonNull View itemView) {
      super(itemView);
      youTubePlayerView = itemView.findViewById(R.id.youtube_player_view_precautions);
      yourFragment.getLifecycle().addObserver(youTubePlayerView);
    }

    private void setDetails(Precautions precautions) {
      youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
        @Override
        public void onReady(@NonNull YouTubePlayer youTubePlayer) {
          String videoId = videoId;
          youTubePlayer.cueVideo(videoId, 0f);
        }
      });
    }
  }`
If any concern feel free to ask:)

**Comment by JuhIzu** [comment]
For those who did not implemented a Recycler View (I have a single YouTubePlayerView in my layout and I only change the video Id when the user clicks a link in my TextView-could be button).

private YouTubePlayer youTubePlayer;
private YouTubePlayerView youTubePlayerView = findViewById(R.id.youTubePlayerView);
private String videoId= "youTube video id";

youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                        @Override
                        public void onReady(YouTubePlayer youTubePlayer2) {
                            youTubePlayer = youTubePlayer2;
                            youTubePlayer.cueVideo(videoId, 0);
                        }
                    });

// I have a textView (could also be a button) which changes the ID of the video when clicked:
textView.setOnClickListener(new View.OnClickListener() {
        @Override
        public void onClick(View v) {
            videoId= "another YouTube video id";
            youTubePlayer.cueVideo(videoId, 0);
        }
    });
