### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/core_release.kotlin_module'

### ISSUE THREAD

**Issue by iamriajul** [PierfrancescoSoffritti/android-youtube-player#537]
Getting This Error When Adding This Library into My Project!
`More than one file was found with OS independent path 'META-INF/core_release.kotlin_module'`

**Comment by PierfrancescoSoffritti** [comment]
Put this in your build.gradle file inside of the `android { }` part

```
// this is needed because I'm importing 2 modules called "core"
packagingOptions {
  exclude 'META-INF/core_release.kotlin_module'
}
```
