### ISSUE TITLE
Player UI is borken

### ISSUE THREAD

**Issue by hiddow** [PierfrancescoSoffritti/Android-YouTube-Player#54]
chromium: [INFO:CONSOLE(85)] "Uncaught TypeError: player.getVideoData is not a function", source: https://www.youtube.com/ (85)

**Comment by PierfrancescoSoffritti** [comment]
Have you tried the sample app? Does the video starts?

Are you connected to the internet?

**Comment by hiddow** [comment]
the sample app is also same, can't move the progressbar, not duration show, not video title show, but also can play.

**Comment by PierfrancescoSoffritti** [comment]
You CAN play? Confirm?
What version of Android are you using?

**Comment by hiddow** [comment]
samsung s7 edge :Android 7.0.1
Nexus5 : Android 6.0.1
yestoday both work fine, but today is not working normal. video can play, can't control the playback progress .

**Comment by hiddow** [comment]
ScreenShot no duration show.

2017年11月14日 14:21，"Pierfrancesco Soffritti" <notifications@github.com>写道：

> You CAN play? Confirm?
> What version of Android are you using?
>

**Comment by PierfrancescoSoffritti** [comment]
I have made no changes to the library release, nor yesterday nor today. Therefore, if yesterday it was working fine you must have changed something in your code, is that possible?

**Comment by hiddow** [comment]
Nope, I also check your app [https://play.google.com/store/apps/details?id=com.pierfrancescosoffritti.shuffly](url) the same situation: not duration, can't change the seek progress , and the sample app I didn't change any code ,as you can see the screenshot [https://imgur.com/gallery/NuqJx](url) , maybe the youtube API changed?

**Comment by PierfrancescoSoffritti** [comment]
Oh wow, I have the same problem on Shuffly. Yeah, YouTube must have changed something T_T
bug fix coming soon, I hope.

**Comment by hiddow** [comment]
Thanks

**Comment by PierfrancescoSoffritti** [comment]
I can confirm that the YouTube API has changed, the method `getVideoData()` is not available anymore. Now we need to find an alternative way to know the video title.
YouTubeData API could solve this problem, but I'm not very keen to add that to the player.

**Comment by PierfrancescoSoffritti** [comment]
@hiddow @mdtuyen I have solve the problem. Version 2.0.0 of the library will work fine. I had to make a few breaking changes, so you will have to change a couple of lines in your code.
The video title is not automatically updated anymore. If you want to show it, you have to fetch it manually. See method `getVideoTitle()` in the [sample app ](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/sample/src/main/java/com/pierfrancescosoffritti/youtubeplayersample/MainActivity.java)for an example.

**Comment by VersanM** [comment]
What about the video duration?

**Comment by PierfrancescoSoffritti** [comment]
That's working fine as before.

**Comment by PierfrancescoSoffritti** [comment]
Now the library is using only documented method from the YouTube API, therefore overnight breaking chances like this won't happen anymore.
