### ISSUE TITLE
Hide player "Title,share button,etc " 

### ISSUE THREAD

**Issue by samatzhusup** [PierfrancescoSoffritti/android-youtube-player#550]
Mister Great Work ! how i can hide ? 

![WhatsApp Image 2020-04-16 at 10 05 54 PM](https://user-images.githubusercontent.com/50781959/79479691-f83fc080-802e-11ea-9cb3-0f327048ef3c.jpeg)

**Comment by PierfrancescoSoffritti** [comment]
You can't. The web player does not allow it.
