### ISSUE TITLE
OnReady doesnt call second time

### ISSUE THREAD

**Issue by shamshadpattani** [PierfrancescoSoffritti/android-youtube-player#554]

**Comment by shamshadpattani** [comment]
private fun init() {

			videoId=notes[0].id
				initYouTubePlayerView(videoId)
				initAdapter())
	}
	private fun initAdapter() {
		recycler_view.setHasFixedSize(true)
		val mLayoutManager: RecyclerView.LayoutManager = LinearLayoutManager(this)
		recycler_view.layoutManager = mLayoutManager
		mAdapter = VideoPlayerAdapter(notes)
		recycler_view.adapter = mAdapter
		mAdapter.setOnItemClickListener { adapter, view, position ->
			Toast.makeText(applicationContext,"click$position",Toast.LENGTH_SHORT).show()
//second time called a diffrenent video id  
			 initYouTubePlayerView(notes[position].id)
		}
	}
	
	
	private fun initYouTubePlayerView(videoId: String) {
		//initPlayerMenu();
		// The player will automatically release itself when the activity is destroyed.
		// The player will automatically pause when the activity is stopped
		// If you don't add YouTubePlayerView as a lifecycle observer, you will have to release it manually.
		lifecycle.addObserver(youtube_player_view);
		youtube_player_view!!.addYouTubePlayerListener(object : AbstractYouTubePlayerListener() {
			override fun onReady(youTubePlayer: YouTubePlayer) {
				youTubePlayer.loadOrCueVideo(lifecycle, videoId,0f)
				addFullScreenListenerToPlayer();
				setPlayNextVideoButtonClickListener(youTubePlayer)
			}
			
		})
		
	}

**Comment by shamshadpattani** [comment]
when i call the initYoutubeplayer in second time it doesn't work.

**Comment by PierfrancescoSoffritti** [comment]
You are supposed to init the player only once.
