### ISSUE TITLE
Showing white screen

### ISSUE THREAD

**Issue by TrickyShakil** [PierfrancescoSoffritti/android-youtube-player#556]
when i load a video only audio is playing.and the video is showing white screen and nothing else.It was working fine a few days ago.But not working now.

**Comment by PierfrancescoSoffritti** [comment]
Are you doing this on a real device? or emulator?

**Comment by TrickyShakil** [comment]
real device

**Comment by Qdafengzi** [comment]
> when i load a video only audio is playing.and the video is showing white screen and nothing else.It was working fine a few days ago.But not working now.

have you solve ？i have same problem

**Comment by TrickyShakil** [comment]
> > when i load a video only audio is playing.and the video is showing white screen and nothing else.It was working fine a few days ago.But not working now.
> 
> have you solve ？i have same problem

No.I couldn't solve it.i just switch to google official youtube player.
