### ISSUE TITLE
java.lang.IllegalStateException: This YouTubePlayerView has already been initialized.

### ISSUE THREAD

**Issue by hetsgandhi** [PierfrancescoSoffritti/android-youtube-player#557]
I am using the YouTubePlayerView in my recyclerview, so when the video id is repeated, i am getting this error. Please help me.

Thanks in advance.

**Comment by PierfrancescoSoffritti** [comment]
Clearly you are trying to initialise the same `YouTubePlayerView` multiple times. This is wrong. You should have a `YouTubePlayerView` for every item in your recyclerview.

**Comment by NaisargiPatel** [comment]
In my case, I have to use the same view to load different videos. Whatever user select URL from the recycler view, it should be loaded in the same video view. Can you please suggest how I can achieve it?

**Comment by Harsh0021** [comment]
how can we make youtube player for every recyclerView items?
It is dynamic.
Can we override the initialization or load video on the same initialization?
???????????????

**Comment by PierfrancescoSoffritti** [comment]
Just put one in every viewholder

**Comment by JalalMadhaji** [comment]
just put [ youTubePlayerView.initialize(...) ] inside try{}catch(){}.

the app crashes because it tries to initialize the YouTubePlayerView when it is already initialized, that because recycle view items lose focus after scrolling away.

**Comment by sarsdin** [comment]
use method: getYouTubePlayerWhenReady
I have solved :)

**Comment by devinspire-gitch** [comment]
Hi, @sarsdin 
Would you share the source code snippet for getYouTubePlayerWhenReady here?

**Comment by PierfrancescoSoffritti** [comment]
You can find it [in the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#1-youtubeplayerviewgetyoutubeplayerwhenready).

**Comment by jeffmoreta** [comment]
@JalalMadhaji No funciona para mi. necesito en la misma actividad cambiar de id del video, para cambiarlo según el id del video tomado de una base de datos. cómo puedo volver a inicializar el YouTubePlayerView, ayuda, estoy en Kotlin

**Comment by YudizAndroidMahek** [comment]
> I am using the YouTubePlayerView in my recyclerview, so when the video id is repeated, i am getting this error. Please help me.
> 
> Thanks in advance.

Hi

is there any update on this issue? i've been facing this issue with recycler view when notifyDataSetChange call happens then it is causing this issue. I am using separate player object for each item and also tried to catch this exception in try..catch block but nothing works for me

it would be very helpful if you have already found the solution for this.

**Comment by PierfrancescoSoffritti** [comment]
If that exception is thrown, it means you are trying to initialize a player that is already initialized. This is not supported by the library.

**Comment by dvd-castro** [comment]
i have de same problem, but i don`t use a RecyclerView, it`s a single activity with a single YouTubePlayerView.

```
class MyYouTubePlayerListener(
    private val ready: (youTubePlayer: YouTubePlayer) -> Unit
) : AbstractYouTubePlayerListener() {
    override fun onReady(youTubePlayer: YouTubePlayer) {
        ready(youTubePlayer)
    }
}

fun YouTubePlayerView.loadVideo(
    url: String,
    containerView: ViewGroup? = null,
    hideControls: Boolean = false,
    loading: (Boolean) -> Unit
) {
    try {
        val enableControls = if (hideControls) 0 else 1
        val iFramePlayerOptions = IFramePlayerOptions.Builder()
            .controls(enableControls)
            .fullscreen(enableControls)
            .autoplay(1)
            .build()

        enableAutomaticInitialization = false

        addFullscreenListener(object : FullscreenListener {
            override fun onEnterFullscreen(fullscreenView: View, exitFullscreen: () -> Unit) {
                setVisible(false)
                containerView?.addView(fullscreenView)
                context.setFullscreenAndRotate(
                    enable = true,
                    rotate = true
                )
            }

            override fun onExitFullscreen() {
                setVisible(true)
                containerView?.removeViewAt(1)
                context.setFullscreenAndRotate(
                    enable = false
                )
            }
        })

        initialize(
            MyYouTubePlayerListener {
                loading(false)
                it.cueVideo(url.getYoutubeVideoId(), 0f)
            },
            iFramePlayerOptions
        )
    } catch (ex: Exception) {
        loading(false)
        Log.d("ERROR_EXCEPTION", ex.message.orEmpty())
    }
}
```
