### ISSUE TITLE
how to remove youtube logo from iframe in player

### ISSUE THREAD

**Issue by prakashraooo** [PierfrancescoSoffritti/android-youtube-player#560]
modestbranding can remove youtube logo but i dont know how to use it in this player

**Comment by jbsplanetmutlu** [comment]
How to set modestbranding=0 ?

**Comment by mdakashhossain1** [comment]
You can use this lib to completely remove the logo of you tube https://github.com/mdakashhossain1/Android-YTPlayer.git
