### ISSUE TITLE
YouTubeThumbnailView not find

### ISSUE THREAD

**Issue by Qdafengzi** [PierfrancescoSoffritti/android-youtube-player#562]
When i have a long listview to display video , cueVideo founction cannot meet actual needs , I see youtube api have YouTubeThumbnailView  ,but i can not find in this project ,how can i use it ?

**Comment by Imran4424** [comment]
Follow these links 
I hope these will solve your problem

[https://stackoverflow.com/questions/8841159/how-to-make-youtube-video-thumbnails-in-android](Thumbnil generation using youtube url)

[https://stackoverflow.com/questions/2471935/how-to-load-an-imageview-by-url-in-android](ImageView set from url)

**Comment by Qdafengzi** [comment]
> Follow these links
> I hope these will solve your problem
> 
> [Thumbnil generation using youtube url](https://stackoverflow.com/questions/8841159/how-to-make-youtube-video-thumbnails-in-android)
> 
> [ImageView set from url](https://stackoverflow.com/questions/2471935/how-to-load-an-imageview-by-url-in-android)

thank you , i have do it
