### ISSUE TITLE
Customizing WebUI: how to disable three dot menu

### ISSUE THREAD

**Issue by kurkuteabhi** [PierfrancescoSoffritti/android-youtube-player#569]
Please know how to customize and disable three dot menu so share and watch later button goes disable. also it open youtube app when we tap on video title. please guide

![Screenshot_1590157775](https://user-images.githubusercontent.com/43174699/82678771-cc37e080-9c67-11ea-9570-43d706a65e95.png)

**Comment by faisalmushtaq007** [comment]
have you found the solution to this issue?

**Comment by kurkuteabhi** [comment]
Not Yet

**Comment by PierfrancescoSoffritti** [comment]
It's not possible to remove that button, the web player does not allow it.

**Comment by kurkuteabhi** [comment]
Thanks for your answer, I have done this by using Google's **YouTubeAndroidPlayerApi** Library
