### ISSUE TITLE
IDE works strangely

### ISSUE THREAD

**Issue by cnbcyln** [PierfrancescoSoffritti/android-youtube-player#571]
Hello there. First of all congratulations. Nice work. But I'm having a problem. I can't write code when I include the library in my project. IDE is starting to work strangely. The problem gets better when I remove the library. Could you help?

**Comment by cnbcyln** [comment]
No one to help? The problem persists. I cannot use AndroidX with this library in the same project.

**Comment by PierfrancescoSoffritti** [comment]
Can you share your build.gradle files?

**Comment by cnbcyln** [comment]
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'com.google.firebase.crashlytics'

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.cnbcyln.app.akordefterim"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0.1"
        multiDexEnabled true
        vectorDrawables.useSupportLibrary = true

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.keystore
        }
        debug {
            minifyEnabled false
            shrinkResources false
            useProguard false
            signingConfig signingConfigs.keystore
        }
    }

    lintOptions {
        abortOnError false
        disable 'MissingTranslation'
    }

    dexOptions {
        //Bu ayar android studio'nun bilgisayar ram'inde kullanacağı kapasiteyi belirler. Önemlidir. Aksi halde derleme yaparken hata verir.. (Can, bu sorunu çözmek için çok uğraştın ;))
        javaMaxHeapSize "6g"
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
    }
}

repositories {
    maven {
        url 'https://mymavenrepo.com/repo/ukAiuNSVkftQiB4kKUPH/'
        name 'FastLogin Repo'
    }
    mavenCentral()
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:cardview-v7:29.0.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.2.0'
    testImplementation 'junit:junit:4.13'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'androidx.core:core-ktx:1.3.0'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.2.2'
    implementation 'androidx.navigation:navigation-ui-ktx:2.2.2'
    implementation 'com.google.android.material:material:1.2.0-alpha06'
    implementation 'com.google.android.gms:play-services-safetynet:17.0.0'
    implementation 'com.google.android.gms:play-services-auth:18.0.0'
    implementation 'com.google.firebase:firebase-core:17.4.2'
    implementation 'com.google.firebase:firebase-analytics:17.4.2'
    implementation 'com.google.firebase:firebase-crashlytics:17.0.0'
    implementation 'com.google.firebase:firebase-messaging:20.2.0'
    implementation 'com.google.firebase:firebase-config:19.1.4'
    implementation 'com.facebook.android:facebook-android-sdk:7.0.0'

    // KOTLİN
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'org.jetbrains:annotations:19.0.0'

    // Dataların GET - POST işlemlerini yapan kütüphane
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Random sayı üretme
    implementation 'org.apache.commons:commons-lang3:3.10'

    // Turkcell Hızlı Giriş
    implementation 'com.turkcell.dssgate:dssgate-aar-beta:2.0.9'

    // JAVA MAIL API
    implementation 'com.sun.mail:android-mail:1.6.5'
    implementation 'com.sun.mail:android-activation:1.6.5'

    // Material TAB Strip
    implementation 'com.jpardogo.materialtabstrip:library:1.1.1'

    // Resim yükleme işleminde loader gösteren kütüphane
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'

    // TextInput Maskeleme
    implementation 'com.redmadrobot:input-mask-android:6.0.0'

    // Ülke telefon kodları kütüphanesi
    implementation 'com.hbb20:ccp:2.3.8'

    // Resim Kırma Kütüphanesi
    implementation project(path: ':ucrop')

    // https://github.com/t2314862168/uCrop-2.2.4

    //implementation 'com.yalantis:ucrop:2.2.0' // Hafifletilmiş versiyon

    //implementation 'com.yalantis:ucrop:2.2.0'

    // Görüntü kalitesini korumak için yerel kodun gücünü elde edin. (bir apk boyutuna yaklaşık 1,5 MB ekler)

    // Image Picker (com.github.yalantis:ucrop kütüphanesiyle birlikte kullanılır)
    implementation 'com.github.dhaval2404:imagepicker:1.7.1'

    // com.github.yalantis:ucrop kütüphanesini kullanmamdaki amaç, com.github.dhaval2404:imagepicker kütüphanesi kullanmı istiyor.

    // Ama ben projemin libs klasöründeki ucrop kütüphanesini kullanmak istiyorum. O yüzden mecburen ekledim..
    implementation 'com.github.yalantis:ucrop:2.2.4'

    // Satır İçi Activity Result'a ulaşabilmeyi sağlayan kütüphane
    implementation 'com.github.florent37:inline-activity-result:1.0.4'

    // Icon TextView (Textview'da istediğin her yere icon eklemeye yarayan kütüphane) https://github.com/AAkira/CompoundIconTextView
    implementation 'com.github.aakira:compound-icon-textview:1.2.1@aar'

    // Bubble SeekBar https://github.com/woxingxiao/BubbleSeekBar
    implementation 'com.xw.repo:bubbleseekbar:3.20'

    // Glide Android işletim sistemi için Bump Technologies tarafından geliştirilmiş resim, gif ve yerel video’ları

    // kolayca uygulamamıza dahil etmek, memory ve disk cache gibi olayları düşünmeden hızlıca uygulama geliştirmek

    // için geliştirilmiş açık kaynak bir kütüphanedir.
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.11.0'

    // SmoothProgress Bar (https://github.com/castorflex/SmoothProgressBar)
    implementation 'com.github.castorflex.smoothprogressbar:library:1.1.0'

    // Liste içindeki item'a sürükleme özelliği ekleyen kütüphane.. (https://github.com/chthai64/SwipeRevealLayout)

    //implementation 'com.chauthai.swipereveallayout:swipe-reveal-layout:1.4.1'

    // Harf sırasına göre dizilim yapan kütüphane. Sağ tarafa harf sıralaması ekler.. (https://github.com/myinnos/AlphabetIndex-Fast-Scroll-RecyclerView)
    implementation 'com.github.myinnos:AlphabetIndex-Fast-Scroll-RecyclerView:1.0.95'

    // FloatingActionButton (https://github.com/Clans/FloatingActionButton)
    //implementation 'com.github.clans:fab:1.6.4'

    // Facebook Shimmer Kütüphanesi (Form Görünümünde Loader)

    //implementation 'com.facebook.shimmer:shimmer:0.5.0@aar'

    // Youtube Player Kütüphanesi (https://developers.google.com/youtube/android/player?hl=tr)
    //implementation files('libs/YouTubeAndroidPlayerApi.jar')

    // Draggable View (View sürükleme kütüphanesi. Belirtilen view'i drag şeklinde sürükleyip bırakmaya yarar. STICKY özelliği vardır. https://github.com/hyuwah/DraggableView)
    implementation 'com.github.hyuwah:DraggableView:0.5.0'

    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5'

    implementation 'com.mikepenz:iconics-core:5.0.3'
    implementation 'com.mikepenz:iconics-views:5.0.3'
    implementation 'com.mikepenz:google-material-typeface:3.0.1.3.original@aar'
    implementation 'com.mikepenz:material-design-iconic-typeface:2.2.0.5@aar'

    //implementation 'net.steamcrafted:load-toast:1.0.12'

    // BOOM Floating Action Button (https://github.com/Nightonke/BoomMenu)
    implementation 'com.nightonke:boommenu:2.1.1'

    implementation 'org.apache.httpcomponents:httpcore:4.4.13'
    implementation 'org.apache.httpcomponents:httpmime:4.5.12'

    implementation 'com.skyfishjy.ripplebackground:library:1.0.1'
}

**Comment by cnbcyln** [comment]
I'm still waiting for help from you..

**Comment by PierfrancescoSoffritti** [comment]
I don't think I can help you. The problem likely not with the library.

**Comment by cnbcyln** [comment]
If you're not helping, why are you publishing a library?

**Comment by PierfrancescoSoffritti** [comment]
lol you're welcome

**Comment by cnbcyln** [comment]
lol.. What is the benefit of the library while I can't use it? Why should I thankful. ty

**Comment by oguzhan2142** [comment]
Same problem.When i import library ide's autocomplete not working.IDE giving me errors about code but there is no error actually.What should i do?
