### ISSUE TITLE
Is there any way we can show captions?

### ISSUE THREAD

**Issue by Imran4424** [PierfrancescoSoffritti/android-youtube-player#572]
Captions is really important for some videos for non native viewers.

I am trying to find a way in your API for caption showing.

 But I couldn't found any.

Is there any way we can show captions.
this will be great, if we have that information in documentation

**Comment by PierfrancescoSoffritti** [comment]
[Here](https://github.com/PierfrancescoSoffritti/android-youtube-player#ccloadpolicy).
