### ISSUE TITLE
Can we use this library without androidX?

### ISSUE THREAD

**Issue by priyankaHv** [PierfrancescoSoffritti/android-youtube-player#573]
Can we use this library without androidX?
I am trying to use in existing old project which have old support libraries which is not allow to change. it gives compatibility error.

**Comment by PierfrancescoSoffritti** [comment]
No, you need androidx.

**Comment by anjalsaneen** [comment]
This library is one of the few that are preventing us from turning off jetifier (which would be a big performance improvement). Are there any plans to upgrade to android?

if we were able to remove jetfier it would help us to improve our incremental build time.
https://adambennett.dev/2020/08/disabling-jetifier/
