### ISSUE TITLE
adding YoutubeListener

### ISSUE THREAD

**Issue by edoardo-tarnoczy** [PierfrancescoSoffritti/android-youtube-player#575]
Hi there, I'm trying to implement a recyclerview but the .addYoutubePlayerListener doesn't work. I can't find any listener that can handle this at all, the example code shows this

`static class ViewHolder extends RecyclerView.ViewHolder {
        private YouTubePlayerView youTubePlayerView;
        private YouTubePlayer youTubePlayer;
        private String currentVideoId;

        ViewHolder(YouTubePlayerView playerView) {
            super(playerView);
            youTubePlayerView = playerView;

            youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                @Override
                public void onReady(@NonNull YouTubePlayer initializedYouTubePlayer) {
                    youTubePlayer = initializedYouTubePlayer;
                    youTubePlayer.cueVideo(currentVideoId, 0);
                }
            });
        }`

how should I implement this?
Thank you

**Comment by PierfrancescoSoffritti** [comment]
I don't understand

**Comment by edoardo-tarnoczy** [comment]
> I don't understand

I'm trying to implement a Recyclerview of youtube videos following your code example, but when i call the .addYoutubePlayerListener method it is not found in the core library

**Comment by edoardo-tarnoczy** [comment]
Solved
