### ISSUE TITLE
while i play the video, i can only hear the audio and the display is black

### ISSUE THREAD

**Issue by faisalmushtaq007** [PierfrancescoSoffritti/android-youtube-player#580]
package com.rationaltabs.zeymal.DASHBOARD;

import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import androidx.annotation.NonNull;
import androidx.fragment.app.Fragment;

import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;
import com.rationaltabs.zeymal.R;

public class VIDEOS extends Fragment {
    private YouTubePlayerView videoView;
    private Button btn;
    public VIDEOS() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        final View OBJ = inflater.inflate(R.layout.fragment_videos, null);

        final String VIDEO_ID = "S0Q4gqBUs7c";
        btn = (Button) OBJ.findViewById(R.id.vid_button);
        videoView = (YouTubePlayerView) OBJ.findViewById(R.id.simple_vid);
        getLifecycle().addObserver(videoView);

        btn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                try {
                    videoView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                        @Override
                        public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                            youTubePlayer.loadVideo(VIDEO_ID, 0);
                        }

                    });
                }catch(Exception e){
                    Log.e("ERROR", e.getMessage());
                }
            }
        });

        return OBJ;
    }
    @Override
    public void onDestroy() {
        super.onDestroy();
        videoView.release();
    }
}

**Comment by hamzaaltaf** [comment]
it can be codec issue.

**Comment by faisalmushtaq007** [comment]
Done with this issue by add **android:hardwareAccelerated="true"** in the Manifest file, but in that activity that uses the player. This issue kept me on toes. Cheers!
