### ISSUE TITLE
Play with a variable String

### ISSUE THREAD

**Issue by irfanpa** [PierfrancescoSoffritti/android-youtube-player#582]
Instead of Using ID in xml, i need to play video using a variable string. I Have used the below method. But it is not working properly. Could you please check and advise?

public class Youtube_Test extends AppCompatActivity {

    String VIDEO_ID="TxAEDXd5yl4";
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_youtube__test);

        YouTubePlayerView youTubePlayerView = findViewById(R.id.youtube_player_view);
        getLifecycle().addObserver(youTubePlayerView);
        youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(YouTubePlayer youTubePlayer) {
                youTubePlayer.loadVideo(VIDEO_ID,0);

            }
        });
    }

}

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:showYouTubeButton="false"
        app:autoPlay="true"

        app:showFullScreenButton="false"/>

</LinearLayout>

**Comment by faisalmushtaq007** [comment]
is the player screen just black?
if so then add android:hardwareAccelerated="true" in the manifest file but in the tag of that particular activity, for example:
<activity
            android:name=".DASHBOARD.DASHBOARD"
            android:label="@string/title_activity_rdash_board"
            android:screenOrientation="portrait"
            tools:ignore="LockedOrientationActivity"
            **### android:hardwareAccelerated="true"**/>

**Comment by PierfrancescoSoffritti** [comment]
remove `app:autoPlay="true"` from your xml.

**Comment by luqman456** [comment]
I am using this player in recycleview with youtube video that I am receive from backend some it not play video and also not give any error or exception

**Comment by Smirky115** [comment]
> remove `app:autoPlay="true"` from your xml.

Is there a way to use a variable string for videoId and still have the video autoplay? 
From the UX perpective, it is adding an extra step.

**Comment by PierfrancescoSoffritti** [comment]
No, it's not possible at the moment.
