### ISSUE TITLE
Question : Does it have any Quota limit like the official API?

### ISSUE THREAD

**Issue by zafarsk227** [PierfrancescoSoffritti/android-youtube-player#587]
I want to know if there is any Quota limit like the official YouTube Android Player API.
I really wish it to not have any but if it has then what is the limit?

Thank You sooo much For this Great library.
It was really needed for my startup plan. You saved my cost of video hosting.
Thanks a Lot.

**Comment by PierfrancescoSoffritti** [comment]
The official YouTube player has no quota limit. This library has no quota limit.
