### ISSUE TITLE
I run the same code on different devices, but the resolution is different.

### ISSUE THREAD

**Issue by hijacker4163** [PierfrancescoSoffritti/android-youtube-player#589]
Device 1：Allwinner T3 - Android 4.4.3

Device 2：Allwinner H6 - Android 7.0

Run the same program code, use onPlaybackQualityChange get quality, Device1 can reach HD720, and Device2 can only reach LARGE.

What caused this?
WebView？
Screen resolution？（adb shell wm size is 1280x800）

Thanks for the reply!

**Comment by PierfrancescoSoffritti** [comment]
The web player decides the resolution, it's probably decided based on a combination of network speed and screen resolution.

**Comment by hijacker4163** [comment]
The network is the same. 
Does resolution determine hardware or system?

**Comment by PierfrancescoSoffritti** [comment]
I am just guessing, but screen resolution is probably part of it.
