### ISSUE TITLE
My youtube view only showing black screen and only audio is playing. I have upgraded the youtube player.

### ISSUE THREAD

**Issue by aarushmat** [PierfrancescoSoffritti/android-youtube-player#594]

**Comment by aarushmat** [comment]
It started working by adding android:hardwareAccelerated="true" in manifest

**Comment by scally-p** [comment]
Hi @PierfrancescoSoffritti great library. 
I'm however facing this issue even though i've added `android:hardwareAccelerated="true"` to my application tag. 

The video load. Audio plays. However there's no video. It's just a black screen. 
Kindly help.

Below is my xml if recyclerview item 
` <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
                android:id="@+id/youtubePlayerView"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />`

And here is the code in my adapter
`  fragment.lifecycle.addObserver(itemViewHolder.youtubePlayerView)
    itemViewHolder.youtubePlayerView.addYouTubePlayerListener(object :
        AbstractYouTubePlayerListener() {
                    override fun onReady(youTubePlayer: YouTubePlayer) {
                        super.onReady(youTubePlayer)
                        mainYouTubePlayer = youTubePlayer
                        mainYouTubePlayer?.cueVideo(currentVideoId ?: "", 0f)
                   }
      })`

**Comment by fantasticrahulrai** [comment]
I am also facing the same problem, is there a way to detect if the video plays with black screen. So that we can refresh the video.

**Comment by sergiambel** [comment]
We have same issue only with some users

**Comment by aarushmat** [comment]
Just try android:hardwareAccelerated="true" or check the ID of youtube link if put correctly.

**Comment by fantasticrahulrai** [comment]
hi dear, android:hardwareAccelerated = "true" doesn't solves the problem. Have already tried that with app level and activity level.


> Just try android:hardwareAccelerated="true" or check the ID of youtube link if put correctly.

**Comment by iut-cse-4301-mubahood** [comment]
> It started working by adding android:hardwareAccelerated="true" in manifest

THIS ONE WORKED FOR ME!!!!

**Comment by linkedintestapp2020** [comment]
I face the same issue and I try to add hardware accelerated by every way I can do, but it still cannot. Does there have anyone resolve that.

In MainActivity:
```java
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        youTubeView = findViewById(R.id.youtube_player_view);
        getLifecycle().addObserver(youTubeView);
        getWindow().setFlags(
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED,
                WindowManager.LayoutParams.FLAG_HARDWARE_ACCELERATED);
        youTubeView.setLayerType(View.LAYER_TYPE_HARDWARE, null);
    }
```

In Manifest:
```xml
      <application
        android:allowBackup="true"
        android:hardwareAccelerated="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        <activity
            android:hardwareAccelerated="true"
            android:name=".MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBar">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
```

My emulator choose `Graphics: Hardware - GLES 2.0`.

**Comment by amirdora** [comment]
android:hardwareAccelerated="true" doesn't work for me, testing on Android nexus 5x

**Comment by razzlakki** [comment]
> Just try android:hardwareAccelerated="true" or check the ID of youtube link if put correctly.

Works for me

**Comment by sanjaymanvani23** [comment]
android:hardwareAccelerated="true"

this solution is working for me

**Comment by jinjin-lee** [comment]
This solution is not working for me

**Comment by guiasos** [comment]
android:hardwareAccelerated="true" works for me

**Comment by PierfrancescoSoffritti** [comment]
Cools, seems like hardware acceleration does it.

It might not fix the problem on an emulator, but I suggest double checking on a real device.

**Comment by guiasos** [comment]
ok, I've already tested it on a real device and it's good. I'm using your
api to load videos into a feed, like instagram.
I have two questions if you can answer me:
1) can I get rid of related videos showing at the end of a video? the rel
option only has options to show from the same channel or from multiple, but
no option not to show.
2) sometimes when tapping on the video a shadow screen appears above the
video with some options like account, loop, copy url, copy code...Can I
prevent this from happening?

Em sex., 12 de ago. de 2022 às 02:33, Pierfrancesco Soffritti <
***@***.***> escreveu:

**Comment by PierfrancescoSoffritti** [comment]
> can I get rid of related videos showing at the end of a video? the rel
option only has options to show from the same channel or from multiple, but
no option not to show.

google's web player doesn't allow to remove that.

> sometimes when tapping on the video a shadow screen appears above the
video with some options like account, loop, copy url, copy code...Can I
prevent this from happening?

see #848
