### ISSUE TITLE
Video restart when mobile screen is rotated..

### ISSUE THREAD

**Issue by madhurkms** [PierfrancescoSoffritti/android-youtube-player#595]

**Comment by ritesh4302** [comment]
Any updates on this?

**Comment by PierfrancescoSoffritti** [comment]
You need to manually handle orientation changes.

**Comment by madhurkms** [comment]
Found solution
add this line -> android:configChanges="keyboardHidden|orientation|screenSize"
for ex: <activity android:name=".MainActivity"
            android:configChanges="orientation|screenSize">

**Comment by madhurkms** [comment]
> Any updates on this?

Found solution
add this line -> android:configChanges="keyboardHidden|orientation|screenSize"
for ex: <activity android:name=".MainActivity"
            android:configChanges="orientation|screenSize">
