### ISSUE TITLE
How to get current playtime of video?

### ISSUE THREAD

**Issue by stoddayy** [PierfrancescoSoffritti/Android-YouTube-Player#61]

**Comment by PierfrancescoSoffritti** [comment]
You need to add a [YouTubePlayerListener ](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayerListener.java)to the YouTubePlayer.
The method `onCurrentSecond `will periodically give the current playtime.

**Comment by stoddayy** [comment]
I'm using the YoutubePlayerView and can't see any method to add the player listener, am I just being blind or do I need to change something?

**Comment by stoddayy** [comment]
Found it cheers!
