### ISSUE TITLE
only audio is on, player not show video

### ISSUE THREAD

**Issue by MahmoudMabrok** [PierfrancescoSoffritti/android-youtube-player#617]
i tried with this video id "ddaSl1Vg-FA" and added it with sample app 
at `CompleteExampleActivity` and i can only hear sound but no video

**Comment by MahmoudMabrok** [comment]
@PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
Try using a real device instead of an emulator. If that doesn't work I have no idea. I've seen other people reporting this but it never happened to me.

**Comment by MahmoudMabrok** [comment]
@PierfrancescoSoffritti  thanks when i try with real device it works.
I suggest you add  **Common Issue section** in your **readme** and add all common issue such current one

**Comment by iut-cse-4301-mubahood** [comment]
I am using a real device but still only the audio is playing

**Comment by MahmoudMabrok** [comment]
@iut-cse-4301-mubahood  may videoID **invalid** or has **restrictions** 
try to use it with sample app code
