### ISSUE TITLE
Is there a way to control rel param in native player?

### ISSUE THREAD

**Issue by RyanVDW** [PierfrancescoSoffritti/android-youtube-player#618]
Is there a way to control `rel` param on native video player? I want to only show videos from the current youtube channel when using the native player?

**Comment by RyanVDW** [comment]
I might have found it, just want to clarify?

`        IFramePlayerOptions iFramePlayerOptions = new IFramePlayerOptions.Builder()
                .rel(0)
                .build();
        youtubePlayerView.initialize(this, true, iFramePlayerOptions);`

Is this the correct way to do this?

**Comment by PierfrancescoSoffritti** [comment]
correct!
