### ISSUE TITLE
How to detect when the user plays the video on YoutubePlayerView

### ISSUE THREAD

**Issue by akashmodak97** [PierfrancescoSoffritti/android-youtube-player#625]
I want to detect the onClick event, i.e., when the user taps on the YoutubePlayerView to play the video (by default, autoplay is set to false). Is there any listener regarding the same?

**Comment by UserI33X** [comment]
There is a listener for when player is playing or stopped aka paused.

**Comment by akashmodak97** [comment]
Okay thanks!
