### ISSUE TITLE
Full screen not working in fragment

### ISSUE THREAD

**Issue by akinfopark** [PierfrancescoSoffritti/android-youtube-player#629]
When I click fullscreen icon in fragment nothing happens only icon is changed to exit full screen icon.

**Comment by malliaridis** [comment]
I might not have contributed to the project or your issue yet, but could you provide more information? Like code for reproduction, device manufacturer and model, and android version?

**Comment by PierfrancescoSoffritti** [comment]
The library does not handle full screen logic. Each app has to do it the way they want.
