### ISSUE TITLE
FullScreenHelper gives the error "Usage of Kotlin internal declaration from different module"

### ISSUE THREAD

**Issue by raghavagg01** [PierfrancescoSoffritti/android-youtube-player#636]
![image](https://user-images.githubusercontent.com/49483235/94536571-591b2800-0260-11eb-96f4-8b52ce2ec43e.png)

**Comment by malliaridis** [comment]
Hey @raghavagg01, that seems understandable because the class you try to acces is not visible (declared internal aka. package private in java). This is probably for a reason. 

What do you try to achieve with the class instantiation?

**Comment by raghavagg01** [comment]
I have copied the code from CustomPlayerUiController.java file as i am trying to implement the Complete Youtube player in my android app.

**Comment by malliaridis** [comment]
Seems like you are importing classes from the wrong package.
I guess you are supposed to copy all the classes from the sample project to yours and import the copied classes. What you do however is importing the package private core classes.

In other words: 
Copy the class(es) from the [Core Sample App directory](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/utils) (in your case the [`FullScreenHelper.java`](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/utils/FullScreenHelper.java)) into your project under `utils` for exmaple, and then import your class from your project. I guess the core's [`FullScreenHelper.kt`](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/utils/FullScreenHelper.kt) class is for defaults purposes in case the developer does not want to implement customizations.

Hope that solves your problem. :)

**Comment by PierfrancescoSoffritti** [comment]
@malliaridis thanks for helping out! my bad for give the same name to internal and sample app class.

**Comment by raghavagg01** [comment]
Thanks for the help, Appreciated !
