### ISSUE TITLE
Hide Youtube related info

### ISSUE THREAD

**Issue by aman-agarwal15** [PierfrancescoSoffritti/android-youtube-player#642]
Hi,
I would like to know if there's a possibility of hiding the Video Title, controls on the top right, and the youtube button/icon on the bottom right? They usually pop up around the start of the video.

Hiding either of them would also do great help.
Thanks!

**Comment by malliaridis** [comment]
hey @aman-agarwal15, is your request related to [this comment](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/640#issuecomment-703249970)?

**Comment by aman-agarwal15** [comment]
> hey @aman-agarwal15, is your request related to [this comment](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/640#issuecomment-703249970)?

I think yes.
Is this a common issue or am I missing something?

**Comment by malliaridis** [comment]
No, I guess it was recently reported in other forms, but seems to be an important part that cannot be affected by this library (neither exists workarounds for that, since this comes from the Youtube API).

**Comment by aman-agarwal15** [comment]
Thanks for the information.
I hope they add a toggle for this 🤞🏻

**Comment by malliaridis** [comment]
It looks like there is already an update under review. See https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/640#issuecomment-703618250

**Comment by PierfrancescoSoffritti** [comment]
You can already enable webUi (see doc) to remove the native controls. Event after the new version is released you won't be able to remove the web controls, those are part of the web YouTube player.

**Comment by aman-agarwal15** [comment]
Yes, I think with the current YouTube API limitations, it is not possible to remove the web controls. Closing this issue for now.
