### ISSUE TITLE
Is it possible to slow down or speed up the videos?

### ISSUE THREAD

**Issue by fmiguelmmartins** [PierfrancescoSoffritti/android-youtube-player#645]
I noticed there is rate in the enum

 enum class PlaybackRate {
        UNKNOWN, RATE_0_25, RATE_0_5, RATE_1, RATE_1_5, RATE_2
    }

Is there a recommended way to set the playbackRate? (Sorry I am not a kotlin guy so I find it a bit hard to navigate in that code!)

Thanks!

**Comment by malliaridis** [comment]
Hello @fmiguelmmartins, there is already a ticket for this (#101) functionality. It might get into a major update soon if it is supported by the IFrame API (which probably is now the case).

**Comment by fmiguelmmartins** [comment]
Thanks for answering mate! That would be brilliant!

**Comment by Serkali-sudo** [comment]
i added video speed function in my fork : https://github.com/Serkali-sudo/android-youtube-player
