### ISSUE TITLE
Hide video title and video logo

### ISSUE THREAD

**Issue by kemaltunc** [PierfrancescoSoffritti/android-youtube-player#656]
Hello, I love using the library. I couldn't find a way to hide the Youtube video title and logo at the bottom right.

**Comment by malliaridis** [comment]
If you mean the title and youtube log like in https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/640#issuecomment-703249970 then there is no way to hide it. They are coming from the iFrame and cannot be removed.

**Comment by kemaltunc** [comment]
@malliaridis okey thank you.
