### ISSUE TITLE
If I use this library Can I use a YouTube clip?

### ISSUE THREAD

**Issue by JJJoonngg** [PierfrancescoSoffritti/android-youtube-player#657]
I want to know if only certain sections can be cut and used by time zone
And....
If I use that clip, Can my application be rejected from the Play Store?.....

**Comment by malliaridis** [comment]
Hello @JJJoonngg, you can simply add an `AbstractYouTubePlayerListener` and override the `onCurrentSecond` method. There you can stop your video at any time you want by comparing the current second passed as parameter with the value you want. The start time can be set in the `loadVideo` method of the `YouTubePlayer` together with the video id after you get an instance of the player. 

About the rejection of the Play Store, it should not be rejected as long as you don't try to to publish some kind of a  "YouTube app". That means as long as you just "embed" the youtube player in your app and the video playback is not the main and only feature of your app, it should be fine. However, we do not know how and why they could reject your app. 
So imho try it out and you will get a reason if it gets rejected.

**Comment by JJJoonngg** [comment]
@malliaridis 
Thanks A lot ;) I was so moved by your careful reply.
I'll give it a try and I'll give you another comment if it goes well. Thank you again!
