### ISSUE TITLE
Support Api16

### ISSUE THREAD

**Issue by tellfa** [PierfrancescoSoffritti/Android-YouTube-Player#66]
please support support api 16+

**Comment by PierfrancescoSoffritti** [comment]
This library runs on WebView, which is updated from the Play Store starting from Lollipop. Right now minSdk is KitKat, but I am considering to just increase it to Lollipop for that reason.
Therefore no, I'm sorry but this library won't support api 16. You can fork it and try to lower the minSdk if you need it.
