### ISSUE TITLE
loadVideo Not Working

### ISSUE THREAD

**Issue by gopaljain1st** [PierfrancescoSoffritti/android-youtube-player#664]
youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer)
            {
                String id="CbdJYCYAgtk";
                youTubePlayer.loadVideo(id,0);
            }
        });

i try to load this video but its not working always 
sometime it load this video or sometime it load default video

**Comment by imrankhanluhar** [comment]
I also getting same issue , some times video not able to load . when to close 3 4 time an Activity then video play .

**Comment by PierfrancescoSoffritti** [comment]
What do you mean with "default video"?

**Comment by aman9400** [comment]
> What do you mean with "default video"?

default video id which we provide in xml
Sometimes it plays the default video id which we provide in xml after 2-3 unsuccessful  attemps , it plays

**Comment by PierfrancescoSoffritti** [comment]
If you're using the library programmatically you should not set the video in the xml.
