### ISSUE TITLE
Rounded corners on player

### ISSUE THREAD

**Issue by Dreyar** [PierfrancescoSoffritti/android-youtube-player#666]
Is there any way to apply rounded corners to the player? I have tried setting it as background with no luck.

```
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="#FFFFFF" />

    <corners
        android:topLeftRadius="32dp"
        android:topRightRadius="32dp" />
</shape>
```

**Comment by AvaHayako** [comment]
Hi, I was able to do this using a FrameLayout with a rounded transparent image as it's foreground image. The selected answer for [this stackoverflow post](https://stackoverflow.com/questions/23300612/how-should-i-override-videoviews-ondraw-in-order-for-it-to-have-transparent-rou/23390070#23390070) should help you out.

**Comment by mkruglikov** [comment]
I made it work by using background with rounded corners and `android:outlineProvider="background"` on the playerView

```
 <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:id="@+id/playerView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:background="@drawable/bg_gray_rounded"
            android:outlineProvider="background" />
```

**bg_gray_rounded.xml**
```
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <corners android:radius="@dimen/default_corners_radius" />
    <gradient
        android:angle="0"
        android:endColor="#BBD1E1"
        android:startColor="#DAE3EA" />
</shape>
```
