### ISSUE TITLE
YouTubePlayerView doesn't go Full Screen

### ISSUE THREAD

**Issue by matteopasotti** [PierfrancescoSoffritti/android-youtube-player#667]
When i press the full screen button it doesn't go full screen.

I have also tried using addFullScreenListener and it goes into onYouTubePlayerEnterFullScreen, and also youtubeView.isFullScreen() returns true. So everything seems to say that yes the view is in full screen but it's not

I have also tried removing the margins and the bottom constraint but nothing

`<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
                    android:id="@+id/youtubeView"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_marginStart="@dimen/margin_medium"
                    android:layout_marginEnd="@dimen/margin_medium"
                    android:elevation="20dp"
                    app:layout_constraintBottom_toBottomOf="@+id/backdrop_image"
                    app:layout_constraintEnd_toEndOf="@+id/backdrop_image"
                    app:layout_constraintStart_toStartOf="@+id/backdrop_image"
                    app:layout_constraintTop_toTopOf="@+id/backdrop_image"
                    app:showYouTubeButton="true" />`

**Comment by j22purikas** [comment]
Did you find a solution for that? I have the same issue.

**Comment by matteopasotti** [comment]
Sorry for my late response, but yea i found it. Basically it seems that we have this issue when we are putting the YoutubeView inside a ConstraintLayout. I have created a fragment with a FrameLayout and the YoutubeView inside and everything works well.

Also if you check the code of the YoutubeView, when we press the full screen button the FullScreenHelper is forcing the layoutparams of the youtubeview to MATCH_PARENT. Maybe with the contraintlayout it does not allow it because of the contraints

**Comment by benni12er** [comment]
Fragment:

```
import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.Fragment
import at.bzdevelopment.trailbook.R
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView


class YoutubeFragment(val videoId: String) : Fragment() {
    private var youTubePlayerView: YouTubePlayerView? = null
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
        val view: View = inflater.inflate(R.layout.fragment_youtube, container, false)
        youTubePlayerView = view.findViewById(R.id.youtube_player_view)
        initYouTubePlayerView()
        return view
    }

    private fun initYouTubePlayerView() {
        lifecycle.addObserver(youTubePlayerView!!)
        youTubePlayerView!!.addYouTubePlayerListener(object : AbstractYouTubePlayerListener() {
            override fun onReady(youTubePlayer: YouTubePlayer) {
                youTubePlayer.cueVideo(videoId, 0f)
            }
        })
    }
}
```

In Adapter:

```
val newFragment: Fragment = YoutubeFragment(variation.youtube)
val ft: FragmentTransaction = activity.supportFragmentManager.beginTransaction()
ft.add(R.id.youtube_player_fragment, newFragment).commit()
```

Still nothing happens if i click on the fullscreen button
