### ISSUE TITLE
Error:(47, 39) No resource found that matches the given name (at 'layout_toStartOf' with value '@id/menu_button').

### ISSUE THREAD

**Issue by rmtic** [PierfrancescoSoffritti/Android-YouTube-Player#67]
Error:(47, 39) No resource found that matches the given name (at 'layout_toStartOf' with value '@id/menu_button').

**Comment by PierfrancescoSoffritti** [comment]
More info would be appreciated.

**Comment by rmtic** [comment]
Information:Gradle tasks [:app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources]
Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior.
/Users/admin/.android/build-cache/d9a53916bb72cdcb58ae16665211c9dd7d80d010/output/res/layout/player_controls.xml
Error:(47, 39) No resource found that matches the given name (at 'layout_toStartOf' with value '@id/menu_button').
/Users/qiu/git space/KUSDOM/app/build/intermediates/res/merged/debug/layout/player_controls.xml
Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by PierfrancescoSoffritti** [comment]
Should be solved in version 3.0.2!

**Comment by rmtic** [comment]
It can't run video。My Code:
@Bind(R.id.youtube_player_view)
YouTubePlayerView youtube_player_view;
.......

youtube_player_view.initialize(new YouTubePlayerInitListener() {
            @Override
            public void onInitSuccess(final YouTubePlayer initializedYouTubePlayer) {
                initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
                    @Override
                    public void onReady() {
                       // String vidoeId = YouTubeUrlParser.getVideoId(MyVideo.getUrl());
                        String vidoeId = "6JYIGclVQdw";
                        initializedYouTubePlayer.loadVideo(vidoeId, 0);
                    }
                });
            }
        }, true);

**Comment by PierfrancescoSoffritti** [comment]
Try to run the sample app. Just clone the github repo and run it. If it works there: you're doing something wrong in your project :)

**Comment by rmtic** [comment]
Thanks!
