### ISSUE TITLE
Is possible list all videos from a playlist link?

### ISSUE THREAD

**Issue by LukeDaniel16** [PierfrancescoSoffritti/android-youtube-player#674]
Hello, I am showing a playlist with a fragment, all right, but I was wondering if I can list all the videos in a playlist in some way, so the user can choose which video to go to instead of skipping one by one?

**Comment by mumenAlmadaineh** [comment]
New, I really need this feature

**Comment by Oclemy** [comment]
This library's responsibility is to play videos not to list them. The listing can be done in a recyclerview.
