### ISSUE TITLE
only audio plays not video

### ISSUE THREAD

**Issue by BhargavBhanshali** [PierfrancescoSoffritti/android-youtube-player#680]
Hi,
i have implemented this in my application. i want to play just video from youtube to direclty in my app.

 <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:layout_width="match_parent"
        android:layout_height="200dp"
        android:layout_below="@id/viewpager_header"
        android:layout_marginTop="8dp"
        app:videoId="dCiJCEyISno"
        app:autoPlay="false"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginBottom="8dp"
        android:id="@+id/viewpager_youTubePlayerView"/>

This is my XML code.

         youTubePlayerView = view.findViewById (R.id.viewpager_youTubePlayerView);
        getLifecycle().addObserver(youTubePlayerView);

This is my Java code.

it shows thumbnail and while click on play it plays only sound of that video.

pl help

**Comment by Renascienza** [comment]
@BhargavBhanshali Maybe your view is too small to reproduce video? Try increase it

**Comment by BhargavBhanshali** [comment]
> @BhargavBhanshali Maybe your view is too small to reproduce video? Try increase it

Thanks for reply.

It is not working in any size of view. I have tried "Wrap content" and "match-parent" and i have also manually increse the size of view but its not working.

**Comment by fantasticrahulrai** [comment]
Hi this is a common issue. Use hardwareAccelaration = true in your mainfest. This should solve the problem.

**Comment by BhargavBhanshali** [comment]
> Hi this is a common issue. Use hardwareAccelaration = true in your mainfest. This should solve the problem.

Thank you so much......

You saved my project.... Thanks again
