### ISSUE TITLE
The video frame hangs

### ISSUE THREAD

**Issue by myounis97** [PierfrancescoSoffritti/android-youtube-player#688]
The video frame hangs on all players some time here is a video show the case 

https://user-images.githubusercontent.com/43533983/103478398-1cb31700-4dcf-11eb-8d1b-8c2d51064a0a.mp4

**Comment by mohamedkhaledalizayed** [comment]
i have the same problem, did you found a solution?

**Comment by Priyanshi-Z** [comment]
i have the same problem, did you found a solution?
