### ISSUE TITLE
Violation Policy of YouTube

### ISSUE THREAD

**Issue by ManosPapadakis95** [PierfrancescoSoffritti/android-youtube-player#690]
Hello,

Google has contact me that using your package I was violating Youtubes policy about playing video. 

"We don’t allow apps that interfere with, disrupt, damage, or access in an unauthorized manner the user’s device, other devices or computers, servers, networks, application programming interfaces (APIs), or services, including but not limited to other apps on the device, any Google service, or an authorized carrier’s network.

Your app shouldn’t access or use the service or API in a manner that violates its terms of service. For example, your app shouldn't download, monetize, or access YouTube videos in a way that violates the YouTube Terms of Service."

I was just loading and playing the video... Google send me a screenshot playing the video and was just showing and ad that moment...

**Comment by PierfrancescoSoffritti** [comment]
Is it an ad from youtube or one of your ads?
Are you using web ui or native ui?

When using web ui the player is just the web player, so there are no potential issues there with YouTube terms of service.

But you can still infringe the term of service by things that you do in your app.

**Comment by ManosPapadakis95** [comment]
The ad is from youtube. Not mine, that is their problem. 
Ok I was using the default ui. I just read about the web i so I am gonna test it to check.
What to you mean by that? they send me a screenshot that was playing a video and that moment throw an ad.

**Comment by PierfrancescoSoffritti** [comment]
I mean that you can still infringe the TOS if you do things that are not allowed, for example playing a video while the player is hidden. Or showing ads in a way that they don't like.

But in this case i think that they're having issues with the default UI. I was planning on removing it but hadn't had time to release a new version of the library yet.

**Comment by ManosPapadakis95** [comment]
Ok yes you are right. I was frightend at that moment because I was showing a simple content without violating anything.  My only permission is the internet. thanks again.

**Comment by spapapan** [comment]
> But in this case i think that they're having issues with the default UI. I was planning on removing it but hadn't had time to release a new version of the library yet.

So from now on we can only use your library with app:useWebUi="true" ? 
Is there any way you can contact Android or Youtube's team to ask them what's wrong with the native UI?

**Comment by ManosPapadakis95** [comment]
I believe the problem with native is that is does not "block" ads. It is forbidden in an app to play youtube videos and ads in it.

**Comment by PierfrancescoSoffritti** [comment]
Native UI might cause problems because it alters the look of the youtube player. That said, i had an app for years live on the play store that was using it, and everything was fine.

To be 100% safe you should use web ui.

**Comment by spapapan** [comment]
> Native UI might cause problems because it alters the look of the youtube player. That said, i had an app for years live on the play store that was using it, and everything was fine.
> 
> To be 100% safe you should use web ui.

The problem is that the official Youtube library for android give's more customization abilities than the Embed Iframe version.  It's a pity that you made such a progress with your native version and they will just cancel it. We need to to something about this.

**Comment by Monabr** [comment]
Can we like contact Google support to new exactly what there are dislike?

**Comment by RunningTheSnail** [comment]
> 
I see your app has been removed, is it because of policy?
