### ISSUE TITLE
Cannot run sample app with error Task 'wrapper' not found in project ':core-sample-app'.

### ISSUE THREAD

**Issue by umanusorn** [PierfrancescoSoffritti/android-youtube-player#697]
Cannot run sample app with error Task 'wrapper' not found in project ':core-sample-app'.

btw, your sample app is wonderful (installed by 10.0.5.apk)

**Comment by umanusorn** [comment]
add

gradle-wrapper.properties

distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by georgiecasey** [comment]
You'll get this error if trying to open the sample project direct `(android-youtube-player/core-sample-app)` in Android Studio when you need to open the root project `(android-youtube-player)` and run the sample app from there.
