### ISSUE TITLE
Rejected from Google Play for library use

### ISSUE THREAD

**Issue by JakeSteam** [PierfrancescoSoffritti/Android-YouTube-Player#70]
Unfortunately I don't have many details, but I believe this library caused an app to be rejected from Google Play. 

Not sure which terms of service in particular was broken, just a heads-up.

> I reviewed [app], and had to reject it because it violates our device and network abuse policy. If you submitted an update, the previous version of your app is still live on Google Play.
> 
> Here’s how you can submit your app for another review:
> 
> * Your app shouldn’t access or use a service or API in a manner that violates its terms of service. For example, make sure your app doesn’t download, monetize, or access YouTube videos in a way that violates the [YouTube Terms of Service](https://www.youtube.com/t/terms).
> * Read through the Device and Network Abuse policy for more details and examples.
> * Make sure your app is compliant with all other policies listed in the Developer Program Policies. Remember that additional enforcement could occur if there are further policy issues with your apps.
> * Sign in to your Developer Console and submit your app.

**Comment by PierfrancescoSoffritti** [comment]
Hi, are you pausing the video when the player is not visible?
With this player is possible to keep the audio going even when the app is not in the foreground. But reproducing videos while not showing the video stream to the user is against their terms of services.

**Comment by JakeSteam** [comment]
Yep. It's in a recyclerview, and gets stopped as soon as it goes off-screen (for memory saving, but also to obey ToS). Might just be the reviewer making a mistake, have resubmitted.

Thanks for the prompt reply.

**Comment by PierfrancescoSoffritti** [comment]
Uhm, yeah it must be.
I have had an app on the store for more than year now. Also the library is basically a wrapper around the IFrame API, it shouldn't give any problem!
Keep me posted about the resubmission!!

**Comment by JakeSteam** [comment]
I have another (extremely similar) app using it, approved ~30 days ago, so who knows!

Will do, thanks for the excellent library.

**Comment by JakeSteam** [comment]
Resubmission was approved, thanks for your help.

**Comment by PierfrancescoSoffritti** [comment]
perfect :)

**Comment by pralgomathic** [comment]
I got the same reply from them. please suggest me what to do. I paused the video while screen goes of (with using broadcast receiver) 

> Your app shouldn’t access or use a service or API in a manner that violates its terms of service. For example, make sure your app doesn’t download, monetize, or access YouTube videos in a way that violates the YouTube Terms of Service.
Read through the Device and Network Abuse policy for more details and examples.
Make sure your app is compliant with all other policies listed in the Developer Program Policies. Remember that additional enforcement could occur if there are further policy issues with your apps.
Sign in to your Developer Console and submit your app.

**Comment by PierfrancescoSoffritti** [comment]
As Jake did, try to resubmit your app. The library by itself  does not violate YouTube terms of service. Let me know if they accept it or not.

**Comment by PierfrancescoSoffritti** [comment]
If they reject it again, send me your apk. Maybe your app is doing something wrong.

**Comment by pralgomathic** [comment]
check your mail..

**Comment by pralgomathic** [comment]
resubmit means, upgrade the apk or create new application (on play store)?

**Comment by PierfrancescoSoffritti** [comment]
I don't see any issue in your app. 
The app's name on the store may be problematic, it should be explicit that the app uses YouTube but is not affiliated to the company. What people usually do is to use this format for the name: app_name for YouTube, app_name for Reddit.. etc.

I'm not sure what do you have to do to resubmit an app, I have never done it. Maybe @JakeSteam can help with that.

**Comment by pralgomathic** [comment]
I've also received this message as well . What should be the reason , any idea? (I tried resubmitting with changing the name you suggested).. They also give me the below message (both times I submitted) Please help.

> rejected for violating our Malicious Behavior or User Data policy. If you submitted an update, the previous version of your app is still available on Google Play.This app uses software that contains security vulnerabilities for users or allows the collection of user data without proper disclosure.

**Comment by PierfrancescoSoffritti** [comment]
That doesn't look related to the library. Please use the issue section only for issues relevant to this library.

**Comment by pralgomathic** [comment]
yeah sure , as it's been related with my previous issue, I posted here. Please reply over mail if you can help me on that.

**Comment by pralgomathic** [comment]
changed app name, created new app, resubmitted and got rejection again! 😭😭

**Comment by pralgomathic** [comment]
for the same reason I've specified above..

**Comment by PierfrancescoSoffritti** [comment]
they're still saying you're violating the [YouTube Terms of Service](https://developers.google.com/youtube/terms/api-services-terms-of-service)? read them to understand if you're doing something wrong of not.

**Comment by pralgomathic** [comment]
I've added Banner and Video Ads, is it violating YouTube policy ?

**Comment by PierfrancescoSoffritti** [comment]
Idk about video ads. I have banners in Shuffly and never had a problem.

**Comment by pralgomathic** [comment]
I was appealed for reinstatement , they replied with "your app displays third party ads while YouTube video is playing"

**Comment by pralgomathic** [comment]
my app is live now, approved 😁
link to check : https://play.google.com/store/apps/details?id=com.grefeed.pralgomathic.youtubelivenow

**Comment by naseemali925** [comment]
@PierfrancescoSoffritti I Am facing the same issue. My app got rejected 2 times by play store. Could you please find some time to check my app? It would be a great help.

**Comment by PierfrancescoSoffritti** [comment]
@naseemali925 sure!

**Comment by naseemali925** [comment]
Should I Email You The App? Email Please.

**Comment by PierfrancescoSoffritti** [comment]
soffritti.pierfrancesco@gmail.com

**Comment by naseemali925** [comment]
Thanks. I Have Shared The Zip With You On Google Drive.

**Comment by PierfrancescoSoffritti** [comment]
Please, send me the apk, not the source code.

**Comment by naseemali925** [comment]
Shared The APK Now. Please Check It.

**Comment by PierfrancescoSoffritti** [comment]
The YouTubePlayerViews in the list are half covered. Also the playback doesn't stop when changing tab in the ViewPager.

Playing the audio without showing the video is against YouTube terms of service.

**Comment by naseemali925** [comment]
But As @JakeSteam Said. The Player Should Stop Itself When It Goes Of The Screen. As It Is Inside A Recycler View. Do I Need To manually Pause The Video?

**Comment by naseemali925** [comment]
I Will Make The Required Changes. Thanks For The Help.

**Comment by naseemali925** [comment]
@PierfrancescoSoffritti Thanks For All Your Help. My App Is Published Successfully Now.
https://play.google.com/store/apps/details?id=softpro.abhitak

**Comment by PierfrancescoSoffritti** [comment]
You're welcome :) good luck with your project!!

**Comment by Kostyshina** [comment]
Hello, thank you for your library, but I also have few questions about YouTube Terms of use and Developer Policy:
1. [Developer Policy](https://developers.google.com/youtube/terms/developer-policies) D.1.d - in that case you don't use any credentials so there is nothing that can be against the policy
2. [YouTube Terms of use](https://www.youtube.com/t/terms?gl=GB) - for some countries (not US) there is 5.1.C term that said that we cannot access content through any technology other than provided by YouTube. But in this case you just get `IFrame API` and put it in WebView so nothing violates the terms also
Am I correct on these two cases ?

**Comment by PierfrancescoSoffritti** [comment]
Yes, correct.

**Comment by androidovshchik** [comment]
As for me google play banned the app with this library
It's a pity but i think there is no yet solution

**Comment by PierfrancescoSoffritti** [comment]
@androidovshchik the library doesn't go against YouTube guidelines. If you want some feedback send me your apk, app name and package name.

**Comment by aavinashj** [comment]
Hey I have used this library and the videos I play in my app from a channel has been suspended because of it can you tell me about this . Is that even possible because if the library

**Comment by PierfrancescoSoffritti** [comment]
@aavinashj I don't understand, the videos have been suspended? Or the app?

**Comment by aavinashj** [comment]
The YouTube channel has been suspende

**Comment by naseemali925** [comment]
Hey @PierfrancescoSoffritti Could You Add My App In The Readme ?
Here Is The Link
https://play.google.com/store/apps/details?id=softpro.abhitak

**Comment by PierfrancescoSoffritti** [comment]
@aavinashj I'm sorry but this library has nothing to do with your channel, it must have been suspended for other reasons.

**Comment by PierfrancescoSoffritti** [comment]
@naseemali925 ok, I'll check out the app and see :)

**Comment by nicktz9** [comment]
Hello, I got the same issue in recent days. The official mentioned that we block the advertisement when the video is playing. I'm curious about the all advertisements are controlled by iFrame API why they still remove my APP from Google Play. Have you got this issue before? Thanks!

**Comment by PierfrancescoSoffritti** [comment]
> The official mentioned that we block the advertisement when the video is playing.

What does this mean?

Are you sure it's not about your own ads (admob etc)? I remember reading a rule about that in the terms of service.

**Comment by nicktz9** [comment]
They use a video with ad to compare my application with YouTube application and mentioned there is no ad on mine but YouTube APP has. I am confused about this violation. :(

My APP is 100% for free. There are no ads in my application.

**Comment by PierfrancescoSoffritti** [comment]
I suggest you reach out/re upload your app, sometimes Google Play makes mistakes. Let me know what happens.

**Comment by nicktz9** [comment]
Thank you! I will let you know if there is any update.
