### ISSUE TITLE
can we remove 3 dots from player

### ISSUE THREAD

**Issue by aniket-yadav** [PierfrancescoSoffritti/android-youtube-player#701]
For one of my project, Client has request for removing 3 dots in player and I don't know if it's possible can you please guide me

**Comment by PierfrancescoSoffritti** [comment]
Which three dots?

**Comment by aniket-yadav** [comment]
![Screenshot_20210205_133919 1](https://user-images.githubusercontent.com/30414261/107006976-e72b9000-67b7-11eb-9315-205bd543305e.jpg)

**Comment by PierfrancescoSoffritti** [comment]
https://github.com/PierfrancescoSoffritti/android-youtube-player#menu

**Comment by PierfrancescoSoffritti** [comment]
Is that the menu that is visible when the player is paused? if yes, not it's not possible to remove it. I would suggest switching to webUi, so it's clickable at least.
