### ISSUE TITLE
Bintray is shutting down on February 1st, 2022. Move to maven central by then.

### ISSUE THREAD

**Issue by arkon** [PierfrancescoSoffritti/android-youtube-player#703]
Could you consider publishing the existing artifacts to Maven Central?

cf. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by PierfrancescoSoffritti** [comment]
Yes, i'm aware of this. Looks like we have until Feb 1st, 2022 to take action.

**Comment by vishalkumarsinghvi** [comment]
Hey, @PierfrancescoSoffritti Any update for the new release with mavencentral?

**Comment by PierfrancescoSoffritti** [comment]
no, there is still plenty of time

**Comment by arkon** [comment]
This became the blocker for me for dropping jcenter, so for anyone else who's interested, you can use jitpack for consuming this library as well. e.g.:

```diff
- implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5'
+ implementation 'com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5'
```

**Comment by PierfrancescoSoffritti** [comment]
@arkon Why was it urgent for you to drop jcenter?

**Comment by arkon** [comment]
Not urgent; just generally try to complete migrations ASAP so that we can avoid last minute issues. I'd still be interested in consuming the library via Maven Central if possible.

**Comment by PierfrancescoSoffritti** [comment]
sure, thanks for letting me know :)

**Comment by DecodeIndustry** [comment]
> ```diff
> implementation 'com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5'
> ```

Thanks man its working in mavenCentral

**Comment by sgpentester** [comment]
> > ```diff
> > implementation 'com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5'
> > ```
> 
> Thanks man its working in mavenCentral

Hi @DecodeIndustry, how do you get it working with that `implementation`? 

I added the exact same `implementation` in my `build.gradle (:app)` file but it seems to be still having problem building my project:  

```
7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/PierfrancescoSoffritti/android-youtube-player/core/10.0.5/core-10.0.5.pom
       - https://repo.maven.apache.org/maven2/com/github/PierfrancescoSoffritti/android-youtube-player/core/10.0.5/core-10.0.5.pom
     Required by:
         project :app
```

**Comment by sgpentester** [comment]
Gradle is able to synchronize normally now after adding the new implementation statement, however, it is still not possible to build the project, or does anyone know how to fix this? I am unable to `Rebuild` my code. 

![image](https://user-images.githubusercontent.com/84804516/132088299-ac46080a-dd59-4d43-a6ad-be64fedc4910.png)

**Comment by sgpentester** [comment]
When I try to `Rebuild` my code, I get the following error message in my `Build Output`:

```
Could not GET 'https://repo.spring.io/plugins-release/com/github/PierfrancescoSoffritti/android-youtube-player/core/10.0.5/core-10.0.5.pom'. Received status code 401 from server: 
Disable Gradle 'offline mode' and sync project
```

I have already disabled my Gradle 'offline mode' though. **Or can someone share a working maven configuration to put in gradle file?** 

If I don't use the following configuration with the `https://repo.spring.io/plugins-release/` I do not even get a chance to get build my code:

```
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/plugins-release/" }
    }
```

If I remove `maven { url "https://repo.spring.io/plugins-release/" }` : 

```
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/github/PierfrancescoSoffritti/android-youtube-player/core/10.0.5/core-10.0.5.pom
       - https://repo.maven.apache.org/maven2/com/github/PierfrancescoSoffritti/android-youtube-player/core/10.0.5/core-10.0.5.pom
     Required by:
         project :app
```

But now I am struggling with the 401 error that I shared at the start of this comment. If anyone is able to help it will be great! Thanks.

**Comment by arkon** [comment]
As per my comment, it's from the JitPack repository, not Maven Central.

**Comment by PierfrancescoSoffritti** [comment]
You can read more here https://jitpack.io/

**Comment by sgpentester** [comment]
Thanks @arkon & @PierfrancescoSoffritti for the prompt response, it really helps and works like a charm!!

**Comment by PierfrancescoSoffritti** [comment]
Hi everyone, thanks for your patience. [Version 11.0.0 is out](https://github.com/PierfrancescoSoffritti/android-youtube-player/releases/tag/11.0.0) and now the library is available [on MavenCentral](https://repo1.maven.org/maven2/com/pierfrancescosoffritti/androidyoutubeplayer/) :)

**Comment by abubakarasifmughal** [comment]
> This became the blocker for me for dropping jcenter, so for anyone else who's interested, you can use jitpack for consuming this library as well. e.g.:
> 
> ```diff
> - implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5'
> + implementation 'com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5'
> ```

This worked for me.
My complete file looks like this

```
apply plugin: "com.android.library"

def DEFAULT_COMPILE_SDK_VERSION = 28
def DEFAULT_BUILD_TOOLS_VERSION = "28.0.3"
def DEFAULT_TARGET_SDK_VERSION = 28
def DEFAULT_MIN_SDK_VERSION = 21

android {
    compileSdkVersion rootProject.hasProperty('compileSdkVersion') ? rootProject.compileSdkVersion : DEFAULT_COMPILE_SDK_VERSION
    buildToolsVersion rootProject.hasProperty('buildToolsVersion') ? rootProject.buildToolsVersion : DEFAULT_BUILD_TOOLS_VERSION

    defaultConfig {
        minSdkVersion rootProject.hasProperty('minSdkVersion') ? rootProject.minSdkVersion : DEFAULT_MIN_SDK_VERSION
        targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
        versionCode 1
        versionName "1.0"
    }

    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility = '1.8'
        targetCompatibility = '1.8'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}

dependencies {
    // implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5'
    implementation 'com.github.PierfrancescoSoffritti.android-youtube-player:core:10.0.5'
    implementation 'com.facebook.react:react-native:+'
}

```

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Why use an old version from jitpack instead of latest from maven?
