### ISSUE TITLE
"Unrecognized feature: 'picture-in-picture'

### ISSUE THREAD

**Issue by sumeetbhut** [PierfrancescoSoffritti/android-youtube-player#704]
I/chromium: [INFO:CONSOLE(629)] "Unrecognized feature: 'picture-in-picture'.", source: https://www.youtube.com/s/player/6eebf7aa/www-widgetapi.vflset/www-widgetapi.js (629)

**Comment by dohakash** [comment]
@sumeetbhut Did you figure out this problem?

**Comment by ajit-sharma** [comment]
I am also getting the same issue.
I can hear the audio but video is not rendering.

Tested on Android Motorola Moto G (5) Plus Android 8.1.0, API 27
And Samsung SM-M315F Android 12, API 31

**Comment by PierfrancescoSoffritti** [comment]
Have you enabled hardware acceleration in your apps? [https://github.com/PierfrancescoSoffritti/android-youtube-player#hardware-acceleration](see doc.)

**Comment by ajit-sharma** [comment]
> Have you enabled hardware acceleration in your apps? [see doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#hardware-acceleration)

Yes, And now its working. Thanks.

**Comment by AbdurRehman-coder** [comment]
How to add this hardware acceleration into Manifest file, could please share the screenshot of Manifest file, I am adding it into flutter application.
