### ISSUE TITLE
Please add example with viewpager2

### ISSUE THREAD

**Issue by Miteshmakwana73** [PierfrancescoSoffritti/android-youtube-player#705]
Please add an example with viewpager2 and manage its state and play next video if current finished

it'll be very useful for everyone

**Comment by AbdullahLatif1** [comment]
Please add an example with viewpager2 and manage its state and play next video if current finished

it'll be very useful for everyone

**Comment by PierfrancescoSoffritti** [comment]
Hi, we already have an example view view pager v1, you can take example from that one.
