### ISSUE TITLE
How to not show option on long press of player

### ISSUE THREAD

**Issue by Miteshmakwana73** [PierfrancescoSoffritti/android-youtube-player#708]
@PierfrancescoSoffritti 

getting this on long-press of player view is there any way to avoid this? 
**or**
any way to hide progress bar when `app:useWebUi="false"`

![device-2021-02-23-152024](https://user-images.githubusercontent.com/38969602/108826900-f2b9ec00-75ea-11eb-8c46-20762748134b.png)

tried this to avoid long press but didn't work
```
youtube_player_view.setOnLongClickListener {
            false
        }
```

some times it also appear while swiping view pager

**Comment by luciferz111** [comment]
@Miteshmakwana73 did you find any workaround I am also facing same issue while scrolling in recyclerview. I am using the customised Iframe version of the player

**Comment by Miteshmakwana73** [comment]
@luciferz111 didn't find any solution so I disable web UI just for this issue

**Comment by t7ank** [comment]
I have noticed the same behavior, when used in Recyclerview. Did not fix a fix yet.

**Comment by PierfrancescoSoffritti** [comment]
Hi, please see #848.
