### ISSUE TITLE
Custom Icon Alignment

### ISSUE THREAD

**Issue by puliajay43** [PierfrancescoSoffritti/android-youtube-player#711]
I have implemented custom icons for play/pause. But they are not center aligned which is like this <br>
![1614662825929](https://user-images.githubusercontent.com/35003996/109602813-d5cf6c80-7b46-11eb-89d2-d6a4de023bb4.jpg)
<b>How to set that custom button to center aligned.</b>

**Comment by PierfrancescoSoffritti** [comment]
Since it's your custom layout, that's up to you. You do it in the same way as you would in a regular view.

**Comment by puliajay43** [comment]
> Since it's your custom layout, that's up to you. You do it in the same way as you would in a regular view.

I am using the methods setCustomAction1() and setCustomAction2(). Not a custom views it's custom icons

**Comment by PierfrancescoSoffritti** [comment]
custom actions are not centred by design. More appropriate names should have been `setCustomActionRight` and `setCustomActionLeft`

**Comment by puliajay43** [comment]
> custom actions are not centred by design. More appropriate names should have been `setCustomActionRight` and `setCustomActionLeft`

Okay, Thank you
