### ISSUE TITLE
Playing sound but not the video? Api level 24

### ISSUE THREAD

**Issue by amirdora** [PierfrancescoSoffritti/android-youtube-player#714]
There are many issues on this problem. Some users suggest setting `HardwareAcceleration` to `true` solves the problem. But on some devices still the issue exists. Can you please look into this issue.

**Comment by vancuong0429** [comment]
I have the same problem on android 8

**Comment by PierfrancescoSoffritti** [comment]
That's a known issue, on some emulators. Try using a real device.

**Comment by vancuong0429** [comment]
yes, Thanks
