### ISSUE TITLE
context menu pops when scrolling the video player by touching it

### ISSUE THREAD

**Issue by luciferz111** [PierfrancescoSoffritti/android-youtube-player#718]
Hi @PierfrancescoSoffritti can you please help me disable the context menu, I am facing this weird issue on some devices where the context menu pops up when trying to scroll the page with player view.
Steps to reproduce:

1. Place the player in either scroll view or recycler-view
2. Scroll the page by touching the player (even the slightest scroll will do)
3. Notice that the context menu pops up

**Expected Behaviour:** The context menu should pop up only when the player is long pressed

**Comment by t7ank** [comment]
I have noticed the same behaviour, when used in Recyclerview. Did not fix a fix yet.

**Comment by PierfrancescoSoffritti** [comment]
Hi, please see #848.
