### ISSUE TITLE
Add support for showing captions

### ISSUE THREAD

**Issue by pralgomathic** [PierfrancescoSoffritti/android-youtube-player#72]

**Comment by PierfrancescoSoffritti** [comment]
I have tried to do that in the past but I encountered limitations in the YouTube IFrame APIs.

Feel free to investigate, pull requests are welcome.

**Comment by Trusted97** [comment]
I'm looking for the same problem and like you i've no solution, but i discover that the caption button on video id generate an [xml file ](https://www.youtube.com/api/timedtext?expire=1530636770&hl=it_IT&v=SXiSVQZLje8&signature=05E3790C49E3BDD66419C149E85C71AA4EAC45E3.6FA298C0BE73457D0305751DEEE1C16F135A56E6&sparams=caps,v,expire&caps&key=yttt1&lang=en&fmt=srv3) and maybe if we discover the post parameters that use we can emulate and then parse the xml file for get the caption?

**Comment by PierfrancescoSoffritti** [comment]
The like gives a 404 error.

**Comment by Kostyshina** [comment]
Also I have found that for loading captures `loadModule` can be used. Please check out [this topic](https://stackoverflow.com/questions/13735783/youtube-api-how-to-use-custom-controls-to-turn-captions-on-off-change-languag) and let me know what you think about it

**Comment by Kostyshina** [comment]
Didn't tried it yet, but will try

**Comment by PierfrancescoSoffritti** [comment]
Great, let me know :)

**Comment by Kostyshina** [comment]
Finally achieved captions, everything works on my Oneplus with API=27:
1. First of all you need to `loadModule` in `onStageChange`
```
function sendPlayerStateChange(playerState) {
    ...
    player.loadModule('captions')
    ...
    switch(...) {...}
}
```
2. To get track list we need to do `getOption` with needed option on `captions` module. We also need to place it into playing, because nothing is available before playing:
```
function sendVideoData(player) {
    ...
    var tracks = player.getOption('captions', 'tracklist')
    sendVideoCaption(tracks) //with this method I'm just recreate JSONArray to send it to the 
                                              //YouTubePlayerBridge, because in tracklist there are a lot of data
    ...
}
```
3. To change or turn off we can do something like this:
```
function showSubtitles(languageCode) {
    var code = languageCode !== "null" ? {"languageCode": languageCode} : {}
    player.setOption('captions', 'track', code);
}
```
The only problem I have that `tracklist` is empty, so I needed to wrap 2. and body of `sendVideoCaption` into  setTimeout(() => {..., 100} with min value. My methods where executed before other code. I don't know javascript so can't tell why it happened

**Comment by PierfrancescoSoffritti** [comment]
that's great!! do you mind pushing this changes to your fork of the library? I'd like to try the project to test it! thanks!!

**Comment by PierfrancescoSoffritti** [comment]
If everything works fine you could send a pull request, after I've tested the changes :)

**Comment by PierfrancescoSoffritti** [comment]
yeah, no worries 👍

**Comment by mankidal19** [comment]
Hi.
Any solution/workaround for this issue?
Would be interesting to be implemented.

**Comment by PierfrancescoSoffritti** [comment]
Hey, I haven't had time to look into it yet. @mankidal19, feel free to explore @Kostyshina suggestions, pull requests are welcomed.

**Comment by PierfrancescoSoffritti** [comment]
Thanks to @ct7ct7ct7 captions are now supported. The option will be available in the next release.
