### ISSUE TITLE
FullScreen Android-youtube-Player

### ISSUE THREAD

**Issue by sevennguyen** [PierfrancescoSoffritti/android-youtube-player#725]
Hi , 
I have a issue with button fullScreen , i set fullscreen video in one fragment, when i try to click button fullscreen, it video is still landscape , but it is not fullscreen , video is just width :  match_parent, and height is a half of screen phone.
one thing is function enterfullscreen in FullScreenHelper, inside function, all View.SYSTEM_UI_FLAG_LAYOUT_STABLE is dedicated. 

I looking foward to your answer, and thank you so much. 
![1](https://user-images.githubusercontent.com/31762027/113372730-85406e80-9393-11eb-8b88-e3141f514eac.png)

**Comment by Areyana** [comment]
+, same issue

**Comment by PierfrancescoSoffritti** [comment]
Hi, the lib doesn't handle full screen. You need to write your own logic.
