### ISSUE TITLE
Migrate to MavenCentral

### ISSUE THREAD

**Issue by ArcherEmiya05** [PierfrancescoSoffritti/android-youtube-player#726]
JCenter will be soon shutdown, may you move this library to Maven Central? 

Thank you

**Comment by ArcherEmiya05** [comment]
Just saw that there is a fork for that. Closing this now

**Comment by PierfrancescoSoffritti** [comment]
Hey, which fork are you referring to?

**Comment by ArcherEmiya05** [comment]
https://github.com/firozanawar/Android-YouTube-Player

**Comment by PierfrancescoSoffritti** [comment]
That's just an old version of the library. I suggest you follow issue #703

**Comment by ArcherEmiya05** [comment]
![image](https://user-images.githubusercontent.com/38008900/116675847-d9f9f800-a9d8-11eb-907e-bc32f1c84947.png)

Have you seen this?

**Comment by PierfrancescoSoffritti** [comment]
again, please look at issue #703

**Comment by ArcherEmiya05** [comment]
Yeah already read that, you mean are we going to wait till that date?

**Comment by PierfrancescoSoffritti** [comment]
I mean there is not rush at the moment.

**Comment by ArcherEmiya05** [comment]
Ok ok thanks
