### ISSUE TITLE
How to set showYouTubeButton() programmatically

### ISSUE THREAD

**Issue by karimsinouh** [PierfrancescoSoffritti/android-youtube-player#729]
Hi, I'm adding the YoutubePlayerView to my activity programmatically not in xml file, and I want to hide the Youtube button and access some of the xml properties, but I can't find them programmatically.

**Comment by MagicDog707** [comment]
Hi, you could find the fullscreen imageview by its id that is "fullscreen_button" and then remove it with visibility.gone:

`youTubePlayerView.findViewById<ImageView>(R.id.fullscreen_button).visibility = View.GONE`

**Comment by karimsinouh** [comment]
Thank you so much, I appreciate it <3
