### ISSUE TITLE
seekbar progressing even if you play live videos

### ISSUE THREAD

**Issue by pralgomathic** [PierfrancescoSoffritti/Android-YouTube-Player#73]

**Comment by PierfrancescoSoffritti** [comment]
Hi, what do you mean exactly? the progress bar should always be at the end. It isn't?

**Comment by pralgomathic** [comment]
Observe Default Youtube player or Youtube API playerview, if you play a live video there's no seekbar exists. For live videos there should be no seekbar on the view.

**Comment by PierfrancescoSoffritti** [comment]
Right. This will be fixed in the next version of the library.
