### ISSUE TITLE
Cannot get any video to load

### ISSUE THREAD

**Issue by curiousbee2020** [PierfrancescoSoffritti/android-youtube-player#730]
I've followed the instructions and checked and doublechecked, but each video I try to load onClick a button, keeps loading forever and never plays. I've also overridden the onError method and do not get any errors. Each of these videos loads fine the first time I install the app on a device, but every time I re-run the app, the video doesn't load. The same videos play fine on youtube. Tried uninstalling and reinstalling the app, same outcome. At my wit's end - what may I be missing? Logcat doesn't show any useful errors. Just an occasional "Application attempted to call on a destroyed WebView".

**Comment by PierfrancescoSoffritti** [comment]
I suggest you take a look at the sample app.

**Comment by curiousbee2020** [comment]
Thanks Pierre, this is a great library! Appreciate your responses to issues, as well.
