### ISSUE TITLE
Flicker/Glitch and non interactive controls

### ISSUE THREAD

**Issue by ArcherEmiya05** [PierfrancescoSoffritti/android-youtube-player#731]
Device: Xiaomi Redmi Note 5
OS: Android L

Issues:

- Glitches/Flickers while playing on some video. So far it only happens on this device, not sure why.

- The suggestion list during pause is not clickable.

Footage sample: https://www.youtube.com/watch?v=MrXQggQlenM

![Screenshot_2021-05-01-02-17-00-042_com devsbitwise cryptonian](https://user-images.githubusercontent.com/38008900/116737658-0ab34f00-aa24-11eb-91a9-133a9d43a16e.png)
![Screenshot_2021-04-30-18-57-22-570_com devsbitwise cryptonian](https://user-images.githubusercontent.com/38008900/116737669-10109980-aa24-11eb-9130-003347a930b3.png)

![Screenshot_2021-04-30-18-38-53-971_com happyluck crypto app](https://user-images.githubusercontent.com/38008900/116737639-04bd6e00-aa24-11eb-9aa8-095384267c9b.png)

![Screenshot_2021-04-30-18-39-13-720_com happyluck crypto app](https://user-images.githubusercontent.com/38008900/116737590-fcfdc980-aa23-11eb-9f1a-d21b74c1b9fb.png)

**Comment by PierfrancescoSoffritti** [comment]
You should enable `webUi` to interact with that UI.

**Comment by ArcherEmiya05** [comment]
Oh so is this all I need to add `app:useWebUi="true"`?

**Comment by PierfrancescoSoffritti** [comment]
Yes
