### ISSUE TITLE
jcenter is deprecated

### ISSUE THREAD

**Issue by Mika-89** [PierfrancescoSoffritti/android-youtube-player#733]
Hello,
I just want to inform you that `jcenter` is deprecated.
You should migrate the library to `maven central`.

The official warning from android studio is following:    
`JCenter is at end of life`

> Please remove usages of `jcenter()` Maven repository from your build scripts and migrate your build to other Maven repositories.
> This repository is deprecated and it will be shut down in the future.
> See http://developer.android.com/r/tools/jcenter-end-of-service for more information.

You should also update the library depencies to the latest ones.

**Comment by PierfrancescoSoffritti** [comment]
dup of #703
