### ISSUE TITLE
How to set the developer  key in the project 

### ISSUE THREAD

**Issue by AdityaABP** [PierfrancescoSoffritti/android-youtube-player#735]
I am unable to find a method to set the developer key in the project. Please suggest. In the Youtube library, we sent the developer key at the time of initialization of youtubeplayerview object.

**Comment by PierfrancescoSoffritti** [comment]
It's not needed.

**Comment by superdiazzz** [comment]
I need this info too. We need to track user who watch from apps source. The data is important for content creator

**Comment by erik-everardo** [comment]
Any news on this? I need to use an api key to track who watches from the app

**Comment by PierfrancescoSoffritti** [comment]
There is not developer key for the IFrame player, as far as I know.
