### ISSUE TITLE
Age-restricted error

### ISSUE THREAD

**Issue by gonzalomonzon02** [PierfrancescoSoffritti/android-youtube-player#736]
First things first, this library is very good! thanks for that!
There are some YouTube videos that are age restricted and the player does not work.

![Captura de Pantalla 2021-05-12 a la(s) 15 12 08](https://user-images.githubusercontent.com/45593771/118024534-2e846800-b335-11eb-8ed3-6b01aa82d00f.png)

Video: 
https://www.youtube.com/watch?v=LQRAfJyEsko
Could do you please help me? 
Thanks a lot!

**Comment by PierfrancescoSoffritti** [comment]
There's not much to do, YouTube doesn't allow embedded players to play those videos. I assume because it's not possible to log in.

**Comment by PierfrancescoSoffritti** [comment]
I suggest you enable webUi on the player, so the user can click those links.
