### ISSUE TITLE
Android Media route button takes very long time to activate when using Fragment!

### ISSUE THREAD

**Issue by netchild76** [PierfrancescoSoffritti/android-youtube-player#737]
Hi All, 
I am using both android-youtube-player and android-Chromecast-sender libraries in my android app. When I use the cast button (Media Route Button) in my Activity to cast the video to my Google Chromecast device, it works with no issue at all. That means the cast button discovered the receiver successfully. Nevertheless, it does not work or works, but after a very long time, I use Fragment with navigation instead of Activity!!
General observation, I built two versions of the same app, one based on Activity and the second based on Fragment. To establish the connection with my Google Chromecast device immediately (the Cast Button discover the receiver), I usually run the Fragment version then switch to the Activity version or any other app then back to the Fragment version; by doing so, the Cast Button on the Fragment version becomes visible, and the casting works fine!!
Any thoughts? And Help is highly approicated.

**Comment by PierfrancescoSoffritti** [comment]
Hi, i don't think the delay you're experiencing has anything to do with the library.
