### ISSUE TITLE
mavenCentral() support

### ISSUE THREAD

**Issue by tjdam007** [PierfrancescoSoffritti/android-youtube-player#739]
Android Studio 4.2 suggests change jcenter() to mavenCentral(). Will mavenCentral() be supported at future updates?

https://developer.android.com/studio/build/jcenter-migration

**Comment by Kevinrob** [comment]
You can use [JitPack](https://jitpack.io/#PierfrancescoSoffritti/android-youtube-player/10.0.5)

**Comment by PierfrancescoSoffritti** [comment]
see #703
