### ISSUE TITLE
Play Playlist or Trigger onVideo end method

### ISSUE THREAD

**Issue by nowfalsalahudeen** [PierfrancescoSoffritti/Android-YouTube-Player#74]
How can i trigger onVideoEnd method..
or provide support for playing Playlist

**Comment by PierfrancescoSoffritti** [comment]
Hi, the state change corresponding to a video's end is automatically fired when the playback of the video reaches the end.
You can play a list of videos simply playing a new video when the current video is over.

Implement [this interface](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayerListener.java) and listen for the "ENDED" event in the `onStateChanged `method.
