### ISSUE TITLE
Orientation save time that was played

### ISSUE THREAD

**Issue by dev-lester94** [PierfrancescoSoffritti/android-youtube-player#744]
Is there a way to save the time that has been played so far in the video and when the device orientates it will load back the time that was saved and load that video at that second?

**Comment by dev-lester94** [comment]
1. Make a new youTubeTracker and add that as a listener to youtubePlayer 
 2. Save the tracker videoId and tracker.currentSEcond into the outState Bundle and a boolean to tell if you have made an orientaiton
 3. Check to see if you are orientating, if yes then get back the videoId and the currentSeconds from the savedInstanceState nundle in onCreateView (fragment) and loadback the video back onto the youtubePlayer

**Comment by dev-lester94** [comment]
I guess my next though is that is there a way to not load the video back when the device orientates. Youtube right now makes it so that the video keeps playing when the device orientates

**Comment by PierfrancescoSoffritti** [comment]
The library doesn't handle orientation changes. If you destroy your Activity on orientation change, it's up to you to save the time and seek the player to it after.
