### ISSUE TITLE
can you hide all controls ?

### ISSUE THREAD

**Issue by mariuspena** [PierfrancescoSoffritti/android-youtube-player#746]
hi. 

I could not find a way to hide web ui, native ui and every other buttons that come with youtube or this library. 
Can someone tell me how ?
I will need to control playback programatically.

thank you

**Comment by PierfrancescoSoffritti** [comment]
you can't disable web ui. but you can disable native ui, which i suggest you do. add `webUi=true` to your YouTubePlayerView.
