### ISSUE TITLE
How to solve this problem?Because certain video can't play outside of youtube

### ISSUE THREAD

**Issue by hafiz013** [PierfrancescoSoffritti/android-youtube-player#750]
![WhatsApp Image 2021-06-16 at 1 30 34 PM](https://user-images.githubusercontent.com/6707224/122165112-53c34380-ceaa-11eb-856c-2b5e7bdbf102.jpeg)

**Comment by Oclemy** [comment]
This typically gets shown when the owner of the video did not allow embedding of the video. You need to contact the owner of the video and ask him/her to allow their video to be embedded on other devices.
