### ISSUE TITLE
Ads showing while app used in USA

### ISSUE THREAD

**Issue by jaypatel9912** [PierfrancescoSoffritti/android-youtube-player#751]
I am using your library in my application and Its working great.
However When users from USA using player, they see ads for first 2 to 3 videos. Its not happening any other location.
Can you help me with this?

How can I overcome this issue or I have to use something from your library?

Currently I am using YouTubePlayerView with enableAutomaticInitialization to false
Please help me out of this @PierfrancescoSoffritti 

![Screenshot 2021-06-18 at 10 57 40 AM](https://user-images.githubusercontent.com/41049335/122511371-c0fae400-d024-11eb-8d69-daca620fb758.png)

**Comment by PierfrancescoSoffritti** [comment]
YouTube decides when to show ads, there's nothing we can do about it unfortunately.
