### ISSUE TITLE
Disable focus and click on watch later, share and more videos.

### ISSUE THREAD

**Issue by KumarVelu** [PierfrancescoSoffritti/android-youtube-player#752]
I am aware that watch later, share and more videos tray that comes when the video is in paused state cannot be removed. However I would like to know how to disable focus and clicks on these elements. 

And also would just like to know if there would be any legal issues from Youtube if I put some overlays on top of these elements.

**Comment by PierfrancescoSoffritti** [comment]
> And also would just like to know if there would be any legal issues from Youtube if I put some overlays on top of these elements.

potentially yes.

>  I would like to know how to disable focus and clicks on these elements.

The only way is to put overlays.

**Comment by KumarVelu** [comment]
> The only way is to put overlays.

The problem is I am using this in tv app development and even if I add overlay on top of these I am able to navigate to those elements via D-pad. Any suggestion / ideas on how I can improve this.

**Comment by PierfrancescoSoffritti** [comment]
My suggestion is to let the user navigate to those buttons and click them.

**Comment by pjmdr11** [comment]
What is the workaround for this case. I am having the same issue on tv.

**Comment by KumarVelu** [comment]
@pjmdr11 ,  What I have done is, added overlay on top of these elements, this covers the ui and on the navigation / focus part, I restricting the user focus to go there.

**Comment by pjmdr11** [comment]
> @pjmdr11 , What I have done is, added overlay on top of these elements, this covers the ui and on the navigation / focus part, I am restricting the user focus to go there.

Did adding a overlay on top of the player restrcited the focus?

**Comment by jharitesh1** [comment]
@pjmdr11  No it will not restrict the focus. In this case, you need to handle the focus as well. For example, if you are adding focus on the upper side. and while pressure D-Pad up button it may take the focus below the overlay. so those cases, you need to restrict and block the focus up navigation. These are just the work arounds.
