### ISSUE TITLE
custom ui not working as expected in android tv.

### ISSUE THREAD

**Issue by KumarVelu** [PierfrancescoSoffritti/android-youtube-player#753]
I am facing a weird problem when using custom ui in android tv. 

I have followed the instructions and the sample app to create the custom ui. The problem is it is behaving more like a web ui, i.e when I click on the screen during play, the top left thumbnail, title and top right icons are visible for a fraction of second,  and now when I do a second click pause action takes place. 

Note I am using an emulator and clicking on the screen using mouse action, though in real tv devices this won't be possible as the only interaction would be with D-pad.

Edit : And also the focus on the ui widgets in custom ui layout is not working.

**Comment by KumarVelu** [comment]
> The problem is it is behaving more like a web ui, i.e when I click on the screen during play, the top left thumbnail, title and top right icons are visible for a fraction of second, and now when I do a second click pause action takes place.

Found that I had missed to add this in custom_player_ui.xml 

`<View
        android:id="@+id/panel"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:clickable="true"
        android:focusable="true"
        android:background="@android:color/black" />`
        
 This was the one which was not allowing the touch / click to reach to webview. If you could highlight this in the doc (or) in the blog it would be great. 
 
 However, the focus problem still persists. I have added play/pause button similar to the code sample, but I am not able to reach the button via D-Pad.

**Comment by KumarVelu** [comment]
> However, the focus problem still persists. I have added play/pause button similar to the code sample, but I am not able to reach the button via D-Pad.

Found a workaround for this as well. 
android:nextFocusUp="@+id/playPauseBtn"

**Comment by PierfrancescoSoffritti** [comment]
nice, glad you solved it!
