### ISSUE TITLE
onReady() is not called when using custom player ui.

### ISSUE THREAD

**Issue by KumarVelu** [PierfrancescoSoffritti/android-youtube-player#754]
onReady() is not called when using CustomPlayerUiController.

This is happening in the Sample app as well. 
Go to to Custom UI example, in CustomPlayerUiController.java there is onReady() callback where the progressbar visibility is set to gone, which doesn't happen and you will see the progressbar running even when the video is playing. 

CustomPlayerUiController.java 

```
@Override
    public void onReady(@NonNull YouTubePlayer youTubePlayer) {
        progressbar.setVisibility(View.GONE);
    }
```

**Comment by doitandbedone** [comment]
I'm encountering the same issue. Trying to port this for Android TV I see the player view with the loading bar but onReady is not being called. 
I'm using a pretty simple implementation:
`
override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
[...]
val playerLayout = inflater.inflate(R.layout.fragment_youtube_player, container, false)
        val playerView: YouTubePlayerView = playerLayout.findViewById(R.id.youtubePlayerView)
        root.addView(playerLayout)
        playerView.apply {
            lifecycle.addObserver(this)
            addYouTubePlayerListener(object : AbstractYouTubePlayerListener() {
                override fun onReady(youTubePlayer: YouTubePlayer) {
                    playbackTransportControlGlue?.playerAdapter?.apply {
                        initPlayer(youTubePlayer)
                        playVideo(video)
                    }
                }
            })
        }
[...]
}
`
![Screen Shot 2021-08-16 at 3 00 32 PM](https://user-images.githubusercontent.com/61026996/129634911-24b1e097-018c-45c6-9321-2d21ab4b57e4.png)

**Comment by PierfrancescoSoffritti** [comment]
Hi, i suggest you take a look at the sample application code.
