### ISSUE TITLE
Unlisted youtube videos played in the youtube player are getting shown in youtube app history for android devices | A content security issue.

### ISSUE THREAD

**Issue by GauravPoswalAndroid** [PierfrancescoSoffritti/android-youtube-player#758]
It is not occurring on all OEMs, We have seen it for Realme & Vivo devices.

**Comment by PierfrancescoSoffritti** [comment]
Not sure what this means. The player has no user information so there's not way to link played videos with user youtube account

**Comment by Som1408** [comment]
Same issue here too! Player somehow gets connected to YouTube account and registers video in Watch History.
