### ISSUE TITLE
Video playing stopped when i Remove youTubePlayerView view from it's parent

### ISSUE THREAD

**Issue by yasahmed** [PierfrancescoSoffritti/android-youtube-player#761]
Im trying to create a media App, so I'm playing videos from code and not via xml using this library :

```
youTubePlayerView = YouTubePlayerView(this)
    youTubePlayerView.addYouTubePlayerListener(object : AbstractYouTubePlayerListener() {
        override fun onReady(youTubePlayer: YouTubePlayer) {
            youTubePlayer.loadVideo("0EVVKs6DQLo",0f)
            layout1.addView(youTubePlayerView)
        }
    })
```

when i add youTubePlayerView to another layout to show video on my activity for example as bellow :

```
layout1.removeView(youTubePlayerView) 
layout2.addView(youTubePlayerView)
```

video was stopped !!, is there any solution to make video still playing even if i remove it's relative view (youTubePlayerView) from it's parent (layout1) because i still have youTubePlayerView instance which is not yet destroyed ? !

Thank's

**Comment by PierfrancescoSoffritti** [comment]
Hi, i don't think this is possible.
