### ISSUE TITLE
How to add a fullscreen icon in webUi.

### ISSUE THREAD

**Issue by RajeevNShetty** [PierfrancescoSoffritti/android-youtube-player#763]
I am getting a menu icon with captions off button in web UI. I am not getting any fullscreen icon. How to add a fullscreen icon when using WebUI. Or Can we add a full-screen icon of our own on top of it?

**Comment by PierfrancescoSoffritti** [comment]
I suggest adding the fullscreen button outside the player. The point of using web Ui is to not alter the default UI of the player and to allow the user to click the buttons.

**Comment by RajeevNShetty** [comment]
okay. Is there any way to get callback clicking anywhere in that web UI. I added on-click listeners but it's not getting triggered.

**Comment by PierfrancescoSoffritti** [comment]
You can try to intercept the click somehow
