### ISSUE TITLE
Doesn't work for targetSDKVersion 30

### ISSUE THREAD

**Issue by shubh261096** [PierfrancescoSoffritti/android-youtube-player#764]
I started getting an error when I updated my targetSDKVersion to 30. Please update this library to support version 30.

**Comment by PierfrancescoSoffritti** [comment]
What error do you get?

**Comment by shubh261096** [comment]
It worked. There was no error. It's just I had to add a query to check if YouTube is installed or not before using its service.

```
<queries>
        <package android:name="com.google.android.youtube" />
</queries>
```
