### ISSUE TITLE
Embedded youtube video stop playing of sound after some minutes  in the background 

### ISSUE THREAD

**Issue by devbest555** [PierfrancescoSoffritti/android-youtube-player#765]
Whenever playing of sound stopped, I got this error message in my android studio logcat.
"chromium: [ERROR:image_reader_gl_owner.cc(305)] no buffers currently available in the reader queue"

If I turn on the screen of the device, then it is working fine.
The problem is when the video plays in the only background.
Wish to solve it ASAP.

**Comment by devbest555** [comment]
Who can help it?

**Comment by PierfrancescoSoffritti** [comment]
You should stop the player before your app goes into the background. As background playback breaks youtube terms of service.

**Comment by yasahmed** [comment]
you have to play your video from a service and not directly from activity

**Comment by devbest555** [comment]
@yasahmed @PierfrancescoSoffritti 
Thank you for your reply.
Could you explain about solution in more detail?

**Comment by PierfrancescoSoffritti** [comment]
YouTube does not allow background playback. What you're trying to do breaks terms of service. So you won't be allowed to publish on Google Play.

**Comment by devbest555** [comment]
> YouTube does not allow background playback. What you're trying to do breaks terms of service. So you won't be allowed to publish on Google Play.

Anyway, I want to play the youtube in the background without stop playing.
can you solve it?

**Comment by PierfrancescoSoffritti** [comment]
https://github.com/PierfrancescoSoffritti/android-youtube-player#play-youtube-videos-in-the-background

**Comment by devbest555** [comment]
> https://github.com/PierfrancescoSoffritti/android-youtube-player#play-youtube-videos-in-the-background

I had tried it already and then youtube is playing in the background.
but video stop playing while it is playing in the background after 3~5 mins

**Comment by PierfrancescoSoffritti** [comment]
Well i don't know, maybe your phone is removing the app from memory after a
while.

**Comment by devbest555** [comment]
> > https://github.com/PierfrancescoSoffritti/android-youtube-player#play-youtube-videos-in-the-background
> 
> I had tried it already and then youtube is playing in the background.
> but video stop playing while it is playing in the background after 3~5 mins

video stop short time and then playing again.
it is repeated often.

**Comment by devbest555** [comment]
Whenever video stop playing,  I got it in Logcat window of android studio
"E/chromium: [ERROR:image_reader_gl_owner.cc(305)] no buffers currently available in the reader queue"
