### ISSUE TITLE
Cannot direct to  official Youtube APP(or new web browser ) after clicked buttons or links in the WebUi mode.

### ISSUE THREAD

**Issue by CloudedDragon** [PierfrancescoSoffritti/android-youtube-player#767]
#We try to use WebUI, but click on the red circled part of WebUI; it will be directed to YoutubeView instead of opening in a new browser or official Youtube APP. But on the same mobile phone, we use Sample Code of "android-youtube-player", and it can directly open in a new browser or official Youtube APP.

Please help ~
@PierfrancescoSoffritti 

![webUI screenshot 1](https://i.imgur.com/oh9UBIc.png)
![webUI screenshot 2](https://i.imgur.com/pWwQ8Bj.png)
![webUI screenshot 3](https://i.imgur.com/HtTPPjQ.png)

**Comment by PierfrancescoSoffritti** [comment]
enable webUi, see docs for more info.
