### ISSUE TITLE
Can this library be used in Kotlin?

### ISSUE THREAD

**Issue by Hsiao-Chien-Ti** [PierfrancescoSoffritti/android-youtube-player#768]
I am using kotlin to make a video player with a scrollable recyclerView which can show more than one video. However, I just don't know how to set up the adapter in Kotlin. I noticed that @PierfrancescoSoffritti  had turned the core into Kotlin, but not the example codes. I am pretty new for android, so I don't know how to turn the java code into kotlin well( I tried the "convert java into kotlin ", but got codes with a lot of error...)
So my question is, can this library be used in Kotlin? Or it's just for Java?
And if it can be used in Kotlin, what should I do in the adapter class...
p.s. Sorry my English is poor...

**Comment by PierfrancescoSoffritti** [comment]
> So my question is, can this library be used in Kotlin? 

yes it can be used with Kotlin.

**Comment by Acidrai0** [comment]
yes it can be used with Kotlin. Then update the example codes too
