### ISSUE TITLE
Android Things

### ISSUE THREAD

**Issue by Gh0stWires** [PierfrancescoSoffritti/Android-YouTube-Player#77]
So I got this working on the new Android Things platform. But it is noticeably slow not too bad but still a lot of frame skipping.  Logcat says I am doing too much on the main thread even with it being the only thing. Is it loading the videos asynchronously and if so can it be improved? If not is there a way to load the videos asynchronously?

**Comment by PierfrancescoSoffritti** [comment]
Hi, this library runs the YouTube player inside a WebView, all the library does right now is to provide an easy to use and native-like experience on Android.
Being the underlying player built by YouTube, there's not much we can do to change how it loads videos. Right now the WebView is handled like a black box, I'm not sure what improvements could be made, but maybe looking into it something can be done.

That said, it's reasonable that on low-end devices WebView performances may not be great.
Let me know if you have ideas on how to improve performances, pull requests are always welcomed :)

**Comment by Gh0stWires** [comment]
Well in my testing the videos play at a decent enough frame rate to be watchable. It is more so the the initial loading. I don't know much about androids webview. But if there was a way to know when the webview is done retrieving the data from youtube. You could then put it on a background thread and only load it into the main thread when its done. Are the network calls asynchronous? I will look through the code further and see if I can make any changes.

**Comment by Gh0stWires** [comment]
ok so this code right here

    @Override
    public void loadVideo(final String videoId, final float startSeconds) {
        mainThreadHandler.post(new Runnable() {
            @Override
            public void run() {
                loadUrl("javascript:loadVideo('" +videoId +"', " +startSeconds +")");
            }
        });
    }

Because of the way you have set up the threading it is trying to load the webviews url on the UI thread. This is bad even for higher end android devices as the more UI elements you have the more they have to compete with all the listeners and networks calls. This will slow any apps load time down to a crawl. All the Runnables in **WebViewYouTubePlayer.java** need to be run on their own thread. Once they have completed there operation then they can be loaded back into the main thread.  I can try and implement these changes if you want?

**Comment by PierfrancescoSoffritti** [comment]
As I see it this is just a call to a Javascript function, that is then executed asynchronously in its own Javascript world, inside of the web page.

But please, feel free to try! If you're right this may result in a major improvement in performance!
Keep me posted!

**Comment by Gh0stWires** [comment]
Can I ask what this code is doing 

    loadUrl("javascript:loadVideo('" +videoId +"', " +startSeconds +")");

It appears to be using the webview's loadUrl function to load javascript. How do you tell when it is finished?

**Comment by PierfrancescoSoffritti** [comment]
In this case it calls the loadVideo function already defined in [the webpage](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/res/raw/youtube_player.html).

When the function is executed the player changes its state, therefore the javascript function `sendPlayerStateChange` is called. `sendPlayerStateChange` then calls the corresponding function in the [YouTubePlayerBridge](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayerBridge.java), which notifies all the subscribed observers that a change has happened.

**Comment by Gh0stWires** [comment]
Ok that makes more sense. And all the listeners are running on the main thread?

**Comment by PierfrancescoSoffritti** [comment]
I'm not sure where Webview runs its Javascript interfaces (YouTubePlayerBridge in this case).
But I'm 100% sure that what happens in the web view is not on the main thread.

**Comment by Gh0stWires** [comment]
Your right cause the webview is supposed to handle everything asynchronously. But the calls to java script functions are all happening on the main thread. Your thread handler gets the main looper which is the ui thread. And then when you post your runnables to it they get added to the bottom of the execution pool on the ui thread. I'm gonna try running the cueVideo function in an asynctask and see what happens. But I think I need to remove some of the functions in your library from runnables so that I can specify my own thread.

**Comment by PierfrancescoSoffritti** [comment]
Remember that you can't call WebView methods from outside the main thread. I'm not sure async task is going to help here.
Also those are basically calls to async functions. I really doubt a simple function call can have any impact on performances!

let me know what you find :)

**Comment by Gh0stWires** [comment]
Yep your right. Shoot. Well I'm gonna keep playing with it and see what else I can find. Learning a lot about Android webviews with this one.
