### ISSUE TITLE
Remove video title, 3 vertical points and youtube logo

### ISSUE THREAD

**Issue by alessandrobonetti-codaq** [PierfrancescoSoffritti/android-youtube-player#770]
Hi everybody, I'm new to this useful library.
I would like to remove the video title, the 3 vertical point on the top right and the youtube logo when video starts.
Is it possible?
My "app:useWebUi" is false in the YouTubePlayerView.
I tried with setSystemUiVisibility(View.GONE) and after witn inflateCustomPlayerUi (a layout with an empy RelativeLayout inside).
Thx in advance for any suggestion.
Alessandro

**Comment by PierfrancescoSoffritti** [comment]
I suggest setting web ui to true.

And no it's not possible to remove those views, the YouTube library does not allow it.
