### ISSUE TITLE
How to identify the start of the video playback

### ISSUE THREAD

**Issue by Arunm619** [PierfrancescoSoffritti/android-youtube-player#773]
Does this library provide an option to identify the exact time of when the video playback starts happenning?
the actual playback may have been delayed (due to network delays, buffering etc.) but I'd like to know the exact time of when the video starts playing. Thanks in advance.

**Comment by PierfrancescoSoffritti** [comment]
Yes, add a listener to the player. [Read doc for more info](https://github.com/PierfrancescoSoffritti/android-youtube-player#youtubeplayerlistener).
