### ISSUE TITLE
Please check <meta> tag in remote version

### ISSUE THREAD

**Issue by Kenny50** [PierfrancescoSoffritti/android-youtube-player#775]
I currently using this library to display live video from YouTube, I noticed that the webui isn't working when I try to use seekbar.

I check issue before, years ago you mentioned that live video doesn't have seekbar, maybe they add this feature.

I read the iframe api document, and source code, after two days I found out, with `<meta name="viewport" content="width=device-width, user-scalable=no" />`, iframe always show the correct webui, instead of the one looks like html `<video>` controls, I check sample code, this line is written in R.raw.ayp...., but I can't check remote version, please check it out, with the `<video> ` controls ui is painful and useless.

Iframe default version webui, also the default version when I set webui=true in my project
![Screenshot_2021-09-10-17-49-14-34_6a715af210d8e058ad546e5de3273a07.jpg](https://user-images.githubusercontent.com/65593417/132997119-19b999e6-8828-477a-8297-890174c6e44c.jpg)

Iframe with <meta ...> , work fine, random ly show up when webui=true, no clue how to set it as default
![Screenshot_2021-09-10-17-44-02-03_6a715af210d8e058ad546e5de3273a07.jpg](https://user-images.githubusercontent.com/65593417/132998381-5b886cb3-d2ad-4b78-ba05-e4d64607e09a.jpg)

**Comment by PierfrancescoSoffritti** [comment]
Hi, i suggest you enable webUi and use that instead of native ui.
