### ISSUE TITLE
initialize on kotlin fragment

### ISSUE THREAD

**Issue by amertaslan** [PierfrancescoSoffritti/android-youtube-player#776]
I have spend 1 day for search and tries but couldn't achieve it. Is anyone know how to implement this player attribute on onCreateView. I am using data binding. So, i can reach the view with binding.videoPlayer. But then what should i do?
Tried binding.videoPlayer.initialize() function but it needs an YoutubePlayerListener parameter but i did not understand how to create and send this parameter.

**Comment by PierfrancescoSoffritti** [comment]
Copy what is shown here: https://github.com/PierfrancescoSoffritti/android-youtube-player#quick-start
