### ISSUE TITLE
Add lifecycle observer to YouTubePlayerView

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [PierfrancescoSoffritti/Android-YouTube-Player#78]

**Comment by PierfrancescoSoffritti** [comment]
implemented in dev branch, will be available in next release

**Comment by gajicm93** [comment]
@PierfrancescoSoffritti what is the proper way of manually managing lifecycle? Is there any documentation?

I need to do it manually to avoid release() being called as I need to reuse my player instances. But all other lifecycle methods like onStop and onPause are private and very protected, so what to do?

**Comment by PierfrancescoSoffritti** [comment]
Hi, just make sure to always pause the video when the player is not visible and to call release when you're done using the player.

May I ask what do you mean exactly with "I need to reuse my player instances"? When the player is added as a LifecycleObserver, release() is called only when the Activity is destroyed.

**Comment by gajicm93** [comment]
@PierfrancescoSoffritti I am using it inside RecyclerView (with Epoxy library), and the ViewHolder is reused on multiple fragments.

I had the problem because I was attaching the player to Fragment lifecycle.. but actually using Activity lifecycle instead of Fragments might be a great idea, thanks for that.

**Comment by PierfrancescoSoffritti** [comment]
Yes, exactly!

If you find the library to be useful consider leaving a star on GitHub :)

**Comment by gajicm93** [comment]
@PierfrancescoSoffritti already did, thanks! 👍
