### ISSUE TITLE
Video reload in full screen mode and start from the beginning

### ISSUE THREAD

**Issue by netacohen1** [PierfrancescoSoffritti/android-youtube-player#780]
When the video enters full screen mode it reloads and start again from the beginning, even if the video is already in the middle...
is there any way to prevent that?

**Comment by PierfrancescoSoffritti** [comment]
Hi, check out how it's done [in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples).
