### ISSUE TITLE
After set volume , volume button is not working

### ISSUE THREAD

**Issue by IamArmaan** [PierfrancescoSoffritti/android-youtube-player#781]
Hi , I want to play video automatically . So , I have initialize youtube player and set volume as` youTubePlayer.setVolume(0)` , its playing fine but after showing video user wants to increase volume using their mobile volume button and it seems its not working . here is my code `youTubePlayerView.initialize(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(YouTubePlayer youTubePlayer) {
                super.onReady(youTubePlayer);
                youTubePlayer.loadVideo("MN8p-Vrn6G0",0);
                youTubePlayer.setVolume(0);
            }
        });`

**Comment by PierfrancescoSoffritti** [comment]
Hi, using `youtubePlayer.setVolume` is a different thing from setting the phone's system volume (volume button).

You could intercept the system volume change and use it to change the player's volume, but it's up to you.

**Comment by IamArmaan** [comment]
Thanks @PierfrancescoSoffritti for commenting , can you please guide me . I want at initially it will be zero or mute ,but if user want then they can change volume using android phone's system volume.

**Comment by IamArmaan** [comment]
Thanks , I did this using `AudioManager` .
