### ISSUE TITLE
Latency is high and flickering observed on bigger screens. Please help

### ISSUE THREAD

**Issue by jharitesh1** [PierfrancescoSoffritti/android-youtube-player#782]
Is this app is supported for TVs? Can we put this app on the TV? I put this apk on my TV and getting below issues:
1) Loading time for any content is too much. Some times, its taking  15+ seconds on good network conditions too. Latency is too high. 
2) On 55" and bigger screens, we are observing frequent flickering.
3) Is there any alternate SDK exist which works well for TV? 

We tried to optimise this apk for TV..but not working it. Can you please help? Appreciate your help.

**Comment by PierfrancescoSoffritti** [comment]
The lib is based on webview. It might be that webview struggles on TV hardware.
