### ISSUE TITLE
 MenuItem not hiding after clicks MenuItem

### ISSUE THREAD

**Issue by naveen-nuveda** [PierfrancescoSoffritti/android-youtube-player#784]
After calling OnClickListener for MenuItem, the MenuItem should be hide. and 3 dots should be appear.
How to do this?

`youTubePlayerView?.getPlayerUiController()
            ?.showMenuButton(true)
            ?.getMenu()
            ?.addItem(com.pierfrancescosoffritti.androidyoutubeplayer.core.ui.menu.MenuItem(
                getString(R.string.my_bookmarks), R.drawable.ic_baseline_bookmark_24
            ) {
                showBookmarks()
            })`

**Comment by PierfrancescoSoffritti** [comment]
Sorry I don't understand what you're asking. Feel free to reopen the issue if you still need help.
