### ISSUE TITLE
YouTube video Stopped playing on number of Phones like 9.0 etc.Earlier it was playing

### ISSUE THREAD

**Issue by rajeshpundeer** [PierfrancescoSoffritti/android-youtube-player#785]
YouTube video Stopped playing on number of Phones like 9.0 etc.Only Voice is audible and picture is not shown.Earlier it was playing.How to resolve it.Please reply soon.My app stopped working.

**Comment by nataliadmuh** [comment]
Youtube video not playing on some devices with API 30, only audio play, video is glitching. https://prnt.sc/202ielf

**Comment by PierfrancescoSoffritti** [comment]
I suggest using a real device and not an emulator. I'm not sure what the issue you're having is about, but it doubt it's related to API version.
