### ISSUE TITLE
Failed to resolve: com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5

### ISSUE THREAD

**Issue by rawalprashant** [PierfrancescoSoffritti/android-youtube-player#788]
Hi,

I have upgraded my application from JCenter() to mavenCentral() and I got the above error. Does anyone have a solution to fix it or any other player recommendation?

Thanks

**Comment by PierfrancescoSoffritti** [comment]
The library is not on maven central yet, see #703

**Comment by rawalprashant** [comment]
@PierfrancescoSoffritti 

I see, so do you have any plan to move the library to maven? as I just read JCenter is going to be closed next year Feb 2022.

As I am working on some big project, it is good for me to decide now.

Thanks

**Comment by PierfrancescoSoffritti** [comment]
Yes, you can read the comments on that issue.
