### ISSUE TITLE
Could not find com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5.

### ISSUE THREAD

**Issue by alfayedoficial** [PierfrancescoSoffritti/android-youtube-player#789]
Could not find com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5.
Required by:
    project :app
Getting Error when using Android YouTube Video Player 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5' after removing JCenter()

**Comment by PierfrancescoSoffritti** [comment]
duplicate #703
