### ISSUE TITLE
Volume is comparatively low than existing YouTube player for Live Videos 

### ISSUE THREAD

**Issue by pralgomathic** [PierfrancescoSoffritti/Android-YouTube-Player#79]

**Comment by PierfrancescoSoffritti** [comment]
You can set the volume of the [YouTubePlayer](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/YouTubePlayer/src/main/java/com/pierfrancescosoffritti/youtubeplayer/player/YouTubePlayer.java). But it should already be at maximum.

**Comment by pralgomathic** [comment]
I tried with setting `initializedYouTubePlayer.setVolume(100);` , but still getting the same result.

**Comment by PierfrancescoSoffritti** [comment]
Are you sure the volume isn't low in the video by itself? Have you tried with different streaming videos?

**Comment by pralgomathic** [comment]
Yeah I tried playing  same videos both this player and YouTube provided player.

**Comment by PierfrancescoSoffritti** [comment]
Uhm weird. Could you please send me the ids? (so that I don't have to fetch the ids from the data apis 😁)

**Comment by pralgomathic** [comment]
Sure, "d9iPHzLF8yM","5KWuqjczFqI"  😄

**Comment by PierfrancescoSoffritti** [comment]
Thanks! I m going to test it now, I ll get back to you in a few minutes.

**Comment by PierfrancescoSoffritti** [comment]
I have tested both the videos on this library's sample app and on the official YouTube app. On my device (Android 8.1) the volume is the same. 
Which version of Android are you using?

**Comment by pralgomathic** [comment]
Oh, that's great ,How this happening for me then ? 😢 I have Android 6.0.1

**Comment by PierfrancescoSoffritti** [comment]
Let me test again on Android 6 :)

**Comment by PierfrancescoSoffritti** [comment]
No issue for me on Android 6 as well. Do you have the same problem using the sample app?

**Comment by pralgomathic** [comment]
Yeah , I do have the same problem ? It could be a device issue? I'm using samsung galaxy J7.

**Comment by PierfrancescoSoffritti** [comment]
mmm it's hard for me to give any insight without being able to replicate the issue. 
I have tried on Pixel 2 XL and Nexus 5, no problem there. Do you have any other Android device? try with them and see what happens.

**Comment by pralgomathic** [comment]
Oh, I don't have another one. I will try then someone else's phone.
