### ISSUE TITLE
My App got removed from playstore due to Violation of Youtube's Terms of Service

### ISSUE THREAD

**Issue by SimonHaenle** [PierfrancescoSoffritti/android-youtube-player#791]
So I am using the latest version 10.5 of the library. My app just got removed yesterday because it violates youtube's terms of service.
Google wrote:
`
About the Device and Network Abuse policy
--
We don’t allow apps that interfere with, disrupt, damage, or access in an unauthorized manner the user’s device, other devices or computers, servers, networks, application programming interfaces (APIs), or services, including but not limited to other apps on the device, any Google service, or an authorized carrier’s network.Your app shouldn’t access or use the service or API in a manner that violates its terms of service. For example, your app shouldn't download, monetize, or access YouTube videos in a way that violates the YouTube Terms of Service.
`

I can only guess but as I have never ever seen any ads that appear at the start of the video when using your youtube player library, I guess you bypass youtube's ads somehow.

They posted me a screenshot showing the violation but that's basically just the player itself:

![discoverflix-InAppExperience-202](https://user-images.githubusercontent.com/29062523/141072177-3410001d-1622-45b2-9ea4-b1af90fd7501.png)

Do you have any ideas?

**Comment by PierfrancescoSoffritti** [comment]
The library does not bypass YouTube ads.

I suggest disabling native UI in the player and just use web ui. Also make sure that no views cover the player.

But in general i would suggest reading YouTube TOS and make sure that you're app is respecting them.

**Comment by sergiambel** [comment]
Check in any case the bottom banner appears over the Youtube video. My
recommendation: Try opening the Youtube video in a new (and empty) activity
and upload to google play. If this doesn't work, replace the current
youtube player by a link to youtube.com.

Good new: an app Removing is not an app Suspension
https://support.google.com/googleplay/android-developer/answer/2477981?hl=en

**Comment by PierfrancescoSoffritti** [comment]
I don't think making changes to the apk and re-uploading it to the Playstore to see what happens is a viable strategy. Sometimes they detect policy violations quickly, some other times it takes them months (at least that was my experience a few years ago).

**Comment by sergiambel** [comment]
I'm sorry the missundestunding. My proposal is make the app compliant and
upload again. Following the Google Play recommendation for removals: "Once
your app is removed, the published version of your app won't be available
on Google Play until a compliant update is submitted."

**Comment by SimonHaenle** [comment]
Thanks for the fast replies.
I hate it that google just throws a big TOS document at you and yells "YOU VIOLATE THE POLICIES; FIX THEM" instead of telling you exactly what the problem is. This is just lazy and despotic behavior.
I can still only guess the problem, but I really think that in some cases, the banner was covering parts of the video cause I did not set the constraints properly. I now added a padding of 10dp around the video and there's always a space between the bottom banner and the video now. Maybe the video was just too close to the bottom banner so the user could accidentally click the banner instead of the video, no one knows. I also use the webUI instead of the native UI.
I just uploaded the new version and will inform you of the outcome.

Stupid Google.

**Comment by codegsaini** [comment]
@SimonHaenle

# Relax, Relax and Relax. Just remove ads from any activity in which there is youtube player.

## I got same issue way back in 2020. Here is the screenshot of email --
![Screenshot (66)](https://user-images.githubusercontent.com/77002578/141282189-5140828a-492e-4c65-b511-a5cc6bae491e.png)

## And this is app's screenshot which they sent. 
![com onusant toppermate-InAppExperience-163](https://user-images.githubusercontent.com/77002578/141282378-14f37bf2-f814-4767-8689-7d0d1bdfb7e2.png)

# To clear any doubt I must clarify, I was using official library.

**Comment by SimonHaenle** [comment]
Thank you so much for this answer. I think you can close @PierfrancescoSoffritti ;)

**Comment by PierfrancescoSoffritti** [comment]
> I now added a padding of 10dp around the video and there's always a space between the bottom banner and the video now. Maybe the video was just too close to the bottom banner so the user could accidentally click the banner instead of the video, no one knows. I also use the webUI instead of the native UI.

You should be fine now :)
