### ISSUE TITLE
onReady(@NotNull YouTubePlayer youTubePlayer) callback taking too much time

### ISSUE THREAD

**Issue by fahmidul** [PierfrancescoSoffritti/android-youtube-player#792]
Sometimes this call-back method responds after 10-15 seconds. But sometimes it takes 2-3 seconds. 
I have checked my internet connections and tested on multiple devices. But the result is the same.

**Comment by PierfrancescoSoffritti** [comment]
well as you said this depends on device/internet connection.

**Comment by fahmidul** [comment]
> well as you said this depends on device/internet connection.
No. It doesn't depend on device/ Internet connections. 
It randomly takes a little or a long time.

**Comment by PierfrancescoSoffritti** [comment]
I don't think your issue is related to the library, so i'm closing it. Feel free to reopen if you find out something new/have more details.
