### ISSUE TITLE
An Error Occured 

### ISSUE THREAD

**Issue by ashwath20** [PierfrancescoSoffritti/android-youtube-player#793]
When i tried to load video i get an error saying "An error occured .Please try again later....:"

implimentation
` private void showYtPlayer(String url) {
        try {
            showOption();
            isVideoViewVisible = true;
            youTubePlayerView.setVisibility(View.VISIBLE);
            String id = LUtils.getVideoId(url);
            LLog.i(TAG, id);
            if(ytPlayer!=null) {
                ytPlayer.loadVideo(id, time);
            }else {
                failedToShowYt = true;

            }
            if (LUtils.isMyServiceRunning(YtService.class)) {
                Intent intent = new Intent(this, YtService.class);
                stopService(intent);
            }
            failedToShowYt = false;
        } catch (Exception e) {
            LLog.i(TAG, "failedToShowYt");

            LLog.e("error", e.getMessage());
            failedToShowYt = true;
        }
    }

	 youTubePlayerView = findViewById(R.id.youtube_player_view);
        getLifecycle().addObserver(youTubePlayerView);
        youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {

            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                ytPlayer = youTubePlayer;
                if (failedToShowFloatingWindow) {
                    LLog.i(TAG, "OnReady Called. Calling showAdvancedPlayer");
                    showYtPlayer(url);
                }
            }`
Below is the error data from webui 
`{
  "vct": "0.000",
  "vd": "NaN",
  "vpl": "",
  "vbu": "",
  "vpa": "1",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "0",
  "vns": "0",
  "vec": "null",
  "vemsg": "",
  "vvol": "1",
  "vdom": "1",
  "vsrc": "0",
  "vw": "0",
  "vh": "0",
  "state": "80",
  "debug_error": "{\"errorCode\":\"api.invalidparam\",\"errorMessage\":\"An error has occurred. Please try again later.\",\"DD\":\"GENERIC_WITHOUT_LINK\",\"ri\":\"\",\"UF\":\"invalidVideodata.1;a6s.1\"}",
  "relative_loudness": "NaN",
  "user_qual": 0,
  "release_version": "youtube.player.web_20211114_00_RC00",
  "0sz": "true",
  "op": "",
  "yof": "true",
  "dis": "",
  "gpu": "Mali-G52",
  "debug_playbackQuality": "unknown",
  "debug_date": "Tue Nov 16 2021 13:19:13 GMT+0530 (India Standard Time)"
}`

Below is the log data i get when this error occures 
`E/BufferQueueProducer: [ImageReader-1x1f23u256m2-19960-1](id:4df800000001,api:3,p:19960,c:19960) detachBuffer: slot 0 is not owned by the producer (state = FREE)
2021-11-16 13:18:35.698 19960-21110/package E/BufferQueueProducer: [ImageReader-1x1f23u256m2-19960-1](id:4df800000001,api:3,p:19960,c:19960) detachBuffer: slot 1 is not owned by the producer (state = FREE)
....
....
....
.....
E/BufferQueueProducer: [MediaCodec.release](id:4df800000002,api:0,p:-1,c:19960) detachBuffer: BufferQueue has no connected producer`

**Comment by PierfrancescoSoffritti** [comment]
Hi, you should provide more information. I'm closing for now, feel free to reopen if you have more details.
