### ISSUE TITLE
YouTube player closes when removing YouTube app from back stack.

### ISSUE THREAD

**Issue by sreehariqb** [PierfrancescoSoffritti/android-youtube-player#794]
I start my activity and the android-youtube-player starts playing video. Now I go to YouTube app in phone by clicking on YouTube icon in android-youtube-player, and then I kill the YouTube app by removing it from the back stack. I am back in my app, but the android-youtube-player has closed. Is this because the android-youtube-player uses service from YouTube app and when the it is force closed the service is no longer available? I would like to know is there any way to have control on this behaviour.

**Comment by PierfrancescoSoffritti** [comment]
The library does not depend on the YouTube app. The issue is most likely in
your code.
