### ISSUE TITLE
About video format

### ISSUE THREAD

**Issue by VeiZhang** [PierfrancescoSoffritti/android-youtube-player#795]
Can I select video format?

For example, https://www.youtube.com/watch?v=WllZh9aekDg
This video format is vp9, is there any param to set videoFormat as mp4 or others?

The reason is my platform didn't support vp9, I need to change other support format.

**Comment by PierfrancescoSoffritti** [comment]
The video is streamed through YouTube's infrastructure, so the format you upload it to YouTube doesn't matter.
