### ISSUE TITLE
Is there any option to use the background play option while muting the video?

### ISSUE THREAD

**Issue by softylogics** [PierfrancescoSoffritti/android-youtube-player#797]
I found this library very useful but still cant find any option for muting the background playback. @PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
You mean playing multiple videos at the same time? i don't think Android allows multiple audio sources to play at the same time, by default. So you'll have to figure out how to do it.

**Comment by softylogics** [comment]
> You mean playing multiple videos at the same time? i don't think Android allows multiple audio sources to play at the same time, by default. So you'll have to figure out how to do it.

No, not multiple videos but just one video which is playing in background but with muted audio.

**Comment by PierfrancescoSoffritti** [comment]
[Follow the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#play-youtube-videos-in-the-background) and set the volume to 0.

**Comment by softylogics** [comment]
> [Follow the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#play-youtube-videos-in-the-background) and set the volume to 0.

Thank you very much, found it in YoutubePlayer class.
