### ISSUE TITLE
cannot resolve com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView

### ISSUE THREAD

**Issue by prakashraooo** [PierfrancescoSoffritti/android-youtube-player#800]
cannot resolve com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView in layout file after 11.0.1 update

@PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
It's working fine for me, there must be some issue in your setup.

**Comment by prakashraooo** [comment]
i just add this in my gradle implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:11.0.1'

do i need to add something more? plz help

**Comment by PierfrancescoSoffritti** [comment]
No, don't think so. Try to `file`->`invalidate caches/restart` in Android Studio.

Can you see YouTubePlayerView from java/kotlin?

**Comment by prakashraooo** [comment]
No i can't see YoutubePlayerView in my java file

@PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
Could you share here your root level and app level `gradle.build` files?

**Comment by prakashraooo** [comment]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 31
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId "com.kingsgray.youtube_player_test_new"
        minSdkVersion 24
        targetSdkVersion 31
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.3.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
    implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:11.0.1'
}




//--------------------------------------------------------------------------------

buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.2"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()


    }

}

task clean(type: Delete) {
    delete rootProject.buildDir
}


@PierfrancescoSoffritti

**Comment by PierfrancescoSoffritti** [comment]
please use proper code formatting, this is not readable

**Comment by PierfrancescoSoffritti** [comment]
But it looks good to me, it should work.

**Comment by prakashraooo** [comment]
```
buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.2"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()


    }

}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by PierfrancescoSoffritti** [comment]
Looks good.

**Comment by prakashraooo** [comment]
My problem is solved after updating android studio . 
But 1 thing i wanna ask how can i disable long press under player view . After long press player shows many options there
