### ISSUE TITLE
Minimum API level supported by this library

### ISSUE THREAD

**Issue by muriloinflue** [PierfrancescoSoffritti/android-youtube-player#804]
My compileSdkVersion is 30. I was using your 10.0.5 version. 

Then the player stopped working (videos load but do not auto play and you also can't play them). No errors on the debug, just one warning that I guess was related to this lib, since it's the only youtube-related lib I'm using:

`I/chromium: [INFO:CONSOLE(920)] "Unrecognized feature: 'picture-in-picture'.", source: https://www.youtube.com/s/player/8da38e9a/www-widgetapi.vflset/www-widgetapi.js (920)`

I came here and saw there was an update to 11.0.1, which is nice because it probably will fix whatever is happening... So i updated my graddle with it.

When I try to build it,  it brings a problem:

```
The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30).
Dependency: androidx.lifecycle:lifecycle-runtime-ktx:2.4.0.
AAR metadata file: ----\jetified-lifecycle-runtime-ktx-2.4.0\META-INF\com\android\build\gradle\aar-metadata.properties
```

Your readme/graddle says the minAPI is 17. But one of your dependencies requires the compileSdk to be 31.... so that 17 is kinda wrong? I guess?

Is there anything I can do to fix this without raising my sdk?

**Comment by PierfrancescoSoffritti** [comment]
`minSdk` and `compileSdk` are two different things. I suggest you update your `compileSdk` to 31.

**Comment by muriloinflue** [comment]
@PierfrancescoSoffritti thanks. That helped... a bit. 

I kept your version to 10.0.5 and updated the sdk from 30 to 31, so I could get rid of that first. The app builded just fine. Yay for sdk 31!

Then I updated your version to 11.0.1. And this popped up:

```
----/.gradle/caches/transforms-2/files-2.1/41bcfda5decfed8b7fc5b6d70729616b/jetified-kotlin-stdlib-jdk7-1.6.0.jar!/META-INF/kotlin-stdlib-jdk7.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
----/.gradle/caches/transforms-2/files-2.1/4e27b4c95942ca62f665126f3bdc1ecf/jetified-core-11.0.1-api.jar!/META-INF/core_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
----/.gradle/caches/transforms-2/files-2.1/582495a9639e214fd0b77250c6574e6e/jetified-kotlin-stdlib-common-1.6.0.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
----/.gradle/caches/transforms-2/files-2.1/6bfea6a51ad5959338f1117dc4ab4789/jetified-kotlin-stdlib-1.6.0.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
----/.gradle/caches/transforms-2/files-2.1/bba88c95443bb5014ba77297370d648f/jetified-kotlin-stdlib-jdk8-1.6.0.jar!/META-INF/kotlin-stdlib-jdk8.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
```

This pops up as soon as (and ONLY if) I upgrade your lib from 10.0.5 to 11.0.1.

Do you have any clue on it?

Thanks a lot!

**Comment by PierfrancescoSoffritti** [comment]
Well, update kotlin to 1.6.0

**Comment by muriloinflue** [comment]
Guess I had to update a ton of things to get it working. It was like a cascade of updates, one update requiring another... but at the end of it all, it's working again. Thanks a lot!

**Comment by PierfrancescoSoffritti** [comment]
Yeah, I didn't know they had so many compatibility issues. But I guess
using the latest is the right thing to do. Glad you solved the issue :)
