### ISSUE TITLE
is that possible to get total video duration before playing it?

### ISSUE THREAD

**Issue by Hawksbillcat** [PierfrancescoSoffritti/android-youtube-player#811]
I've tried to add listener into the player object in the OnReady scope,  also used the the onVideoDuration function but coudn't get the total duration, the returning value with real duration only happens after playing, so is there any way to retrive the duration before playing?

**Comment by PierfrancescoSoffritti** [comment]
Hi, this is a player library, not a library to retrieve data from YouTube. If you want to get data from YouTube without playing videos, you need to use the [YouTube Data API](https://developers.google.com/youtube/v3).
