### ISSUE TITLE
app:showFullScreenButton error

### ISSUE THREAD

**Issue by shipofsea** [PierfrancescoSoffritti/android-youtube-player#815]
when add  app:showFullScreenButton="true" at the xml file, "ERROR: attribute showFullScreenButton  not found" occurs.
how can fix it?

**Comment by TinhHuynh** [comment]
https://github.com/PierfrancescoSoffritti/android-youtube-player/releases/tag/11.0.0

Since version 11.0.0, attributes like useWebUi, enableLiveVideoUi, showYouTubeButton etc have been removed, as they don't make sense with web ui as default.

**Comment by PierfrancescoSoffritti** [comment]
As @TinhHuynh says.

You can replicate the old behaviour by using [DefaultPlayerUiController](https://github.com/PierfrancescoSoffritti/android-youtube-player#defaultplayeruicontroller)
