### ISSUE TITLE
After calling webview.pauseTimer() in other webview, player does not work.

### ISSUE THREAD

**Issue by pparkppark** [PierfrancescoSoffritti/android-youtube-player#822]
webView.pauseTimer() has a global effect, it also affects other webviews, so the JavaScriptInterface does not work. Somewhere in WebViewYouTubePlayer it seems necessary to call resumeTimer. (e.g. in onResume)

**Comment by PierfrancescoSoffritti** [comment]
Hey thanks for reporting the issue. Have you tried manually calling `resumeTimer`? does it work?

**Comment by pparkppark** [comment]
yes. I created empty webview on screen and call resumeTimer, player works normally.

**Comment by PierfrancescoSoffritti** [comment]
It makes sense that pausing the global timer affects the library. It should be up to the caller to restore the timer.
