### ISSUE TITLE
Unable to restart after release

### ISSUE THREAD

**Issue by arunkr83** [PierfrancescoSoffritti/android-youtube-player#824]
How to restart the player after calling 'playerview.release'. 

videoPlay.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {

                         youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                            @Override
                            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                                super.onReady(youTubePlayer);
                                youTubePlayerView.setVisibility(VISIBLE);
                                youTubePlayer.loadVideo(getVideoId(url), 0);
                            }
                        });
 }
                        });

 @Override
    public void onBackPressed() {
             youTubePlayerView.release();
}

 It is not calling onReady once it is released. How can i solve.? Please help

**Comment by PierfrancescoSoffritti** [comment]
You should release the player only when you intend to stop using it. You can't restart after release.
