### ISSUE TITLE
showFullScreenButton not found 

### ISSUE THREAD

**Issue by Dkathayat** [PierfrancescoSoffritti/android-youtube-player#826]
I am enable to link showfullscreenbutton and other attributes like showYouTubeButton,showVideoCurrentTime etc in XML i am only tyring to use  showfullscreenbutton but other options does not show either
![Screenshot 2022-03-12 091844](https://user-images.githubusercontent.com/64710620/158002575-87a51f6c-9478-4798-ad0a-f5c3f74eaf35.jpg)

**Comment by Dilmohit** [comment]
dude i am also having the same issue. did you find any solution??

`AAPT: error: attribute showVideoDuration (aka com.diltech.firebaserecv:showVideoDuration) not found.`

**Comment by PierfrancescoSoffritti** [comment]
Hi, which version of the library are you using?

**Comment by Dilmohit** [comment]
> Hi, which version of the library are you using?

`implementation 'com.pierfrancescosoffritti.androidyoutubeplayer:core:11.0.1'`

Am trying to get videoID from firebase Realtime Database in recyclerView

**Comment by Dilmohit** [comment]
@PierfrancescoSoffritti 

hi, thanks for replying

i am trying to get videoIds from firebase realtime database in recyclerview. Everything works fine the videos gets stream in recyclerview perfectly. but these attributes that i have add does not work and i get an error like this.

Android resource linking failed - AAPT: error: attribute showSeekBar (aka com.diltech.firebaserecv:showSeekBar) not found.

<img width="609" alt="cardverror" src="https://user-images.githubusercontent.com/96916323/161194836-4d4cc05e-548a-4ace-b8c9-90aa17303307.png">


however when i remove these attributes everything just works fine

here are the dependencies that i use 

<img width="548" alt="depen" src="https://user-images.githubusercontent.com/96916323/161195002-57be3314-4bfb-4e98-ba85-f1c6d32d5398.png">

**Comment by PierfrancescoSoffritti** [comment]
Version 11 does not support those attributes, see release notes: https://github.com/PierfrancescoSoffritti/android-youtube-player/releases/tag/11.0.0

**Comment by him130** [comment]
I'm Also find the same error 

attribute showFullScreenButton (aka com.webandappdevelopment.serviceshop:showFullScreenButton) not found.
![error](https://user-images.githubusercontent.com/132055498/235136959-79f923bf-b63e-4371-8bb8-6c028fdcf0af.png)
