### ISSUE TITLE
YouTube button not working

### ISSUE THREAD

**Issue by porkyhead** [PierfrancescoSoffritti/Android-YouTube-Player#83]
When pressing the YouTube button nothing happens.

Is it possible to listen for click event for that button or hide the button entirely?

Testing on:
Google Pixel
Android 8.1

**Comment by PierfrancescoSoffritti** [comment]
Hi, thank you for reporting the issue. I've just patched the issue, the button is working in version 4.1.4!

One of the upcoming features will allow users of the library to completely replace the UI, it will be possible to better customize the appearance then.

**Comment by porkyhead** [comment]
Thanks for the fast action - 4.1.4 fixes the issue! 

Looking forward to the upcoming features.

**Comment by polysiya** [comment]
Great update :) Please update README @PierfrancescoSoffritti
