### ISSUE TITLE
onReady never called when enter and exit activity quickly

### ISSUE THREAD

**Issue by ducdat-ptit** [PierfrancescoSoffritti/android-youtube-player#830]
https://user-images.githubusercontent.com/12276929/159845665-beb807da-adb2-412d-8adb-0622808b264f.mp4

**Comment by PierfrancescoSoffritti** [comment]
did you make any change to the code?

**Comment by ducdat-ptit** [comment]
> did you make any change to the code?

No. I didn't. The video is from sample apk:  ([core v11.0.1.apk](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/apk/core%20v11.0.1.apk)

**Comment by nerooke** [comment]
> did you make any change to the code?

 I have same issue, player do not ready in this case.

**Comment by PierfrancescoSoffritti** [comment]
Which device are you using?

**Comment by ducdat-ptit** [comment]
I checked on Samsung s10 (api 31), Samsung note10 (api 31), Pixel 4 (api 30), Xiaomi redmi note 8 (api 30)

**Comment by PierfrancescoSoffritti** [comment]
I just tried and everything works fine for me. Maybe it's something local to your build?

**Comment by ralexey** [comment]
@PierfrancescoSoffritti 
I tried to use your library at the project for my client and i got the same behaviour.
Tested on several devices with Android 12 (Pixel 3a XL in my case)
I can open/close 2-3 time the activity and it shows the YT video, but it shows the black screen on the next time and doesn't call the onReady. But if i close/open the activity again - it works fine.

I used the manual initialisation, set the lifecycle and manual load or cue the YT video id.

**Comment by Wayne-Wang-Wayne** [comment]
I got the same issue here, what is the fix QQ?

**Comment by Fangzsx** [comment]
Faced the same issue. Any workaround to fix this?

**Comment by minseokchoi** [comment]
I have same issue
chrome app 98.0.4758.101 No problem
chrome app 100.0.4896.88 there is a problem

This is a problem caused by the latest Chrome update.
If your app is large, you may have to wait longer. 5 to 10 seconds

@PierfrancescoSoffritti
Any workaround to fix this?

**Comment by Fangzsx** [comment]
Hi guys. I know this seems messy but I tried overriding the onError. I called the youtubePlayer.loadVideo again and insert the responding videoID. If the youtube player display playback error, if you click the video, loadvideo will be called once again hence, loading the video again.

**Comment by brain-deaf** [comment]
Also encountering this issue when replacing the fragment with a new one. The `YouTubePlayerCallback` is never called.

**Comment by robm92** [comment]
Same issue here, when contained in an AndroidView for Jetpack Compose, recomposing often causes a blank screen on the player.

**Comment by PierfrancescoSoffritti** [comment]
It could be related to the version of WebView. 

The only idea I have is to try building a simple sample app with compose and try to fix it from there.

**Comment by flauschtrud** [comment]
It's not a compose issue, both the black webview as the NoClassDefFoundError can be reproduced with the sample apps (with a new enough Chrome/Webview version). It's hard to tell whether they are independent problems or one causes the other, but they both seem to occur only with newer Chrome/Webview versions.

I'm willing to spend some time to look deeper into it, but do not have an idea yet where to start. 

(but I updated all the dependencies in the core project and the sample app, this did not change anything)

**Comment by whogashaga** [comment]
If onReady() was not called, is there any way to reinitialize the PlayerView ?

**Comment by PierfrancescoSoffritti** [comment]
Thanks to @flauschtrud , this will be available starting from version 11.1.0.

**Comment by sreejith-hme** [comment]
Similar issue is happening with latest version 11.1.0.

Player works fine initially, but stops working if any other webview is opened within the app.
In our app, there is webview browser to read webpages. Once that webview is opened, and then tries to load youtubeplayer in another activity, YoutubePlayerView is not loading webview and there is no onReady callback.

Looking at chrome debug, webview is blank, no content is loaded.

Tried reverting to 11.0.0. It is stuck with white youtubeplayer view. 
In 11.1.0, white view comes, then goes black, but no web player.
