### ISSUE TITLE
Regarding "http" url added on DefaultPlayerUiController

### ISSUE THREAD

**Issue by sunilparmar04** [PierfrancescoSoffritti/android-youtube-player#831]
Hi Guys,

Thanks you for beautiful library.This help us a lot.

There is one issue when we use  android:usesCleartextTraffic="false" in one of our app VAPT report we got issue use "HTTP" instead of "HTTPS".

After debugging found that in your core library one of method onVideoId()  in  DefaultPlayerUiController containing static url "http://www.youtube.com/watch?v="
<img width="1273" alt="Screenshot 2022-04-01 at 1 05 35 PM" src="https://user-images.githubusercontent.com/17490366/161217218-f1c70e72-35d3-4538-8b8c-d64b55222186.png">

Here I am attaching screenshot:
Version used: com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5
Library: ndroidyoutubeplayer:core
Class: DefaultPlayerUiController
Method: onVideoId

Please make it HTTPS that will help us to resolve VAPT issue 

Thank you,
Regards,
Sunil

**Comment by PierfrancescoSoffritti** [comment]
Hi, i suggest you update to version 11, this issue should be solved.

**Comment by sunilparmar04** [comment]
Got it. Thanks for prompt response.
