### ISSUE TITLE
How to check if youtubeplayerview is initialized?

### ISSUE THREAD

**Issue by BhagyashreeWani** [PierfrancescoSoffritti/android-youtube-player#832]
Hi, Thank you for this library.

Use case -

 I have set enableAutomaticInitialization to false and initializing youtubeplayerview manually. I have loadVideo("xyz") method inside onReady().

First time video is playing correctly but  For the second video to play when I am using the same code it is throwing error as - 
 java.lang.IllegalStateException: This YouTubePlayerView has already been initialized.
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.LegacyYouTubePlayerView.initialize(LegacyYouTubePlayerView.kt:87)
        at com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView.initialize(YouTubePlayerView.kt:96)

So how can I check if it is already initialized?

**Comment by PierfrancescoSoffritti** [comment]
You can't initialize the same player twice. Please take a look at the examples in the sample app.

**Comment by BhagyashreeWani** [comment]
Is there any method to check if player is already initialized?

**Comment by jeffmoreta** [comment]
@BhagyashreeWani I'm in the same, I need a solution
