### ISSUE TITLE
Save video state on orientation change without adding config changes in manifest

### ISSUE THREAD

**Issue by Jiordiro** [PierfrancescoSoffritti/android-youtube-player#834]
Hello, thank you very much for the contribution, I would like to implement it in an application that I have been developing for a while , the application restarts when a change is made in the configuration, so I cannot put:
android:configChanges="orientation|screenSize|keyboardHidden|smallestScreenSize|screenLayout"
in the manifest

How could I save the state of the youTubePlayerView when making a change in orientation?

Mainly the video load and playback time.

**Comment by PierfrancescoSoffritti** [comment]
If your app needs to restart on orientation change, you can save the player state (video id, playback time) and restore them manually when the app restarts.
