### ISSUE TITLE
Play video error : Video unavailable (This video contains content from Nmedia Network, who has blocked it from display this application. Watch on Youtube. 

### ISSUE THREAD

**Issue by hoanglocmdc** [PierfrancescoSoffritti/android-youtube-player#835]

**Comment by PierfrancescoSoffritti** [comment]
As the error says, YouTube doesn't allow you to play this video outside of the YouTube app/website.

**Comment by hoanglocmdc** [comment]
@PierfrancescoSoffritti how do I fix this?

**Comment by PierfrancescoSoffritti** [comment]
I don't think you can.

**Comment by hoanglocmdc** [comment]
But i used the other Youtube player view then i can watch this video. Can you help me fix this issue, it is so important for my project.

**Comment by PierfrancescoSoffritti** [comment]
As the error says, the owner of the video blocked the video from playing outside of YouTube.
