### ISSUE TITLE
Second video does not initialize

### ISSUE THREAD

**Issue by victorasou** [PierfrancescoSoffritti/android-youtube-player#836]
Hi guys, I just setted two videos in two different youtubePlayerView. When you click on, the video starts correctly, with no problems, but when you start the second video, this one does not start at the time, one minute later (aprox.), if yoyu click on the video again, this starts. My problem is that I cannot start two videos one after other, the second one just initialize but not starts :(

Thanks!!

**Comment by Wayne-Wang-Wayne** [comment]
In my scenario. Sometimes onReady function didn't be called so the video didn't play. The situation will happen when I play the next video too quickly. I don't know why webView didn't fire onReady function properly.

**Comment by PierfrancescoSoffritti** [comment]
Maybe related to #830 ?

**Comment by PierfrancescoSoffritti** [comment]
This should be fixed in version 11.1.0.
