### ISSUE TITLE
YoutubePlayerView Doesn't Get Filtered in FireStoreRecyclerAdapter Search

### ISSUE THREAD

**Issue by ikhayat** [PierfrancescoSoffritti/android-youtube-player#837]
So in my app, I have a `FireStoreRecyclerAdapter `which is just a recyclerview that takes in data from firestore and so the problem, in short, is that the 'YoutubePlayerView' doesn't get filtered when I search using `addOnTextChangedListener`.  

As you can see here when I search it doesn't get filtered like the text.
![E](https://user-images.githubusercontent.com/58909346/162431662-810a79d5-ac09-4a70-b936-9ace8a42cc3a.PNG)
![E1](https://user-images.githubusercontent.com/58909346/162431673-ee2bdb91-c379-4bb6-86a6-f11d36f5724d.PNG)

**This is the code that is being used to filter/search in the FireStoreRecyclerAdapter**
![E4](https://user-images.githubusercontent.com/58909346/162431654-db3807bc-b49d-4290-b9a9-945c1e811985.PNG)

**This is the code in my `OnBindViewHolder` in the `FireStoreRecyclerAdapter`**
![E5](https://user-images.githubusercontent.com/58909346/162431659-84a22be7-ccf1-45c5-a75c-10914938ef79.PNG)

**Comment by ikhayat** [comment]
Also, the version I'm using is `11.0.1`

**Comment by PierfrancescoSoffritti** [comment]
I don't understand, isn't the issue in your Firestore adapter? can you explain how the issue is related to the YouTube player?

**Comment by ikhayat** [comment]
> I don't understand, isn't the issue in your Firestore adapter? can you explain how the issue is related to the YouTube player?

I'm not really sure, since the adapter works quite well. The YoutubePlayer doesn't get reinitialized when I search, though the texts (aka titles & subtitles in card) do change and get filtered (view example in the uploaded photos, if you may), I am not sure why the YoutubePlayer doesn't.

(I also must thank you in advance for this amazing library, I am pretty sure you'll have a successful life ahead, and I myself wish you all the best)

**Comment by PierfrancescoSoffritti** [comment]
I don't have enough information to help you exactly, but i suggest you don't re initialize the player each time you search for something. Keep the initialized players in the recycler view, then just cue/load a new video when you search.

Re initializing should also be fine, but i think will take longer.

**Comment by ikhayat** [comment]
> I don't have enough information to help you exactly, but i suggest you don't re initialize the player each time you search for something. Keep the initialized players in the recycler view, then just cue/load a new video when you search.
> 
> Re initializing should also be fine, but i think will take longer.

Ohhhh I think that I understand what you mean now, thank you! Also, thanks a lot for this library!!
