### ISSUE TITLE
hide youtube button

### ISSUE THREAD

**Issue by didi789** [PierfrancescoSoffritti/Android-YouTube-Player#84]
Can you add an option to hide youtube button?

**Comment by PierfrancescoSoffritti** [comment]
This change will require a major version bump, I should have designed the interface differently. I plan to redesign it in the next major version, this functionality will be implemented there.

It will be possible to completely replace the UI allowing for far better customization.

For now I suggest you just fork the lib and add the method yourself.

**Comment by PierfrancescoSoffritti** [comment]
related to #68

**Comment by PierfrancescoSoffritti** [comment]
Starting from version 4.1.7 you can remove the YouTubeButton.

`youTubePlayerView.getPlayerUIController().showYouTubeButton(false);`
