### ISSUE TITLE
Swipe off screen to resume playback

### ISSUE THREAD

**Issue by Kola-Chao** [PierfrancescoSoffritti/android-youtube-player#843]
This is a great library, thanks for your efforts. I encountered a problem when integrating in the project, the playView is placed in a RecycleView. When the playView is slid off screen. The video playback will automatically pause, how can I make it slide off the screen and continue playing?

**Comment by PierfrancescoSoffritti** [comment]
It's against the youtube terms of service to play a video while it's not visible on the screen.

**Comment by Kola-Chao** [comment]
> It's against the youtube terms of service to play a video while it's not visible on the screen.

OK，thanks
