### ISSUE TITLE
Not show full screen button in player

### ISSUE THREAD

**Issue by KishanViramgama** [PierfrancescoSoffritti/android-youtube-player#850]
**Not show full screen button in player** 

![Screenshot_1](https://user-images.githubusercontent.com/18188589/166096010-0eaf456d-1903-481a-88b4-e0111b479f1e.png)

**Can i am using full screen control in `11.0.1` library**

**Comment by PierfrancescoSoffritti** [comment]
Hi, the library does not handle full screen logic, it's up to you to write it in your app. Take a look at the sample app for examples.
