### ISSUE TITLE
OnReady Callback not received in Recycler view 

### ISSUE THREAD

**Issue by venbab** [PierfrancescoSoffritti/android-youtube-player#852]
@PierfrancescoSoffritti using API 31 Hardware (SOS) .When we run activity with 6 YouTube player list item by using recycle view sample code which is present in this git hub , the first 4 Youtube videos are cued, but the second two videos are not cued, if we scroll up and down and then launch activity again, some of the YouTube videos are not cued.  When i debugged onReady callback is not called for those videos which is not loaded, So could you please give a clue why it is not working . It's not sample problem i have checked multiple SOS hardware 

This issue is happening with sample Recycler view also , Just do multiple scroll up and down 

I have checked in QOS and ROS hardware   ,it is working fine 

Chrome app version in ROS hardware (98.0.4758.101) ( It is working fine )
chrome app version in SOS hardware : 101.0.4951.61 (it is not working )

Do we need to change any underlying concept of JS callback system to android ? , I am not familiar with  JS , But i am trying to do search for the same.

If you have get any information please let me know .

**Comment by eduardoyuren-happydev** [comment]
I have the same issue, any update?

**Comment by fcoconstante** [comment]
The same issue, it seems that it takes too much time to load, also it just load one time on the recycler view.

**Comment by Rocher0724** [comment]
The same problem occurs with viewpager2.

**Comment by PierfrancescoSoffritti** [comment]
This should be fixed in version 11.1.0.
