### ISSUE TITLE
Remove suggested videos or thumbnails from imbedded video

### ISSUE THREAD

**Issue by JosiYosi** [PierfrancescoSoffritti/android-youtube-player#853]
Is there any method on how to remove suggested videos or thumbnails from imbedded video when the current video ended playing.

**Comment by PierfrancescoSoffritti** [comment]
Hi, unfortunately it's not possible. It's part of the YouTube IFrame Player.

**Comment by JosiYosi** [comment]
Ok, Thanks for your reply. Actually, I read it in YouTube documentation that it says exactly like you said it. The only reason I asked this question is that if there is any hack. I found on though. When video playing ended, seek back to 0 and then pause video. Or Cue video . Even though it is not perfect, it works though. 



                    ` @Override
            public void onStateChange(@NonNull YouTubePlayer youTubePlayer, PlayerConstants.PlayerState state) {


                
               if(state.equals(PlayerConstants.PlayerState.ENDED)){
                    //When video playing ended, seek back to 0 and then pause video
                    //Its purpose is to avoid displaying suggested related videos from youtube.
                   

                    //Option one
                    youTubePlayer.cueVideo(videoId,0);
                    
                    //Option two
                    youTubePlayer.seekTo(0);
                    youTubePlayer.pause();
                   
                   }


            }
`
