### ISSUE TITLE
Please add option to hide channel logo title and 3 dot menu. and add full screen button again.

### ISSUE THREAD

**Issue by fuchsialab** [PierfrancescoSoffritti/android-youtube-player#854]

**Comment by PierfrancescoSoffritti** [comment]
Hi, it's not possible because the IFrame player does not allow it.

**Comment by pramodshri-tgsys** [comment]
the logo, title & the 3 dot menu appears even when `DefaultPlayerUiController` is used and the video is not playing. Is that expected? Is there a way to hide them atleast in `DefaultPlayerUiController`?

**Comment by PierfrancescoSoffritti** [comment]
It's not possible to hide them. The IFrame player does not allow it.

**Comment by adarshdhakad** [comment]
you can hide them use 
        android:layout_marginTop="-100dp"
        android:layout_marginBottom="-100dp"

then they will gone
