### ISSUE TITLE
When clicked by a pointing device(mouse), connected to the mobile/device, videos are getting redirected to youtube(on the click of the video title or youtube logo).

### ISSUE THREAD

**Issue by articlp** [PierfrancescoSoffritti/android-youtube-player#865]
Attaching video for reference

[https://drive.google.com/file/d/1YNxdtlgx8HxEgXO3nMWz24xKOIaNGKTb/view?usp=sharing](url)

**Comment by PierfrancescoSoffritti** [comment]
I can't access your video. But from what you're saying this seems intended behaviour to me.

**Comment by articlp** [comment]
Is there any way to prevent it like how we prevent it for finger touch? 

To play the video, copy the URL and open it in a new tab
