### ISSUE TITLE
Video is redirecting to youtube when we connect the device to mouse and click the youtube watermark or heading

### ISSUE THREAD

**Issue by GauravPoswalAndroid** [PierfrancescoSoffritti/android-youtube-player#866]
Problem:
- Top UI(in custom UI example) is working fine as it is not letting us open youtube when we click it via finger but with pointing device it's redirecting to youtube.

Question
- What's the trigger point for mouse click events and how can I prevent it?

Attaching the video for reference

https://user-images.githubusercontent.com/79838202/179747887-e8287dbc-f01f-4ef0-823a-11c00701bb13.mp4

**Comment by articlp** [comment]
I too am facing the same issue. I think we need to make parent view clickable false. @PierfrancescoSoffritti any suggestions?

**Comment by PierfrancescoSoffritti** [comment]
This is the expected result, those views are clickable in the IFrame player.

**Comment by articlp** [comment]
Is there any way we can make it non-clickable?

**Comment by PierfrancescoSoffritti** [comment]
Hi, in your layout you can just add a View above the player to intercept clicks.
