### ISSUE TITLE
Pop How to disable

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#868]
Pop How to disable

what should i do? 
#[](url
![WechatIMG5](https://user-images.githubusercontent.com/30317994/180424976-1ea4b437-f118-4880-815e-1e847f25cbfc.jpeg)
)

**Comment by karshsoni** [comment]
You cant or wont be able to disable with native UI. Customize the ui and it'll be gone.

**Comment by PierfrancescoSoffritti** [comment]
I think you need to intercept clicks to the view. Or create a custom UI as @karshsoni suggests.

**Comment by AzizaHelmy** [comment]
@karshsoni  @PierfrancescoSoffritti  can you display more how can customize the ui, please ? 
as i used custom view but nothing gone still same issue

My code:
val customView=DefaultPlayerUiController(this@apply,youTubePlayer)
                                customView.showFullscreenButton(false)
                                customView.showYouTubeButton(false)
                                setCustomPlayerUi(customView.rootView)
