### ISSUE TITLE
Why are we not using the WebView's cache?

### ISSUE THREAD

**Issue by flauschtrud** [PierfrancescoSoffritti/android-youtube-player#869]
I noticed that caching is explicitly set to `WebSettings.LOAD_NO_CACHE` in WebViewYouTubePlayer.initWebView.

Is there a reasoning behind this?

I set it to `WebSettings.LOAD_DEFAULT` and did not encounter any problems, while saving a lot of network traffic (thumbnails, JS and CSS for the embedded player).

The doc for reference: https://developer.android.com/reference/android/webkit/WebSettings#LOAD_NO_CACHE
`WebSettings.LOAD_NO_CACHE`: Don't use the cache, load from the network.
`WebSettings.LOAD_DEFAULT`: Default cache usage mode. If the navigation type doesn't impose any specific behavior, use cached resources when they are available and not expired, otherwise load resources from the network.

**Comment by PierfrancescoSoffritti** [comment]
Yeah, we should probably use the cache.

**Comment by PierfrancescoSoffritti** [comment]
Feel free to send a PR for this, if you have time. Otherwise I'll do it before releasing the next version.

**Comment by PierfrancescoSoffritti** [comment]
Thanks to @flauschtrud , this will be available starting from version `11.1.0`.
