### ISSUE TITLE
Only controls/audio play, video does not play

### ISSUE THREAD

**Issue by Matt-Owens** [PierfrancescoSoffritti/Android-YouTube-Player#87]
I have an issue where the controls of the video are shown but the video itself doesn't play.  I can hear audio noise but it's almost as if the video is completely transparent/invisible.  I am also able to pause/play, etc.

Any idea why this could be happening?

Here is my code:

In OnActivityCreated:
```
        val youTubePlayerView = youtube_player_view
        youTubePlayerView.initialize({ initializedYouTubePlayer ->
            initializedYouTubePlayer.addListener(object : AbstractYouTubePlayerListener() {
                override fun onReady() {
                    val videoId = "0PWu3BRxn60"
                    initializedYouTubePlayer.loadVideo(videoId, 0f)
                }
            })
        }, true)
```

in Layout:
```
    <com.pierfrancescosoffritti.youtubeplayer.player.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="500dp"
        android:layout_height="wrap_content"
        android:rotation="90"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintDimensionRatio="w,16:9"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:layout_constraintVertical_bias="0.45" />
```

**Comment by PierfrancescoSoffritti** [comment]
Hi, can you tell which phone and version of Android are you using? and whether you're using a custom rom.
I have encountered a similar problem on KitKat, with Cyanogenmod on a Samsung Galaxy S2.

**Comment by Matt-Owens** [comment]
@PierfrancescoSoffritti I am using the Pixel 2 XL API 27 emulator.  Although it seems to happen on a number of devices I test both on the emulators and browserstack app live, no custom ROM.

**Comment by PierfrancescoSoffritti** [comment]
Ok, I can confirm the player has this problem on emulators. I think it's related to the version of Webview or the graphics drivers they're using. I'm not particularly familiar with Browserstack app live, but I suppose the problems are related.

I suggest testing the player on a real device. I have an app in production using it and never had any issue, this problem is limited to emulators.

**Comment by Matt-Owens** [comment]
@PierfrancescoSoffritti Browserstack app live uses real devices to test, and I tested on a Nexus 6.  Our client also tested on their phone and experienced the issue (waiting to hear what device they were on).

**Comment by Matt-Owens** [comment]
Edit: Bug happens on Samsung Galaxy S7 as well.

**Comment by PierfrancescoSoffritti** [comment]
This library has been tested on a good number of real devices, including nexus 6, and it worked well. Probably Browserstack had to do some adjustments to the OS, similar to those on the Android emulator.

Is this S7 a physical or virtual/remote device?

**Comment by PierfrancescoSoffritti** [comment]
I've just rebuilt the app on my pixel 2 XL, to check if maybe YouTube has changed something in the Javascript API. I can confirm everything is working as expected on my device.

**Comment by Matt-Owens** [comment]
Ok, most likely it's something I've done with other videos that might be affecting the playback.  I'm going to dig a little deeper and update if I find a resolution.  Thanks so much for your quick help.

**Comment by PierfrancescoSoffritti** [comment]
I've now tested on a Nexus5 and 5X, everything works there as well.
Again, I'm confident the issue is in the emulated/remote device.

Let me know if you make any progress!

**Comment by Matt-Owens** [comment]
@PierfrancescoSoffritti The issue seems to stem from adding the following inside manifest.
`android:hardwareAccelerated="false"`

Once that is removed, everything works fine.

Thank you for your help and the great library you've created.

**Comment by PierfrancescoSoffritti** [comment]
That makes sense! I will add it to the library.
Thanks to you for the help, this never occurred to me.

**Comment by ekoforiakoto** [comment]
Thanks@@PierfrancescoSoffritti I was having a similar issue when I was using the Pixel 4XL emulator , the video was not showing. But when I changed it to Pixel 2XL  as recommended the video is showing and playing seamlessly. Thumbs up **@PierfrancescoSoffritti**

**Comment by simar1810** [comment]
> @PierfrancescoSoffritti The issue seems to stem from adding the following inside manifest. `android:hardwareAccelerated="false"`
> 
> Once that is removed, everything works fine.
> 
> Thank you for your help and the great library you've created.

Thanks a lot Mat-Owens , I was Facing Same Issue , now it is done Thanks ALot.
