### ISSUE TITLE
Default UI Does Not Contains the FULL Screen Icon.

### ISSUE THREAD

**Issue by narendra2313** [PierfrancescoSoffritti/android-youtube-player#879]
I integrate the this lib with default behavior but not able to see the full screen icon over there. also added DefaultPlayerUiController but seems not working properly so can u plz provide a solution for that how the full screen icon will be shown ??

**Comment by PierfrancescoSoffritti** [comment]
I suggest not adding the full screen button to the player, as it might break YouTube terms of service. Use the default webUi and find alternative UX to enter full screen.
