### ISSUE TITLE
Use YouTubePlayerView no work in Android TV 

### ISSUE THREAD

**Issue by fiveshit** [PierfrancescoSoffritti/android-youtube-player#880]
I use Emulator and use YouTubePlayerView  to implement youtube play function in Android TV
Android Studio version : 2021.2.1 , Android TV (1080p) API 30
My XML file code as below 
```
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:id="@+id/layout_youtube"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_marginLeft="100dp"
        android:layout_marginBottom="100dp"
        android:layout_marginRight="100dp"
        android:layout_marginTop="100dp"
        app:videoId="NUjV1qClr_c"
        app:autoPlay="true"
        />
```
I think It will play youtube when android TV is started. but it's  blackscreen.
 I try same code burn to phone. It can work on phone. 
I don't know why

**Comment by ishraftaifur** [comment]
@fiveshit I am also facing this issue. Did you find any solution?

**Comment by PierfrancescoSoffritti** [comment]
Sometimes emulators have problems with WebView.

Also double check that you Activity is hardware accelerated
