### ISSUE TITLE
react-native-sdk package 

### ISSUE THREAD

**Issue by 92sajid110** [PierfrancescoSoffritti/android-youtube-player#882]
i am using  react-native-sdk package and depends upon version 'com.pierfrancescosoffritti.androidyoutubeplayer:core:10.0.5' but it didn't found please help me to find this package

**Comment by PierfrancescoSoffritti** [comment]
I suggest you use version `11.1.0`. Version `10.0.5` does not exist.

**Comment by 92sajid110** [comment]
but react-native package is not updated from 2 years and i didn't know java to update package

**Comment by PierfrancescoSoffritti** [comment]
I never published any react native package, can you please explain what are you referring to?
