### ISSUE TITLE
hidden title not working

### ISSUE THREAD

**Issue by xueqiya** [PierfrancescoSoffritti/android-youtube-player#885]
hidden title not working
val options = IFramePlayerOptions.Builder().controls(1).build()

**Comment by Serkali-sudo** [comment]
`controls` parameter doesn't hide the title, it just hides controllable objects like slidebar etc...
There is a unofficial workaround to delete it but **changing UI may be against to Youtube IFrame Terms. I am not sure .**
Anyways here it is:
1) go to res/raw/ayp_youtube_player.html and add this code(**Call this function from onReady callback**):
```js
function hideVideoTitle() {
    setInterval(() => {
        const playerIFrame = document.querySelector("iframe");

        if (!playerIFrame) {
            return;
        }

        const frameDoc = playerIFrame.contentDocument;

        if (!frameDoc) {
            return;
        }

        const title = frameDoc.querySelector('.ytp-chrome-top');
        if (title) {
            title.style.display = 'none';
        }

    }, 100);
}

```

**Comment by PierfrancescoSoffritti** [comment]
@Serkali-sudo Maybe we can add these workarounds to the FAQ section in the readme?

**Comment by Serkali-sudo** [comment]
> @Serkali-sudo Maybe we can add these workarounds to the FAQ section in the readme?

Well i have more workarounds.
If you think it will help the users I can combine and pr them
Here's list of workarounds i have so far:
1. [Changing playback quality](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/27#issuecomment-1187111255)
2. [User authentication to play private videos](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/845#issuecomment-1119508927)
3. Blocking Ads ( Auto Ad Skip )
4. Remove views that cannot be removed by the `controls` parameter ( For example annoying 'other videos' view when you stop video)
5. Hiding Subtitles (official function for hiding subtitle doesn't work for some reason so there is workaround)
6. Playing next video by getting video id from 'other videos' section.(The video does not need to be in a playlist to play the next video.)
7. Does it support YouTube shorts ? questions

**Comment by PierfrancescoSoffritti** [comment]
Yes, if you have the time I think it would be very useful! We can't implement these features in the library because they might break at anytime, but some users might be ok with taking the risk :)
