### ISSUE TITLE
Possibility to load another playlist when there is already one playing?

### ISSUE THREAD

**Issue by joneserick** [PierfrancescoSoffritti/android-youtube-player#886]
I'm trying to load another playlist when the user touches a view. But currently I can only see support for loading videos by its id.

I'm setting up the iframe options before initializing the player itself but I can't see any options to change the current playlist that is playing.

Is there any possibility to do it?

I thought that would be nice to have a `loadPlaylist()` and `cuePlaylist()` methods but I also couldn't see anything related to it on iframe's documentation.

**Comment by joneserick** [comment]
Just to update, I've found something related to [loading playlists](https://developers.google.com/youtube/iframe_api_reference#Playlist_Queueing_Functions). I'm going to work on it to provide this support.

**Comment by joneserick** [comment]
Yeah I did, but I couldn't find something related to load another playlist in the current player because `loadVideo` or `cueVideo` methods doesn't work by passing the playlist id.

**Comment by joneserick** [comment]
I just tried other approach! I'm recreating the PlayerView with the new playlist id when the user chooses a option to load other playlist. 

It looks like a workaround! Would be nice to have the option to load another playlist without recreating the entire view.

**Comment by PierfrancescoSoffritti** [comment]
I am glad you found a solution for now :)
