### ISSUE TITLE
 Issue : enableAutomaticInitialization  not working programmatically

### ISSUE THREAD

**Issue by NaveenDevrani** [PierfrancescoSoffritti/android-youtube-player#889]
youtubePlayerView?.enableAutomaticInitialization = true
this is not working programmatically,
if I use like this app:enableAutomaticInitialization="false" 
then it works

please find the solution 

Also, can you tell me, how to adjust the screen aspect ratio?
On top and bottom lot of space is visible.

**Comment by aryangupta24** [comment]
I also faced the same

**Comment by PierfrancescoSoffritti** [comment]
Hi, I am not sure what you're asking. Can you be more specific?

I'm closing for now as this issue is quite old. Feel free to reopen if you want to continue the conversation.
