### ISSUE TITLE
Failed to resolve: com.github.PierfrancescoSoffritti:AndroidYouTubePlayer:4.1.*

### ISSUE THREAD

**Issue by SrHalf** [PierfrancescoSoffritti/Android-YouTube-Player#89]
Hi! Recently I have found your project and I'm considering replace the official YoutubePlayerAPI in my app, but Gradle isn't downloading any version (4.1.4, 4.1.5).
How can I fix this?

**Comment by PierfrancescoSoffritti** [comment]
Hi, have you added this to your project-level build.gradle file?
```
allprojects {
  repositories {
    ...
    maven { url "https://jitpack.io" }
  }
}
```

**Comment by SrHalf** [comment]
Oh yeah! But there was a odd little typo! Haha
Sorry about that

Congrats for the project! It's gonna be so much useful

**Comment by PierfrancescoSoffritti** [comment]
Thanks, hope so 😄

**Comment by TommyXjaomi** [comment]
Failed to resolve: com.pierfrancescosoffritti.androidyoutubeplayer:ui:12.1.0
Omg i really helps :<
