### ISSUE TITLE
Make YouTubePlayerView class open so it can be inherited

### ISSUE THREAD

**Issue by 1nikolas** [PierfrancescoSoffritti/android-youtube-player#890]
# Feature Request

### Describe your idea
I'm making a custom Player UI. I wanted to modify `YouTubePlayerView` in order to override stuff like `onTouchEvent` or add an `OnGestureListener` (this way you can add brightness and volume gesture controls, swipe to seek, etc) but it seems to not be possible due to the class not being `open`. ExoPlayer allows similar functionality (inheriting the PlayerView). I know that there are many other ways to do this but this seems the more appropriate solution.

### What happens now:
![image](https://user-images.githubusercontent.com/30593419/193890407-31297b74-e660-4d20-86ac-b46420682660.png)

### Required changes
I think this would be enough (at least that's what it says [here](https://stackoverflow.com/a/48401985/8627813))

`class` -> `open class`
https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/f0cc03e87d3d363de0d423ce2e3efc713ada2ae5/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/YouTubePlayerView.kt#L22

**Comment by PierfrancescoSoffritti** [comment]
Hi, have you tried [creating a custom UI](https://github.com/PierfrancescoSoffritti/android-youtube-player#create-your-own-custom-ui) first?

**Comment by 1nikolas** [comment]
Okay I took a look on the `DefaultPlayerUiController` and found a better solution to this. I can make a view behind the controller which would have the Gesture Listener (and also act as a WebView click blocker. I don't know why I stuck to the hard solution (I mean theoretically adding the Gesture Listener to the WebView would be more efficient but this is good enough)

**Comment by PierfrancescoSoffritti** [comment]
Cool, glad you found a solution :)
