### ISSUE TITLE
3d Video Touching features

### ISSUE THREAD

**Issue by johnfung95** [PierfrancescoSoffritti/android-youtube-player#897]
Hi, I would like to know whether the DefaultPlayerUiController disables the screen touching feature in a 3d video.

For example, I have embedded the following video using the DefaultPlayerUiController, while the angles of the video can be changed when moving the mobile device, it loses the touching feature (i.e. drag and move the angles within the video).
https://www.youtube.com/watch?v=hNAbQYU0wpg

Are there any advice to enable the feature?

**Comment by johnfung95** [comment]
the video is embedded using as IFramePlayerOptions, and rendered through the DefaultPlayerUiController

**Comment by PierfrancescoSoffritti** [comment]
I suggest you use webUi only (no DefaultPlayerUiController) and see if it works.

**Comment by johnfung95** [comment]
It works but there is no full screen button control in the video...

**Comment by PierfrancescoSoffritti** [comment]
The IFrame player doesn't have a fullscreen button unfortunately. You should implement your own UI, probably outside the player.

**Comment by johnfung95** [comment]
Out of curiosity, may I know the difference between this android-youtube-player and the official youtube player api? I could not play 3d video with the latter in my phone, but I could using your product though....

**Comment by PierfrancescoSoffritti** [comment]
As you can read in the documentation, this library is a wrapper around the
YouTube web player API. The official library shipped by YouTube is a native
implementation of the player (does not use WebView, most likely).

**Comment by johnfung95** [comment]
Okay, thanks a lot~
