### ISSUE TITLE
I want to change package name in only one module core-sample-app but it gives me error of missing class package R, how to solve it?

### ISSUE THREAD

**Issue by Harsh3way** [PierfrancescoSoffritti/android-youtube-player#899]
# Question / Problem

**Comment by Harsh3way** [comment]
I am using this library in my app and i want to publish on playstore so it gives me error of package name exist so i want to change package name in core-sample-app only..

**Comment by PierfrancescoSoffritti** [comment]
The sample app is not meant to be published on the PlayStore. The sample app's package name has my name in it, so please chose your own package name.
