### ISSUE TITLE
Issue with Full screen landscape mode of player

### ISSUE THREAD

**Issue by Noshad22** [PierfrancescoSoffritti/Android-YouTube-Player#90]
Hi thanks for the wonderful library,
 I came across with the weird issue i had arraylist of video ids and i load each video to player on itemClicklistner of listView by using listView position for example when user click on 6 position it will load the 6th video id from arraylist and it will play in portrait mode but the issue is there when user flip to full screen landscape mode the player can not play the current index video it will load and play the first index video which i loaded inside  youTubePlayerView.initialize(youTubePlayerInitListener) in oncreate for the first time when user visit to that screen.
So my question how can i play the current index video when user flip to fullscreen mode.

**Comment by PierfrancescoSoffritti** [comment]
Hi, sorry I was traveling this weekend. I'll get back to you tomorrow!

**Comment by PierfrancescoSoffritti** [comment]
Hi, from your description is very likely that the issue is in your code. Can't say much about that.
