### ISSUE TITLE
YouTubePlayerView is just a black screen, onReady() is never called, no video or audio.

### ISSUE THREAD

**Issue by mrmattkennedy** [PierfrancescoSoffritti/android-youtube-player#900]
# Bug Report

### Description of the Bug

Attempting to load any videos just results in a black screen for the. YouTubePlayerView. I have tried everything, down to copying the basic sample exactly into a new file and project, just getting a black screen.  I can load youtube videos in my browser fine, so I don't believe it's a network issue.

I have tried using the sample exactly as is, initializing automatically and programmatically, tried adding an AbstractYouTubePlayerListener and overriding the onReady() function (it never gets called). Not sure if I am missing something.

### Environment details

Android Version:  13
API Version:  31

Tested devices:

Pixel 5 API 33
Pixel 3a API 33

Youtube Player Library Version: 
Core 11.1.0

### Steps to reproduce the bug
Just running the sample app on any device. A small window will load for the YouTubePlayerView, and will flash white briefly then just go black.

### Expected behavior

Expected to play the video

### Additional information

Layout file:
```
<com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"

            app:videoId="S0Q4gqBUs7c"
            app:autoPlay="true" />
```

Java class:
```
youTubePlayerView = findViewById(R.id.youtube_player_view);
getLifecycle().addObserver(youTubePlayerView);
```

**Comment by PierfrancescoSoffritti** [comment]
Did you run the sample app? (without copying in your own app, I mean running the sample app straight from this project, or by installing the [apk](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/apk/core%20v11.1.0.apk))

**Comment by mrmattkennedy** [comment]
I ran it straight from the project. I just got access to a windows machine and tried it on there, and it seems to work fine. So I am thinkin the issue is the fact that I am using a Mac (it has an apple m1 chip)

**Comment by PierfrancescoSoffritti** [comment]
Thanks for updating the issue. It could be an emulator issue.
