### ISSUE TITLE
Popup not displaying when i click the menu button

### ISSUE THREAD

**Issue by rajkanna7** [PierfrancescoSoffritti/android-youtube-player#902]
Popup not displaying when i click the menu button

<img width="193" alt="image" src="https://user-images.githubusercontent.com/115771799/203725632-d5d7e4df-cf3e-4079-ba64-47b1476cfaea.png">

samsung m12

**Comment by PierfrancescoSoffritti** [comment]
Hi, please update the library to the last version, or if you want to use an
older version use webUi.

**Comment by rajkanna7** [comment]
@PierfrancescoSoffritti  how to disable the that menu option on  WebView , Custom view we have the option to hide that menu but no option in webview

**Comment by PierfrancescoSoffritti** [comment]
The IFrame API doesn't allow it unfortunately.

**Comment by rajkanna7** [comment]
@PierfrancescoSoffritti any option to add listener for webview menu item click listener?
