### ISSUE TITLE
change front page of app

### ISSUE THREAD

**Issue by buffalopilot** [PierfrancescoSoffritti/android-youtube-player#904]
hi, first of all a BIG THANK YOU for this submission.  i was so frustrated with the api and have been wanting better controls for a long time. :) thanks bud.

i was wondering how is the front page being generated, the app goes from main to a simple ectivity with a package exclude that i cant find and then to the selected example.  where is this middle actitity?.  is it comming from a website?  how mucb of the core app is comming from external online source to the app.  how do i get control of the front page?  id like to copy that it comes from a website just to learn and then change  to an activity.

thanks!
cody godines

ps i dowloaded from my pc and am writting this on my mobile.  i dont know why my pass didnt work so typing this seems like i didnt pull it but i did.

**Comment by PierfrancescoSoffritti** [comment]
Hi I'm glad you're finding the library useful. The main page comes from [here](https://github.com/PierfrancescoSoffritti/library-sample-app-template)

**Comment by buffalopilot** [comment]
thank you!! im workung it everyday.  thank you for being so quick and awesome.
