### ISSUE TITLE
DefaultPlayerUiController in recyclerview

### ISSUE THREAD

**Issue by reddragonarchfiend** [PierfrancescoSoffritti/android-youtube-player#905]
I'm having some trouble using DefaultPlayerUiController inside recyclerview.

Where would be the right place to call setFullScreenButtonClickListener for each video, inside onReady in the listener or maybe inside onYouTubePlayer in getYouTubePlayerWhenReady, but there I don't have a reference to the DefaultPlayerUiController ?

Inside the FullScreenButtonClickListener I would like the access the current adapter position and the current YouTubePlayerView

**Comment by PierfrancescoSoffritti** [comment]
You need to do this from the viewholder.
