### ISSUE TITLE
add textview to recycler view example

### ISSUE THREAD

**Issue by buffalopilot** [PierfrancescoSoffritti/android-youtube-player#908]
hi!  can you please show me an example of adding a textview, or button, or edittext in between any of the vids in the recyclerviewexample?  i think you just need to mod recyclerview, the adapter, and add a text or button or edit text xml.

for example replace one vidid with a string and put it in a textview or something.

i have a broken example i tried modding yours, but cant upload directories to github from my terminal.  i commit but dont see files in my repository.  maybe you can just show a quick example until i can figure it out.  how do you upload your stuff to github all at once and if the files are over 25mb anyways?

**Comment by codygo01** [comment]
<androidx.cardview.widget.CardView xmlns:card_view="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/card_view"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginTop="@dimen/activity_horizontal_margin"
    card_view:cardElevation="10dp">
    <TextView
        android:id="@+id/type"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:padding="10dp"
        />


</androidx.cardview.widget.CardView>

package com.pierfrancescosoffritti.androidyoutubeplayer.core.sampleapp.examples.recyclerViewExample;

import android.os.Bundle;

import com.pierfrancescosoffritti.aytplayersample.R;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

public class RecyclerViewActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_recycler_view_example);

        RecyclerView recyclerView = findViewById(R.id.recycler_view);
        recyclerView.setHasFixedSize(true);

        RecyclerView.LayoutManager mLayoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(mLayoutManager);

        String[] videoIds = {"6JYIGclVQdw", "LvetJ9U_tVY", "6JYIGclVQdw", "LvetJ9U_tVY"};
        int[] types = {2,1,1,1};

        RecyclerView.Adapter recyclerViewAdapter = new RecyclerViewAdapter(videoIds, this.getLifecycle(), types);
        recyclerView.setAdapter(recyclerViewAdapter);
    }

}


package com.pierfrancescosoffritti.androidyoutubeplayer.core.sampleapp.examples.recyclerViewExample;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.sampleapp.examples.choreoAID.MultiViewTypeAdapter;
import com.pierfrancescosoffritti.aytplayersample.R;

import androidx.annotation.NonNull;
import androidx.cardview.widget.CardView;
import androidx.lifecycle.Lifecycle;
import androidx.recyclerview.widget.RecyclerView;
// THIS ORDER BELOW THEN CYCLES THROUGH, GET ITEM COUNT ON CREATE VIEW HOLDER BIND 4X
class RecyclerViewAdapter extends RecyclerView.Adapter<RecyclerViewAdapter.ViewHolder> {
    private String[] videoIds;
    private Lifecycle lifecycle;
    private int[] types; // 1 = youtubeplayer, 2 = text box
    private int currentPosition;
    // CONSTRUCTOR
    RecyclerViewAdapter(String[] videoIds, Lifecycle lifecycle,int[] types) {
        this.videoIds = videoIds;
        this.lifecycle = lifecycle;
        this.types = types;
    }
    // THIRD ON CREATE
    @NonNull
    @Override
    public RecyclerViewAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view;

        if (this.types[this.currentPosition]==1) {
            YouTubePlayerView youTubePlayerView = (YouTubePlayerView) LayoutInflater.from(parent.getContext()).inflate(R.layout.recycler_view_item, parent, false);
            lifecycle.addObserver(youTubePlayerView);
            return new ViewHolder(youTubePlayerView);
        }
        if (this.types[this.currentPosition]==2) {
            view = LayoutInflater.from(parent.getContext()).inflate(R.layout.text_type, parent, false);
            return new TextTypeViewHolder(view);
        }
        return null;
    }

    // 5TH
    @Override
    public void onBindViewHolder(@NonNull ViewHolder viewHolder, int position) {
        this.currentPosition=viewHolder.getAbsoluteAdapterPosition();
        // youtube
        if (this.types[viewHolder.getAbsoluteAdapterPosition()]==1)  {
            viewHolder.cueVideo(videoIds[position]);
        }
        // text type
        if (this.types[viewHolder.getAbsoluteAdapterPosition()]==2)  {
            ((this.TextTypeViewHolder) viewHolder).setText("hi");
        }

    }
    // 2ND GET ITEM COUNT
    @Override
    public int getItemCount() {
        return videoIds.length;
    }
    //------------------
    // FOURTH VIEW HOLDER
    static class ViewHolder extends RecyclerView.ViewHolder {
        private YouTubePlayerView youTubePlayerView;
        private YouTubePlayer youTubePlayer;
        private String currentVideoId;

        ViewHolder(YouTubePlayerView playerView) {
            super(playerView);
            youTubePlayerView = playerView;

            youTubePlayerView.addYouTubePlayerListener(new AbstractYouTubePlayerListener() {
                @Override
                public void onReady(@NonNull YouTubePlayer initializedYouTubePlayer) {
                    youTubePlayer = initializedYouTubePlayer;
                    youTubePlayer.cueVideo(currentVideoId, 0);
                }
            });
        }

        void cueVideo(String videoId) {
            currentVideoId = videoId;

            if(youTubePlayer == null)
                return;

            youTubePlayer.cueVideo(videoId, 0);
        }

    } // ViewHolder class --------

    public static class TextTypeViewHolder extends RecyclerView.ViewHolder {

        TextView txtType;
        CardView cardView;

        public TextTypeViewHolder(View itemView) {
            super(itemView);

            this.txtType = (TextView) itemView.findViewById(R.id.type);
            this.cardView = (CardView) itemView.findViewById(R.id.card_view);
        }
    }

}

**Comment by codygo01** [comment]
two accounts I need to figure this out :(

**Comment by buffalopilot** [comment]
they are both me, Cody or buffalo pilot

**Comment by PierfrancescoSoffritti** [comment]
You need to change the Recycler View adapter to handle different types of views.
