### ISSUE TITLE
Please, Explanation in a youtube video :(

### ISSUE THREAD

**Issue by xLeDiaa** [PierfrancescoSoffritti/android-youtube-player#909]
Hi, I'm a newbie in programming and especially with AndroidStudio. I'm making an app that requires to import youtubevideos. I read the library and everything.. yet I can't apply what I read, I get a lot of errors and crashes.. so, can anyone please make a youtube video explaining how to customize the UI ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, this issue is too generic. Please present a specific question if you're having issues.
