### ISSUE TITLE
YouTube video is flickering, but plays OK after pausing and resuming

### ISSUE THREAD

**Issue by milan-fabian** [PierfrancescoSoffritti/android-youtube-player#910]
# Bug Report

### Description of the Bug

I am using this library in a Digital Signage app to play YouTube videos and I received a bug report from one user that a video flickers on their device. I haven't managed to reproduce this bug on any of my devices yet, but I am curious whether anybody has any pointer to what could cause this problem.

### Environment details

Android Version: 9

Android System WebView version: 108.0.5359.128

Tested devices:
- Xiaomi Mi Box 4

Youtube Player Library Version: 11.0.1

### Steps to reproduce the bug

1. Download and install Slideshow app (https://slideshow.digital/how-to-get-it/) on Xiaomi Mi Box 4
2. Display YouTube video on the screen using the app

### Expected behavior
The YouTube video plays flicker-free

### Actual behavior
The YouTube video flickers and there are following messages in the logcat:
```
18:43:30.848  4890  5015 E chromium: [ERROR:image_reader_gl_owner.cc(296)] no buffers currently available in the reader queue
18:43:30.848  4890  5015 E chromium: [ERROR:video_image_reader_image_backing.cc(210)] Failed to get the hardware buffer.
```
The recording of the behavior is here: https://www.youtube.com/watch?v=-tbXBv9BEQ8

After manually pausing and resuming the video (using `YouTubePlayer.pause()` and `YouTubePlayer.play()`) the video is flicker-free and playback is OK.

**Comment by Serkali-sudo** [comment]
Try enabling or disabling hardware acceleration.

**Comment by milan-fabian** [comment]
@Serkali-sudo do you mean enable/disable hardware acceleration in the entire app, or is there a way to enable/disable hardware acceleration just for YouTubePlayerView?

**Comment by Serkali-sudo** [comment]
YouTubePlayerView is actually webview and there is a way to enable/disable hardware acceleration for webview spesifically.
If enabling or disabling hardware acceleration in the entire app causes problems other parts of the app you can try to enable/disable YouTubePlayerView's hardware acceleration spesifically but you are gonna have edit the library to do that.

**Comment by milan-fabian** [comment]
I accessed WebViewYouTubePlayer via reflection and tried:

- `webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null)` - YouTube controls were displayed, but without any video, on all test devices. I assume WebView requires hardware acceleration for video.
- `webView.setLayerType(View.LAYER_TYPE_HARDWARE, null)` - the same behavior as before, it works correctly on all tested devices except Xiaomi Mi Box 4. It's flickering on Xiaomi Mi Box 4 at the beginning.

If you have any other suggestion to try, I would be really grateful.

**Comment by Serkali-sudo** [comment]
i have more ideas but not sure if they will work but if you want to try them anyways:

1. Try to clear cache of the "Android System Webview" app and if Chrome app is installed you can try to switch webview engine to Chrome's webview
2. There may be conflicts with other apps that running on background try closing them
3. Try to open this demo : https://developers.google.com/youtube/youtube_player_demo on a system webview powered browser(eg: [Via Browser](https://play.google.com/store/apps/details?id=mark.via.gp) ) if flickering happens there too then it is probably hardware gpu issue.
4. After quick search on the web i found this issue that is similar to what you are experiencing : https://bugs.chromium.org/p/chromium/issues/detail?id=1109016#c41

**Comment by PierfrancescoSoffritti** [comment]
I am closing the issue for now because of inactivity.

If this is still a problem can you provide:

1. Stack traces
2. Information about the device on which the error happens (model, api version)
3. If possible, the app on which the issue happens. Either code or apk is fine.
