### ISSUE TITLE
issues when trying to hide the menu button

### ISSUE THREAD

**Issue by xLeDiaa** [PierfrancescoSoffritti/android-youtube-player#911]
Hi, I want to hide this menu button from the UI. 
![image](https://user-images.githubusercontent.com/63806066/209436645-ff5c560d-b4c0-4ddf-8882-844fe45cbea7.png)

but I get errors when I try to paste the code. should I place it somewhere else ? do I have to initialize anything before pasting the code? I really appreciate any explanation.
![image](https://user-images.githubusercontent.com/63806066/209436554-a6b09c86-aae3-4562-a764-50a65d8d8948.png)

**Comment by Serkali-sudo** [comment]
Hi it seems like you are intended to use custom ui but you are using webui.Custom ui doesnt add menu button by default so that button comes from webui.Meaning that function(showMenuButton) wont work for webui menu button anyways, The only way to remove that is removing that element with js.

Which i already answered similar question, Here : #885

**Comment by xLeDiaa** [comment]
So, I have to get into "ayp_youtube_player.html" file (the one you mentioned in #885) and write some code in order to remove that? I really can't find any file with that name

**Comment by Serkali-sudo** [comment]
To be able to edit the library you have to add this library as a module not implementation way or you can search the internet for alternative way

**Comment by xLeDiaa** [comment]
> To be able to edit the library you have to add this library as a module not implementation way

Thanks a lot. Just one more question, please. If I edited the webUi or just covered these 3 dots button with something (like a useless button) just so the user won't be able to share the video, will be that a problem if I tried to publish my app on Google Store?

**Comment by PierfrancescoSoffritti** [comment]
It might be a problem, you're not supposed to alter the UI of the web player.
