### ISSUE TITLE
React Native: Bridge: Method addObserver must be called on the Main Thread

### ISSUE THREAD

**Issue by manoj-paramesh-learngram-ai** [PierfrancescoSoffritti/android-youtube-player#913]
# Question / Problem

### Summary
Trying to implement this library into react native. Although followed the SimpleExampleActivity.java 

```
public class SimpleExampleActivity extends AppCompatActivity {

    private YouTubePlayerView youTubePlayerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_simple_example);

        youTubePlayerView = findViewById(R.id.youtube_player_view);
        getLifecycle().addObserver(youTubePlayerView);
    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        // Checks the orientation of the screen
        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            youTubePlayerView.enterFullScreen();
        }
        else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){
            youTubePlayerView.exitFullScreen();
        }
    }
}
```

### The error : 

<img width="286" alt="image" src="https://user-images.githubusercontent.com/93116762/211324955-3fddd366-1843-4ecf-9e20-541a9c73f40e.png">

### What i have tried

```
 runOnUiThread(new Runnable() {
            @Override
            public void run() {
                getActivity().addObserver(youTubePlayerView);
            }
        });
```
The problem here is that , this is already an activity , getActivity() will not make sense . Looking for suggestions / help.

I have also created a new react-native project to help understand my implementation (please find the links below) :
Repo : https://github.com/learngram-ai/native-youtube-player-rn
The files : https://github.com/learngram-ai/native-a-player-rn/tree/main/android/app/src/main

Thanks

**Comment by manoj-paramesh-learngram-ai** [comment]
yes , this is what i tried next , still its the same error : 
```
public class SimpleExampleActivity extends AppCompatActivity {

    private YouTubePlayerView youTubePlayerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_simple_example);

        youTubePlayerView = findViewById(R.id.youtube_player_view);
        runOnUiThread(new Runnable() {
        @Override
        public void run() {
          getLifecycle().addObserver(youTubePlayerView);
        }
      });
    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        // Checks the orientation of the screen
        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE) {
            youTubePlayerView.enterFullScreen();
        }
        else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){
            youTubePlayerView.exitFullScreen();
        }
    }
}
```

**Comment by Serkali-sudo** [comment]
Try creating handler and posting that to the main thread.Maybe?
```java
new Handler(Looper.getMainLooper()).post(new Runnable() {
       @Override
       public void run() {
           getLifecycle().addObserver(youTubePlayerView);
       }
});
```

**Comment by manoj-paramesh-learngram-ai** [comment]
@Serkali-sudo  Thanks for the reply, Even if i don't add the addObserver line, still the "Method addObserver must be called on the main thread" is thrown. It might be coming from the library internally itself ?

Also tried your suggestion by adding the Handle/Looper , it still gives me the same error.

**Comment by Serkali-sudo** [comment]
You can try to remove LifecycleObserver from YouTubePlayerView by editing this class [YouTubePlayerView.kt#L23](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/views/YouTubePlayerView.kt#L23) from the library then you can add those lifecycles manually to your class.This library uses `androidx.lifecycle:lifecycle-runtime-ktx:$lifecycle_version` library to catch lifecycles so maybe the problem is with the library so maybe deleting that library and removing LifecycleObserver  could work or you can try to update the library also. Doc : https://developer.android.com/jetpack/androidx/releases/lifecycle#lifecycle-*-2.5.1

**Comment by PierfrancescoSoffritti** [comment]
> Thanks for the reply, Even if i don't add the addObserver line, still the "Method addObserver must be called on the main thread" is thrown. It might be coming from the library internally itself ?

This doesn't sound like an issue with the library. Can you show us a stacktrace?

**Comment by manoj-paramesh-learngram-ai** [comment]
@PierfrancescoSoffritti 
Stack Traces : 
[https://pastebin.com/raw/mZfDtgvB](https://pastebin.com/raw/mZfDtgvB) - Stack Trace with the addObserver line 

[https://pastebin.com/raw/E5EVDvF5](https://pastebin.com/raw/E5EVDvF5) - Stack Trace with addObserver removed (No error exceptions here , on calling the function it does nothing)

I have also created a new react-native project and add my implemented to better understand this issue : 
Repo : [https://github.com/learngram-ai/native-youtube-player-rn](https://github.com/learngram-ai/native-youtube-player-rn)
The files : [https://github.com/learngram-ai/native-a-player-rn/tree/main/android/app/src/main](https://github.com/learngram-ai/native-a-player-rn/tree/main/android/app/src/main)

**Comment by manoj-paramesh-learngram-ai** [comment]
@PierfrancescoSoffritti  @Serkali-sudo  Thank you for the replies! It will be super helpful if you can check and provide some guidance on this issue .


I have also created a new react-native project to help understand my implementation better (please find the links below) :
Repo : https://github.com/learngram-ai/native-youtube-player-rn
The files : https://github.com/learngram-ai/native-a-player-rn/tree/main/android/app/src/main

**Comment by PierfrancescoSoffritti** [comment]
[You are manually creating an Activity class](https://github.com/learngram-ai/native-youtube-player-rn/blob/main/android/app/src/main/java/com/nativeyoutubeplayer/ReactOneCustomMethod.java#L45). This is wrong, Activities are created by the framework.
