### ISSUE TITLE
Adding the fs(Full Screen) option to the IFramePlayerOptions.

### ISSUE THREAD

**Issue by oia05** [PierfrancescoSoffritti/android-youtube-player#914]
# Feature Request

**Comment by PierfrancescoSoffritti** [comment]
Hi, you need to handle that from your app unfortunately.

**Comment by PierfrancescoSoffritti** [comment]
You don't need to fork the library. You can simply use the callbacks to handle full screen. [Have a look at the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample/CompleteExampleActivity.java#L26).

**Comment by oia05** [comment]
But I want the Full Screen Button. It is only available with the default custom UI, and I don't want to use it since if I did so, I would have 2 menu buttons( one from the custom ui and one from the Iframe Ui.) Therefore, I am not adding the custom UI, and I am using controls(1), but the full screen button is still missing. I would need something like fs(1).

Thank you

**Comment by PierfrancescoSoffritti** [comment]
Unfortunately that's not possible. We don't have control over the IFrame Player's UI.

You could hack together a solution, but it would break YouTube terms of service, so you won't be able to upload to the PlayStore, if you care about that. Also the hacky solution would break when YouTube updates their library. I suggest finding a way to do it without using a button inside the player.

**Comment by oia05** [comment]
Emm, but the YouTube Player API specifies the attribute fs when set to 1 would make the Full Screen button visible. Why would that break their terms?
Thank you

**Comment by PierfrancescoSoffritti** [comment]
I see, I forgot they have an actual `fs` option. Thank you for pointing that out.

It's going to be easy to enable that, I just tried and it works. But I don't know if we can intercept when the user clicks the button. Can you check if there is a way to do that in the IFrame Player?

If we can be notified of the click on the Javascript side it's going to be easy to send that to Android.

**Comment by oia05** [comment]
No problem. What happens currently when you press on the button?

**Comment by PierfrancescoSoffritti** [comment]
In the Webview: nothing. In a browser I imagine the player just goes full screen.

You can easily test it, [set this to 1](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/options/IFramePlayerOptions.kt#L47) and run the sample app.

**Comment by oia05** [comment]
Okay thank you. I will try from my side. In the mean time if you have any update, inform me please
