### ISSUE TITLE
Orientation issue for some videos in amazon firestick

### ISSUE THREAD

**Issue by mobcluster** [PierfrancescoSoffritti/android-youtube-player#915]
I have integrated this in my android app and it really works great. Thanks a lot. 

I am facing one issue: I am using my android app in amazon firestick, since amazon firestick does not have device orientation i am rotating my view by 90 degree to support portrait. 

Currently i am getting title, audio controls, captions everything in portrait however the ytplayer seems to be loading in landscape mode only. Do you have any idea what can i do to achieve ?

**Comment by PierfrancescoSoffritti** [comment]
Hi, I suggest not rotating the view. You can [look at the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample/CompleteExampleActivity.java#L26) for how to implement full screen.

**Comment by mobcluster** [comment]
Hi, Thanks for quick revert. I have looked the sample app and its working great in Android TV / Tablets and phones. 

However i am trying to load this into Amazon firestick. Amazon firestick has one landscape orientation only. For me to achieve this, i thought to manually rotate the view. I am getting titles and captions properly in portrait but middle portion where video plays, it is in landscape only.

**Comment by PierfrancescoSoffritti** [comment]
Can't you just call `YouTubePlayerView#enterFullScreen`?

**Comment by mobcluster** [comment]
I am doing that however the video in middle portion is playing in landscape 

I have attached the screenshot. If you observe, the captions are displaying properly however the video is displaying in landscape (the area is portrait only so video is getting squeezed) 
![IMG_9654](https://user-images.githubusercontent.com/122819214/212825596-20acb461-5155-4510-8cc9-6a41f1b8e44f.jpg)

**Comment by PierfrancescoSoffritti** [comment]
So you have TV in portrait orientation. Why don't you keep the video portrait then?

**Comment by mobcluster** [comment]
I have kept the video view in portrait only so the captions are loading properly in portrait however the video is displaying in landscape... i am using fragment

**Comment by mobcluster** [comment]
Hi,

Do you have any idea why only video is playing in such a weird manner? I have tried everything.. 

Please note: https://www.youtube.com/watch?v=bUounn_Bmy4 (**This video is playing absolutely fine**) The problem is with all other videos like https://www.youtube.com/watch?v=W6NZfCO5SIk

Your help is highly appreciated.

**Comment by PierfrancescoSoffritti** [comment]
No, I am not sure why this happens. I find it surprising that it only happens with some videos.

The issue could be:
1. in your code
2. in the IFrame Player code
3. or in the library [here](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/res/raw/ayp_youtube_player.html).

Let us know if you make any progress.

**Comment by PierfrancescoSoffritti** [comment]
Hi, in version 12.0.0 we have improved how fullscreen is handled. I suggest you try using that version of the library :)

Feel free to reopen if this is still a problem!
