### ISSUE TITLE
When the Youtube Video is paused don't show more videos, title and share options

### ISSUE THREAD

**Issue by murali129** [PierfrancescoSoffritti/android-youtube-player#916]
# Feature Request

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks for the suggestion. This is not going to be implemented as it will break YouTube terms of service. I suggest you for the library and implement this on your fork. You can find [another solution here](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/dev#remove-annoying-views).
