### ISSUE TITLE
When we are customizing YouTube-Player then it is customized perfectly and YouTube player working fine but SHARE and YOUTUBE icon appear on controller. Can we remove these icons from YouTube player?.

### ISSUE THREAD

**Issue by FusioniTechnologies** [PierfrancescoSoffritti/android-youtube-player#917]
**After Customizing UI Share and YouTube icons still showing**

   ### For Disabling web UI

        IFramePlayerOptions options = new IFramePlayerOptions.Builder().controls(0).build();
        binding.youtubePlayerView.initialize(listener, options);
        
       ///////////////////////////////////////////////////////////////

         
getLifecycle().addObserver(binding.youtubePlayerView);

   ###  Initializing Youtube

        YouTubePlayerListener listener = new AbstractYouTubePlayerListener() {
            @RequiresApi(api = Build.VERSION_CODES.Q)
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                View customPlayerUi = binding.youtubePlayerView.inflateCustomPlayerUi(R.layout.media_controller_view_exoplayer);
                customPlayerUiController = new CustomUiController(YouTubeVideoPlayerActivity.this, customPlayerUi, youTubePlayer, binding.youtubePlayerView, videoId);
                customPlayerUiController.initialize();
            }

            @Override
            public void onError(@NonNull YouTubePlayer youTubePlayer, @NonNull PlayerConstants.PlayerError error) {

            }

            @Override
            public void onStateChange(@NonNull YouTubePlayer youTubePlayer, @NonNull PlayerConstants.PlayerState state) {
                if (state == PlayerConstants.PlayerState.BUFFERING) {
                    // Code
                } else if (state == PlayerConstants.PlayerState.PLAYING) {
                    // Code
                } else if (state == PlayerConstants.PlayerState.ENDED) {
                    finishMyActivity();
                } else {
                }
            }

            @Override
            public void onCurrentSecond(@NonNull YouTubePlayer youTubePlayer, float second) {
                super.onCurrentSecond(youTubePlayer, second);
            }

            @Override
            public void onVideoDuration(@NonNull YouTubePlayer youTubePlayer, float duration) {
                super.onVideoDuration(youTubePlayer, duration);
            }
        };

        
  ###       Player View
 <com.PierfrancescoSoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:autoPlay="true"
        app:enableAutomaticInitialization="false"
        app:videoId="yHCo9N64lRk" />

### have any solution about it?.

**Comment by PierfrancescoSoffritti** [comment]
Unfortunately those buttons can't be removed, they are part of the IFrame Player.

**Comment by FusioniTechnologies** [comment]
Okay, but can you please try to remove it?.

**Comment by ThreeMinutesFix** [comment]
if we do so there is no use of this library. we can simply make it play with exoplayer! but youtube or playstore will strike the app
