### ISSUE TITLE
 Can you update the example code? It's really hard to setup using kotlin

### ISSUE THREAD

**Issue by Acidrai0** [PierfrancescoSoffritti/android-youtube-player#918]
I have been trying since yesterday to make it work with kotlin but I can't get it to work

Any help will be appreciated

**Comment by PierfrancescoSoffritti** [comment]
Hi, what are you having problems with? The library is actually written in Kotlin. It works with Kotlin as it does with Java.

**Comment by Acidrai0** [comment]
I can't figure out out to load a video using kotlin

**Comment by PierfrancescoSoffritti** [comment]
Can you please show your code?

**Comment by Acidrai0** [comment]
I figured it out 

for anyone having the same issue 

this is what worked for me

val youTubePlayerView = findViewById<YouTubePlayerView>(R.id.youtube_player_view)
lifecycle.addObserver(youTubePlayerView)

     youTubePlayerView.addYouTubePlayerListener(object : AbstractYouTubePlayerListener() {
            override fun onReady(@NonNull youTubePlayer: YouTubePlayer) {
                val videoId = "S0Q4gqBUs7c"
                youTubePlayer.cueVideo(videoId, 0f)
            }
        })

**Comment by PierfrancescoSoffritti** [comment]
Thank you. Glad you figured it out.

Btw, this is exactly as show [in the doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#quick-start) and sample app :)

**Comment by Acidrai0** [comment]
I'm sorry I didn't check the sample app and the docs is in java
