### ISSUE TITLE
How can I check if a user is seeking the seekbar?

### ISSUE THREAD

**Issue by Acidrai0** [PierfrancescoSoffritti/android-youtube-player#920]
How can I check if a user is seeking the seekbar?

Is it possible using the YouTubePlayerSeekBarListener ?

I am just using the default webui player

**Comment by PierfrancescoSoffritti** [comment]
Hi, I don't think it's possible without adding custom methods the the Javascript code.

**Comment by Acidrai0** [comment]
Well the only option I have now is to add the custom seekbar In YouTubePlayerSeekBar I need access to  seekBarTouchStarted but its private so I forked the repo and made some changes and added jitpack to my project but I am getting build errors 
[https://jitpack.io/com/github/Acidrai0/android-youtube-player/d3155be9f3/build.log](url)

How can I resolve this?

**Comment by PierfrancescoSoffritti** [comment]
It's not recommended to use the native UI. You should stick to web ui (the default) to avoid risk breaking YouTube terms of service.
