### ISSUE TITLE
call setVideoTitle off the main UI thread

### ISSUE THREAD

**Issue by codygo01** [PierfrancescoSoffritti/android-youtube-player#921]
I'm trying to get the video title, but I think we need to set it then get it and call the set off the main thread.

I'm looking into it but still working it.  Maybe you can give a quick pointer please.

Thanks so much!

Cody Godines

**Comment by PierfrancescoSoffritti** [comment]
Hi Cody, can you please clarify what you're trying to do?

**Comment by PierfrancescoSoffritti** [comment]
Closing as obsolete. Feel free to reopen if you want to discuss.
