### ISSUE TITLE
How to build this library 

### ISSUE THREAD

**Issue by Acidrai0** [PierfrancescoSoffritti/android-youtube-player#922]
I need to make some changes so I cloned the library to my PC and made the changes how now can I use that in my app?

Things I tried 

**1** - I forked the library on GitHub and tried to build it on JitPack but I am always getting errors Artifacts not found [log](https://jitpack.io/com/github/Acidrai0/android-youtube-player/d3155be9f3/build.log)

One more thing I noticed in jitpack.yml file  

```
# configuration file for building snapshots and releases with jitpack.io
jdk:
  - openjdk11
before_install:
  - ./scripts/prepareJitpackEnvironment.sh`
```

**But there is no prepareJitpackEnvironment.sh file in scripts folder**

 
**2** - I tried to build the project locally and copied the core-11.1.0-sources from libs folder to my project and added it as library but I can't use it 
![Screenshot (5)](https://user-images.githubusercontent.com/63885660/214433700-52d1583e-e10f-4614-8103-5eee713318e2.png)

**Comment by Acidrai0** [comment]
**Edit - I finally got it to work here is how to do it for someone struggling the same** 

Make a clone of the repo locally on your computer

**3**  Import it as a module 
![Capture](https://user-images.githubusercontent.com/63885660/214434352-cd3b51f2-51c3-4535-8e57-e68bfc99e203.PNG)

Go to Project View > Core > build.gradle

Remove the ext block and apply from: "../scripts/publish-module.gradle" from the bottom

![31](https://user-images.githubusercontent.com/63885660/214438842-1a5c18a3-d0ed-41da-8324-84d04a6ad241.PNG)


Now copy and paste dependencies.gradle from the root folder of android-youtube-player to the root of your project 

Lastly in the app level gradle put implementation project (':core')
![Capture21](https://user-images.githubusercontent.com/63885660/214439562-60875d7a-c501-45ac-be63-a1d3f8a02e29.PNG)


Now Sync your project it should work

**Comment by PierfrancescoSoffritti** [comment]
👍  glad you figured it out

**Comment by rachit1797** [comment]
I am trying this method but I am unable to sync the project can you please provide some comprehensive way to solve the problem. Or can you provide the Complete steps to solve the problem
No signature of method: build_7sfmj1c1tjx87yaweiylswn44.android() is applicable for argument types: (build_7sfmj1c1tjx87yaweiylswn44$_run_closure1) values: [build_7sfmj1c1tjx87yaweiylswn44$_run_closure1@30582b2a]

**Comment by SureshTimma** [comment]
> **Edit - I finally got it to work here is how to do it for someone struggling the same** 
> 
> Make a clone of the repo locally on your computer
> 
> **3**  Import it as a module 
> ![Capture](https://user-images.githubusercontent.com/63885660/214434352-cd3b51f2-51c3-4535-8e57-e68bfc99e203.PNG)
> 
> Go to Project View > Core > build.gradle
> 
> Remove the ext block and apply from: "../scripts/publish-module.gradle" from the bottom
> 
> ![31](https://user-images.githubusercontent.com/63885660/214438842-1a5c18a3-d0ed-41da-8324-84d04a6ad241.PNG)
> 
> 
> Now copy and paste dependencies.gradle from the root folder of android-youtube-player to the root of your project 
> 
> Lastly in the app level gradle put implementation project (':core')
> ![Capture21](https://user-images.githubusercontent.com/63885660/214439562-60875d7a-c501-45ac-be63-a1d3f8a02e29.PNG)
> 
> 
> Now Sync your project it should work

Could you please help me in building this library in my android project?
