### ISSUE TITLE
Can we play list of video in queue just like playlist?.

### ISSUE THREAD

**Issue by FusioniTechnologies** [PierfrancescoSoffritti/android-youtube-player#923]
# Question / Problem

**Comment by PierfrancescoSoffritti** [comment]
[Yes](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/playlistExample/PlaylistExampleActivity.java).

**Comment by AZKZero** [comment]
The url is broken at the moment

**Comment by PierfrancescoSoffritti** [comment]
Fixed.
