### ISSUE TITLE
Leak of this Lib

### ISSUE THREAD

**Issue by billdizl** [PierfrancescoSoffritti/android-youtube-player#924]
![image](https://user-images.githubusercontent.com/30317994/215986852-21d2d4b4-4c9b-49cf-8b77-a5bd8952c276.png)
  I know why, because you lib Utils.class --isOnline --method, val connectivityManager = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
        val networkInfo = connectivityManager.activeNetworkInfo
        return networkInfo != null && networkInfo.isConnected
use context not applicationContext,  you can fix it,please.
![5aa781fc8289ccbe7ae34e0874e3bfc8](https://user-images.githubusercontent.com/30317994/215991144-dc21d769-2e29-411e-b9b1-12f8c999ba5c.png)
![5fae0b26fdbbe018a35e59b93d6d2b7a](https://user-images.githubusercontent.com/30317994/215991161-c18af2bc-aaaa-4ca7-b853-e518e7ae8a03.png)

**Comment by PierfrancescoSoffritti** [comment]
Thanks for reporting this. Feel free to send a pull request.

**Comment by PierfrancescoSoffritti** [comment]
This is fixed. Will be available in the next version of the library.

**Comment by PierfrancescoSoffritti** [comment]
Version 12.0.0 is not available.

**Comment by PierfrancescoSoffritti** [comment]
Version 12.0.0 is now available.
