### ISSUE TITLE
Add modestbranding option

### ISSUE THREAD

**Issue by test1-ko** [PierfrancescoSoffritti/android-youtube-player#929]
Hello.
I want the YouTube logo to be displayed at the bottom of the player.
Please Add "modestbranding" to Supported IFramePlayerOptions.
Thank you.

**Comment by PierfrancescoSoffritti** [comment]
Hi, it looks like modest branding [is already there](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/player/options/IFramePlayerOptions.kt), and is set to 1 by default.

**Comment by test1-ko** [comment]
@PierfrancescoSoffritti 
There is a MODEST_BRANDING option, but it is fixed to 1.
I want to change the option to 0 and display the YouTube logo.
Can you make a function that changes the option?

**Comment by PierfrancescoSoffritti** [comment]
Please [read the doc](https://developers.google.com/youtube/player_parameters#modestbranding). A value of 1 means that modest branding is already enabled.
