### ISSUE TITLE
Add ability to programmatically click fullscreen button in IFrame Player

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [PierfrancescoSoffritti/android-youtube-player#932]
The fullscreen button can be enabled in the IFrame Player by setting the `fs` parameter in `IFramePlayerOptions`.

We can use `FullScreenListener` to react to fullscreen events when the user clicks the button in the UI. But currently there is no way to enter fullscreen mode programmatically.

It would be nice for example to have the option to automatically enter fullscreen mode when the orientation of the device goes from portrait to landscape.

In order to do this we need to figure out if the IFrame Player exposes an API to enter fullscreen. If not, we might want to check if fullscreen can be triggered from the `WebView` or `WebChromeClient`.

**Comment by PierfrancescoSoffritti** [comment]
@Praveen-Pable in case you have ideas.

**Comment by Praveen-Pable** [comment]
> 

Need to check @PierfrancescoSoffritti, i'll try to achieve this and let you know.

**Comment by Praveen-Pable** [comment]
Hi @PierfrancescoSoffritti , I have raised one pull request for enable user to automatically enter fullscreen mode when orientation of device changed. Please review.

**Comment by PierfrancescoSoffritti** [comment]
`YouTubePlayer.toggleFullscreen` is available starting from version 12.0.0. See #936
