### ISSUE TITLE
Video is not showing

### ISSUE THREAD

**Issue by iamvaidarbhi** [PierfrancescoSoffritti/android-youtube-player#933]
Hello @PierfrancescoSoffritti Please find below issue

   I am using `com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView` in my kotlin project. I have list of youtube videos URL from an API and I call it like below
   
   
       val link = youtubeDataList.youtube_url     // This variable contain API parameter data

        holder.binding.youtubePlayer.addYouTubePlayerListener(object :
            AbstractYouTubePlayerListener() {
            override fun onReady(youTubePlayer: YouTubePlayer) {
                super.onReady(youTubePlayer)
                val VIDEO_ID = Utils.getYoutubeVideoId(link.toString())
                youTubePlayer.cueVideo(VIDEO_ID, 0f)
                youTubePlayer.play()
                Log.e("", "onReady: ${link.toString()} ")
            }

            override fun onError(youTubePlayer: YouTubePlayer, error: PlayerConstants.PlayerError) {
                super.onError(youTubePlayer, error)
                Log.e("", "onError: ${error.name}")
            }
        })

I simply call link in youtube player but in some video URL I am getting `INVALID_PARAMETER_IN_REQUEST` error and it is not playing in my application as it work fine in chrome browser youtube.

 I already referred your `Some videos receive "invalid parameters". #195` but it can't help me . So it will great if you please provide me another solution.

**Comment by PierfrancescoSoffritti** [comment]
If you're sure the URL is correct and the URL never plays, it could be because YouTube doesn't allow that video to play in an embedded player.

**Comment by gifandadelasty** [comment]
> If you're sure the URL is correct and the URL never plays, it could be because YouTube doesn't allow that video to play in an embedded player.

Please help, I face same issue.. getting error `INVALID PARAMETER IN REQUEST` but my videos is allowed for embedded player. Its run perfectly before, but now I get this error.
