### ISSUE TITLE
in XML app:showFullScreenButton is not working

### ISSUE THREAD

**Issue by Leonard-GitHub** [PierfrancescoSoffritti/android-youtube-player#934]
I tried to use app:showFullScreenButton="ture" in XML but its not working. 

I'm new to this, how do I get it to work?

**Comment by PierfrancescoSoffritti** [comment]
Hi, thanks for reporting the issue. Since now `webUi` is on by default, that attribute should probably be deprecated. The next version of the library will have better full screen support from web ui. See #926

**Comment by Leonard-GitHub** [comment]
thank you for your response. waiting for the next version!!!

**Comment by PierfrancescoSoffritti** [comment]
No problem. I will aim to release it sometimes next week.

**Comment by PierfrancescoSoffritti** [comment]
I have removed obsolete attributes like `showFullScreenButton`, see [commit](https://github.com/PierfrancescoSoffritti/android-youtube-player/commit/77f7c1e319a1ad5a039ac16c0824d35f58893ea4).

**Comment by Leonard-GitHub** [comment]
Great!!!

**Comment by PierfrancescoSoffritti** [comment]
Version 12.0.0 is now available.
