### ISSUE TITLE
setCustomPlayerUi is not working

### ISSUE THREAD

**Issue by roma-hladilka** [PierfrancescoSoffritti/android-youtube-player#937]
# Question / Problem

I want to use your library in my react native project, but I kind of new in native development.
I have a class with two methods: createViewInstance for creating youtube view instance and setVideoId to pass this param from react native side.
`public class YoutubeViewManager extends SimpleViewManager<YouTubePlayerView> {
    public static final String REACT_CLASS = "YoutubeViewManager";

    @Override
    public String getName() {
        return REACT_CLASS;
    }

    @Override
    protected YouTubePlayerView createViewInstance(ThemedReactContext reactContext) {
        YouTubePlayerView youTubePlayerView = new YouTubePlayerView(reactContext);

        youTubePlayerView.setEnableAutomaticInitialization(false);
        Lifecycle lifecycle = ((AppCompatActivity) reactContext.getCurrentActivity()).getLifecycle();
        lifecycle.addObserver(youTubePlayerView);

        YouTubePlayerListener listener = new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                // using pre-made custom ui
                DefaultPlayerUiController defaultPlayerUiController = new DefaultPlayerUiController(youTubePlayerView, youTubePlayer);
                youTubePlayerView.setCustomPlayerUi(defaultPlayerUiController.getRootView());
            }
        };

        // disable web ui
        IFramePlayerOptions options = new IFramePlayerOptions.Builder().controls(0).build();

        youTubePlayerView.initialize(listener, options);

        return youTubePlayerView;
    }

    @ReactProp(name = "videoId")
    public void setVideoId(YouTubePlayerView youTubePlayerView, String videoId) {
        youTubePlayerView.getYouTubePlayerWhenReady(youTubePlayer -> {
            youTubePlayer.cueVideo(videoId, 0);
        });
    }
}`

if enableAutomaticInitialization = true, I can see player controls, but where is no fullscreen button there, so I try to apply DefaultPlayerUiController to player. But in this case there is no controls at all (looks like setCustomPlayerUi didn't applied defaultPlayerUiController to view). My goal is to have fullscreen button either with DefaultPlayerUiController or not.
Could you help me here?

**Comment by roma-hladilka** [comment]
@PierfrancescoSoffritti or when a new release is planned to be? As I can see, IFramePlayerOptions has 'fullscreen' method in dev branch, it would be helpfull

**Comment by PierfrancescoSoffritti** [comment]
Hi, yes the new version will have better support for fullscreen. I should be able to release it at the end of this week.

**Comment by roma-hladilka** [comment]
@PierfrancescoSoffritti 
Ok, sounds good!
Maybe you could say, what I am doing wrong in the snippet above? If not, ok, will wait for release.

**Comment by PierfrancescoSoffritti** [comment]
I suggest you take a look at the sample app, there are examples pretty much for everything you need :)

**Comment by roma-hladilka** [comment]
Yea, I took the above code from default custom ui example. This is why I am asking)

**Comment by PierfrancescoSoffritti** [comment]
Version 12.0.0 is now available :) see [fullscreen doc](https://github.com/PierfrancescoSoffritti/android-youtube-player#full-screen).
