### ISSUE TITLE
getListeners() Unresolved reference

### ISSUE THREAD

**Issue by WeiHungHuang** [PierfrancescoSoffritti/android-youtube-player#943]
Followed the guides of "Change Video Quality".
 When doing the following step

```
@JavascriptInterface
fun sendVideoQuality(quality: String) {
  mainThreadHandler.post {
    for(listener in youTubePlayerOwner.getListeners()) {
      // also add this new method to the listener interface
      listener.onVideoQuality(youTubePlayerOwner.getInstance(), quality)
    }
  }
}
```

Android Studio showed the error "Unresolved reference getListeners()"

**Comment by PierfrancescoSoffritti** [comment]
You might need to adapt this code snippet to the latest version of the library. Also remember this approach is a hack.
