### ISSUE TITLE
Toggle overlay controls

### ISSUE THREAD

**Issue by yurabuloichik** [PierfrancescoSoffritti/android-youtube-player#944]
Hi, I'm trying to use your library on device with remote control (tv/tv-box).  Is there any possibility to toggle whole overlay with controls? (similar to touch event on smartphone)
Example: KeyEvent.KEYCODE_DPAD_UP > show controls; KeyEvent.KEYCODE_BACK -> hide controls (if they are visible)

Tried View.performClick() with focusable and clickable attributes - no result as expected

Thanks in advance.

**Comment by PierfrancescoSoffritti** [comment]
Is this what you need? #888

**Comment by yurabuloichik** [comment]
> Is this what you need? #888

No, pause, play, seek, volume - everything is ok. The problem is only in showing/hiding whole overlay(title, controls, progressbar, etc.) on "clicking" (as touch event on smartphones) . Clicking on a YouTubePlayerView via performClick() does nothing.

**Comment by PierfrancescoSoffritti** [comment]
I see, but you are doing the click using a remote? Can I ask you do you need to perform the click?

Anyway, maybe the click is not dispatched to the view? Maybe you can try `performClick` on a regular Android smartphone and see if it works there?

**Comment by PierfrancescoSoffritti** [comment]
I'm glad you found a solution :)
