### ISSUE TITLE
mute/ unmute option + full screen option on playerview 

### ISSUE THREAD

**Issue by charmysolanki** [PierfrancescoSoffritti/android-youtube-player#945]
I want to have mute/ unmute option and also full screen option in player view, how can i achieve that ?

Rightnow If I use DefaultPlayerUiController, i can see full screen option at the bottom right corner, but there is no mute/unmute option which is available in your CompleteExampleActivity. please let me know how can I have both the options on playerview.

**Comment by PierfrancescoSoffritti** [comment]
You can stop using DefaultPlayerUiController and use the default web ui instead. You can look at the examples and replicate what is shown there :)
