### ISSUE TITLE
How to install the forked version with listed workarounds in local m2 folder

### ISSUE THREAD

**Issue by MananArya22** [PierfrancescoSoffritti/android-youtube-player#947]
# Question / Problem

### Summary
I want to implement the workaround listed in readme "https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/dev#hide-title" and install it in my local m2 folder so that it can be used in my android application. I have made the suggested changes but cannot find the build inside the m2 folder. Its dependency remains unresolvable.

### What I've tried
I have implanted the change listed https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/dev#hide-title and changed the publishVersion_core to '12.0.0-local'. I have added "mavenLocal()" inside repositories. Then I ran "gradlew install". It's successful but I can't find this in the m2 folder or resolve its dependency in my android application.

**Comment by PierfrancescoSoffritti** [comment]
Hi, I am not sure how to do what you're trying to do. But why don't you just add the code as a module library in your project?

**Comment by MananArya22** [comment]
Hi @PierfrancescoSoffritti! Can you please help me by letting me know what changes must be done to create an AAR file of the core module so that it can be [added as a dependency](https://developer.android.com/studio/projects/android-library#psd-add-aar-jar-dependency) in the target android application?

**Comment by PierfrancescoSoffritti** [comment]
I don't know how to do it, but [looks like it should be fairly easy](https://stackoverflow.com/a/24316467/4306449).
