### ISSUE TITLE
Reload a YouTube video when clicking on a RecyclerView.

### ISSUE THREAD

**Issue by aleacx** [PierfrancescoSoffritti/android-youtube-player#948]
I am building an application using the pierfrancescosoffritti library, but I am having trouble loading a new video from a RecyclerView; when clicking, the new video is not being updated. I currently use a button to perform the action, but I am looking to have it done directly from the RecyclerView. Thank you in advance for your time.

Activity where the RecyclerView and the player are located:

**PLAYER ACTIVITY - JAVA**

`package com.education.photoapp.activities;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.res.Configuration;
import android.graphics.PorterDuff;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.education.photoapp.R;
import com.education.photoapp.adapters.ClassesAdapter;
import com.education.photoapp.classes.ClassesVo;
import com.education.photoapp.classes.PlatformVo;
import com.education.photoapp.classes.UnityVo;
import com.education.photoapp.interfaces.IComunica;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.options.IFramePlayerOptions;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.YouTubePlayerUtils;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;

import java.util.ArrayList;
import java.util.Objects;

public class PlayerActivity extends AppCompatActivity implements IComunica{

    YouTubePlayerView ytPlayer;

    TextView titleUnity;
    Button btnNext;

    RecyclerView recyclerView;
    ClassesAdapter classesAdapter;

    ArrayList<UnityVo> unityList;
    ArrayList<ClassesVo> classList;

    String titleTool, titleUnities, linkClass;
    Toolbar toolbar;

    boolean isFullScreen = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player);

        ytPlayer = findViewById(R.id.player_video);
        startYtPlayer();

        titleUnity = findViewById(R.id.title_unity_activity);
        titleUnities = getIntent().getStringExtra("unityComplete");
        titleUnity.setText(titleUnities);

        btnNext = findViewById(R.id.btn_test);
        btnNext.setOnClickListener(v -> {
            //recreate();

        });

        titleTool = getIntent().getStringExtra("title");
        toolbar = findViewById(R.id.toolbar_player_fragment);
        setSupportActionBar(toolbar);
        Objects.requireNonNull(getSupportActionBar()).setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setTitle(titleTool);
        toolbar.setTitleTextColor(getColor(R.color.white));
        toolbar.setNavigationOnClickListener(v -> onBackPressed());

        final Drawable menuIcon = getResources().getDrawable(R.drawable.ic_back);
        menuIcon.setColorFilter(getResources().getColor(R.color.white), PorterDuff.Mode.SRC_ATOP);
        getSupportActionBar().setHomeAsUpIndicator(menuIcon);

        fillRecycler();

    }

    private void startYtPlayer() {
        IFramePlayerOptions iFramePlayerOptions = new IFramePlayerOptions.Builder()
                .controls(1)
                .fullscreen(0)
                .build();

        getLifecycle().addObserver(ytPlayer);
        ytPlayer.initialize(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {

                nextVideo(youTubePlayer);

                YouTubePlayerUtils.loadOrCueVideo(
                        youTubePlayer, getLifecycle(),
                        getIntent().getStringExtra("link"), 0f
                );
            }
        }, true, iFramePlayerOptions);
    }

    private void nextVideo(YouTubePlayer youTubePlayer) {
        
        YouTubePlayerUtils.loadOrCueVideo(
                youTubePlayer, getLifecycle(),
                linkClass, 0
        );

    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig){
        super.onConfigurationChanged(newConfig);

        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE){

            ytPlayer.matchParent();

        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){

            ytPlayer.wrapContent();

        }

    }

    private void fillRecycler() {

        unityList = getUnityList();

        classList = getClassList();
        ClassesVo classes;

        int i;

        if(titleUnities.equals(getString(R.string.unity_1))) {

            ArrayList<ClassesVo> unityUno = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_1_))){
                    unityUno.add(classes);
                    classesAdapter = new ClassesAdapter(unityUno, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        } else if(titleUnities.equals(getString(R.string.unity_2))) {

            ArrayList<ClassesVo> unityDos = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_2_))){
                    unityDos.add(classes);
                    classesAdapter = new ClassesAdapter(unityDos, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        } else if(titleUnities.equals(getString(R.string.unity_3))) {

            ArrayList<ClassesVo> unityTres = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_3_))){
                    unityTres.add(classes);
                    classesAdapter = new ClassesAdapter(unityTres, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        }

    }

    private ArrayList<UnityVo> getUnityList() {

        ArrayList<UnityVo> unitiesList = new ArrayList<>();
        unitiesList.add(new UnityVo(getString(R.string.unity_1), getString(R.string.unity_1_description), R.drawable.unity_1, R.drawable.unity_1_ds));
        unitiesList.add(new UnityVo(getString(R.string.unity_2), getString(R.string.unity_2_description), R.drawable.unity_2, R.drawable.unity_2_ds));
        unitiesList.add(new UnityVo(getString(R.string.unity_3), getString(R.string.unity_3_description), R.drawable.unity_3, R.drawable.unity_3_ds));

        return unitiesList;
    }

    private ArrayList<ClassesVo> getClassList() {

        ArrayList<ClassesVo> classList = new ArrayList<>();

        //fill the recycler
        //Unity 1
        classList.add(new ClassesVo(1, getString(R.string.class_1), getString(R.string.class_1_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_1_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_2), getString(R.string.class_2_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_2_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_3), getString(R.string.class_3_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_3_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_4), getString(R.string.class_4_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_4_link)));

        //Unity 2
        classList.add(new ClassesVo(1, getString(R.string.class_5), getString(R.string.class_5_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_5_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_6), getString(R.string.class_6_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_6_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_7), getString(R.string.class_7_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_7_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_8), getString(R.string.class_8_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_8_link)));

        //Unity 3
        classList.add(new ClassesVo(1, getString(R.string.class_9), getString(R.string.class_9_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_9_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_10), getString(R.string.class_10_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_10_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_11), getString(R.string.class_11_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_11_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_12), getString(R.string.class_12_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_12_link)));

        return classList;
    }

    @Override
    public void openActivity(String nameActivity) {

    }

    @Override
    public void openClass(ClassesVo classes) {
        Toast.makeText(this, "Open: " + classes.getTitleClass(), Toast.LENGTH_SHORT).show();

        String titleNew = classes.getTitleClass();
        getSupportActionBar().setTitle(titleNew);

        linkClass = classes.getLinkClass();

    }

    @Override
    public void openPlatform(PlatformVo platform) {

    }
}
`

**PLAYER ACTIVITY - XML**

`package com.education.photoapp.activities;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.res.Configuration;
import android.graphics.PorterDuff;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.education.photoapp.R;
import com.education.photoapp.adapters.ClassesAdapter;
import com.education.photoapp.classes.ClassesVo;
import com.education.photoapp.classes.PlatformVo;
import com.education.photoapp.classes.UnityVo;
import com.education.photoapp.interfaces.IComunica;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.options.IFramePlayerOptions;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.YouTubePlayerUtils;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;

import java.util.ArrayList;
import java.util.Objects;

public class PlayerActivity extends AppCompatActivity implements IComunica{

    YouTubePlayerView ytPlayer;

    TextView titleUnity;
    Button btnNext;

    RecyclerView recyclerView;
    ClassesAdapter classesAdapter;

    ArrayList<UnityVo> unityList;
    ArrayList<ClassesVo> classList;

    String titleTool, titleUnities, linkClass;
    Toolbar toolbar;

    boolean isFullScreen = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player);

        ytPlayer = findViewById(R.id.player_video);
        startYtPlayer();

        titleUnity = findViewById(R.id.title_unity_activity);
        titleUnities = getIntent().getStringExtra("unityComplete");
        titleUnity.setText(titleUnities);

        btnNext = findViewById(R.id.btn_test);
        btnNext.setOnClickListener(v -> {
            //recreate();

        });

        titleTool = getIntent().getStringExtra("title");
        toolbar = findViewById(R.id.toolbar_player_fragment);
        setSupportActionBar(toolbar);
        Objects.requireNonNull(getSupportActionBar()).setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setTitle(titleTool);
        toolbar.setTitleTextColor(getColor(R.color.white));
        toolbar.setNavigationOnClickListener(v -> onBackPressed());

        final Drawable menuIcon = getResources().getDrawable(R.drawable.ic_back);
        menuIcon.setColorFilter(getResources().getColor(R.color.white), PorterDuff.Mode.SRC_ATOP);
        getSupportActionBar().setHomeAsUpIndicator(menuIcon);

        fillRecycler();

    }

    private void startYtPlayer() {
        IFramePlayerOptions iFramePlayerOptions = new IFramePlayerOptions.Builder()
                .controls(1)
                .fullscreen(0)
                .build();

        getLifecycle().addObserver(ytPlayer);
        ytPlayer.initialize(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {

                nextVideo(youTubePlayer);

                YouTubePlayerUtils.loadOrCueVideo(
                        youTubePlayer, getLifecycle(),
                        getIntent().getStringExtra("link"), 0f
                );
            }
        }, true, iFramePlayerOptions);
    }

    private void nextVideo(YouTubePlayer youTubePlayer) {
        
        YouTubePlayerUtils.loadOrCueVideo(
                youTubePlayer, getLifecycle(),
                linkClass, 0
        );

    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig){
        super.onConfigurationChanged(newConfig);

        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE){

            ytPlayer.matchParent();

        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){

            ytPlayer.wrapContent();

        }

    }

    private void fillRecycler() {

        unityList = getUnityList();

        classList = getClassList();
        ClassesVo classes;

        int i;

        if(titleUnities.equals(getString(R.string.unity_1))) {

            ArrayList<ClassesVo> unityUno = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_1_))){
                    unityUno.add(classes);
                    classesAdapter = new ClassesAdapter(unityUno, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        } else if(titleUnities.equals(getString(R.string.unity_2))) {

            ArrayList<ClassesVo> unityDos = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_2_))){
                    unityDos.add(classes);
                    classesAdapter = new ClassesAdapter(unityDos, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        } else if(titleUnities.equals(getString(R.string.unity_3))) {

            ArrayList<ClassesVo> unityTres = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_3_))){
                    unityTres.add(classes);
                    classesAdapter = new ClassesAdapter(unityTres, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        }

    }

    private ArrayList<UnityVo> getUnityList() {

        ArrayList<UnityVo> unitiesList = new ArrayList<>();
        unitiesList.add(new UnityVo(getString(R.string.unity_1), getString(R.string.unity_1_description), R.drawable.unity_1, R.drawable.unity_1_ds));
        unitiesList.add(new UnityVo(getString(R.string.unity_2), getString(R.string.unity_2_description), R.drawable.unity_2, R.drawable.unity_2_ds));
        unitiesList.add(new UnityVo(getString(R.string.unity_3), getString(R.string.unity_3_description), R.drawable.unity_3, R.drawable.unity_3_ds));

        return unitiesList;
    }

    private ArrayList<ClassesVo> getClassList() {

        ArrayList<ClassesVo> classList = new ArrayList<>();

        //fill the recycler
        //Unity 1
        classList.add(new ClassesVo(1, getString(R.string.class_1), getString(R.string.class_1_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_1_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_2), getString(R.string.class_2_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_2_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_3), getString(R.string.class_3_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_3_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_4), getString(R.string.class_4_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_4_link)));

        //Unity 2
        classList.add(new ClassesVo(1, getString(R.string.class_5), getString(R.string.class_5_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_5_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_6), getString(R.string.class_6_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_6_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_7), getString(R.string.class_7_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_7_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_8), getString(R.string.class_8_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_8_link)));

        //Unity 3
        classList.add(new ClassesVo(1, getString(R.string.class_9), getString(R.string.class_9_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_9_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_10), getString(R.string.class_10_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_10_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_11), getString(R.string.class_11_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_11_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_12), getString(R.string.class_12_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_12_link)));

        return classList;
    }

    @Override
    public void openActivity(String nameActivity) {

    }

    @Override
    public void openClass(ClassesVo classes) {
        Toast.makeText(this, "Open: " + classes.getTitleClass(), Toast.LENGTH_SHORT).show();

        String titleNew = classes.getTitleClass();
        getSupportActionBar().setTitle(titleNew);

        linkClass = classes.getLinkClass();

    }

    @Override
    public void openPlatform(PlatformVo platform) {

    }
}
`

**ADAPTER**

`package com.education.photoapp.activities;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.res.Configuration;
import android.graphics.PorterDuff;
import android.graphics.drawable.Drawable;
import android.os.Build;
import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.education.photoapp.R;
import com.education.photoapp.adapters.ClassesAdapter;
import com.education.photoapp.classes.ClassesVo;
import com.education.photoapp.classes.PlatformVo;
import com.education.photoapp.classes.UnityVo;
import com.education.photoapp.interfaces.IComunica;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.options.IFramePlayerOptions;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.utils.YouTubePlayerUtils;
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView;

import java.util.ArrayList;
import java.util.Objects;

public class PlayerActivity extends AppCompatActivity implements IComunica{

    YouTubePlayerView ytPlayer;

    TextView titleUnity;
    Button btnNext;

    RecyclerView recyclerView;
    ClassesAdapter classesAdapter;

    ArrayList<UnityVo> unityList;
    ArrayList<ClassesVo> classList;

    String titleTool, titleUnities, linkClass;
    Toolbar toolbar;

    boolean isFullScreen = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_player);

        ytPlayer = findViewById(R.id.player_video);
        startYtPlayer();

        titleUnity = findViewById(R.id.title_unity_activity);
        titleUnities = getIntent().getStringExtra("unityComplete");
        titleUnity.setText(titleUnities);

        btnNext = findViewById(R.id.btn_test);
        btnNext.setOnClickListener(v -> {
            //recreate();

        });

        titleTool = getIntent().getStringExtra("title");
        toolbar = findViewById(R.id.toolbar_player_fragment);
        setSupportActionBar(toolbar);
        Objects.requireNonNull(getSupportActionBar()).setDisplayHomeAsUpEnabled(true);
        getSupportActionBar().setDisplayShowHomeEnabled(true);
        getSupportActionBar().setTitle(titleTool);
        toolbar.setTitleTextColor(getColor(R.color.white));
        toolbar.setNavigationOnClickListener(v -> onBackPressed());

        final Drawable menuIcon = getResources().getDrawable(R.drawable.ic_back);
        menuIcon.setColorFilter(getResources().getColor(R.color.white), PorterDuff.Mode.SRC_ATOP);
        getSupportActionBar().setHomeAsUpIndicator(menuIcon);

        fillRecycler();

    }

    private void startYtPlayer() {
        IFramePlayerOptions iFramePlayerOptions = new IFramePlayerOptions.Builder()
                .controls(1)
                .fullscreen(0)
                .build();

        getLifecycle().addObserver(ytPlayer);
        ytPlayer.initialize(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {

                nextVideo(youTubePlayer);

                YouTubePlayerUtils.loadOrCueVideo(
                        youTubePlayer, getLifecycle(),
                        getIntent().getStringExtra("link"), 0f
                );
            }
        }, true, iFramePlayerOptions);
    }

    private void nextVideo(YouTubePlayer youTubePlayer) {
        
        YouTubePlayerUtils.loadOrCueVideo(
                youTubePlayer, getLifecycle(),
                linkClass, 0
        );

    }

    @Override
    public void onConfigurationChanged(@NonNull Configuration newConfig){
        super.onConfigurationChanged(newConfig);

        if (newConfig.orientation == Configuration.ORIENTATION_LANDSCAPE){

            ytPlayer.matchParent();

        } else if (newConfig.orientation == Configuration.ORIENTATION_PORTRAIT){

            ytPlayer.wrapContent();

        }

    }

    private void fillRecycler() {

        unityList = getUnityList();

        classList = getClassList();
        ClassesVo classes;

        int i;

        if(titleUnities.equals(getString(R.string.unity_1))) {

            ArrayList<ClassesVo> unityUno = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_1_))){
                    unityUno.add(classes);
                    classesAdapter = new ClassesAdapter(unityUno, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        } else if(titleUnities.equals(getString(R.string.unity_2))) {

            ArrayList<ClassesVo> unityDos = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_2_))){
                    unityDos.add(classes);
                    classesAdapter = new ClassesAdapter(unityDos, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        } else if(titleUnities.equals(getString(R.string.unity_3))) {

            ArrayList<ClassesVo> unityTres = new ArrayList<>();
            recyclerView = findViewById(R.id.recycler_video);
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(this);
            recyclerView.setLayoutManager(linearLayoutManager);

            for(i=0 ; i < classList.size(); i++) {

                classes = classList.get(i);

                if(classes.getUnityClass().equals(getString(R.string.unity_3_))){
                    unityTres.add(classes);
                    classesAdapter = new ClassesAdapter(unityTres, (IComunica) this);
                    recyclerView.setAdapter(classesAdapter);
                }
            }

        }

    }

    private ArrayList<UnityVo> getUnityList() {

        ArrayList<UnityVo> unitiesList = new ArrayList<>();
        unitiesList.add(new UnityVo(getString(R.string.unity_1), getString(R.string.unity_1_description), R.drawable.unity_1, R.drawable.unity_1_ds));
        unitiesList.add(new UnityVo(getString(R.string.unity_2), getString(R.string.unity_2_description), R.drawable.unity_2, R.drawable.unity_2_ds));
        unitiesList.add(new UnityVo(getString(R.string.unity_3), getString(R.string.unity_3_description), R.drawable.unity_3, R.drawable.unity_3_ds));

        return unitiesList;
    }

    private ArrayList<ClassesVo> getClassList() {

        ArrayList<ClassesVo> classList = new ArrayList<>();

        //fill the recycler
        //Unity 1
        classList.add(new ClassesVo(1, getString(R.string.class_1), getString(R.string.class_1_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_1_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_2), getString(R.string.class_2_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_2_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_3), getString(R.string.class_3_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_3_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_4), getString(R.string.class_4_time), getString(R.string.unity_1_), getString(R.string.unity_1), getString(R.string.class_4_link)));

        //Unity 2
        classList.add(new ClassesVo(1, getString(R.string.class_5), getString(R.string.class_5_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_5_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_6), getString(R.string.class_6_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_6_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_7), getString(R.string.class_7_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_7_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_8), getString(R.string.class_8_time), getString(R.string.unity_2_), getString(R.string.unity_2), getString(R.string.class_8_link)));

        //Unity 3
        classList.add(new ClassesVo(1, getString(R.string.class_9), getString(R.string.class_9_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_9_link)));
        classList.add(new ClassesVo(2, getString(R.string.class_10), getString(R.string.class_10_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_10_link)));
        classList.add(new ClassesVo(3, getString(R.string.class_11), getString(R.string.class_11_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_11_link)));
        classList.add(new ClassesVo(4, getString(R.string.class_12), getString(R.string.class_12_time), getString(R.string.unity_3_), getString(R.string.unity_3), getString(R.string.class_12_link)));

        return classList;
    }

    @Override
    public void openActivity(String nameActivity) {

    }

    @Override
    public void openClass(ClassesVo classes) {
        Toast.makeText(this, "Open: " + classes.getTitleClass(), Toast.LENGTH_SHORT).show();

        String titleNew = classes.getTitleClass();
        getSupportActionBar().setTitle(titleNew);

        linkClass = classes.getLinkClass();

    }

    @Override
    public void openPlatform(PlatformVo platform) {

    }
}
`

**Comment by PierfrancescoSoffritti** [comment]
Hi, we have [a complete example in the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/tree/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/recyclerViewExample). Please refer to the example.

**Comment by aleacx** [comment]
Thanks for your answer, but I got a new doubt, it's possible to change the video from a recycler with a Interface with onClick.. 🤔 

I did it with a button, but I am looking that when I press the recycler a new video load.. thanks for your time to answer.. 😀

![Screenshot_2023-03-30-16-30-47-836_com education photoapp](https://user-images.githubusercontent.com/129437450/228969543-32e8f250-d538-4856-a473-bdf13d4f1895.jpg)

**Comment by PierfrancescoSoffritti** [comment]
Yeah, everything should be possible :)
