### ISSUE TITLE
Stop video when fragment is not visible

### ISSUE THREAD

**Issue by memobeyle** [PierfrancescoSoffritti/android-youtube-player#949]
Hello,

There are 4 fragments with scrolling and I am using youtubeplayer in one of them, when the video is playing, when I switch to a different fragment, the video continues to play. But I want the video to stop. Previously, when using youtube player api, there was UNAUTHORIZED_OVERLAY option, how can we do it here?

**Comment by PierfrancescoSoffritti** [comment]
What do you mean? you can call `youTubePlayer.pause()` and the video will stop playing.

**Comment by memobeyle** [comment]
The part with LifecycleObserver didn't work, as you said, I need to manually check the overlay event and make a pause, but I couldn't find how to do it clearly. How can I understand that the youtube player is covered when something comes on top of youtubeplayer, when the notification screen or fragment changes?

**Comment by PierfrancescoSoffritti** [comment]
Well that depends on how your app is made :)

**Comment by memobeyle** [comment]
Application made by a junior (I hope you can guess :) ) thank you for your help, let me do a research on this. But there are some things I would like you to add in order to improve the library;

1- Getting UNAUTHORIZED_OVERLAY error
2- add onseekto event
3- show youtube ads
