### ISSUE TITLE
Youtube video starts pausing on its own

### ISSUE THREAD

**Issue by kaustubhamrit** [PierfrancescoSoffritti/Android-YouTube-Player#95]
I have used the youtube player view in a recycler view and the youtube player gets paused on its own sometimes when i come back to the same video again

**Comment by PierfrancescoSoffritti** [comment]
Hi, unfortunately I can't say much about your code. I recommend you take a look to the [sample app](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/sample/src/main/java/com/pierfrancescosoffritti/youtubeplayersample/MainActivity.java) to see if you're doing something wrong in regards of the library.

**Comment by kaustubhamrit** [comment]
I am using the library by placing the youtube player view to the feed card view and the recycler view inflates the feed card view accordingly if the feed is a youtube video or something else.Everything works fine..thanks to you!But the video pauses sometimes on its own..i have seen the sample app and have implemented my player similarly and i am using load video to autoplay.I used a player listener also to check the current state and if the view is focused and video is paused i make it play but then it plays and pauses consecutively on its own because something is triggering the video to get paused.I have exactly followed the sample app

**Comment by PierfrancescoSoffritti** [comment]
Hi, I have just built a [sample app using recycler view](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/tree/master/sample/src/main/java/com/pierfrancescosoffritti/youtubeplayersample/recyclerViewSample). As you can see everything works fine. The issue must be in your code.

I suggest not using `loadVideo` when you have multiple players in a recycler view. You won't know which one is going to be the last one to start playing, and it will stop all the other players from playing. `cueVideo` is more reasonable for this use case.

**Comment by kaustubhamrit** [comment]
ok..thanks!
