### ISSUE TITLE
How to minimize/dismiss settings control without pausing the video

### ISSUE THREAD

**Issue by MananArya22** [PierfrancescoSoffritti/android-youtube-player#952]
# Question / Problem

### Summary
Go to settings control and change the playback speed. Now to minimize the settings controls click on the playing youtube video player view. This minimizes the settings control but also pauses the video. How to minimize the settings control but prevent the video from pausing?

<img width="669" alt="Screenshot 2023-04-02 at 12 18 22 PM" src="https://user-images.githubusercontent.com/17155215/229337405-9a6596cc-96cc-4c51-a533-6fd80fca8577.png">

**Comment by PierfrancescoSoffritti** [comment]
Hi, the library has no control over the settings panel. It is part of the IFrame Player.

**Comment by MananArya22** [comment]
@PierfrancescoSoffritti This behaviour works perfectly fine in website using the same IFrame based YouTube player(Default Web View). 
Please see this in YouTube player demo: https://developers.google.com/youtube/youtube_player_demo

Is this issue specific for Android?

**Comment by PierfrancescoSoffritti** [comment]
We don't make any special modification to the IFrame Player, so probably.
