### ISSUE TITLE
Share disabled 

### ISSUE THREAD

**Issue by GirijaHegdeGit** [PierfrancescoSoffritti/android-youtube-player#958]
Hi,

When we say YouTubePlayerView.setCustomPlayerUi(defaultPlayerUiController.getRootView()); 

And run the app,
1. youTube player background events are getting disabled like **click on share** nothing will happen
2.  In we go to full screen view the image of the button won't change to go to **normal screen view** link in you tube

**Comment by GirijaHegdeGit** [comment]
<img width="208" alt="2023-04-06" src="https://user-images.githubusercontent.com/129252158/230375244-462f3c10-2460-4622-a4f5-802012aaa565.png">

**Comment by PierfrancescoSoffritti** [comment]
That is expected, clicks on the custom UI prevent clicks from being dispatched to the web ui. I suggest using web ui.

**Comment by PierfrancescoSoffritti** [comment]
[It does](https://github.com/PierfrancescoSoffritti/android-youtube-player#full-screen).

**Comment by GirijaHegdeGit** [comment]
I am using version 11.1.0 and I can't integrate 12.0.0 some reason

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PierfrancescoSoffritti** [comment]
Why not? what happens?

**Comment by GirijaHegdeGit** [comment]
Any constraints on version 12.0.0, which we need to take care. Bcz 11.1.0 is getting downloaded properly not 12.0.0 from Android Studio. Any permission required??

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by PierfrancescoSoffritti** [comment]
Can you show me the error you're getting?

**Comment by PierfrancescoSoffritti** [comment]
I just noticed you are the same person from issue #954. I would suggest trying to figure out why you're not able to download version 12.
