### ISSUE TITLE
Fullscreen controls in v12.0.0

### ISSUE THREAD

**Issue by valkoasd** [PierfrancescoSoffritti/android-youtube-player#959]
Documentation says: 

> When FullscreenListener#onEnterFullscreen is called, **the player will be rendered inside fullscreenView instead of YouTubePlayerView**, until FullscreenListener#onExitFullscreen is called. Therefore you are required to add fullscreenView to your app's view hierarchy when fullscreen is started, and remove it when fullscreen is ended.

but if we use this fullscreenView to render the video in it, how to add controls to it? Because it is not a **YouTubePlayerView** and we can't use **setCustomPlayerUi()** with **DefaultPlayerUiController** for example.

**Comment by PierfrancescoSoffritti** [comment]
If you want to use custom controls you can't use `FullscreenListener`, you need to have a custom solution. Also have a look at the sample app, the example using `DefaultPlayerUiController` is handling fullscreen.
