### ISSUE TITLE
does autoplay affect views?

### ISSUE THREAD

**Issue by memobeyle** [PierfrancescoSoffritti/android-youtube-player#962]
Hello,

As you know, when we use play() and loadvideo() the video is started. When we use them, will there be problems such as decreases in the number of views or not being counted?

**Comment by PierfrancescoSoffritti** [comment]
I don't think so. YouTube is smart in how they count a view.

**Comment by memobeyle** [comment]
So when I autostart the video or trigger play() , youtube doesn't count it, does it?

**Comment by PierfrancescoSoffritti** [comment]
Probably not.

**Comment by memobeyle** [comment]
so let me test it and come back here so that others can benefit as well.
