### ISSUE TITLE
How to disable "More options" sub items to view on long click

### ISSUE THREAD

**Issue by MananArya22** [PierfrancescoSoffritti/android-youtube-player#963]
# Question / Problem

### Summary
In the settings tab, there is a "More options" menu item below the "Quality" menu item, which further contains a lot of useless sub-items. I am able to hide this from the settings menu using the solution discussed in [Issue #960](https://github.com/PierfrancescoSoffritti/android-youtube-player/issues/960). But these "More options" sub-items are still visible when we long click on the youtube view. I want to disable these options.

![WhatsApp Image 2023-04-15 at 1 47 19 PM](https://user-images.githubusercontent.com/17155215/232200120-46886983-a681-4caa-9a19-e82285f1a322.jpeg)

### What I've tried
I have already tried setting up a OnLongClickListener on the youtube view, but it doesn't work.

`View.OnLongClickListener mYouTubePlayerViewLongClickListener = new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View v) {
                return true;
            }
        };
 youTubePlayerView.setOnLongClickListener(mYouTubePlayerViewLongClickListener);`

I have also tried setting up the OnLongClickListener on the WebViewYouTubePlayer in its initialize method. 

`internal fun initialize(initListener: (YouTubePlayer) -> Unit, playerOptions: IFramePlayerOptions?) {
    youTubePlayerInitListener = initListener
    initWebView(playerOptions ?: IFramePlayerOptions.default)
    this.setOnLongClickListener { true }
  }`

But even this doesn't work.

I am able to achieve this by setting display as none for the HTML Tags, but I don't want to edit the HTML, rather achieve this by setting onLongClickListener.

`const s_popup = frameDoc.querySelector(".ytp-contextmenu");
s_popup.style.display = 'none';`

@Serkali-sudo @PierfrancescoSoffritti Please suggest a solution for this.

**Comment by PierfrancescoSoffritti** [comment]
You can put an invisible view on top of the player, then set the long click listener on that view.

**Comment by fxxs** [comment]
I just put an invisible view on top of the player and set the long click listener on that, but it blocked the touch event on the player.(I initialized player with webUI.)

**Comment by PierfrancescoSoffritti** [comment]
You need to set the invisible view to GONE when you want to interact with the player.
