### ISSUE TITLE
Do you have the .jar file for 9.0.1 version? I need version before the kotlin rewrite please

### ISSUE THREAD

**Issue by Aloau** [PierfrancescoSoffritti/android-youtube-player#966]
Looked at maven central but it seems the oldest version hosted is 11.0.x
Help pls

**Comment by Aloau** [comment]
Is there a version that doesn't require androidx support? Working on really old devices here

**Comment by PierfrancescoSoffritti** [comment]
Why do you need the old version? you can probably find it in Jcenter.

**Comment by Aloau** [comment]
I need somethng before the androidx and kotlin rewrite, as I have special use case where my target device is running Android 4.4 (API level 19), I tried using 10.0.3 and it gave error : resource android attr dialog corner radius not found. I am unable to target a higher SDK with androidx support, my target is API 19.

Do you know how I can download 8.0.1 or do you have an archive link?

https://jcenter.bintray.com/com/pierfrancescosoffritti/androidyoutubeplayer/core/8.0.1
gives 403 forbidden error on jcenter

**Comment by PierfrancescoSoffritti** [comment]
Can't you set your target sdk to a higher API version and keep the min sdk to api 19?

Every release contains the source code in a zip file, you could use that to build your local version of the library.

**Comment by Aloau** [comment]
but android 4.4 doesn't have androidx either

**Comment by Aloau** [comment]
do you have the old version that was made with java before the migration to androidx

**Comment by PierfrancescoSoffritti** [comment]
Only the target sdk matters, the min sdk can be as low as you wish. [See docs](https://developer.android.com/jetpack/androidx).

As i said, you can find old versions [in the release artifacts](https://github.com/PierfrancescoSoffritti/android-youtube-player/releases).
