### ISSUE TITLE
Ads have started coming from version 12.0.0 onwards

### ISSUE THREAD

**Issue by MananArya22** [PierfrancescoSoffritti/android-youtube-player#967]
# Question / Problem

### Summary
We are using the version 12.0.0 and have observed that ads are coming while playing the videos. Is this change of showing ads introduced from version 12.0.0 onwards? Can downgrading the version help us in blocking the ads? If yes, on which version to downgrade to stop seeing the ads? Also, on what basis does YouTube decide to show ads before the video? Does that depend on if the channel has enabled ads on a particular video or YouTube plays ads even when the channel has not enabled ads on that video?

@PierfrancescoSoffritti @Serkali-sudo Please help on this. Facing this issue on production environment post app release.

**Comment by PierfrancescoSoffritti** [comment]
Ads showing up is not related to version 12. YouTube decides when to show them.
