### ISSUE TITLE
The video does not play in the fragment

### ISSUE THREAD

**Issue by mixggggg** [PierfrancescoSoffritti/android-youtube-player#968]
<!-- Hello. I use your library in my application. I found a small problem. If you implement the player programmatically in activity, then it works without problems (videos are played). And if I insert the same code to implement programmatically into a fragment, then the video does not play and an error appears on the player layout that the video is not loaded. And if you register the video ID in xml, then everything works, but I need to implement the player programmatically in a fragment. How can I solve this problem?

**Comment by PierfrancescoSoffritti** [comment]
Please provide more information if you need assistance.
