### ISSUE TITLE
Does not play video from fragments

### ISSUE THREAD

**Issue by mixggggg** [PierfrancescoSoffritti/android-youtube-player#969]
I can't play the video from the fragments programmatically with the same code as the activity

Hello. I have a problem with playing a video in a fragment. if you implement video playback in the activity, then everything works fine. And if you programmatically implement video playback in a fragment, then the video does not load. I use the code as in the activity. It is possible to play the video in an xml fragment, but I need to make a software implementation. If you programmatically open a video from a fragment, an error appears that the video was not found. Maybe there is a separate code for fragments?

I tried to find many ways

**Comment by mixggggg** [comment]
Hello. I have a problem with playing a video in a fragment. if you implement video playback in the activity, then everything works fine. And if you programmatically implement video playback in a fragment, then the video does not load. I use the code as in the activity. It is possible to play the video in an xml fragment, but I need to make a software implementation. If you programmatically open a video from a fragment, an error appears that the video was not found. Maybe there is a separate code for fragments?

**Comment by PierfrancescoSoffritti** [comment]
The code to play videos in Activity and Fragment is the same. It's probably a bug in your code.
