### ISSUE TITLE
Play controls still work when invisible

### ISSUE THREAD

**Issue by Janneman84** [PierfrancescoSoffritti/android-youtube-player#972]
I noticed that when the controls have faded out they still work. So depending on where you tap on the video stuff still happens when you probably didn't want it to.

In the YouTube app and other video players you always need to tap first to show the controls before you can actually use them. Would that be possible here too?

I'm not using custom UI btw.

**Comment by PierfrancescoSoffritti** [comment]
Hi, web UI is controlled by the IFrame Player, it is the UI implemented by YouTube. The library doesn't have any control over it.

**Comment by Janneman84** [comment]
Is it somehow possible to check if the controls are on screen or not?

If so I know how to hack around the issue :).
