### ISSUE TITLE
My video is not going fullscreen when using the fullscreen button

### ISSUE THREAD

**Issue by yenhoangvn** [PierfrancescoSoffritti/android-youtube-player#983]
# My video is not going fullscreen when using the fullscreen button

### Summary
Context: My app will be always in landscape mode, first I need to render the video with half-screen size when the user clicks on the fullscreen button => it should render the video with fullscreen size. 
![Screenshot_20230508_123132 (1)](https://user-images.githubusercontent.com/89490337/236802348-aacd82b5-c8b1-46d8-b1ee-5657c912b8d2.png)

However, the bottom bar of the video is not going fullscreen despite the title of the video rendering correctly ( see the screenshot below).
![344293167_3307015159515617_1886294744554259331_n](https://user-images.githubusercontent.com/89490337/236797402-4a3a7550-3482-443b-97c8-c5f952055e95.jpg)

### What I've tried
activity_main.xml
`  
    <FrameLayout
        android:id="@+id/full_screen_view_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:visibility="gone" />

    <FrameLayout
        android:id="@+id/youtube_player_view_container"
        android:layout_height="0dp"
        android:layout_width="0dp"
        app:layout_constraintBottom_toBottomOf="@id/gl_bottom"
        app:layout_constraintEnd_toEndOf="@id/gl_right"
        app:layout_constraintStart_toStartOf="@+id/side_bar_end2"
        app:layout_constraintTop_toTopOf="@id/search_bar_end2">

        <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
            android:id="@+id/youtube_player_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </FrameLayout>
`
MainActivity.java
` private void initYouTubePlayerView() {
        getLifecycle().addObserver(youTubePlayerView);
        youTubePlayerView.setEnableAutomaticInitialization(false);
        youTubePlayerView.addFullscreenListener(new FullscreenListener() {
            @Override
            public void onEnterFullscreen(@NonNull View view, @NonNull Function0<Unit> function0) {
                youTubePlayerView.setVisibility(View.GONE);
                fullscreenViewContainer.setVisibility(View.VISIBLE);
                fullscreenViewContainer.addView(view);
            }

            @Override
            public void onExitFullscreen() {
                youTubePlayerView.setVisibility(View.VISIBLE);
                fullscreenViewContainer.setVisibility(View.GONE);
                fullscreenViewContainer.removeAllViews();
            }
        });
        YouTubePlayerListener youTubePlayerListener = new AbstractYouTubePlayerListener() {
            @Override
            public void onReady(@NonNull YouTubePlayer youTubePlayer) {
                super.onReady(youTubePlayer);
                setYouTubePlayer(youTubePlayer);
            }

            @Override
            public void onStateChange(@NonNull YouTubePlayer youTubePlayer, @NonNull PlayerConstants.PlayerState state) {
                super.onStateChange(youTubePlayer, state);
                onNewState(state);

            }

        };
        IFramePlayerOptions iFramePlayerOptions = new IFramePlayerOptions.Builder()
                .controls(1)
                .fullscreen(1) // enable full screen button
                .build();
        youTubePlayerView.initialize(youTubePlayerListener, iFramePlayerOptions);
    }`

**Comment by PierfrancescoSoffritti** [comment]
It looks like this is a bug in your own application. Please look at the sample app for working examples of how to use the library.
