### ISSUE TITLE
I have a Question  - videos can only be watched from within the application

### ISSUE THREAD

**Issue by yhackup** [PierfrancescoSoffritti/android-youtube-player#984]
Hello, I have not used the library yet, I need to learn something beforehand.

I want to add my unlisted videos on youtube to the application.

However, the user certainly can not see the url of these youtube videos, you can not share it with someone else. I want to be able to watch videos only from within the application, is this possible?

**Comment by PierfrancescoSoffritti** [comment]
It should be possible, as long as the videos are available for people that have the URL.

**Comment by yhackup** [comment]
how should i set it i tried a few times but the share button appears on the frame

**Comment by PierfrancescoSoffritti** [comment]
What do you mean?

**Comment by yhackup** [comment]
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/15657038/6180cfe8-1143-434e-9c1b-7ed5c956b8a9)

this way i don't want the video to be shared url access

**Comment by PierfrancescoSoffritti** [comment]
I don't think you can remove the share button. You can have a look at the IFrame API documentation.

**Comment by yhackup** [comment]
I didn't see anything about this in the docs so I asked here
