### ISSUE TITLE
App Crashes when using YouTube Player view in a RecyclerView (specifically with fullscreen functionality)

### ISSUE THREAD

**Issue by Devenom1** [PierfrancescoSoffritti/android-youtube-player#987]
### Description of the Bug
I use a RecyclerView to show multiple YouTube videos in the YouTube player view. I also need the fullscreen functionality. So I have to manually initialize the player with the `initialize` function. The issue happens when the views get recycled/reused in the RecyclerView. I get the following error `java.lang.IllegalStateException: This YouTubePlayerView has already been initialized` and the app crashes. 

This is the code I use to initialize the YouTube player view in the RecyclerView Adapter.
```
youtubePlayerView.enableAutomaticInitialization = false

val iFramePlayerOptions = IFramePlayerOptions.Builder()
    .controls(1)
    .fullscreen(1) // enable full screen button
    .build()

youtubePlayerView.addFullscreenListener(object : FullscreenListener {
    override fun onEnterFullscreen(fullscreenView: View, exitFullscreen: () -> Unit) {
        isFullscreen = true
       .....
    }

    override fun onExitFullscreen() {
        isFullscreen = false
       .....
    }
})

youtubePlayerView.initialize(object : AbstractYouTubePlayerListener() {
    override fun onReady(youTubePlayer: YouTubePlayer) {
        youTubePlayer.cueVideo(video.youtubeVideoId, 0f)
        ......
    }
}, iFramePlayerOptions)
```

 So here's whats happening in the recyclerview adapter. Since the cells/item views get recycled the view containing the youtube player view also gets recycled. And because of that one of the youtube player view that was already initialized before calls the initialize method again.

I've very new to this library. I love it though. There's at least one good youtube library that supports youtube videos. Please correct me if I'm doing something wrong. Or let me know if there is a work around.

I've implemented a work around but it's not a good one and affects performance.

### Environment details

Android Version: Android 5 up to Android 13
API Version: 21-33

Tested devices:
Mutliple Emulators And Poco X3

Youtube Player Library Version: 12.0.0

### Steps to reproduce the bug

1. Create a RecyclerView with 10-20 items each containing a YouTube Player View.
2. Make sure that the Youtube Player View has fullscreen functionality. This means enabling manual initialization.
3. Scroll a little bit and the app will crash

### Expected behavior
The App shouldn't crash when the Youtube Player View with fullscreen functionality loads in a RecyclerView adapter

### Actual behavior
The App shouldn't crashes when the Youtube Player View with fullscreen functionality loads in a RecyclerView adapter

**Comment by PierfrancescoSoffritti** [comment]
You should keep a reference to the `YouTubePlayer` object in the the `ViewHolder`. Once a `YouTubePlayerView` has been initialized you can't initialize it again. So store the reference to `YouTubePlayer` and reuse that to load new videos.

The [sample app has an example showing how to do this](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/recyclerViewExample/RecyclerViewAdapter.kt#L39).

**Comment by Devenom1** [comment]
Hi @PierfrancescoSoffritti Thank you. I had referenced the same example and done it. But how do I use the FullScreen functionality with it. The FullScreen functionality requires us to call the initialize method on the youtubeplayer view along with the iFrame options. I'm a bit confused with the specific case of having full-screen functionality inside the RecyclerView specifically. 

Is there another way to initialise the player to enable full-screen functionality?

**Comment by PierfrancescoSoffritti** [comment]
> The FullScreen functionality requires us to call the initialize method on the youtubeplayer view along with the iFrame options

You initialize the player once, using the IFrameOptions. You also set the FullScreenListener once, using `YouTubePlayerView#addFullscreenListener`. After this is done you're set and everything should work fine.

For example (this is pseudo code, it doesn't compile)

```
class MyViewHolder() : ViewHolder {
  private var youtubePlayer: YouTubePlayer? = null
  init {
    youtubePlayerView.setFullScreenListener( .. )
    youtubePlayerView.initialize(options) { initializedPlayer ->
      youtubePlayer = initializedPlayer
    }
  }
}
```
after this you can use the `youtubePlayer` every time the content of the `ViewHolder` changes.

**Comment by Devenom1** [comment]
Hey @PierfrancescoSoffritti Thanks again. I understood the fullscreen functionality much better now. I just implemented it this way.

But there's another minor issue.
![Youtube Player View issue](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/11510037/45ce3312-e82f-4295-a327-78e03c8e47fd)
The first 2 views don't seem to load the first time. It might probably be because they are not initialized yet. How can I work around this?

The collapsible views in the gif above are using a library `com.github.cachapa:ExpandableLayout` that just hides or shows the view with animation.

**Comment by PierfrancescoSoffritti** [comment]
I am not sure, hard to say without seeing your code. Since these are not issues with the library I am going to close this issue for now. Thanks for using the library!

**Comment by Devenom1** [comment]
Hey @PierfrancescoSoffritti I won't open a new issue but can you check this out? This is my code. I think I've done everything the way you mentioned.

```
package com.telyport.telyportagentlite.ui.training_screen

import android.text.method.LinkMovementMethod
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.FrameLayout
import androidx.core.view.isVisible
import androidx.databinding.DataBindingUtil
import androidx.recyclerview.widget.RecyclerView
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.YouTubePlayer
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.AbstractYouTubePlayerListener
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.listeners.FullscreenListener
import com.pierfrancescosoffritti.androidyoutubeplayer.core.player.options.IFramePlayerOptions
import com.telyport.telyportagentlite.R
import com.telyport.telyportagentlite.data.models.TrainingVideoData
import com.telyport.telyportagentlite.databinding.RvItemTrainingVideoBinding
import com.telyport.telyportagentlite.utilities.toHtmlSpanned

/**
 * Recycler view adapter for the list of videos
 * @param videoData The list of videos to be shown in the recycler view
 * @param ytFrameLayout The frame layout in which the youtube player will be added
 * @param onPlayerSet The callback to be called when the player is set
 * @param onFullscreen The callback to be called when the player is set to fullscreen
 */
class VideoDataRVAdapter(
    val videoData: List<TrainingVideoData>,
    val ytFrameLayout: FrameLayout? = null,
    val onPlayerSet: (YouTubePlayer) -> Unit = {},
    val onFullscreen: (Boolean) -> Unit = {}
) :
    RecyclerView.Adapter<VideoDataRVAdapter.TrainingVideoViewHolder>() {

    private var selectedPosition: Int = 0

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): TrainingVideoViewHolder {
        val inflater = LayoutInflater.from(parent.context)
        val binding: RvItemTrainingVideoBinding =
            DataBindingUtil.inflate(inflater, R.layout.rv_item_training_video, parent, false)
        return TrainingVideoViewHolder(binding)
    }

    override fun getItemCount() = videoData.size

    override fun getItemId(position: Int) = position.toLong()

    override fun onBindViewHolder(holder: TrainingVideoViewHolder, position: Int) =
        holder.bind(position)

    inner class TrainingVideoViewHolder(private val binding: RvItemTrainingVideoBinding) :
        RecyclerView.ViewHolder(binding.root) {

        private var isFullscreen = false

        private var youTubePlayer: YouTubePlayer? = null

        init {
            binding.youtubePlayerView.enableAutomaticInitialization = false

            val iFramePlayerOptions = IFramePlayerOptions.Builder()
                .controls(1)
                .fullscreen(1) // enable full screen button
                .build()
            binding.youtubePlayerView.addFullscreenListener(object : FullscreenListener {
                override fun onEnterFullscreen(fullscreenView: View, exitFullscreen: () -> Unit) {
                    isFullscreen = true

                    this@TrainingVideoViewHolder.youTubePlayer?.let(onPlayerSet)
                    onFullscreen(true)
                    // the video will continue playing in fullscreenView
                    binding.youtubePlayerView.visibility = View.GONE
                    ytFrameLayout?.visibility = View.VISIBLE
                    ytFrameLayout?.addView(fullscreenView)

                     requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE
                }

                override fun onExitFullscreen() {
                    isFullscreen = false
                    onFullscreen(false)
                    // the video will continue playing in the player
                    binding.youtubePlayerView.visibility = View.VISIBLE
                    ytFrameLayout?.visibility = View.GONE
                    ytFrameLayout?.removeAllViews()
                }
            })

            binding.youtubePlayerView.initialize(object : AbstractYouTubePlayerListener() {
                override fun onReady(youTubePlayer: YouTubePlayer) {
                    this@TrainingVideoViewHolder.youTubePlayer = youTubePlayer
                }
            }, iFramePlayerOptions)
        }

        fun bind(position: Int) {
            val video = videoData[position]
            with(binding) {
                titleTv.isVisible = video.title?.isNotBlank() == true
                if (video.title?.isNotBlank() == true) {
                    titleTv.text = String.format("<u>%s</u>", video.title).toHtmlSpanned()
                }
                video.youtubeVideoId?.takeIf { it.isNotBlank() }?.let {         
                    youTubePlayer?.cueVideo(video.youtubeVideoId, 0f)
                }
                youtubePlayerView.isVisible = video.youtubeVideoId?.isNotBlank() == true

                youtubeLinkTv.isVisible = video.youtubeLink?.isNotBlank() == true
                youtubeLinkTv.isClickable = true
                youtubeLinkTv.movementMethod = LinkMovementMethod.getInstance()
                if (video.youtubeLink?.isNotBlank() == true) {
                    val text = "<a href='${video.youtubeLink}'><u>${video.youtubeLink}</u></a>"
                    youtubeLinkTv.text = text.toHtmlSpanned()
                }

                descriptionTv.isVisible = video.description?.isNotBlank() == true
                descriptionTv.text = video.description

                expandableLayout.isExpanded = selectedPosition == position
                val rotateAngle = if (selectedPosition == position) 0f else 180f
                expArrowIb.animate()?.rotation(rotateAngle)?.start()

                touchLl.isVisible = selectedPosition != position

                listOf(titleCl, touchLl).forEach {
                    it.setOnClickListener {
                        val prevPosition = selectedPosition
                        selectedPosition = position
                        notifyItemChanged(position)
                        if (prevPosition != -1) {
                            notifyItemChanged(prevPosition)
                        }
                    }
                }
            }
        }

    }


}
```

**Comment by Devenom1** [comment]
Hey @PierfrancescoSoffritti Thanks. I figured out the issue. Sorry I had to deleted the previous 2 comments as it had company code and app screen recordings.

**Comment by PierfrancescoSoffritti** [comment]
I'm glad you figured it out. If your company is profiting from this project, consider asking them to [support the project here](https://github.com/sponsors/PierfrancescoSoffritti)
