### ISSUE TITLE
Please help me hide additional choose 

### ISSUE THREAD

**Issue by MohamedElkhouly123** [PierfrancescoSoffritti/android-youtube-player#989]
Please I want hide additional choose button from player and show only quality button how can do this

**Comment by PierfrancescoSoffritti** [comment]
Hi, it's not possible. Because the IFrame player doesn't allow it.

**Comment by MohamedElkhouly123** [comment]
Thanks

في الأربعاء، ٢٤ مايو ٢٠٢٣ ٩:٥٦ م Pierfrancesco Soffritti <
***@***.***> كتب:
