### ISSUE TITLE
Try to make it more easier to use.

### ISSUE THREAD

**Issue by Trusted97** [PierfrancescoSoffritti/Android-YouTube-Player#99]
For example write a guide where explain how use in another project and which file are necessary.

**Comment by PierfrancescoSoffritti** [comment]
Hi, that explanation is both in the [readme file](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/blob/master/README.md) and in the [Wiki](https://github.com/PierfrancescoSoffritti/Android-YouTube-Player/wiki/Quick-start).

**Comment by Trusted97** [comment]
Sorry, but for me it's not a good explanation :)

**Comment by PierfrancescoSoffritti** [comment]
Could you elaborate on that? what is missing in the explanation to be clearer?

**Comment by PierfrancescoSoffritti** [comment]
Or, what makes it unclear to you.

**Comment by Trusted97** [comment]
Sure is probably that is unclear for me. But who are the essential files? The method getLifecycle() where is defined?

**Comment by PierfrancescoSoffritti** [comment]
You need a layout file, in which you have to add the YouTubePlayerView

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical" >

    <com.pierfrancescosoffritti.youtubeplayer.player.YouTubePlayerView
        android:id="@+id/youtube_player_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</LinearLayout>
```

and in your Activity/Fragment you need to get a reference to the view and initialize it, like this:

```
YouTubePlayerView youTubePlayerView = findViewById(R.id.youtube_player_view);

youTubePlayerView.initialize(new YouTubePlayerInitListener() {
    @Override
    public void onInitSuccess(final YouTubePlayer initializedYouTubePlayer) {    
        initializedYouTubePlayer.addListener(new AbstractYouTubePlayerListener() {
            @Override
            public void onReady() {
                String videoId = "6JYIGclVQdw";
                initializedYouTubePlayer.loadVideo(videoId, 0);
            }
        });        
    }
}, true);
```
---
`getLifecycle()` is a method that every lifecycle owner has. Activity and Fragment are lifecycle owners.

**Comment by Trusted97** [comment]
Any idea because `this.getLifecycle().addObserver(youTubePlayerView);` say to me "Cannot resolve method getLifecycle()" ?

**Comment by PierfrancescoSoffritti** [comment]
Is your Activity extending `AppCompatActivity`?

**Comment by PierfrancescoSoffritti** [comment]
if you don't want to use the lifecycle of your Activity you can do this instead:

```
@Override
public void onDestroy() {
    super.onDestroy();
    youTubePlayerView.release();
}
```

**Comment by Trusted97** [comment]
> Is your Activity extending AppCompatActivity?
Yes is it. 


i'll try this
```
@Override
public void onDestroy() {
    super.onDestroy();
    youTubePlayerView.release();
}
```

**Comment by Trusted97** [comment]
Ok i'm getting made to use it. What i need to do for install this library in android studio?

**Comment by PierfrancescoSoffritti** [comment]
As explained in the introduction:

Add this to your project-level build.gradle

```
allprojects {
  repositories {
    ...
    maven { url "https://jitpack.io" }
  }
}
```
Add this to your module-level build.gradle

```
dependencies {
  implementation 'com.github.PierfrancescoSoffritti:AndroidYouTubePlayer:4.1.7'
}
```
