### ISSUE TITLE
Not able to made changes WebViewYouTubePlayer.kt File.

### ISSUE THREAD

**Issue by samaransa** [PierfrancescoSoffritti/android-youtube-player#994]
# Bug Report

### Environment details

Android Version: 
API Version: 

Tested devices:

Youtube Player Library Version: 

### Steps to reproduce the bug
---
name: Bug report
about: Use this template for reporting bugs
labels: bug
---

 

# Bug Report

### Environment details

Android Version: 
API Version: 

Tested devices:

Youtube Player Library Version: 

### Additional information
<!-- Provide here further information that might help understand the issue or reproduce the bug, e.g. 
- standalone code snippets of implementation that can copy-pasted and work without any missing classes
- screenshot(s) of visualising the bug
- error logs
- any useful background infromation

**Comment by samaransa** [comment]
i am not able to write any things in these file.

**Comment by PierfrancescoSoffritti** [comment]
You need to import the project to be able to edit it. Including a library is not enough.
