### ISSUE TITLE
YouTubePlayer.play() not working in android-youtube-player

### ISSUE THREAD

**Issue by ben-WIM** [PierfrancescoSoffritti/android-youtube-player#999]
### Discussed in https://github.com/PierfrancescoSoffritti/android-youtube-player/discussions/998

<div type='discussions-op-text'>

<sup>Originally posted by **ben-WIM** June 12, 2023</sup>
Hi all,
So I'm a bit stuck with trying to play a youtube video programmatically. When I use a custom button which calls play() on the YoutubePlayer Object then it invokes the library function which registers the playVideo command (and I do indeed do a cueVideo before that), yet the youtube player doesn't seem to respond in any way. There are no exceptions, warnings or errors. The video cues just fine and I can play it without any issue when I use the Youtube UI directly. Can someone tell me what I'm missing?

Here's how I initialize it 

```
void loadYoutubeFragment() {
        // You can assume all null checks and relevant initializations were done
        if (webView == null) {
            webView = (YouTubePlayerView) (Object) player.findSiblingFragment(R.id.youtube_fragment);
        }

        try {
            YouTubePlayerListener listener = new AbstractYouTubePlayerListener(){};
            IFramePlayerOptions options = new IFramePlayerOptions.Builder().controls(0).build();
            webView.setEnableAutomaticInitialization(false);
            webView.initialize(listener, options);
            webView.getYouTubePlayerWhenReady(youTubePlayer -> {
                //Add a tracker to get various info from the video
                youTubePlayer.addListener(tracker);
                video = Optional.of(youTubePlayer);
            });
        } catch (IllegalStateException e) {
            UnisonMobileLog.e("YoutubePlayerFragment", "Exception initialising youtube webview.", e);
        }
    }

```
And then (within the same class) the onClick event which should start the video executes this code (and some variations I tried)

```
public void play() {
    video.ifPresent(YouTubePlayer::play);

//.............Also tried this
//        webView.getYouTubePlayerWhenReady(youTubePlayer -> {
//            youTubePlayer.play();
//        });

//............And this (where video in this case is youtubePlayer tyepe)
//        if(video != null){
//            video.play();
//        }
    }
```

And then this is what my XML looks like for the element
```
    <com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView
        android:id="@+id/youtube_fragment"
        android:name="com.pierfrancescosoffritti.androidyoutubeplayer.core.player.views.YouTubePlayerView"
        android:layout_width="match_parent"
        android:layout_height="241dp"
        app:videoId="@string/yt_test_video_a"
        app:handleNetworkEvents="false"
        android:background="@android:color/black"
        tools:ignore="Instantiatable" />
```

Like I said, the video initializes and cues correctly and can be played directly via the UI but I cannot seem to get it to play using the play() method. Please let me know if there's something I'm missing an thanks for and thanks for taking the time to look through this question.
</div>

**Comment by PierfrancescoSoffritti** [comment]
Hey, thanks for sponsoring the project!

Did you have a chance to [look at the sample app](https://github.com/PierfrancescoSoffritti/android-youtube-player/blob/master/core-sample-app/src/main/java/com/pierfrancescosoffritti/androidyoutubeplayer/core/sampleapp/examples/completeExample/CompleteExampleActivity.kt)? The code there probably contains the answer you're looking for.

**Comment by ben-WIM** [comment]
I did, yes. So it's very similar to how this example is setup. I have an onClickListener which essentially calls the play() function in my code above. 
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/122349875/03952d8e-6beb-464d-829a-632ea304a8d2)
So when you click on the button (bottom left half offscreen) it basically triggers the youtubePlayer.play() function which gets invoked in the webViewYouTubePlayer.kt class. The view it's linked to is the video fragment you see in the screenshot 
![image](https://github.com/PierfrancescoSoffritti/android-youtube-player/assets/122349875/3b76ae19-14b4-45e8-b1af-82b2bb781b89)
So after it exits that function in which it registered the playVideo command nothing happens to the video. I'm just wondering why that could be

**Comment by PierfrancescoSoffritti** [comment]
Are you sure you're managing fragment state correctly? Is it possible that you're invoking an instance of YoutubePlayerView in another fragment? it's hard for me to provide useful help without seeing your project. But I suspect the issue is on your end, not in the library.

**Comment by ben-WIM** [comment]
You were right, this was a problem on my end, I was referencing the parent view of the element. Although I am now facing the same problem as this issue: "Got this video is unavailable when programmatically loadOrCueVideo #698 " which I see is still an open issue.
